### ISSUE TITLE
Reset consumables

### ISSUE THREAD

**Issue by ipod86** [copystring/ioBroker.roborock#100]
Hallo,

gibt es eine Möglichkeit zum resetten der einzelnen consumables in den Adapter einzubauen?

**Comment by copystring** [comment]
Hallöchen, klar. Wenn du magst, kannst du es hier testen oder auf den nächsten Release warten: https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by ipod86** [comment]
Gerade mit den Sensoren getestet.
Hat Funktioniert. 

Vielen dank.

Darf ich eine kleine Zwischenfrage stellen?

Für was ist 
dust_collection_work_times
cleaning_brush_work_times
filter_element_work_time
?

Stehen alle schon immer auf 0h.

**Comment by copystring** [comment]
Manche Roboter haben Zusatzmodule. z. B. die Absaugstation. Wenn diese vorhanden ist, dann werden die entsprechenden Daten ausgefüllt. Fehlt diese dann bleiben die Daten bei 0 stehen.
Ich schließe das hier erstmal. Wenn du weitere Fragen hast, schreib gern hier weiter.

**Comment by copystring** [comment]
Added via https://github.com/copystring/ioBroker.roborock/commit/19cc715e5c907cdd6734d45953a28f96d9944edd
