### ISSUE TITLE
Adapter ist grün obwohl Login Daten inkorrekt

### ISSUE THREAD

**Issue by Duese123** [copystring/ioBroker.roborock#109]
**Describe the bug**  

**To Reproduce**  
1. Wrong login data
2 . Adapter is green

**Expected behavior**  
Adapter shows Red signal because login to backend Not happened

**Comment by copystring** [comment]
Ich bin mir nicht sicher, welches Verhalten besser wäre. Aktuell steht im log, dass das Kennwort und/oder Benutzername falsch ist.

**Comment by Duese123** [comment]
Ja das hab ich auch lange überlegt... ich denke die meisten schauen ob das Symbol grün wird

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/pull/116
Der Adapter wird erst dann grün, wenn Benutzername und Passwort korrekt sind. Ansonsten bleibt er gelb.
