### ISSUE TITLE
Two attributes send as Error

### ISSUE THREAD

**Issue by hahnet** [copystring/ioBroker.roborock#131]
<html>
<body>

Roborock Q7 Max
--
Unsported attribute: charge_status of get_status. Please contact the dev to add the newly found attribute of your robot.

roborock.0 | 2023-04-14 18:55:29.886 | error | Unsported attribute: switch_map_mode of get_status. Please contact the dev to add the newly found attribute of your robot.

</body>
</html>

**Comment by copystring** [comment]
Thanks. Fixed via https://github.com/copystring/ioBroker.roborock/commit/5bb518ab31436b9bed1ec9ca640e6d6ee4d72938 which is available in the latest dev version.
