### ISSUE TITLE
Fehlermeldung error: roborock.0 (1262) Failed to execute *****with id **** timed out after 10 seconds for response.102

### ISSUE THREAD

**Issue by DonToben** [copystring/ioBroker.roborock#132]
Mit letzten Dev Branch bekomme ich u.a. folgende Meldungen im Log.
Der Roborock lässt sich aber trotz der Meldungen einwandfrei steuern.
Ein Neustart des RPI konnte das Problem nicht beheben.

Mit dem Stable Main Branch treten die Fehlermeldungen nicht auf

`2023-04-16 09:34:17.975 - error: roborock.0 (1262) Failed to execute get_consumable. Error: Error: Request with id 3206 timed out after 10 seconds for response.102
2023-04-16 09:34:17.975 - debug: roborock.0 (1262) Length of message queue: 1
2023-04-16 09:34:17.979 - error: roborock.0 (1262) Failed to execute get_carpet_mode. Error: Error: Request with id 6503 timed out after 10 seconds for response.102
2023-04-16 09:34:17.981 - debug: roborock.0 (1262) Length of message queue: 0
2023-04-16 09:34:17.982 - error: roborock.0 (1262) Failed to execute get_carpet_clean_mode. Error: Error: Request with id 3666 timed out after 10 seconds for response.102`

Anbei noch der Debug Log

[Roborock Log.txt](https://github.com/copystring/ioBroker.roborock/files/11241544/Roborock.Log.txt)

**Comment by copystring** [comment]
Wie oft kommt das vor?
Letztendlich ist es eine Funktion. Der Server von Roborock hat halt nicht auf die Anfrage vom Adapter geantwortet. Daher der Fehler.

**Comment by DonToben** [comment]
Ganz unterschiedlich. Manchmal gehäuft, manchmal gar nicht.

**Comment by copystring** [comment]
Ich denke, dass es normal ist. Natürlich abhängig davon, wie stabil deine Leitung ist und wie kooperativ die Server von Roborock sind.
Ich habe die Timeouts einbauen müssen, da es sonst sehr oft Fehler beim Zuordnen der Nachrichten gab. Dadurch wurden dann teilweise Werte falsch abgelegt bzw. konnten gar nicht zugeordnet werden.

**Comment by kopierschnitte** [comment]
Könnte man diese Meldungen eventuell in eine andere Log-Stufe packen?

Bei mir sind mehrere Staubsauger unterwegs und mir persönlich würde es reichen, wenn der Adapter dann einfach auf "Rot" wechselt und ich ggf. die Fehler im "Warn"-Loglevel lesen könnte.

**Comment by copystring** [comment]
Ja, darüber habe ich schon paar mal nachgedacht. Habe es mal als warning anstatt error in der aktuellen dev angepasst.
Bitte mal checken, ob dann weiterhin der message queue sauber aufgeräumt wird.

**Comment by DonToben** [comment]
Habe noch paar Errors mit der letzten Dev, ist aber merklich weniger geworden.

![Screenshot_20230429-171835_Opera](https://user-images.githubusercontent.com/61901880/235310308-fb2d1ab5-85d0-4f8c-aa90-a3c73c508f91.jpg)

**Comment by copystring** [comment]
Das habe ich mir anders vorgestellt. Es treten trotzdem noch Fehler auf, wenn ein Timeout auftaucht.
Das Timeout selbst kann ich nicht beeinflussen. Nur die Art wie das gehandhabt wird.
Ab sofort werden in der dev alle Fehler bezüglich des Abrufens von Daten als Warnung ausgegeben.

**Comment by DonToben** [comment]
Habe noch immer folgende Errors.

![Screenshot_20230430-111141_Opera](https://user-images.githubusercontent.com/61901880/235345242-47b03aa7-a30a-43cb-9334-c76bb722ca32.jpg)

**Comment by copystring** [comment]
Dann hast du nicht die aktuelle dev Version.

**Comment by DonToben** [comment]
Doch ist die aktuelle Dev. Oder haben die Errors im Screenshot eine andere Ursache?

**Comment by copystring** [comment]
In der aktuellen dev werden alle "Failed to execute ..." als Warnungen ausgegeben. Siehe hier z. B. https://github.com/copystring/ioBroker.roborock/commit/675fe221a8583685664f329c42e17c4f51bfce9e#diff-84da5ac6c3c4eac27ec3e77d1993c13caae93b4cf843d59052e568b1b39e32d9L263
Bei dir ist das nicht so. Du musst nochmal aktualisieren.

**Comment by DonToben** [comment]
Habe ich schon 2x gemacht. Leider immer noch die Meldungen.

**Comment by copystring** [comment]
Auf GitHub wurden die Änderungen aber sauber angenommen. Irgendwas stimmt bei dir nicht.
Hier sind die entsprechenden commits dafür https://github.com/copystring/ioBroker.roborock/commit/675fe221a8583685664f329c42e17c4f51bfce9e und https://github.com/copystring/ioBroker.roborock/commit/fbab2b6b10369cff33ecd5d1ef5cb68b965254ec

**Comment by DonToben** [comment]
Nach dem dritten Versuch hat's geklappt. Error Meldungen sind nun weg. Danke

**Comment by copystring** [comment]
👍

**Comment by copystring** [comment]
Mal als Anmerkung nebenbei. Du hast ziemlich viele timeouts. Ich denke, dass bei dir am Netzwerk etwas nicht stimmt. Läuft das über WLAN mit einem RPi?
Bei mir läuft das tagelang mit keinem oder kaum timeouts.

**Comment by DonToben** [comment]
Sehr komisch. Pi ist über Netzwerkkabel verbunden. Sehr stabiles Internet.

**Comment by DonToben** [comment]
Es sind eigentlich nur diese. Falls es ein grundsätzliches Verbindungsproblem geben würde, müssten es dann nicht noch andere sein?
![Screenshot_20230430-180816_Opera](https://user-images.githubusercontent.com/61901880/235363776-c77c9510-c367-4511-89ac-13b1326acbf6.jpg)

**Comment by copystring** [comment]
Wie meinst du das mit andere? Andere Adapter?
Mach doch mal ein log über mehrere Stunden für mich.

**Comment by DonToben** [comment]
Ich meine mehrere Statuswerte des Roborock Adapters ...

----------------------------------------

*Von: *copystring ***@***.***>
*An: *copystring/ioBroker.roborock ***@***.***>
*Kopie: *DonToben ***@***.***>; Author ***@***.***>
*Datum: *30.04.2023 18:20:31
*Betreff: *Re: [copystring/ioBroker.roborock] Fehlermeldung error: roborock.0 (1262) Failed to execute *****with id **** timed out after 10 seconds for response.102 (Issue #132)

**Comment by copystring** [comment]
Schwer zu sagen. Es sind aber auf jeden Fall bei dir schon einige, die keine Antwort bekommen und das ist halt merkwürdig.

**Comment by DonToben** [comment]
Hier der Debug Log.

[Roborock Log.txt](https://github.com/copystring/ioBroker.roborock/files/11361901/Roborock.Log.txt)

**Comment by copystring** [comment]
Das Log ist etwas zu kurz. Eine Stunde reicht nicht. Lass es mal über Nacht laufen oder so.
Auffällig ist aber auf jeden Fall das hier:

```
2023-04-30 19:23:24.408 - warn: roborock.0 (22384) Failed to execute get_water_box_custom_mode. Error: Error: Request with id 5575 timed out after 10 seconds for response.102
...
2023-04-30 19:24:11.750 - debug: roborock.0 (22384) dps debug: {"id":5575,"result":{"water_box_mode":202}}
```

Was für meine Theorie passt, dass irgendwas bei dir sehr langsam ist. Die Antwort auf die Anfrage mit ID 5575 kam erst extrem spät. Aber wie gesagt, um es richtig zu sehen, brauche ich ein längeres Log. Und auch dann, kann ich die Probleme bei dir nicht beheben, sondern nur darstellen ...

**Comment by DonToben** [comment]
Hier die Meldungen über einen längeren Zeitraum.

[Roborock Log.txt](https://github.com/copystring/ioBroker.roborock/files/11364172/Roborock.Log.txt)

**Comment by copystring** [comment]
Kann es sein, dass dein Roboter nicht in der Station steht und schläft? Ansonsten sieht das Log normal aus. Hier und da mal ein Timeout. Das ist dann halt so. Das kann ich mit dem Adapter halt nicht steuern.
