### ISSUE TITLE
in App Angelegtes Programm(Routine) Abrufen und starten

### ISSUE THREAD

**Issue by pad81** [copystring/ioBroker.roborock#133]
Hi,

in der iOS App habe ich unter Programme eine Zone angelegt. Diese scheint auch in der Cloud gespeichert zu werden, da sie mir auf allen Endgeräten angezeigt wird, wenn ich sie einmal erstelle. Es wäre super praktisch dieses Programm bzw diese Zone abzurufen und starten zu können. 

Im Englischen heisst das ganze wohl Routine. 

![Screenshot 2023-04-16 154005](https://user-images.githubusercontent.com/55508622/232315883-0c48020a-8f51-493d-9d8d-e9aa54f6ef68.png)

**Comment by copystring** [comment]
Hey, hast du zufälligerweise auch einen anderen Roboter? So wie ich das sehe, kann das nur der S7 MaxV.
Wenn das nur der S7 MaxV kann, dann brauche ich einiges an Hilfe von dir das entsprechend einzubauen.

**Comment by dako0815** [comment]
Hi. Ich habe einen S7 pro ultra. Bei dem ist das genauso. Was bräuchtest du denn alles?

**Comment by copystring** [comment]
Hi, ich weiß eben nicht, welche Roboter die Planung unterstützen. Bei mir fehlt der Eintrag oder ich finde es einfach nicht. Daher wäre es einfach gewesen, wenn jemand beide hat und dann vergleichen kann.
Oder magst du mir einen Screenshot schicken, wo man das einstellt?

**Comment by brasax** [comment]
S8 Pro Ultra kann das auch, S6MaxV hingegen nicht. 

Ich kann auch gerne was liefern.

![image](https://user-images.githubusercontent.com/73777365/236566790-34af0013-4bda-4a6a-b8b6-ed6488637ba5.png)

![image](https://user-images.githubusercontent.com/73777365/236566804-78fdd7cb-94e5-4dcf-b646-fa9565c4b96d.png)

**Comment by copystring** [comment]
Um deine Hilfe bin ich sehr dankbar. Meine beiden Saugroboter können das nicht.
Bitte mal die neue Dev installieren und einfach ein Log hier als Textdatei anhängen. Dann kann ich mir das mal angucken.

**Comment by brasax** [comment]
Hier mal das Log. Habe ein Programm gestartet, erst saugen, dann wischen einer Zone:

[log_programm.txt](https://github.com/copystring/ioBroker.roborock/files/11414793/log_programm.txt)

**Comment by copystring** [comment]
Schade. Das war nicht das gewünschte Ergebnis. Teste bitte mal die neue dev Version und häng entsprechende neue Logs hier an.
Beim Starten vom Adapter werden die aktuellen gespeicherten Timer (hoffentlich) abgerufen und ins Debuglog geschrieben.

**Comment by pad81** [comment]
[robolog.txt](https://github.com/copystring/ioBroker.roborock/files/11420768/robolog.txt)
sorry, ich hatte viel zu tun.

**Comment by copystring** [comment]
Sorry hatte Corona :D
Schade, das ist auch nicht das, was ich mir vorgestellt habe.
Vielleicht gibt es einen neuen Befehl für den S8. Wird schwer den herauszufinden, da ich keinen S8 habe.

**Comment by pad81** [comment]
Wäre ich Millionär…..😂Am 13.05.2023 um 13:27 schrieb copystring ***@***.***>:﻿
Sorry hatte Corona :D
Schade, das ist auch nicht das, was ich mir vorgestellt habe.
Vielleicht gibt es einen neuen Befehl für den S8. Wird schwer den herauszufinden, da ich keinen S8 habe.

**Comment by copystring** [comment]
Mittlerweile ist es möglich, den Datenverkehr aus der App mitzuschneiden. Darüber könnte man dann herausfinden, wie die App eine Routine festlegt. Das kann ich dann in den Adapter einbauen.
Wenn du dir das zutraust, hier steht, wie das geht: https://github.com/copystring/ioBroker.roborock/wiki/Sniffing-Roborock-MQTT-traffic
