### ISSUE TITLE
error: Unsported attribute

### ISSUE THREAD

**Issue by Vumer4** [copystring/ioBroker.roborock#134]
Hallo:
Adapter v0.1.6
Roborock Q7 Max

99+ mal
`<html><body>

roborock.0 | 2023-04-21 19:12:31.632 | error | Unsported attribute: charge_status of get_status. Please contact the dev to add the newly found attribute of your robot.
-- | -- | -- | --
roborock.0 | 2023-04-21 19:12:31.632 | error | Unsported attribute: switch_map_mode of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-04-21 19:11:31.634 | error | Unsported attribute: charge_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-04-21 19:11:31.633 | error | Unsported attribute: switch_map_mode of get_status. Please contact the dev to add the newly found attribute of your robot.

</body>
</html>`

Um welchen Attribut handelt es sich?  Wie kann ich helfen?

**Comment by copystring** [comment]
Hi,

das ist in der aktuelle dev Version bereits behoben. https://github.com/copystring/ioBroker.roborock/commit/5bb518ab31436b9bed1ec9ca640e6d6ee4d72938
