### ISSUE TITLE
Extrem viele Fehlermeldungen bzgl. "Unsported attribute" und "State X"

### ISSUE THREAD

**Issue by SchlumpfIOB** [copystring/ioBroker.roborock#135]
Hallo,

Seit heute morgen habe ich folgende Meldungen im Log:

`Unsported attribute: 539 of get_status. Please contact the dev to add the newly found attribute of your robot.`
und
`State "roborock.0.Devices.XXX.consumables.168" has no existing object, this might lead to an error in future versions`
zusätzlich grade noch:
`Unsported attribute: side_brush_work_time of get_status. Please contact the dev to add the newly found attribute of your robot.`

Hab jetzt mal nur Beispiele hier rein geschrieben, da die erste Meldung von 0 bis 539 ging, die zweite von 0 bis 169 usw. Insgesamt hatte ich grade ca. 3.000 Fehler und Warnungen im Log und wollte die hier nicht alle rein schreiben. :D

Gruß
Jan

**Comment by copystring** [comment]
Hi, welche Version ist das? Sie dev Version?

**Comment by SchlumpfIOB** [comment]
Die ganz normale denke ich. Version 0.1.6

Kann ich irgendwo sehen ob es die dev Version ist?

**Comment by copystring** [comment]
Ja steht ganz am Anfang vom Log.

**Comment by SchlumpfIOB** [comment]
`starting. Version 0.1.6 (non-npm: copystring/ioBroker.roborock#89c927a4a30ca395e6824e1130337cb8343a9a19) in /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0, js-controller: 4.0.24`

Das?

**Comment by Lyssid** [comment]
Moin moin ich habe das gleiche Problem. Ebenfalls die 0.1.6:
```2023-04-24 18:28:56.993 - error: roborock.0 (53965) Unsported attribute: 0 of get_status. Please contact the dev to add the newly found attribute of your robot.```
bis hin zu
```2023-04-24 18:28:57.157 - error: roborock.0 (53965) Unsported attribute: 577 of get_status. Please contact the dev to add the newly found attribute of your robot.```

Zudem habe ich einige Einträge nach einem Reboot:
```
2023-04-24 19:06:56.518 - error: roborock.0 (53965) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-04-24 19:06:56.520 - error: roborock.0 (53965) unhandled promise rejection: getaddrinfo ENOTFOUND api-eu.roborock.com
2023-04-24 19:06:56.522 - error: roborock.0 (53965) Error: getaddrinfo ENOTFOUND api-eu.roborock.com
```
```2023-04-24 19:06:56.523 - error: roborock.0 (53965) Exception-Code: ENOTFOUND: getaddrinfo ENOTFOUND api-eu.roborock.com
2023-04-24 19:06:56.535 - info: roborock.0 (53965) terminating
2023-04-24 19:06:56.538 - warn: roborock.0 (53965) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-04-24 19:06:57.127 - error: host.raspberrypi instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)```

Ich nutze einen Roborock S7 und das ganze läuft in einem IOBrocker auf nem Raspy 4

**Comment by copystring** [comment]
Mal bitte die aktuelle dev testen und Rückmeldung geben.

**Comment by SchlumpfIOB** [comment]
Die Fehler und Warnungen sind bisher bei mir nicht mehr aufgetaucht.

Ich werde es die Tage mal im Auge behalten.

👍

**Comment by SchlumpfIOB** [comment]
Nach geplantem, automatischem Neustart der Instanz heute morgen folgende Fehlermeldungen:

`<html><body>


<html><body>


roborock.0 | 2023-04-26 09:30:19.944 | error | Failed to execute get_room_mapping. Error: Error: Request with id 6633 timed out after 10 seconds for response.102
-- | -- | -- | --
roborock.0 | 2023-04-26 09:30:19.942 | error | Failed to execute get_water_box_custom_mode. Error: Error: Request with id 9657 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:30:19.941 | error | Failed to execute get_carpet_clean_mode. Error: Error: Request with id 6266 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:30:19.938 | error | Failed to execute get_carpet_mode. Error: Error: Request with id 3337 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:30:19.937 | error | Failed to execute get_network_info. Error: Error: Request with id 4603 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:30:19.936 | error | Failed to execute get_consumable. Error: Error: Request with id 7499 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:30:19.934 | error | Failed to execute get_status. Error: Error: Request with id 8544 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:29:19.943 | error | Failed to execute get_room_mapping. Error: Error: Request with id 4948 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:29:19.942 | error | Failed to execute get_water_box_custom_mode. Error: Error: Request with id 8792 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:29:19.940 | error | Failed to execute get_carpet_clean_mode. Error: Error: Request with id 7860 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:29:19.939 | error | Failed to execute get_carpet_mode. Error: Error: Request with id 1725 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:29:19.937 | error | Failed to execute get_network_info. Error: Error: Request with id 4259 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:29:19.935 | error | Failed to execute get_consumable. Error: Error: Request with id 7395 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:29:19.934 | error | Failed to execute get_status. Error: Error: Request with id 7889 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:28:19.944 | error | Failed to execute get_room_mapping. Error: Error: Request with id 5029 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:28:19.943 | error | Failed to execute get_water_box_custom_mode. Error: Error: Request with id 5232 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:28:19.941 | error | Failed to execute get_carpet_clean_mode. Error: Error: Request with id 8763 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:28:19.939 | error | Failed to execute get_carpet_mode. Error: Error: Request with id 3011 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:28:19.937 | error | Failed to execute get_network_info. Error: Error: Request with id 9850 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:28:19.936 | error | Failed to execute get_consumable. Error: Error: Request with id 7575 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:28:19.934 | error | Failed to execute get_status. Error: Error: Request with id 5717 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:26:19.949 | error | Failed to execute get_room_mapping. Error: Error: Request with id 2867 timed out after 10 seconds for response.102
-- | -- | -- | --
roborock.0 | 2023-04-26 09:26:19.946 | error | Failed to execute get_water_box_custom_mode. Error: Error: Request with id 6255 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:26:19.944 | error | Failed to execute get_carpet_clean_mode. Error: Error: Request with id 7390 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:26:19.941 | error | Failed to execute get_carpet_mode. Error: Error: Request with id 5643 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:26:19.938 | error | Failed to execute get_network_info. Error: Error: Request with id 6896 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:26:19.937 | error | Failed to execute get_consumable. Error: Error: Request with id 1358 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:26:19.933 | error | Failed to execute get_status. Error: Error: Request with id 8227 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.976 | error | Failed to execute get_room_mapping. Error: Error: Request with id 3241 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.950 | error | Failed to execute get_clean_summary. Error: Error: Request with id 2914 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.947 | error | Failed to execute get_water_box_custom_mode. Error: Error: Request with id 3285 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.945 | error | Failed to execute get_carpet_clean_mode. Error: Error: Request with id 3449 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.944 | error | Failed to execute get_carpet_mode. Error: Error: Request with id 3323 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.942 | error | Failed to execute get_network_info. Error: Error: Request with id 5971 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.941 | error | Failed to execute get_consumable. Error: Error: Request with id 5739 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.939 | error | Failed to execute get_status. Error: Error: Request with id 3536 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.936 | error | Failed to execute get_multi_map_list. Error: Error: Request with id 9704 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:19.934 | error | Failed to execute get_fw_features. Error: Error: Request with id 4827 timed out after 10 seconds for response.102
roborock.0 | 2023-04-26 09:25:05.638 | info | MQTT initialized
roborock.0 | 2023-04-26 09:25:04.977 | info | starting.  Version 0.1.6 (non-npm: copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0,  js-controller: 4.0.2


</body>
</html>`

**Comment by copystring** [comment]
Das ist normal. Entweder antwortet der Server von roborock nicht oder du hast Netzwerkprobleme

**Comment by guggu1** [comment]
ich habe ähnliche Fehlermeldungen. Viele aufs Mal, dann tagelang wieder keine.
Adapterversion 0.1.6

Fehlerlog
=======



2023-04-28 05:12:04.793 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.msg_ver" has no existing object, this might lead to an error in future versions
--
2023-04-28 05:12:04.795 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.msg_seq" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.797 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.state" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.797 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.battery" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.798 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.clean_time" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.798 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.clean_area" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.799 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.error_code" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.800 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.map_present" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.800 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.in_cleaning" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.800 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.in_returning" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.801 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.in_fresh_state" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.802 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.lab_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.804 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.water_box_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.805 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.fan_power" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.806 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.dnd_enabled" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.807 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.map_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.807 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.is_locating" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.808 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.lock_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.809 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.water_box_mode" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.809 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.water_box_carriage_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.810 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.mop_forbidden_enable" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.810 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.adbumper_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.811 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.water_shortage_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.811 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.dock_type" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.812 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.dust_collection_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.812 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.auto_dust_collection" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.813 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.mop_mode" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.813 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.debug_mode" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.813 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.dock_error_status" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.814 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.unsave_map_reason" has no existing object, this might lead to an error in future versions
2023-04-28 05:12:04.814 - warn: roborock.0 (9399) State "roborock.0.Devices.56a8YNlcJHpcekqh74xB0A.consumables.unsave_map_flag" has no existing object, this might lead to an error in future versions
2023-04-28 05:13:42.286 - info: bmw.0 (16200) Found 1 bmw vehicles

**Comment by copystring** [comment]
@guggu1 hast du es mal mit der aktuellen dev Version probiert?

**Comment by guggu1** [comment]
habs nicht versucht - weil ich nicht weiss, wie man die installiert.

christoph S

**Comment by copystring** [comment]
Mit der aktuellen dev Version https://github.com/copystring/ioBroker.roborock/tree/dev mal bitte neu testen und dann ein vollständiges Debug Log hier anhängen.
Wenn der Roboter einen Status haben sollte, an dem erkennbar ist, dass dieser gerade schläft, dann könnte ich alle anfragen natürlich pausieren.

**Comment by SchlumpfIOB** [comment]
Hab ich gemacht, hier das debug Log:

<html><body>


roborock.0 | 2023-05-03 08:52:28.884 | warn | Failed to execute get_room_mapping. Error: Error: Request with id 6351 timed out after 10 seconds for response.102
-- | -- | -- | --
roborock.0 | 2023-05-03 08:52:28.883 | debug | Length of message queue: 0
roborock.0 | 2023-05-03 08:52:28.879 | warn | Failed to execute get_water_box_custom_mode. Error: Error: Request with id 6239 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:52:28.877 | debug | Length of message queue: 1
roborock.0 | 2023-05-03 08:52:28.876 | warn | Failed to execute get_carpet_clean_mode. Error: Error: Request with id 6875 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:52:28.874 | debug | Length of message queue: 2
roborock.0 | 2023-05-03 08:52:28.870 | warn | Failed to execute get_carpet_mode. Error: Error: Request with id 4751 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:52:28.869 | debug | Length of message queue: 3
roborock.0 | 2023-05-03 08:52:28.868 | warn | Failed to execute get_network_info. Error: Error: Request with id 2244 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:52:28.866 | debug | Length of message queue: 4
roborock.0 | 2023-05-03 08:52:28.864 | warn | Failed to execute get_consumable. Error: Error: Request with id 4783 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:52:28.862 | debug | Length of message queue: 5
roborock.0 | 2023-05-03 08:52:28.858 | warn | Failed to execute get_status. Error: Error: Request with id 6688 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:52:28.857 | debug | Length of message queue: 6
roborock.0 | 2023-05-03 08:52:21.953 | debug | homedata successfully updated
roborock.0 | 2023-05-03 08:52:18.872 | debug | getParameter: get_water_box_custom_mode
roborock.0 | 2023-05-03 08:52:18.869 | debug | getParameter: get_carpet_clean_mode
roborock.0 | 2023-05-03 08:52:18.865 | debug | getParameter: get_carpet_mode
roborock.0 | 2023-05-03 08:52:18.863 | debug | getParameter: get_network_info
roborock.0 | 2023-05-03 08:52:18.860 | debug | getParameter: get_consumable
roborock.0 | 2023-05-03 08:52:18.859 | debug | getParameter: get_room_mapping
roborock.0 | 2023-05-03 08:52:18.855 | debug | getParameter: get_status
roborock.0 | 2023-05-03 08:52:18.853 | debug | Latest data requested
roborock.0 | 2023-05-03 08:51:28.910 | warn | Failed to execute get_room_mapping. Error: Error: Request with id 4406 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.907 | debug | Length of message queue: 0
roborock.0 | 2023-05-03 08:51:28.890 | warn | Failed to execute get_clean_summary. Error: Error: Request with id 2911 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.888 | debug | Length of message queue: 1
roborock.0 | 2023-05-03 08:51:28.882 | warn | Failed to execute get_water_box_custom_mode. Error: Error: Request with id 4782 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.881 | debug | Length of message queue: 2
roborock.0 | 2023-05-03 08:51:28.880 | warn | Failed to execute get_carpet_clean_mode. Error: Error: Request with id 5859 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.879 | debug | Length of message queue: 3
roborock.0 | 2023-05-03 08:51:28.878 | warn | Failed to execute get_carpet_mode. Error: Error: Request with id 3927 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.876 | debug | Length of message queue: 4
roborock.0 | 2023-05-03 08:51:28.874 | warn | Failed to execute get_network_info. Error: Error: Request with id 3158 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.873 | debug | Length of message queue: 5
roborock.0 | 2023-05-03 08:51:28.872 | warn | Failed to execute get_consumable. Error: Error: Request with id 6404 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.870 | debug | Length of message queue: 6
roborock.0 | 2023-05-03 08:51:28.867 | warn | Failed to execute get_status. Error: Error: Request with id 4278 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.866 | debug | Length of message queue: 7
roborock.0 | 2023-05-03 08:51:28.864 | warn | Failed to execute get_multi_map_list. Error: Error: Request with id 3415 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.863 | debug | Length of message queue: 8
roborock.0 | 2023-05-03 08:51:28.861 | warn | Failed to execute get_fw_features. Error: Error: Request with id 9874 timed out after 10 seconds for response.102
roborock.0 | 2023-05-03 08:51:28.858 | debug | Length of message queue: 9
roborock.0 | 2023-05-03 08:51:21.934 | debug | homedata successfully updated
roborock.0 | 2023-05-03 08:51:21.867 | debug | Made ./lib/go2rtc/go2rtc_linux_arm executable
roborock.0 | 2023-05-03 08:51:18.874 | debug | downloadURL: https://github.com/AlexxIT/go2rtc/releases/download/v1.3.0/go2rtc_linux_arm
roborock.0 | 2023-05-03 08:51:18.874 | debug | System type: go2rtc_linux_arm
roborock.0 | 2023-05-03 08:51:18.874 | debug | platform: linux
roborock.0 | 2023-05-03 08:51:18.873 | debug | arch: arm
roborock.0 | 2023-05-03 08:51:18.868 | debug | getParameter: get_water_box_custom_mode
roborock.0 | 2023-05-03 08:51:18.867 | debug | getParameter: get_carpet_clean_mode
roborock.0 | 2023-05-03 08:51:18.866 | debug | getParameter: get_carpet_mode
roborock.0 | 2023-05-03 08:51:18.865 | debug | getParameter: get_network_info
roborock.0 | 2023-05-03 08:51:18.864 | debug | getParameter: get_consumable
roborock.0 | 2023-05-03 08:51:18.863 | debug | getParameter: get_room_mapping
roborock.0 | 2023-05-03 08:51:18.861 | debug | getParameter: get_status
roborock.0 | 2023-05-03 08:51:18.860 | debug | Latest data requested
roborock.0 | 2023-05-03 08:51:18.859 | debug | getParameter: get_multi_maps_list
roborock.0 | 2023-05-03 08:51:18.853 | debug | Firmware features request
roborock.0 | 2023-05-03 08:51:18.853 | debug | getParameter: get_fw_features
roborock.0 | 2023-05-03 08:51:15.404 | debug | Robot key: roborock.vacuum.a15
roborock.0 | 2023-05-03 08:51:15.402 | debug | RoomIDs  debug:  {"11541503":"Gästezimmer","11541504":"Schlafzimmer","11541506":"Küche","11541508":"Flur","11541509":"Badezimmer","11541510":"Wohnzimmer","11541511":"Esszimmer"}
roborock.0 | 2023-05-03 08:51:15.401 | info | MQTT initialized
roborock.0 | 2023-05-03 08:51:14.914 | info | starting.  Version 0.1.6 (non-npm: copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0,  js-controller: 4.0.24
roborock.0 | 2023-05-03 08:51:14.437 | debug | Plugin sentry Initialize Plugin (enabled=true)
roborock.0 | 2023-05-03 08:51:14.297 | debug | States connected to redis: 127.0.0.1:9000
roborock.0 | 2023-05-03 08:51:14.256 | debug | States create User PubSub Client
roborock.0 | 2023-05-03 08:51:14.254 | debug | States create System PubSub Client
roborock.0 | 2023-05-03 08:51:14.231 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
roborock.0 | 2023-05-03 08:51:14.186 | debug | Objects connected to redis: 127.0.0.1:9001
roborock.0 | 2023-05-03 08:51:14.178 | debug | Objects client initialize lua scripts
roborock.0 | 2023-05-03 08:51:14.094 | debug | Objects create User PubSub Client
roborock.0 | 2023-05-03 08:51:14.093 | debug | Objects create System PubSub Client
roborock.0 | 2023-05-03 08:51:14.089 | debug | Objects client ready ... initialize now
roborock.0 | 2023-05-03 08:51:14.013 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
host.raspberrypi-iobroker | 2023-05-03 08:51:11.923 | info | instance system.adapter.roborock.0 started with pid 10568
host.raspberrypi-iobroker | 2023-05-03 08:51:11.569 | info | "system.adapter.roborock.0" enabled
host.raspberrypi-iobroker | 2023-05-03 08:50:57.261 | info | instance system.adapter.roborock.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
roborock.0 | 2023-05-03 08:50:57.107 | error | DB closed
roborock.0 | 2023-05-03 08:50:57.106 | error | Error:  DB closed    at close  (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25)     at Socket.<anonymous>  (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20)     at Object.onceWrapper (node:events:628:26)    at Socket.emit  (node:events:513:28)    at Socket.emit (node:domain:489:12)    at  TCP.<anonymous> (node:net:301:12)
roborock.0 | 2023-05-03 08:50:57.100 | error | unhandled promise rejection: DB closed
roborock.0 | 2023-05-03 08:50:57.099 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
roborock.0 | 2023-05-03 08:50:57.003 | info | MQTT initialized
host.raspberrypi-iobroker | 2023-05-03 08:50:56.582 | info | stopInstance system.adapter.roborock.0 send kill signal
roborock.0 | 2023-05-03 08:50:56.572 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2023-05-03 08:50:56.569 | info | terminating
roborock.0 | 2023-05-03 08:50:56.566 | info | Got terminate signal TERMINATE_YOURSELF
host.raspberrypi-iobroker | 2023-05-03 08:50:56.556 | info | stopInstance system.adapter.roborock.0 (force=false, process=true)
host.raspberrypi-iobroker | 2023-05-03 08:50:56.556 | info | "system.adapter.roborock.0" disabled
roborock.0 | 2023-05-03 08:50:56.193 | info | starting.  Version 0.1.6 (non-npm: copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0,  js-controller: 4.0.24
host.raspberrypi-iobroker | 2023-05-03 08:50:53.229 | info | instance system.adapter.roborock.0 started with pid 10513
host.raspberrypi-iobroker | 2023-05-03 08:50:50.562 | info | instance system.adapter.roborock.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.raspberrypi-iobroker | 2023-05-03 08:50:50.004 | info | stopInstance system.adapter.roborock.0 send kill signal
roborock.0 | 2023-05-03 08:50:49.917 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2023-05-03 08:50:49.914 | info | terminating
roborock.0 | 2023-05-03 08:50:49.911 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>

Das neu installieren und das Log wurde erstellt während der Roborock schläft. Dies ist eine der Stati unter roborock.0.Devices.XxXxXxX.deviceStatus.state. Zusätzlich sollte das auch erkennbar daran sein, dass der Roboter nicht online ist. Das könnte allerdings natürlich auch genau den Grund haben für die die Fehlermeldungen gedacht sind (Netzwerkprobleme/Server down).

**Comment by copystring** [comment]
Das Problem ist, wenn ich das Aktualisieren der Anfragen pausiere, kann nicht erkannt werden, dass der Roboter aus dem Schlaf wieder aufgewacht ist, weil roborock.0.Devices.XxXxXxX.deviceStatus.state ja nicht mehr aktualisiert wird.

**Comment by SchlumpfIOB** [comment]
Habe noch etwas festgestellt, was evtl weiterhelfen könnte. Scheinbar geht der Roborock genau 12 Stunden nachdem er in den Status "Sleeping" geht, in eine Art "Stand-By"-Modus. Dieser unterbricht auch die Verbindung mit dem W-Lan. Ab da gehen dann, logischerweise, die Fehlermeldungen los.

Ich hab noch nichts gefunden wo dieser "Stand-by"-Betrieb angezeigt wird. Selbst die App gibt hierbei keine Benachrichtigung aus.

Aber noch eine Verständnissfrage, warum sind die Fehler denn nur bei 7 Stati?

**Comment by SchlumpfIOB** [comment]
Hallo nochmal,

ich komm nochmal auf diesen Issue zurück:

Können wir irgendeine Möglichkeit finden, dass die dauerhaften Warnungen aufgrund des Standby Betriebes (nicht im W-Lan) des Roboters nicht mehr angezeigt werden? Diese tauchen alle 10 sec auf und es sind bis zur nächsten Aktivierung der Stromzufuhr (täglich) hunderte von Warnmeldungen. Ich denke nicht das ich der einzige bin der den Roboter nicht dauerhaft am Strom hängen hat und wenn dann beispielsweise nur alle paar Tage der Roboter eingeschaltet wird, kommen hier sicher tausende Warnungen raus.

Falls es hilft, ich hatte vorher den mihome-vacuum Adapter installiert, wobei die Skripte dieselben waren. Hier gab es diese Warnmeldungen nicht.

Vielen Dank für deine Geduld

Gruß
Jan

**Comment by copystring** [comment]
Klar. Der Adapter muss ja nicht auf Debug laufen. Mit der aktuellen dev das logging auf Error umstellen reicht also aus.

**Comment by SchlumpfIOB** [comment]
Also ich hab ihn derzeit auf info stehen. Wenn ich auf Error stelle, verpasse ich da nicht evtl. wichtige Meldungen?

**Comment by copystring** [comment]
Nicht unbedingt. Die wären ja zum testen oder debuggen.

**Comment by SchlumpfIOB** [comment]
Ok, dann mach ich das vorerst mal. Wenn es dann zur normalen Version kommt und evtl zur Stable, sollte man dann nochmal was daran machen? Biete gerne Unterstützung im Bereich des testens an (von allem anderen habe ich höchst warscheinlich keine Ahnung).

**Comment by SchlumpfIOB** [comment]
Ach ja, noch eine kurze Frage die ich mir letztens gestellt habe (ich weiß, gehört hier eigentlich nicht hin), gibt es einen Wert/Objekt das mir anzeigt ob der Wassertank leer ist? In unregelmäßigen Abständen sagt mir die App das. Leider sehr komisch, da er es manchmal erkennt und manchmal nicht. Gibt es hierfür einen Sensor? Habe in der Bediehnungsanleitung hierzu nichts gefunden.

**Comment by copystring** [comment]
Aktuell ist das nicht eingebaut.

**Comment by SchlumpfIOB** [comment]
Kannst du das, wenn ich ganz lieb frage, einbauen?

**Comment by copystring** [comment]
Das hat mit lieb fragen nicht zu tun. Wenn ich wüsste, welche Parameter das ist, hätte ich den schon eingebaut.

**Comment by SchlumpfIOB** [comment]
Was sind denn die die da zum Wassertank mit drin sind? bei denen hab ich noch keine Veränderungen feststellen können:

roborock.0.Devices.XXX.deviceStatus.water_box_carriage_status          (???)
roborock.0.Devices.XXX.deviceStatus.water_box_custom_mode           (Modus, ob viel oder wenig Wasser genutzt wird?)
roborock.0.Devices.XXX.deviceStatus.water_box_mode                        (nochmal Modus.....?)
roborock.0.Devices.XXX.deviceStatus.water_box_status                       (ob Box drin oder nicht?)

**Comment by copystring** [comment]
Die ändern sich nur dann, wenn du diese über die App oder commands vom Adapter änderst. Zum Beispiel wie viel Wasser verwendet werden soll oder wie stark der Mopp schrubben soll.
