### ISSUE TITLE
Fehlender Support für Roborock S4 Max

### ISSUE THREAD

**Issue by Reddingo** [copystring/ioBroker.roborock#137]
Hallo,

leider bekomm ich beim Starten des Adapters zig Fehlermeldungen, vermutlich weil noch kein S4 Max unterstützt wird?
Installiert habe ich die Version v0.1.6 auf einem aktuellen iobroker v6.3.5 mit Node.js: v18.7.0(18.16.0) und NPM: 8.18.0(8.19.4)

<html><body>

roborock.0 | 2023-04-28 13:01:08.380 | info | terminating
-- | -- | -- | --
roborock.0 | 2023-04-28 13:01:08.363 | error | Exception-Code:  MODULE_NOT_FOUND: Cannot find module './undefined'Require stack:-  /opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js-  /opt/iobroker/node_modules/iobroker.roborock/main.js
roborock.0 | 2023-04-28 13:01:08.362 | error | Error:  Cannot find module './undefined'Require stack:-  /opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js-  /opt/iobroker/node_modules/iobroker.roborock/main.js    at  Function.Module._resolveFilename  (node:internal/modules/cjs/loader:956:15)    at Function.Module._load  (node:internal/modules/cjs/loader:804:27)    at Module.require  (node:internal/modules/cjs/loader:1022:19)    at require  (node:internal/modules/cjs/helpers:102:18)    at new vacuum  (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:42:31)    at  /opt/iobroker/node_modules/iobroker.roborock/main.js:176:28
roborock.0 | 2023-04-28 13:01:08.356 | error | unhandled  promise rejection: Cannot find module './undefined'Require stack:-  /opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js-  /opt/iobroker/node_modules/iobroker.roborock/main.js
roborock.0 | 2023-04-28 13:01:08.356 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
roborock.0 | 2023-04-28 13:01:08.354 | error | The model ${robotModel} is not supported. Get in touch with the dev to get this robot supported.
roborock.0 | 2023-04-28 13:01:08.352 | info | MQTT initialized

</body>
</html>

**Comment by Reddingo** [comment]
Okay. Problem wohl gelöst.
Ich hab noch keinen Plan wie man einen Vorschlag zur Fehlerbehebung in fremden Projekten vorschläg da ich ganz neu bin bei guthubt, daher habe ich dein Projekt mal geforkt und modifiziert.

Man muss die Klasse roborock_vacuum_a19 von roborock_vacuum_s4 ableiten und in der vacuum.js einbinden.
Laut Beschreibung ist der S4 Max identisch mit dem normalen S4 nur dass er beim Teppich mehr Power hat?

Ich würde weiter noch vorschlagen die Zeile in der if-Abfrage im constructor in der vacuum.js wie folgte anzupassen:

`this.adapter.log.error("The model '" + robotModel + '" is not supported. Get in touch with the dev to get this robot supported.");
`

Dann steht auch im Logfile welches Model nicht supported ist, das mit dem ${robotModel} ist wohl ein copy/paste Fehler woher auch immer.

**Comment by copystring** [comment]
Super! Du kannst aus deinem Fork heraus ein PR machen. Dann kann ich das hinzufügen.
Der Fehler, dass das fehlende Modell nicht angezeigt wird, ist in der dev Version bereits behoben.

**Comment by Reddingo** [comment]
Ich hab was gemacht was aussah wie ein Pullrequest, ich hoffe das war korrekt :-)

**Comment by copystring** [comment]
Danke. Ist drin. Bitte beim nächsten Mal einen Fork von https://github.com/copystring/ioBroker.roborock/tree/dev erstellen und dafür ein PR erstellen. 👍
