### ISSUE TITLE
Minimal Wert für "update interval"

### ISSUE THREAD

**Issue by guggu1** [copystring/ioBroker.roborock#138]
Wenn das update interval sehr klein ist, z.B. 2 Sekunden, gibt es offenbar einen Netzwerkkonflikt mit dem Dieser versucht ständig am Dock die Karte abzuspeichern, wird dabei aber offenbar unterbrochen. Dies äussert sich darin, dass die Anzeige auf der Roborock app ständig zwischen "Saving Map" und "Charging" wechselt. Die neue Karte wird nicht abgespeichert, manchmal geht sie sogar verloren, so, dass man die Backup Karte laden muss. Die hat dann natürlich die neuesten Änderungen nicht.

Ich habe das Update Interval erhöht. Seither tritt das Problem nicht mehr auf. Habe aber ziemlich lange gebraucht, bis ich die Ursache gefunden habe.

Mein Vorschlag: Update Interval im Konfigurationsbildschirm nach unten begrenzen.

Christoph

**Comment by copystring** [comment]
Hi,
kann eigentlich nicht sein, wenn dein Netzwerk stabil und schnell genug ist. Kann natürlich sein, dass es auf einem RPi nicht schnell genug abgearbeitet wird, dort dann manuell den Intervall anpassen. Die voreingestellten 2 Sekunden sind ja nur ein Vorschlag. Ich lese zum ersten mal von diesem Problem. Wenn das nur bei dir auftritt, dann wüsste ich jetzt nicht, warum ich den vorgeschlagenen Intervall von 2 Sekunden auf etwas anderes ändern sollte.
Auf welchen System läuft das denn bei dir?

**Comment by copystring** [comment]
Des weitern ist es so, dass der Adapter die Karte gar nicht aktualisiert, wenn der Roboter in der Station geparkt ist. Falls doch, dann brauche ich ein komplettes Debug Log.
