### ISSUE TITLE
Auffälligkeiten S4 Max

### ISSUE THREAD

**Issue by Reddingo** [copystring/ioBroker.roborock#140]
Mir sind ein paar Sachen aufgefallen beim S4 Max (a19) mit der aktuellen Version 0.1.6

Wenn ich den Roboter in einen Fehlerzustand bringe (einfach hochheben und warten), dann bekomme ich in der App eine Fehlermeldung **"7": "Wheel blocked"**, im Adapter ändert sich die folgende Node aber nicht und bleibt bei 0
roborock.0.Devices.meineID.deviceStatus.error_code

Dann habe ich aus dem Log noch ein paar fehlende Objects bzw unsupported Attribute

<html><body>

roborock.0 | Datum | Level| Text
-- | -- | -- | --
roborock.0 | 2023-04-29 12:04:37.240 | warn | **State   "roborock.0.Devices.meineID.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions**
roborock.0 | 2023-04-29 12:04:37.239 | debug | dps  debug:  {"id":8084,"result":[{"main_brush_work_time":320860,"side_brush_work_time":320860,"filter_work_time":320860,"filter_element_work_time":0,"sensor_dirty_time":13034}]}
roborock.0 | 2023-04-29 12:04:37.225 | debug | dps debug: {"id":4816,"result":"unknown_method"}
roborock.0 | 2023-04-29 12:04:37.216 | warn | **State   "roborock.0.Devices.meineID.deviceStatus.water_box_custom_mode"  has no existing object, this might lead to an error in future versions**
roborock.0 | 2023-04-29 12:04:37.201 | warn | **State  "roborock.0.Devices.meineID.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions**
roborock.0 | 2023-04-29 12:04:37.194 | debug | dps debug: {"id":8407,"result":"unknown_method"}
roborock.0 | 2023-04-29 12:04:37.194 | debug | dps debug: {"id":9916,"result":[{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]}
roborock.0 | 2023-04-29 12:04:37.149 | error | **Unsported attribute: water_box_status of get_status. Please contact the dev to add the newly found attribute of your robot.**
roborock.0 | 2023-04-29 12:04:37.149 | debug | get_status:   {"msg_ver":2,"msg_seq":2640,"state":10,"battery":100,"clean_time":93,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":1,"in_returning":0,"in_fresh_state":0,"lab_status":3,"water_box_status":0,"fan_power":102,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0}
roborock.0 | 2023-04-29 12:04:37.149 | debug | dps  debug:  {"id":4069,"result":[{"msg_ver":2,"msg_seq":2640,"state":10,"battery":100,"clean_time":93,"clean_area":0,"error_code":0,"map_present":1,"in_cleaning":1,"in_returning":0,"in_fresh_state":0,"lab_status":3,"water_box_status":0,"fan_power":102,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0}]}
roborock.0 | 2023-04-29 12:04:37.079 | debug | getParameter: get_water_box_custom_mode
roborock.0 | 2023-04-29 12:04:37.079 | debug | getParameter: get_carpet_clean_mode
roborock.0 | 2023-04-29 12:04:37.079 | debug | getParameter: get_carpet_mode
roborock.0 | 2023-04-29 12:04:37.079 | debug | getParameter: get_network_info
roborock.0 | 2023-04-29 12:04:37.078 | debug | getParameter: get_consumable
roborock.0 | 2023-04-29 12:04:37.078 | debug | getParameter: get_status
roborock.0 | 2023-04-29 12:04:37.077 | debug | Latest data requested

</body>
</html>

**Comment by copystring** [comment]
Bitte die aktuelle dev testen und dann nochmal Rückmeldung geben. https://github.com/copystring/ioBroker.roborock/commits/dev

**Comment by Reddingo** [comment]
Planst du bald eine  0.1.7 zu releasen?

**Comment by copystring** [comment]
Ja, hat aber nichts mit dem Issue zu tun?

**Comment by Reddingo** [comment]
Nicht direkt.
War nur am Überlegen ob ich nun alles runterschmeisen soll und die DEV zu installieren oder ob ich gleich die nächste Beta teste ob die Themen da behoben sind

**Comment by copystring** [comment]
Was hält dich davon ab, die dev zu installieren? Du musst nichts löschen oder herausschmeißen.
