### ISSUE TITLE
DEV Branch Adapter startet immer wieder neu

### ISSUE THREAD

**Issue by DonToben** [copystring/ioBroker.roborock#149]
Mit dem aktuellen DEV Brach startet der Adapter immer wieder neu. Aktueller Main Branch funktioniert.

Hier das Log File:

[Roborock Log.txt](https://github.com/copystring/ioBroker.roborock/files/11427869/Roborock.Log.txt)

**Comment by SchlumpfIOB** [comment]
Hab in der dev genau das Selbe Problem, auch nach Neuinstallation:

<html><body>


host.raspberrypi-iobroker | 2023-05-09 08:59:12.752 | error | instance system.adapter.roborock.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.raspberrypi-iobroker | 2023-05-09 08:59:12.752 | error | Caught by controller[1]:     at processTimers (node:internal/timers:502:7)
host.raspberrypi-iobroker | 2023-05-09 08:59:12.752 | error | Caught by controller[1]:     at listOnTimeout (node:internal/timers:559:17)
host.raspberrypi-iobroker | 2023-05-09 08:59:12.751 | error | Caught  by controller[1]:     at Timeout._onTimeout  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:1220:17)
host.raspberrypi-iobroker | 2023-05-09 08:59:12.751 | error | Caught by controller[1]:     at /opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:272:12
host.raspberrypi-iobroker | 2023-05-09 08:59:12.751 | error | Caught by controller[1]: Error: Request with id 9979 timed out after 10 seconds for response.102
host.raspberrypi-iobroker | 2023-05-09 08:59:12.750 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:
roborock.0 | 2023-05-09 08:59:11.992 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
roborock.0 | 2023-05-09 08:59:11.990 | info | terminating
roborock.0 | 2023-05-09 08:59:11.968 | error | Request with id 9979 timed out after 10 seconds for response.102
roborock.0 | 2023-05-09 08:59:11.967 | error | Error:  Request with id 9979 timed out after 10 seconds for response.102    at  /opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:272:12     at Timeout._onTimeout  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:1220:17)     at listOnTimeout (node:internal/timers:559:17)    at processTimers  (node:internal/timers:502:7)
roborock.0 | 2023-05-09 08:59:11.638 | error | unhandled promise rejection: Request with id 9979 timed out after 10 seconds for response.102
roborock.0 | 2023-05-09 08:59:11.637 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
roborock.0 | 2023-05-09 08:59:01.634 | warn | Failed to execute get_status. Error: Error: Request with id 6813 timed out after 10 seconds for response.102
roborock.0 | 2023-05-09 08:58:51.630 | warn | Failed to execute get_multi_map_list. Error: Error: Request with id 8031 timed out after 10 seconds for response.102
roborock.0 | 2023-05-09 08:58:41.626 | warn | Failed to execute get_fw_features. Error: Error: Request with id 4493 timed out after 10 seconds for response.102
roborock.0 | 2023-05-09 08:58:27.787 | info | MQTT initialized
roborock.0 | 2023-05-09 08:58:27.012 | info | starting.  Version 0.1.6 (non-npm: copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0,  js-controller: 4.0.24
host.raspberrypi-iobroker | 2023-05-09 08:58:23.992 | info | instance system.adapter.roborock.0 started with pid 28857
host.raspberrypi-iobroker | 2023-05-09 08:58:21.460 | info | instance system.adapter.roborock.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
roborock.0 | 2023-05-09 08:58:20.800 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2023-05-09 08:58:20.797 | info | terminating
host.raspberrypi-iobroker | 2023-05-09 08:58:20.793 | info | stopInstance system.adapter.roborock.0 send kill signal
roborock.0 | 2023-05-09 08:58:20.792 | info | Got terminate signal TERMINATE_YOURSELF
host.raspberrypi-iobroker | 2023-05-09 08:58:20.784 | info | stopInstance system.adapter.roborock.0 (force=false, process=true)
roborock.0 | 2023-05-09 08:58:07.058 | error | Username or password missing!
roborock.0 | 2023-05-09 08:58:06.946 | info | starting.  Version 0.1.6 (non-npm: copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v16.19.0,  js-controller: 4.0.24
host.raspberrypi-iobroker | 2023-05-09 08:58:03.855 | info | instance system.adapter.roborock.0 started with pid 28805


</body>
</html>

Warnungen bzgl. "get_status" warscheinlich wegen Roboter im "Stand-By", siehe anderes Issue.

Gruß
Jan

**Comment by SchlumpfIOB** [comment]
Könnte der Fehler auch mit dem "Stand-By" zu tun haben wie in dem anderen Issue? Oder wurde er schon behoben? Hab jetzt keinen Fehler mehr seit ich die Instanz neu gestartet habe.

**Comment by DonToben** [comment]
Kann ich jetzt auch bestätigen. Wird der Adapter gestartet wenn der Saugroboter gerade aktiv ist, dann funktioniert der Adapter auch und macht keine Resets.

**Comment by DonToben** [comment]
Ich kann's auf die schnelle leider nicht testen. 
@SchlumpfIOB evtl kannst du helfen.

**Comment by copystring** [comment]
Ich kann mich jetzt wieder in ein paar Dinge kümmern. Hatte Corona.
Das Problem habe ich mir mal angeschaut. Wenn mein Saugroboter abgeschaltet war, startete bei mir der Adapter ebenfalls ständig neu. Ich habe an einer Stelle vergessen, den Fehler abzufangen. Dies habe ich in der neuen dev korrigiert. Bitte mal testen.

**Comment by SchlumpfIOB** [comment]
Entschuldigt die späte Rückmeldung, war viel los am Wochenende.

Scheinbar ist es wie gesagt ein Unterschied, ob der Roboter nur in den "sleeping"-Modus geht oder ganz ausschaltet bzw. in eine Art Stand-By ohne Netzwerkverbindung geht.

Bei mir startet die Instanz dann etwa 3mal neu und wird dann nicht mehr rebootet vom Host aus (bleibt also aus).

Hab die neue dev Version jetzt installiert und beobachte es die nächsten Tage.

**Comment by DonToben** [comment]
Fehler behoben
