### ISSUE TITLE
Beschreibungen der Werte

### ISSUE THREAD

**Issue by scriper88** [copystring/ioBroker.roborock#152]
Hallo,

sorry bin erst neu im Game (falls die Frage dumm sein sollte): Wo finde ich denn eine Beschreibung der Objekte die ich in IOBroker sehe und welche ich davon mit Skripten steuern kann?

**Comment by copystring** [comment]
Hi,

deine Frage verstehe ich tatsächlich nicht, aber wenn es sich nicht um einen Fehler oder Wunsch nach einer neuen Funktion des Adapters handelt, wäre es angebrachter im Forum von iobroker nachzufragen.

**Comment by jahnbes** [comment]
Hallo copystring, ich habe die Frage schon verstanden und habe sie (teilweise) auch. Vielleicht stelle ich sie mal anders, gibt es eine Aufstellung, welche Werte der Objektliste welchen realen Werten des roborock entsprechen. Das ist nicht immer eindeutig und manche Werte suche ich schon lang. "Wo bist du" habe ich gefunden und es funktioniert, "Ab zur Ladestation" finde ich nicht. Kannst Du einen Tipp geben, wo eine solche Aufstellung zu finden ist? Viele Grüße und Dank im voraus, Bert.

**Comment by copystring** [comment]
Hallo @jahnbes,

eigentlich sollte alles selbsterklärend sein. Das ist zumindest mein Ansporn. Für start_type z.B. müsste ich noch einbauen, wofür die einzelnen Werte stehen. Das könnte sein, dass 0 für Start durch die App steht, 1 für einen Start durch Zeitplan.
Das kann man ja ausprobieren und die Werte entsprechend in den Adapter einbauen. Dann steht es entsprechend davor, wie hier z.B.: 
![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/ef55584c-b097-4360-8f23-802a8b32201d)
101 steht hier für Quiet
