### ISSUE TITLE
I tried to install on iobroker but got errors

### ISSUE THREAD

**Issue by neanderl** [copystring/ioBroker.roborock#163]
installed with npm i iobroker.roborock
on my Raspberry but got errors

npm ERR! extraneous: semver@6.3.0 /root/node_modules/make-dir/node_modules/semver
npm ERR! extraneous: minipass@3.3.6 /root/node_modules/fs-minipass/node_modules/minipass
npm ERR! extraneous: minipass@3.3.6 /root/node_modules/minizlib/node_modules/minipass
npm ERR! extraneous: debug@2.6.9 /root/node_modules/body-parser/node_modules/debug
npm ERR! extraneous: cookie@0.5.0 /root/node_modules/express/node_modules/cookie
npm ERR! extraneous: debug@2.6.9 /root/node_modules/express/node_modules/debug
npm ERR! extraneous: debug@2.6.9 /root/node_modules/finalhandler/node_modules/debug
npm ERR! extraneous: debug@2.6.9 /root/node_modules/send/node_modules/debug
npm ERR! extraneous: ms@2.1.3 /root/node_modules/send/node_modules/ms
npm ERR! extraneous: ws@7.5.9 /root/node_modules/mqtt/node_modules/ws
root@Homestation:~# npm i iobroker.roborock
npm WARN saveError ENOENT: no such file or directory, open '/root/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

It is at this time not visible in iobroker.

Any ideas or help highly welcome.

Thanks for developing the npm for the roborock app as alternative to the Mii app which I am not using.

**Comment by copystring** [comment]
https://www.youtube.com/watch?v=Sgj_80GCZxE
