### ISSUE TITLE
Support for S7 Max Ultra

### ISSUE THREAD

**Issue by TheRealJohnWick42** [copystring/ioBroker.roborock#206]
Hi,

I just tried to get the adapter working with my S7 Max Ultra (not MaxV). The error log says, that this model is not supported.

_The model ${robotModel} is not supported. Get in touch with the dev to get this robot supported._

I am happy to help testing as soon as some update is available.

Thank You!
John

**Comment by copystring** [comment]
Please try this version https://github.com/copystring/ioBroker.roborock/tree/dev and if the issue persists, post a new log.

**Comment by TheRealJohnWick42** [comment]
Only a slightly different error message now:

_The model roborock.vacuum.a65 is not supported. Get in touch with the dev to get this robot supported._

**Comment by copystring** [comment]
Thanks. This is what I needed. Finally had time to implement it. Please test https://github.com/copystring/ioBroker.roborock/tree/dev again. It has basic support for S7 Max Ultra. There will probably be errors because there will most likely new parameters. Please post a full debug log after testing.

**Comment by TheRealJohnWick42** [comment]
My feedback so far:
Installation worked smoothly, the robot was recognized and there is long list of objects and states which look good to me. I haven't testet the commands yet. From the log I can see the following error messages:

Unsported attribute: dss of get_status. Please contact the dev to add the newly found attribute of your robot.
Unsported attribute: rss of get_status. Please contact the dev to add the newly found attribute of your robot.
Unsported attribute: clean_percent of get_status. Please contact the dev to add the newly found attribute of your robot.
Unsported attribute: rdt of get_status. Please contact the dev to add the newly found attribute of your robot.
Unsported attribute: dry_status of get_status. Please contact the dev to add the newly found attribute of your robot.
Unsported attribute: wash_status of get_status. Please contact the dev to add the newly found attribute of your robot.

Also I think, as this robot has no camera, it would be nice to have the web server for camera streaming optional, to reduce resource consumption.

regards
John

**Comment by copystring** [comment]
Thanks.

I have updated the definition of the robot and made it based of off the S7 instead of S7 MaxV this time. This removes camera support, but there might be new unsupported attributes now.
Please try the new dev: https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by jona7o** [comment]
Hi @copystring, I just installed the new dev version and i got the following unsuported attributes:

`


roborock.0 | 44506 | 2023-07-02 22:13:52.938 | error | Unsported attribute: charge_status of get_status. Please contact the dev to add the newly found attribute of your robot.
-- | -- | -- | -- | --
roborock.0 | 44506 | 2023-07-02 22:13:52.936 | error | Unsported attribute: switch_map_mode of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 44506 | 2023-07-02 22:13:52.935 | error | Unsported attribute: collision_avoid_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 44506 | 2023-07-02 22:13:52.933 | error | Unsported attribute: avoid_count of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 44506 | 2023-07-02 22:13:52.929 | error | Unsported attribute: camera_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 44506 | 2023-07-02 22:13:52.925 | error | Unsported attribute: wash_ready of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 44506 | 2023-07-02 22:13:52.923 | error | Unsported attribute: wash_phase of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 44506 | 2023-07-02 22:13:52.920 | error | Unsported attribute: back_type of get_status. Please contact the dev to add the newly found attribute of your robot.


`

**Comment by copystring** [comment]
Thanks. Please try the new dev.

**Comment by jona7o** [comment]
Here is the next output. Still one new value missing. :)

roborock.0
2023-07-03 18:03:19.797	warn	Failed to execute get_consumable. TypeError: Cannot read properties of undefined (reading 'divider')

roborock.0
2023-07-03 18:03:19.663	error	Unsported attribute: charge_status of get_status with value1. Please contact the dev to add the newly found attribute of your robot.

roborock.0
2023-07-03 18:02:23.009	warn	State "roborock.0.Devices.XXXX.cleaningInfo.Records.9.map_flag" has no existing object, this might lead to an error in future versions

roborock.0
2023-07-03 18:02:23.008	warn	State "roborock.0.Devices.XXXX.cleaningInfo.Records.9.wash_count" has no existing object, this might lead to an error in future versions

roborock.0
2023-07-03 18:02:23.007	warn	State "roborock.0.Devices.XXXX.cleaningInfo.Records.9.avoid_count" has no existing object, this might lead to an error in future versions

**Comment by jona7o** [comment]
I have created a pull request with the missing value. After adding "charge_status" there are no more attributes to add for a65. 

https://github.com/copystring/ioBroker.roborock/pull/316

**Comment by jona7o** [comment]
One last warning, but i am not sure if it is also relevant?


roborock.0 | 2023-07-03 20:29:08.407 | warn | Failed to execute get_consumable. TypeError: Cannot read properties of undefined (reading 'divider')
-- | -- | -- | --
roborock.0 | 2023-07-03 20:29:02.628 | info | MQTT initialized
roborock.0 | 2023-07-03 20:29:00.185 | info | starting. Version 0.1.6 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.16.1, js-controller: 4.0.24

**Comment by copystring** [comment]
Yes. This is relevant but I need a full log to fix this.

**Comment by copystring** [comment]
Thanks for helping (via E-Mail).
Fixed via https://github.com/copystring/ioBroker.roborock/commit/cc2c3b7cfa03a4624ccaa566429eb7c7c2ecb9a2
