### ISSUE TITLE
Adapter throws DB errors; terminates itself (loop); does not show rooms

### ISSUE THREAD

**Issue by mbefore305** [copystring/ioBroker.roborock#26]
**Describe the bug**
See attached log. Several errors:
- DB Error 
- Rooms are not in the adapter objects (but they are visible in the log)
- The adapter terminates itself and then restarts (restart loop).

**To Reproduce**  
Uninstall existing old adapter version (remove adapter object tree, delete instance, delete adapter)
Install new version v0.0.5-alpha.0
Create instance and set instance log level to debug
In instance provide login credentials

**Expected behavior**  
See all robot data in object tree

**Screenshots & Logfiles**  
Debug log attached.

**Versions:**  
 - Adapter version: v0.0.5-alpha.0
 - JS-Controller version: 4.0.24
 - Node version: v16.19.0
 - Operating system: Linux (iobroker runs in a docker container)

**Additional context**  
-
[robolog.txt](https://github.com/copystring/ioBroker.roborock/files/10529410/robolog.txt)

**Comment by copystring** [comment]
Can you try https://github.com/copystring/ioBroker.roborock/tree/report_unknown_attributes and post a new log please?
It seems like your robot has some attributes this adapter does not know yet.

**Comment by mbefore305** [comment]
Great! This works. Rooms are created in Object Tree. No more errors, just the warning
State "roborock.0.Devices.lvv6NMk0FgHC9CvYhGlBT.cleaningInfo.0" has no existing object, this might lead to an error in future versions
Log attached.
[robolog.txt](https://github.com/copystring/ioBroker.roborock/files/10529473/robolog.txt)

**Comment by copystring** [comment]
Ok. Thanks but I need a another log with the latest push. There is still an error so I added some more logging.

**Comment by copystring** [comment]
Ok. Thanks but I need a another log with the latest push. There is still an error so I added some more logging.

**Comment by mbefore305** [comment]
Attached new log.
[robolog.txt](https://github.com/copystring/ioBroker.roborock/files/10529498/robolog.txt)

**Comment by copystring** [comment]
Thanks. As expected your robot has some attributes this adapter does not know yet: distance_off of get_status, camera_status, is_exploring, home_sec_status and home_sec_enable_password

**Comment by copystring** [comment]
Try this again https://github.com/copystring/ioBroker.roborock/tree/report_unknown_attributes and post a new log. The missing attributes should be in deviceStatus but I don't know which data type they have. I might have to correct this according to your log.

**Comment by mbefore305** [comment]
Here comes another log.
[robolog.txt](https://github.com/copystring/ioBroker.roborock/files/10529714/robolog.txt)
