### ISSUE TITLE
0.0.5_report_unknown_attributes Commands Charge, Stop, Pause not working anymore

### ISSUE THREAD

**Issue by DonToben** [copystring/ioBroker.roborock#28]
**Describe the bug**  
0.0.5_report_unknown_attributes Commands Charge, Stop, Pause not working anymore

[Log.log](https://github.com/copystring/ioBroker.roborock/files/10529765/Log.log)

**Comment by copystring** [comment]
https://github.com/copystring/ioBroker.roborock/issues/20#issuecomment-1407649249

**Comment by DonToben** [comment]
Super, gelöst
