### ISSUE TITLE
Alpha 0.0.6 unknown Object values

### ISSUE THREAD

**Issue by wendy2702** [copystring/ioBroker.roborock#30]
Some Objects are empty or showing unknown values:

![grafik](https://user-images.githubusercontent.com/33424168/215342254-c1b893bd-b898-4860-b62c-20f7b9151ef6.png)

![grafik](https://user-images.githubusercontent.com/33424168/215342857-4e0239c3-dfc8-4da4-9b51-5e5b65cddb07.png)

**Comment by copystring** [comment]
This is the data the API provides. No error here.

**Comment by wendy2702** [comment]
OK.

Thanks for Information
