### ISSUE TITLE
Not all rooms are shown as objects

### ISSUE THREAD

**Issue by ravenst0ne** [copystring/ioBroker.roborock#325]
**Describe the bug**  
All rooms are recognized properly:
roborock.0 | 2023-07-13 10:20:46.039 | debug | RoomIDs  debug:  {"7197793":"Arbeitszimmer","7197795":"Schlafzimmer","7197807":"Gästeklo","7197811":"Bad","7197815":"Flur","7223392":"Küche","7223395":"Essbereich","7223396":"Wohnbereich"}

But then not all of them are working to get created:

roborock.0 | 2023-07-13 10:21:59.927 | debug | Mapped room matched: 7223395 with name: Essbereich
roborock.0 | 2023-07-13 10:21:59.926 | debug | Mapped room matched: 7197807 with name: Gästeklo
roborock.0 | 2023-07-13 10:21:59.924 | debug | Mapped room matched: 7197795 with name: Schlafzimmer
roborock.0 | 2023-07-13 10:21:59.924 | debug | Mapped room matched: 7197793 with name: Arbeitszimmer
roborock.0 | 2023-07-13 10:21:59.923 | debug | Mapped room matched: 7197815 with name: Flur
roborock.0 | 2023-07-13 10:21:59.923 | debug | Mapped room matched: 7197811 with name: Bad

**Versions:**  
 - Adapter version: 0.2.1

**Additional context**  
The missing rooms are self-devided. So "Essbereich", "Küche" and "Wohnbereich" were just one room on initial map creation

**Comment by copystring** [comment]
Have you tried uninstalling and reinstalling the adapter?

**Comment by copystring** [comment]
There should be a "All mapped rooms: ..." in your log. Please post that line.

**Comment by ravenst0ne** [comment]
All mapped rooms: [[17,"7197811"],[18,"7197815"],[19,"7197793"],[20,"7197795"],[21,"7197807"],[24,"7223395"]]

**Comment by copystring** [comment]
Weird. There are rooms missing. This is why it's not working. The problem is, this is what roborock provides. I'd have to try to find another way to map the rooms.
Seems to be an issue with how IDs are created after splitting the rooms.
I'll try to find time for this, but I'm afraid it will take a while.

**Comment by ravenst0ne** [comment]
If this issue wasn't recognized by others before as well, no need to give this priority:)

**Comment by ravenst0ne** [comment]
Please to reopen since issue not addressed yet
