### ISSUE TITLE
Betriebsstunden

### ISSUE THREAD

**Issue by Ricox1975** [copystring/ioBroker.roborock#330]
**Versions:**  
 - Adapter version: <0.2.1>
 - JS-Controller version: <4.0.24>
 - Node version: <18.5>
 - Operating system: <asahi linux >

In wieweit kann man dem Betriebsstundenzähler vertrauen.? 
Ich habe das Gerät  (S7 Max Ultra) neu erworben. 
<img width="1395" alt="Bildschirmfoto 2023-07-30 um 15 40 44" src="https://github.com/copystring/ioBroker.roborock/assets/52467622/6f9e76a7-208d-4c72-9c95-849e9f2bf3cd">

**Comment by copystring** [comment]
Das kannst du auch in der Handy App unter dem Reinigungsverlauf finden. Stimmt das überein?

![Screenshot_20230730-162059.png](https://github.com/copystring/ioBroker.roborock/assets/1298861/21b5885e-cd06-4a6d-a456-1409feb545ef)

**Comment by JackDaniel007** [comment]
hier sind es auch 470 stunden, und in wirklichkeit
![Screenshot_20230730-162334](https://github.com/copystring/ioBroker.roborock/assets/2413204/e501e718-f9f8-4aa1-a1a5-c2bc1acfc88f)

**Comment by copystring** [comment]
Entschuldige. Die echte Zeit findest du hier :
![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/a9b4cad3-a86d-4ef7-b737-afcf84c28691)

Was der andere Parameter ausdrückt, weiß ich nicht.

**Comment by Ricox1975** [comment]
33min, dachte schon bin gescammt worden.

![IMG_B4182B1FF972-1](https://github.com/copystring/ioBroker.roborock/assets/52467622/f2d7defd-deb2-4811-8471-15be009681ed)
