### ISSUE TITLE
beim db commands.set_water_box_custom_mode fehlt die auswahl von benutzerdefiniert

### ISSUE THREAD

**Issue by JackDaniel007** [copystring/ioBroker.roborock#331]
habs mal bei mir so geändert und funktioniert (q revo):

{
  "type": "state",
  "common": {
    "name": "Scrub Intensity",
    "type": "number",
    "def": 201,
    "role": "value",
    "read": true,
    "write": true,
    "states": {
      "200": "Off",
      "201": "Mild",
      "202": "Moderate",
      "203": "Intense",
      "207": "User defined"
    }
  },
  "native": {},
  "_id": "roborock.0.Devices.2t7w2Fu7NQgiuZTRbEgxWa.commands.set_water_box_custom_mode",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.jackdaniel",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.jackdaniel",
  "ts": 1690792876166
}

**Comment by JackDaniel007** [comment]
reopen

**Comment by JackDaniel007** [comment]
ja aber nur einmal, dann kann man wie hier über die vis und den adapter das benutzerdefiniert einfach starten
das anlegen der benutzerdefinierten reinigung über den adapter stell ich mir sehr kompliziert vor, man muss ja auf der karte den raum auswählen, definieren was gemacht werden soll (saugen, wischen od. beides), die itensität derer usw...

**Comment by copystring** [comment]
Das ließ sich auch einfach über Datenpunkte realisieren. Für jeden Raum ein wert in dem steht was gemacht werden soll.
