### ISSUE TITLE
Hinzufügen Xiaomi Vacuum S12

### ISSUE THREAD

**Issue by Franek-23** [copystring/ioBroker.roborock#338]
Ist es möglich den neuen Xiaomi Vacuum S12 Staubsaugerroboter mit aufzunehmen?

**Comment by copystring** [comment]
Nein. Die Roborock App unterstützt den nicht und kann daher auch hier nicht hinzugefügt werden. Das ist eine Limitierung von Roborock selbst. Für die Xiaomi Geräte muss der xiaomi Adapter mit Xiaomi App verwendet werden.
