### ISSUE TITLE
Unsupported attribute

### ISSUE THREAD

**Issue by mproper23** [copystring/ioBroker.roborock#34]
0.0.6-alpha.0  installiert.
Debug beim Adapter eingestellt. Hier der Auszug. Hoffe das hilft

`<html><body>

roborock.0 | 2023-01-30 10:23:47.357 | warn | State   "roborock.0.Devices.5jvoTYPcMgvzBKdzXt0fqC.consumables.cleaning_brush_work_times"  has no existing object, this might lead to an error in future versions
-- | -- | -- | --
roborock.0 | 2023-01-30 10:23:47.357 | warn | State   "roborock.0.Devices.5jvoTYPcMgvzBKdzXt0fqC.consumables.strainer_work_times"  has no existing object, this might lead to an error in future versions
roborock.0 | 2023-01-30 10:23:47.328 | error | Unsported attribute: charge_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.328 | error | Unsported attribute: switch_map_mode of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.328 | error | Unsported  attribute: collision_avoid_status of get_status. Please contact the dev  to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.328 | error | Unsported attribute: avoid_count of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.328 | error | Unsported  attribute: home_sec_enable_password of get_status. Please contact the  dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.328 | error | Unsported attribute: home_sec_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.328 | error | Unsported attribute: is_exploring of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.327 | error | Unsported attribute: camera_status of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.327 | error | Unsported attribute: wash_ready of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.327 | error | Unsported attribute: wash_phase of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.327 | error | Unsported attribute: back_type of get_status. Please contact the dev to add the newly found attribute of your robot.
roborock.0 | 2023-01-30 10:23:47.128 | info | MQTT initialized
roborock.0 | 2023-01-30 10:23:46.967 | info | starting.  Version 0.0.6-alpha.0 (non-npm:  copystring/ioBroker.roborock#150a18a009f6fef4f1bd9e8172184412230a6ca3)  in C:/Program Files/iobroker/SmartHome/node_modules/iobroker.roborock,  node: v16.19.0, js-controller: 4.0.24

</body>
</html>`

**Comment by copystring** [comment]
Bitte immer ein komplettes log hier als Datei anhängen oder via pastebin hier verlinken andernfalls kann ich das nicht richtig zuordnen. Danke.

**Comment by mproper23** [comment]
[Roborock.log](https://github.com/copystring/ioBroker.roborock/files/10535392/Roborock.log)
Habe mal das ganze log nochmal hochgeladen

**Comment by copystring** [comment]
Danke aber auch das log ist nicht vollständig. Mir fehlt welcher Roboter das ist. Ganz am Anfang steht immer so etwas: `Robot key: roborock.vacuum.a15`

**Comment by copystring** [comment]
Gelöst via https://github.com/copystring/ioBroker.roborock/pull/56
