### ISSUE TITLE
Installation ioBroker Adapter

### ISSUE THREAD

**Issue by patafix18** [copystring/ioBroker.roborock#346]
Hallo,

ich habe leider Probleme den Adapter im ioBroker zu installieren. Im ioBroker wähle ich die Installation per URL aus (YouTube Video wurde in anderen Issues oft als Referenz angegeben). Als URL habe ich "https://github.com/copystring/ioBroker.roborock" angegeben.
Leider erhalte ich die Fehlermeldung:

$ iobroker url https://github.com/copystring/ioBroker.roborock --host raspberrypi --debug
install copystring/ioBroker.roborock#f322e1c88ca7af6886360894ad8a605bae9b7c62
Installing copystring/ioBroker.roborock#f322e1c88ca7af6886360894ad8a605bae9b7c62... (System call)
host.raspberrypi Cannot install copystring/ioBroker.roborock#f322e1c88ca7af6886360894ad8a605bae9b7c62: 1
ERROR: Process exited with code 25

Habt ihr Tipps zur Fehlerbehebung oder ist die Vorgehensweise zur Installation Falsch?

Danke und viele Grüße

[iobroker.2023-08-09.log.zip](https://github.com/copystring/ioBroker.roborock/files/12302964/iobroker.2023-08-09.log.zip)

**Comment by copystring** [comment]
Hallo,

der Adapter ist in der latest repo verfügbar. Wenn du diese in ioBroker aktivierst, kannst du den Adapter einfach so installieren wie alle anderen Adapter auch. Installieren über die URL ist nicht mehr notwendig, es sei denn es gibt irgendwas Spezielles zum Testen.

Viele Grüße zurück

**Comment by patafix18** [comment]
Leider bleibt bei der Installation der Aufheller bestehen. Ich bekomme nachfolgende Fehlermeldung:
$ iobroker add roborock auto --host raspberrypi --debug
Installing iobroker.roborock@0.2.1... (System call)
host.raspberrypi Cannot install iobroker.roborock@0.2.1: 1
ERROR: Process exited with code 25

**Comment by copystring** [comment]
Was passiert, wenn du versuchst irgendeinen anderen Adapter zu installieren?

**Comment by patafix18** [comment]
Alle anderen Adapter werden ohne Fehlermeldung installiert

**Comment by copystring** [comment]
Prüf Mal bitte, dass der Ordner iobroker.roborock in /opt/iobroker/node_modules/ nicht existiert. Vielleicht kommt das daher.

**Comment by patafix18** [comment]
Der Ordner iobroker.roborock ist in den node_modules bei mir nicht vorhanden. So sollte es auch sein, oder?

**Comment by patafix18** [comment]
Log:


2023-08-22 07:20:28.224 | info | iobroker npm ERR! gyp ERR! node -v v16.13.2npm ERR! gyp ERR! node-gyp -v v8.4.1npm ERR! gyp ERR! not ok npm ERR! node-pre-gyp ERR! build error npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)npm ERR! node-pre-gyp ERR! stack at ChildProcess.<anonymous> (/opt/iobroker/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)npm ERR! node-pre-gyp ERR! stack at ChildProcess.emit (node:events:390:28)npm ERR! node-pre-gyp ERR! stack at maybeClose (node:internal/child_process:1064:16)npm ERR! node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)npm ERR! node-pre-gyp ERR! System Linux 5.4.51-v7+npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/opt/iobroker/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"npm ERR! node-pre-gyp ERR! cwd /opt/iobroker/node_modules/canvasnpm ERR! node-pre-gyp ERR! node -v v16.13.2npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11npm ERR! node-pre-gyp ERR! not oknpm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2023-08-22T05_19_27_699Z-debug-0.log
-- | -- | --
host.raspberrypi | 2023-08-22 07:20:28.221 | info | iobroker npm ERR! gyp ERR! cwd /opt/iobroker/node_modules/canvas
host.raspberrypi | 2023-08-22 07:20:28.209 | info | iobroker npm ERR! path /opt/iobroker/node_modules/canvasnpm ERR! command failednpm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binarynpm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/opt/iobroker/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)npm ERR! node-pre-gyp info it worked if it ends with oknpm ERR! node-pre-gyp info using node-pre-gyp@1.0.11npm ERR! node-pre-gyp info using node@16.13.2 \| linux \| armnpm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-linux-glibc-arm.tar.gznpm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-linux-glibc-arm.tar.gz npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@16.13.2 (node-v93 ABI, glibc) (falling back to source compile with node-gyp) npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v93-linux-glibc-arm.tar.gz npm ERR! gyp info it worked if it ends with oknpm ERR! gyp info using node-gyp@8.4.1npm ERR! gyp info using node@16.13.2 \| linux \| armnpm ERR! gyp info ok npm ERR! gyp info it worked if it ends with oknpm ERR! gyp info using node-gyp@8.4.1npm ERR! gyp info using node@16.13.2 \| linux \| armnpm ERR! gyp info find Python using Python version 3.7.3 found at "/usr/bin/python3"npm ERR! gyp info spawn /usr/bin/python3npm ERR! gyp info spawn args [npm ERR! gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',npm ERR! gyp info spawn args 'binding.gyp',npm ERR! gyp info spawn args '-f',npm ERR! gyp info spawn args 'make',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/opt/iobroker/node_modules/canvas/build/config.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',npm ERR! gyp info spawn args '-I',npm ERR! gyp info spawn args '/home/iobroker/.cache/node-gyp/16.13.2/include/node/common.gypi',npm ERR! gyp info spawn args '-Dlibrary=shared_library',npm ERR! gyp info spawn args '-Dvisibility=default',npm ERR! gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/16.13.2',npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',npm ERR! gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/16.13.2/<(target_arch)/node.lib',npm ERR! gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/canvas',npm ERR! gyp info spawn args '-Dnode_engine=v8',npm ERR! gyp info spawn args '--depth=.',npm ERR! gyp info spawn args '--no-parallel',npm ERR! gyp info spawn args '--generator-output',npm ERR! gyp info spawn args 'build',npm ERR! gyp info spawn args '-Goutput_dir=.'npm ERR! gyp info spawn args ]npm ERR! Package cairo was not found in the pkg-config search path.npm ERR! Perhaps you should add the directory containing `cairo.pc'npm ERR! to the PKG_CONFIG_PATH environment variablenpm ERR! No package 'cairo' foundnpm ERR! gyp: Call to 'pkg-config cairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gypnpm ERR! gyp ERR! configure error npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1npm ERR! gyp ERR! stack at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:259:16)npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:390:28)npm ERR! gyp ERR! stack at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)npm ERR! gyp ERR! System Linux 5.4.51-v7+npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/opt/iobroker/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/opt/iobroker/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
host.raspberrypi | 2023-08-22 07:20:28.191 | info | iobroker npm ERR! code 1
host.raspberrypi | 2023-08-22 07:19:26.525 | info | iobroker Installing iobroker.roborock@0.2.1... (System call)

**Comment by copystring** [comment]
Ja so ist es richtig.

**Comment by copystring** [comment]
Hast du noch ein anderes System wo man das installieren vom Adapter testen könnte? Es ist nicht das erste Mal, dass der Adapter auf einem Raspberry Pi nicht läuft da die canvas Bibliothek auf einem Raspberry Pi nicht läuft. Diese wird aber für das erstellen der Karte benötigt.

**Comment by patafix18** [comment]
Leider nein. Es scheint aber wirklich an der canvas Bibliothek zu liegen. Ich kann diese bei mir leider nicht installieren, da diese wohl nicht mehr verfügbar ist

**Comment by copystring** [comment]
Kannst du dann auf dem Raspberry pi auch die Kartenerstellung aktivieren und nutzen, ohne dass der Adapter abstürzt? Das war bisher nicht möglich bzw. war unklar, wie das zu realisieren ist.

**Comment by patafix18** [comment]
Nein. Sobald ich die Kartendarstellung aktiviere stürzt der Adapter ab.

**Comment by copystring** [comment]
Ok. Schade. Dann bleibt es dabei, dass die Kartenerstellung auf einem Pi nicht geht. Kann also abgeschlossen werden, da die Installation durchlief?

**Comment by patafix18** [comment]
Kann geschlossen werden, danke für die Unterstützung.
