### ISSUE TITLE
Unknown block type! Please report this to the developer. Block type is:34

### ISSUE THREAD

**Issue by JackDaniel007** [copystring/ioBroker.roborock#347]
Q Revo

`<html>
<body>

roborock.0 | 2023-08-10 15:27:36.057 | warn | Unknown block type! Please report this to the developer. Block type is:34
-- | -- | -- | --
roborock.0 | 2023-08-10 15:27:36.052 | debug | Length of message queue: 0
roborock.0 | 2023-08-10 15:27:36.025 | debug | Length of message queue: 1
roborock.0 | 2023-08-10 15:27:36.025 | debug | Not clearing messageQueue. null - 36426
roborock.0 | 2023-08-10 15:27:36.024 | debug | dps debug: {"id":9085,"result":["ok"]}
roborock.0 | 2023-08-10 15:27:35.818 | debug | Update map
roborock.0 | 2023-08-10 15:27:35.072 | warn | Unknown block type! Please report this to the developer. Block type is:34
roborock.0 | 2023-08-10 15:27:35.056 | debug | Length of message queue: 0
roborock.0 | 2023-08-10 15:27:35.028 | debug | Length of message queue: 1
roborock.0 | 2023-08-10 15:27:35.028 | debug | Not clearing messageQueue. null - 36329
roborock.0 | 2023-08-10 15:27:35.027 | debug | dps debug: {"id":1457,"result":["ok"]}
roborock.0 | 2023-08-10 15:27:34.818 | debug | Update map
roborock.0 | 2023-08-10 15:27:34.065 | warn | Unknown block type! Please report this to the developer. Block type is:34
roborock.0 | 2023-08-10 15:27:34.038 | debug | Length of message queue: 0
roborock.0 | 2023-08-10 15:27:34.008 | debug | Length of message queue: 1
roborock.0 | 2023-08-10 15:27:34.008 | debug | Not clearing messageQueue. null - 36232
roborock.0 | 2023-08-10 15:27:34.007 | debug | dps debug: {"id":6746,"result":["ok"]}
roborock.0 | 2023-08-10 15:27:33.817 | debug | Update map
roborock.0 | 2023-08-10 15:27:33.102 | warn | Unknown block type! Please report this to the developer. Block type is:34
roborock.0 | 2023-08-10 15:27:33.082 | debug | Length of message queue: 0
roborock.0 | 2023-08-10 15:27:33.055 | debug | Length of message queue: 1
roborock.0 | 2023-08-10 15:27:33.055 | debug | Not clearing messageQueue. null - 36133
roborock.0 | 2023-08-10 15:27:33.054 | debug | dps debug: {"id":2210,"result":["ok"]}
roborock.0 | 2023-08-10 15:27:32.817 | debug | Update map
roborock.0 | 2023-08-10 15:27:32.104 | warn | Unknown block type! Please report this to the developer. Block type is:34
roborock.0 | 2023-08-10 15:27:32.094 | debug | Length of message queue: 0
roborock.0 | 2023-08-10 15:27:32.049 | debug | Length of message queue: 1
roborock.0 | 2023-08-10 15:27:32.048 | debug | Not clearing messageQueue. null - 36036
roborock.0 | 2023-08-10 15:27:32.048 | debug | dps debug: {"id":6812,"result":["ok"]}
roborock.0 | 2023-08-10 15:27:31.817 | debug | Update map
roborock.0 | 2023-08-10 15:27:31.126 | warn | Unknown block type! Please report this to the developer. Block type is:34
roborock.0 | 2023-08-10 15:27:31.109 | debug | Length of message queue: 0
roborock.0 | 2023-08-10 15:27:31.061 | debug | Length of message queue: 1
roborock.0 | 2023-08-10 15:27:31.061 | debug | Not clearing messageQueue. null - 35938
roborock.0 | 2023-08-10 15:27:31.060 | debug | dps debug: {"id":2902,"result":["ok"]}
roborock.0 | 2023-08-10 15:27:30.816 | debug | Update map
roborock.0 | 2023-08-10 15:27:30.095 | warn | Unknown block type! Please report this to the developer. Block type is:34

</body>
</html>`

**Comment by Bloe0815** [comment]
> Maybe you can help me figure out which block type this is, so I can correctly add this to the map created by this adapter.

How can I help you with this?

**Comment by copystring** [comment]
Blocks are objects on the map. With the new robots there is probably a new object type on the map.
Did this error appear from the beginning?
Maybe it happened after you crested a new object on the map or maybe the robot might have found a new object.
If you want you can post a screenshot of the map and I might see what's going on.

**Comment by Bloe0815** [comment]
I guess the errer is from the beginning, but I am not sure. Nothing was changed since then.
as you can see there are virual walls, nogo-areas and 'Dustpan's. In the app these are obstacles.
![image](https://github.com/copystring/ioBroker.roborock/assets/140397849/510fbc07-95ec-4854-a956-658e390d1ff7)

Does this help?

**Comment by copystring** [comment]
Does the error disappear when you remove the walls and forbidden zones?

**Comment by copystring** [comment]
Wait. No that should not matter. I need a screenshot of the map in the app. Not in the adapter.

**Comment by Bloe0815** [comment]
I hope you can see the symbols here:
![Screenshot_20230827-011309](https://github.com/copystring/ioBroker.roborock/assets/140397849/d4576561-b5d4-4f0d-a99f-043856661947)

**Comment by Bloe0815** [comment]
One annotation:
The block type warning appears every 0.5-2 s, but only when the robot is moving. I assume that this is because the map get refreshed?
If I turn off the map option the warning does not longer appear, but of course the map does not get updated in the ioBroker anymore.

**Comment by copystring** [comment]
Yes, the map does not get updated unless the robot is currently cleaning.
I have to think of something how to debug this further. Needs a special build of the adapter. I'll take a look at what I can do to make this work.
