### ISSUE TITLE
after software update on roborock to02.58.40

### ISSUE THREAD

**Issue by jahnbes** [copystring/ioBroker.roborock#348]
<html>
<body>

roborock.0 | 2023-08-11 15:29:01.823 | error | Unsported attribute: clean_percent of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.
-- | -- | -- | --

</body>
</html>

**Comment by copystring** [comment]
Thanks but I always need a full debug log to know which robot needs the adjustment.

**Comment by jahnbes** [comment]
It's a roborock S7 MaxV without any dock. Here is the hopefully complete log:
[iobroker.2023-08-14.log](https://github.com/copystring/ioBroker.roborock/files/12333257/iobroker.2023-08-14.log)

**Comment by copystring** [comment]
OK. I checked the log. Sadly it's missing the start of the adapter. Please restart the adapter and then post the log of that. I need this to get the correct model of robot.

**Comment by jahnbes** [comment]
High copystring, here is it. Hopefully. Best regards, Bert.
[iobroker.2023-08-22.log](https://github.com/copystring/ioBroker.roborock/files/12405951/iobroker.2023-08-22.log)

**Comment by copystring** [comment]
Please try the dev to see if it's fixed: https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by jahnbes** [comment]
It's ok now, thanks, I have immediately entered  **clean_percent** into the Wiki.

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/commit/5c4b161312687e8d94989d7772b726c4564bc825
