### ISSUE TITLE
fehlende Funktionen

### ISSUE THREAD

**Issue by mproper23** [copystring/ioBroker.roborock#35]
Was mir noch aufgefallen ist:
In der App habe ich die Möglichkeit manuell das Absaugen und das Mopwaschen an zu stoßen.
Wäre es möglich dies auch zu integrieren?
Was auch fehlt sind von der Station die Reinigungsbürste und der Wasserfilter als DP

**Comment by copystring** [comment]
An sich ist das ganz sicherlich möglich aber dafür müsste ich die Befehle kennen.
Ich werde nachher Mal danach schauen.

**Comment by copystring** [comment]
Ist das wirklich das Waschen des Mops oder das trocknen? Für das Trocknen habe ich was gefunden aber nicht fürs Waschen.

**Comment by mproper23** [comment]
![F70844A2-E69E-41CA-A9F7-E7A7D7E6B1B6](https://user-images.githubusercontent.com/25171131/216147853-dc4b541e-565d-4647-8b56-acc193f76627.jpeg)

man kann manuell die wäsche und das absaugen anstoßen

**Comment by copystring** [comment]
S7 MaxV Ultra oder?

**Comment by copystring** [comment]
Habe app_start_wash und app_stop_wash gefunden und entsprechend hinzugefügt.

**Comment by mproper23** [comment]
Ja

**Comment by mproper23** [comment]
App_Start_collect_dust löst das absaugen an der Station aus
App_Start_wash löst das Mop waschen aus.
Passt soweit

**Comment by copystring** [comment]
Und das absaugen?

**Comment by mproper23** [comment]
hab gerade meinen Comment aktualisiert. Sorry

**Comment by copystring** [comment]
OK und funktioniert dust_collection?

**Comment by copystring** [comment]
> roborock.0.Devices.5jvoTYPcMgvzBKdzXt0fqC.consumables.cleaning_brush_work_times
> Das ist dann die Waschbürste für den Mop
> High-Speed maintenance brush in der App
> roborock.0.Devices.5jvoTYPcMgvzBKdzXt0fqC.consumables.strainer_work_times
> und das der Wasserfilter in der Station
> Water Filter in der App

Sind das dann die Zeiten bis die ersetzt werden müssen? Magst du mir ein Screenshot von der App schicken? Wenn ich weiß wie es da aussieht kann ich mit den Daten mehr anfangen

**Comment by mproper23** [comment]
![0E39B8BF-9901-4A71-8BB1-863CD4D16470](https://user-images.githubusercontent.com/25171131/216335353-73af21cd-1a94-4289-9958-e0b180403e83.png)

**Comment by mproper23** [comment]
bei den States fehlen noch die Objekte.
`roborock.0
	2023-02-02 14:19:52.827	warn	State "roborock.0.Devices.5jvoTYPcMgvzBKdzXt0fqC.consumables.cleaning_brush_work_times" has no existing object, this might lead to an error in future versions
roborock.0
	2023-02-02 14:19:52.827	warn	State "roborock.0.Devices.5jvoTYPcMgvzBKdzXt0fqC.consumables.strainer_work_times" has no existing object, this might lead to an error in future versions`

**Comment by copystring** [comment]
OK.
Alles sollte durch https://github.com/copystring/ioBroker.roborock/pull/55 und https://github.com/copystring/ioBroker.roborock/pull/56 gelöst sein.

**Comment by mproper23** [comment]
@copystring Status 23 und 26 sind in der 0.0.7 noch nicht integriert?

**Comment by copystring** [comment]
Doch: https://github.com/copystring/ioBroker.roborock/commit/5aab0ca3886e63ccf74f9e1db7d048515b7ac29d

**Comment by mproper23** [comment]
Dann lösch ich den Adapter nochmal und installiere neu
