### ISSUE TITLE
Roboter offline --> viele Einträge im Log

### ISSUE THREAD

**Issue by fuchs-1978** [copystring/ioBroker.roborock#352]
Einer meiner S7 muss leider wegen eines defekten Lüfters in der Garantie zur Reparatur.

Der Adapter erzeugt jetzt sehr viele Infomeldungen 99+.

<html>
<body>

roborock.0 | 2023-08-22 10:22:41.954 | warn | Failed to execute get_carpet_mode. Error: Request with id 3731 timed out after 10 seconds for response.102
-- | -- | -- | --
roborock.0 | 2023-08-22 10:22:41.954 | warn | Failed to execute get_timer. Error: Request with id 6797 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:22:41.953 | warn | Failed to execute get_server_timer. Error: Request with id 3750 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:22:31.952 | warn | Failed to execute get_network_info. Error: Request with id 5216 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:22:21.951 | warn | Failed to execute get_consumable. Error: Request with id 7850 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:22:11.950 | warn | Failed to execute get_status. Error: Request with id 3467 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:22:01.962 | warn | Failed to execute get_water_box_custom_mode. Error: Request with id 7554 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:22:01.948 | warn | Failed to execute get_status. Error: Request with id 1082 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:51.961 | warn | Failed to execute get_carpet_clean_mode. Error: Request with id 8986 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:41.959 | warn | Failed to execute get_carpet_mode. Error: Request with id 4699 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:41.958 | warn | Failed to execute get_timer. Error: Request with id 7275 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:41.954 | warn | Failed to execute get_server_timer. Error: Request with id 4381 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:39.594 | warn | Failed to execute load_multi_map. Error: There was an error processing the request with id 4414 error: {"code":-10007,"message":"invalid status"}
roborock.0 | 2023-08-22 10:21:31.963 | warn | Failed to execute get_clean_summary. Error: Request with id 9143 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:31.951 | warn | Failed to execute get_network_info. Error: Request with id 2467 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:21.962 | warn | Failed to execute get_water_box_custom_mode. Error: Request with id 4400 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:21.950 | warn | Failed to execute get_consumable. Error: Request with id 4877 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:11.961 | warn | Failed to execute get_carpet_clean_mode. Error: Request with id 4216 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:11.948 | warn | Failed to execute get_status. Error: Request with id 7828 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:01.960 | warn | Failed to execute get_carpet_mode. Error: Request with id 9981 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:01.958 | warn | Failed to execute get_timer. Error: Request with id 6190 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:01.958 | warn | Failed to execute get_server_timer. Error: Request with id 3622 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:21:01.946 | warn | Failed to execute get_status. Error: Request with id 1695 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:20:51.956 | warn | Failed to execute get_network_info. Error: Request with id 2034 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:20:41.955 | warn | Failed to execute get_consumable. Error: Request with id 2442 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:20:31.953 | warn | Failed to execute get_status. Error: Request with id 3057 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:20:21.952 | warn | Failed to execute get_status. Error: Request with id 8676 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:20:11.951 | warn | Failed to execute get_multi_map_list. Error: Request with id 7609 timed out after 10 seconds for response.102
roborock.0 | 2023-08-22 10:20:01.949 | warn | Failed to execute get_fw_features. Error: Request with id 9240 timed out after 10 seconds for response.102

</body>
</html>

Vielleicht kann man diese unterdrücken mit der einfachen Meldung Roboter ist offline?

**Comment by copystring** [comment]
Reicht es nicht das logging auf Error umzustellen? Warnungen und Infos sind nur fürs Debugging interessant.

**Comment by fuchs-1978** [comment]
Wenn es ein beabsichtigtes Verhalten ist auf alle Fälle, so habe ich es auch gemacht. Dachte nur das wäre so nicht gewollt 😜 dann gerne schließen
