### ISSUE TITLE
Dock_Error_Status

### ISSUE THREAD

**Issue by mproper23** [copystring/ioBroker.roborock#36]
0 = kein Fehler
38 = Hallsensor Frischwassertank ausgelöst. Tank leer oder nicht eingesetzt

Wird noch ergänzt

**Comment by copystring** [comment]
https://community.symcon.de/t/modul-roborock-xiaomi-vacuum-cleaner/46511/473

**Comment by copystring** [comment]
https://github.com/rytilahti/python-miio/blob/master/miio/integrations/roborock/vacuum/vacuumcontainers.py#L93-L97

**Comment by mproper23** [comment]
„dock_error_status“:0 => Alles OK.
„dock_error_status“:34 => Ladestation blockiert bei automatischer Entleerung. Staubbehälter, Filter oder Luftkanal ist verstopft. Prüfen und reinigen Sie die Komponenten.
„dock_error_status“:38 => Hallsensor für Reinwassertank ausgelöst. Überprüfen Sie, ob der Reinwassertank korrekt eingesetzt ist oder füllen Sie diesen wie empfohlen nach.
„dock_error_status“:39 => Überprüfen Sie den Schmutzwassertank. Überprüfen Sie, ob der Schmutzwassertank korrekt eingesetzt ist oder leeren Sie diesen wie empfohlen.
„dock_error_status“:46 => Staubbehälter nicht installiert. Staubbehälter mit Beutel wieder einsetzen und erneut versuchen.

**Comment by copystring** [comment]
Gibt es vielleicht noch Möglichkeiten oder nur 0,34,38,39,46?
Das Problem ist, dass jedes mal wenn neue Statusmöglichkeiten hinzugefügt werden, muss das entsprechende Objekt in ioBroker gelöscht werden damit sich das richtige neu geholt wird.
Daher wäre es wichtig dies nur ein mal aber vollständig anzupassen.

**Comment by mproper23** [comment]
Ich habe gestern noch versucht mehr Meldungen zu bekommen. Aber es scheint so als ob diese 4 alle sind. Die Mobwaschbürste wird wohl nicht abgefragt, nur als Consumable. Genauso der Wasserfilter

**Comment by mproper23** [comment]
Kann ich machen, sobald wieder ein Fehler ansteht. App lässt sich umstellen

**Comment by mproper23** [comment]
„dock_error_status“:38 => Check the clean water Tank. Check the tank placement or refill as required
Rest kommt nach

**Comment by mproper23** [comment]
„dock_error_status“:39 => Check the dirty water tank. Check the tank palcement or emtpy as required

**Comment by copystring** [comment]
Konntest du noch weitere Wörter finden?

**Comment by mproper23** [comment]
Mehr habe ich bisher nicht bekommen

**Comment by mproper23** [comment]
Einen hab ich noch:
„dock_error_status“:42 => Maintencance brush jammed. Clean it an remove blockages
