### ISSUE TITLE
Action button Clean für jeden Raum einzeln

### ISSUE THREAD

**Issue by belstroem** [copystring/ioBroker.roborock#368]
gibt es die Möglichkeit, wie im Mi-home Vakuum Adapter für jeden Raum einen einzelnen Start Befehl zu haben? 
Ich konnte damit direkt die einzelne Raumreinigung starten

Vielen Dank
Gruss
Björn

**Comment by copystring** [comment]
Hallo Björn,

das ist bereits möglich. Siehe den Beitrag um Forum von Bert: https://forum.iobroker.net/topic/67186/neuer-adapter-f%C3%BCr-roborock-staubsauger/6?_=1694036670847

Ist das ausreichend?

Viele Grüße zurück

**Comment by belstroem** [comment]
Hallo Danke für die Info das hatte ich gesehen, dann muss ich für jeden Raum ein Script schreiben, das wollte ich umgehen. Danke und GrussBjörn Am 06.09.2023 um 23:54 schrieb copystring ***@***.***>:﻿
Hallo Björn,
das ist bereits möglich. Siehe den Beitrag um Forum von Bert: https://forum.iobroker.net/topic/67186/neuer-adapter-f%C3%BCr-roborock-staubsauger/6?_=1694036670847
Ist das ausreichend?
Viele Grüße zurück
