### ISSUE TITLE
Adapter funktioniert nicht

### ISSUE THREAD

**Issue by lysy23** [copystring/ioBroker.roborock#369]
Hi,

funktioniert bei mir nicht. Vielleicht kannst du mit helfen. 

[roborock.0.csv](https://github.com/copystring/ioBroker.roborock/files/12567733/roborock.0.csv)

**Comment by copystring** [comment]
Hi,

poste bitte ein debug log. Du musst das Logging für den Adapter von Error auf debug umstellen.

**Comment by lysy23** [comment]
hab ich gemacht, leider bekomme ich kein debug Fehler nur error was ich schone gepostet habe. 
![roborock](https://github.com/copystring/ioBroker.roborock/assets/144564555/ec29007f-c00c-43cf-a46d-38861f30cc45)

**Comment by copystring** [comment]
Welche Version von nodejs, js-controller?
Hast du schon mal versucht den Adapter zu löschen und neu zu installieren?

**Comment by lysy23** [comment]
Node.js: v18.17.1
NPM: 9.6.7
js-controller: 4.0.24

ich hab ihn mehrmals gelöscht und neu installiert. Bis gestern habe ich ein  mihome-vacuum Adapter verwendet und es hat alles funktioniert nur mit der Smartphone-App war ich nicht so zufrieden deswegen wollte ich zur Roborock-App wechseln.

**Comment by copystring** [comment]
zeig mal das log vom installieren des adapters

**Comment by lysy23** [comment]
[loginst.csv](https://github.com/copystring/ioBroker.roborock/files/12567966/loginst.csv)

**Comment by copystring** [comment]
Das ist dasselbe log wie davor, wenn der Adapter gestartet wird.
Wenn der Adapter installiert wird, sieht das so aus: 
![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/4c51ccd5-9020-4a28-ad4d-aba163a3c8b5)
Das log brauche ich.

**Comment by lysy23** [comment]
[instalog.csv](https://github.com/copystring/ioBroker.roborock/files/12567971/instalog.csv)

**Comment by copystring** [comment]
Ok. Lösch mal bitte den Adapter aus Instanzen und aus der liste von Adapter heraus und installier ihn dann wieder.
![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/0696cb24-bf97-4e2f-8dba-8357a093ea7f)

**Comment by lysy23** [comment]
Hat nicht geholfen. Oder hat das mit dem Webserver Port zu tun ?

**Comment by copystring** [comment]
Glaube nicht. Bei dir ist das Problem canvas.
Error: \\?\C:\yyyyyyyyyyy\xxxxxxxxxx\zzzzzzzzzz\node_modules\canvas\build\Release\canvas.node ist keine zulässige Win32-Anwendung.

Zeig mal deine Einstellungen.

**Comment by lysy23** [comment]
![23](https://github.com/copystring/ioBroker.roborock/assets/144564555/a921afac-d728-4cf9-802e-6829ecccc020)

**Comment by copystring** [comment]
OK. Sieht gut aus.
Existiert C:\yyyyyyyyyyy\xxxxxxxxxx\zzzzzzzzzz\node_modules\canvas\build\Release\canvas.node denn überhaupt?

**Comment by lysy23** [comment]
ja die Datei ist vorhanden. Egal, wenn es nicht geht dann werde ich wieder zur Mihome wechseln.

**Comment by lysy23** [comment]
Hab die Datei canvas.node gelöscht und der Adapter funktioniert jetzt

**Comment by jensus11** [comment]
Sieht jetzt erst mal besser aus. Keine Warn -oder Fehlermeldungen.
Leider öffnet sich die map.html nicht mehr.

![Bildschirmfoto 2023-09-10 um 15 46 13](https://github.com/copystring/ioBroker.roborock/assets/17987533/158d685d-92ae-4fe7-8ad4-5023f1a47c3e)

**Comment by copystring** [comment]
Für die Karte wird die canvas benötigt. Irgendwas stimmt mit deinem System halt nicht.

**Comment by jensus11** [comment]
Ich habe mich korrigiert. Muss auch Kartenerstellung aktivieren.
Seite und Karte wird mir angezeigt.
Diese Meldungen kommen noch.

Failed to execute get_clean_record_map on robot XXXXXX Error: Request with 7986 timed out after 10 seconds for response.301

Failed to execute get_clean_record_map on robot XXXXXXX Error: Request with id 2428 timed out after 10 seconds for response.102

**Comment by copystring** [comment]
Das sind keine Fehlermeldungen. Timeouts kommen halt, wenn der Roboter nicht antwortet oder keine Internetverbindung da ist.

**Comment by jensus11** [comment]
Ok, das ist nur während des Reinigens, wenn er am Dock hängt, kommen keine Meldungen.

**Comment by copystring** [comment]
Ja, weil nur beim Reinigen die Karte aktualisiert wird.
