### ISSUE TITLE
Unsported attribute: distance_off of get_status

### ISSUE THREAD

**Issue by D-Hunt3r** [copystring/ioBroker.roborock#37]
Version 0.0.6-alpha.0
Roborock s5 Max
[RoboRock_log.txt](https://github.com/copystring/ioBroker.roborock/files/10535609/RoboRock_log.txt)

**Comment by copystring** [comment]
Please set logging of the Adapter to debug and create a new log so I can assign this issue properly to my code. Thanks.

**Comment by D-Hunt3r** [comment]
@copystring 
https://pastebin.com/u1tU2RQw

**Comment by copystring** [comment]
Added distance_off and also changed the way cleaningInfo for this robot ist defined. Try https://github.com/copystring/ioBroker.roborock/tree/missing_attributes_s5e and add a new log via pastebin. Thank you.

**Comment by D-Hunt3r** [comment]
https://pastebin.com/gzdqgrET

**Comment by copystring** [comment]
Thanks but not I had to add more logging and fix cleaningInfo IDs. Please test this and post a new log: https://github.com/copystring/ioBroker.roborock/commits/missing_attributes_s5e
Then I can most likely fix your issues.

**Comment by D-Hunt3r** [comment]
https://pastebin.com/8ci2fJkA

**Comment by copystring** [comment]
Thanks. I made some updates: https://github.com/copystring/ioBroker.roborock/commits/missing_attributes_s5e
I'm sure that there will be more things to add so I need another log after this one. I assume the cleaning records won't work yet.

Can you confirm this by comparing the values to the values provided by the app?
roborock.0.Devices.YOUR_ID.cleaningInfo.0 = cleaning area
roborock.0.Devices.YOUR_ID.cleaningInfo.1 = cleaning time
roborock.0.Devices.YOUR_ID.cleaningInfo.2 = cleaning count

**Comment by D-Hunt3r** [comment]
![grafik](https://user-images.githubusercontent.com/22468325/216264618-fb0f5cb2-0f0f-4cb6-b8f7-74f5cad7cb18.png)
![grafik](https://user-images.githubusercontent.com/22468325/216264648-1787468c-1497-460b-8f5d-e9c2f3c3b3a7.png)

**Comment by D-Hunt3r** [comment]
Ob die Einheit Stimmt kann ich nicht sehen

**Comment by D-Hunt3r** [comment]
https://github.com/copystring/ioBroker.roborock/commits/missing_attributes_s5e gelöscht? Wollte es gerade testen

**Comment by copystring** [comment]
Ja da hab es einen Fehler. Muss das heute Abend neu erstellen wenn ich wieder zu Hause bin

**Comment by copystring** [comment]
https://github.com/copystring/ioBroker.roborock/commits/missing_attributes_s5e ist wieder da

**Comment by D-Hunt3r** [comment]
https://pastebin.com/2sf766vM

**Comment by copystring** [comment]
Neues Update: https://github.com/copystring/ioBroker.roborock/tree/missing_attributes_s5e

**Comment by D-Hunt3r** [comment]
Da ist ein { zu viel in Zeile 433

`if ((cleaningAttribute != "records") && (cleaningAttribute != "3")) **_{_** {`

**Comment by D-Hunt3r** [comment]
Jetzt habe ich keine Fehlermeldungen mehr.
Nur noch, dass das nicht richtig ist:

![grafik](https://user-images.githubusercontent.com/22468325/216701646-d4316cb4-0ce2-41cb-a2af-692d627023b0.png)

![grafik](https://user-images.githubusercontent.com/22468325/216701895-d2b92750-af10-4cba-9aef-b255804cd2dc.png)

**Comment by copystring** [comment]
OK. Müsste jetzt gefixt sein: https://github.com/copystring/ioBroker.roborock/tree/missing_attributes_s5e dann müssten die Gesamtzeit und der Gesamtbereich passen

**Comment by D-Hunt3r** [comment]
Perfekt 

![grafik](https://user-images.githubusercontent.com/22468325/216706433-10cc502f-ff0a-47d9-a6af-21591cf99836.png)

**Comment by copystring** [comment]
Ok. Eine Sache noch in meinem Interesse. Für das Testen wurde ein Attribut 3 angelegt. Das ist aber eigentlich der Ordner Records. Wird Records bei dir sauber ausgefüllt? Dann könnte ich das hier abschließen.

**Comment by D-Hunt3r** [comment]
Obwohl, da steht m³ anstatt m² 

Das habe ich bei record:
![grafik](https://user-images.githubusercontent.com/22468325/216707053-944c6e0d-bd1c-435b-95c0-330e531c9d0b.png)

**Comment by copystring** [comment]
OK. Sollte jetzt laufen und m³ habe ich m² geändert. https://github.com/copystring/ioBroker.roborock/tree/missing_attributes_s5e

**Comment by D-Hunt3r** [comment]
da hast du ein m³ übersehen

https://github.com/copystring/ioBroker.roborock/blob/missing_attributes_s5e/lib/roborock_vacuum_s5e.js

**Comment by copystring** [comment]
Stimmt. Hab es angepasst.

**Comment by D-Hunt3r** [comment]
jetzt passt es 👍

**Comment by copystring** [comment]
Records wird auch sauber ausgefüllt?

**Comment by D-Hunt3r** [comment]
Ne da hat sich nichts verändert

**Comment by copystring** [comment]
Oh ja kann nicht gehen. Jetzt müsste es aber laufen.

**Comment by D-Hunt3r** [comment]
https://pastebin.com/0ZyK6haA

**Comment by copystring** [comment]
Äh okay und das ging vor dem letzten Update?

**Comment by copystring** [comment]
Bitte nochmal testen. Hoffentlich habe ich diesmal alles erwischt: https://github.com/copystring/ioBroker.roborock/tree/missing_attributes_s5e

**Comment by D-Hunt3r** [comment]
jetzt geht es wieder, aber jetzt gaaaanz viele andere Meldungen :-P

https://pastebin.com/FmTVseTB

**Comment by copystring** [comment]
Genau die hab ich aber gebraucht. Bei dem S5 (Max) scheint alles über nummern anstatt über Namen zu laufen. Das muss man alles für den nochmal anpassen.

**Comment by copystring** [comment]
Ich habe mehr logging zur branch hinzugefügt. Dann kann ich im Log sehen wie ich den Adapter für deinen Roboter anpassen muss.

**Comment by D-Hunt3r** [comment]
https://pastebin.com/HEr5z5Fp

**Comment by copystring** [comment]
Danke für das log. Das war genau das was ich gebraucht habe.
Ich habe jetzt ein Update erstellt. Theoretisch müsste jetzt alles laufen.

**Comment by D-Hunt3r** [comment]
Ich teste es :-) Danke

**Comment by D-Hunt3r** [comment]
Sieht gut aus, keine Fehler

![grafik](https://user-images.githubusercontent.com/22468325/216773123-36e1a32b-3c32-4d4b-96f6-45d316a50dc0.png)

**Comment by copystring** [comment]
Wunderbar. Dann kann ich das so abschließen.

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/pull/58
