### ISSUE TITLE
Adapter stürzt laufend ab

### ISSUE THREAD

**Issue by jensus11** [copystring/ioBroker.roborock#370]
Hi, 
ich bekomme immer Fehlermeldungen, das geht dann so weit, dass Iobroker eine Warnung über häufig abstürzende Adapter herausgibt.
Muss ich was nach installieren(Caught by controller[0]: Downloading AlexxIT/go2rtc@v1.7.0...) oder fehlen irgendwelche Rechte?
Neuinstallation des Adapters hat nicht gebracht.
Saugroboter ist der S8 Pro.

![Bildschirmfoto 2023-09-10 um 12 41 08](https://github.com/copystring/ioBroker.roborock/assets/17987533/ee8cae7a-c576-44d6-b8e9-97cb814bdf30)
![Bildschirmfoto 2023-09-10 um 12 41 42](https://github.com/copystring/ioBroker.roborock/assets/17987533/1afaabff-0836-47f5-82ce-5aa0237ca542)

**Comment by copystring** [comment]
Bitte ein debug log anhängen.

**Comment by jensus11** [comment]
Bitte, ich hoffe, da sind keine sensiblen Daten enthalten.
[Roborock.txt](https://github.com/copystring/ioBroker.roborock/files/12568029/Roborock.txt)

**Comment by copystring** [comment]
Nein. Alles gut. Aber in dem log ist kein absturz.

**Comment by jensus11** [comment]
Das kam jetzt, nachdem ich eine Zone markiert habe und auf Start gedrückt habe.

![Bildschirmfoto 2023-09-10 um 13 05 45](https://github.com/copystring/ioBroker.roborock/assets/17987533/012e1e5b-be76-4cea-a645-6618fc086134)

**Comment by jensus11** [comment]
![Bildschirmfoto 2023-09-10 um 13 08 46](https://github.com/copystring/ioBroker.roborock/assets/17987533/b62969c9-37bf-4fb6-bd49-dcdd3343ac82)
![Bildschirmfoto 2023-09-10 um 13 09 46](https://github.com/copystring/ioBroker.roborock/assets/17987533/baf11cee-04f1-4be0-b889-3f0a0cf2a34b)

**Comment by jensus11** [comment]
Ist leider nach einer erneuten Reinigung wieder abgestürzt. 
![Bildschirmfoto 2023-09-10 um 16 24 14](https://github.com/copystring/ioBroker.roborock/assets/17987533/58a78b2b-b896-4e3d-b4c2-7d06ee3acb9b)

**Comment by jensus11** [comment]
![Bildschirmfoto 2023-09-10 um 16 26 28](https://github.com/copystring/ioBroker.roborock/assets/17987533/8e5913e4-1028-4e2e-be3d-41f32bbc9922)

**Comment by copystring** [comment]
Ist die dev Version?

**Comment by jensus11** [comment]
Ja, habe ich so installiert. Die Alte natürlich vorher deinstalliert.
![Bildschirmfoto 2023-09-10 um 16 29 24](https://github.com/copystring/ioBroker.roborock/assets/17987533/ea5642f8-045e-4593-84b2-4e6bf79c61aa)

**Comment by copystring** [comment]
Ja, das ist OK so. Hast du vielleicht für den Adapter die Sentryfunktion deaktiviert?

**Comment by jensus11** [comment]
nicht das ich wüsste, wie aktiviert man die?

**Comment by jensus11** [comment]
Ist bei mir deaktiviert. Muss das an sein?

**Comment by jensus11** [comment]
Verkehrt geschaut. Sentry ist an, Statistiken habe ich deaktiviert.

**Comment by copystring** [comment]
Hast du andere Adapter die auch sentry verwenden?

**Comment by jensus11** [comment]
Fast alle haben das.
![Bildschirmfoto 2023-09-10 um 17 00 35](https://github.com/copystring/ioBroker.roborock/assets/17987533/a5833f85-6c32-4836-a973-b9a1145cc76f)

**Comment by copystring** [comment]
OK. Ich weiß nicht, was ich weiter prüfen kann. Vom Gefühl her würde ich sagen, dass irgendwas mit Sentry bei dir nicht stimmt. PC schon mal neu gestartet?

**Comment by jensus11** [comment]
Bei mir läuft Iobroker in einem Proxmox LXC Container. Ich habe gerade das ganze Debian aktualisiert und neu gestartet. Mache ich eigentlich regelmäßig. Mal schauen, wie es sich jetzt verhält.

**Comment by jensus11** [comment]
Ich habe das Gefühl, sobald ich die map.html aktualisiere, kommt es zu dem Crash.

![Bildschirmfoto 2023-09-10 um 19 17 08](https://github.com/copystring/ioBroker.roborock/assets/17987533/ce5bd5f2-2f49-4824-b35a-c249e7b46e16)

**Comment by copystring** [comment]
Das ist nicht zufälligerweise ein Raspberry Pi oder ein anderes arm system?

**Comment by jensus11** [comment]
ein Intel Nuc mit Proxmox.

**Comment by copystring** [comment]
Wie verhält sich das, wenn du Sentry für den Adapter deaktivierst?

**Comment by jensus11** [comment]
Erster Test lief durch. kann auch die Seite aktualisieren. Werde ich mal beobachten.
Lass das dann erst mal aus.
![Bildschirmfoto 2023-09-10 um 21 42 54](https://github.com/copystring/ioBroker.roborock/assets/17987533/b597f64a-506e-47e0-97b8-92f764f36a33)

**Comment by copystring** [comment]
Ich schließe das erstmal. Wüsste auch nicht, was ich tun kann, wenn es wieder auftritt. Vielleicht hat vorübergehend etwas mit der Onlineanbindung von Sentry nicht gestimmt.
