### ISSUE TITLE
Warnings/Errors im Normalbetrieb

### ISSUE THREAD

**Issue by tritanium73** [copystring/ioBroker.roborock#371]
**Describe the bug**  
Nach Adapter "Neustart" kommen Fehler bzw. Error Meldungen

**To Reproduce**  
Ein "normaler" Adapter Neustart reicht aus um den Zusatnad herbei zu führen.

**Screenshots & Logfiles**  
![grafik](https://github.com/copystring/ioBroker.roborock/assets/144626519/9361c5c6-6f5f-4bd3-9bc9-809e05a7b716)

**Versions:**  
 - Adapter version: 0.3.2
 - JS-Controller version: 4.0.24
 - Node version: 18.17.0
 - Operating system: Linux Ubuntu 22.04.2 LTS
 - NPM 9.6.7
 - 

**Additional context**  
[roborock_q7_max+_debug_tritanium.txt](https://github.com/copystring/ioBroker.roborock/files/12570184/roborock_q7_max%2B_debug_tritanium.txt)

**Comment by copystring** [comment]
Kannst du mal https://devicetests.com/packet-loss-test über WLAN machen? Mit dem Smartphone oder Laptop.
Das sollte unter 1% liegen.
![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/eb6bb2c1-5074-420d-831b-885d9ad67e90)

**Comment by tritanium73** [comment]
Also den Test, den du vorschlägst bekomme ich nicht zum laufen.

Mit keinem Browser, weder per Smartphone noch via Notebook aus dem WLAN!

Habe jetzt mal einen anderen herausgesucht:

https://devicechecker.org/packet-lost-test/

![grafik](https://github.com/copystring/ioBroker.roborock/assets/144626519/1dbb45a8-70b8-4836-ae9a-5bc634d8b77c)

Ergebnisse:

![grafik](https://github.com/copystring/ioBroker.roborock/assets/144626519/6671a8ac-f110-4c92-8031-2c801a7a81f9)


Ich hoffe das hilft dir...

**Comment by tritanium73** [comment]
Guten Morgen,

kurioserweise, ohne das ich was gemacht habe, ist seit heute Morgen, Ruhe im Logging.

Keine ERRORS, keine Warnings.

Mach erst einmal nix, ich warte ab!

-> Passiert ist nix, ausser das der Robi heute morgen ganz normal seine Tour gedreht hat.

Ob das allerdings damit zu tun hat ?!

Ich melde mich wieder dazu....

**Comment by tritanium73** [comment]
Da ich derzeit keine weiteren Probleme sehe, schliesse ich erst einmal das Issue :-)
