### ISSUE TITLE
Battery status and charge level

### ISSUE THREAD

**Issue by KaeptnKluk** [copystring/ioBroker.roborock#372]
Hello,

is it possible to query the battery and charging status of the robot vacuum cleaner? I have the S7 Pro Ultra. Unfortunately, such values are not displayed to me. 

Otherwise, it is a very nice adapter. Thanks for the work! I really appreciate it.

**Comment by tritanium73** [comment]
Actually the Battery Percentage Status is under "deviceStatus" already implemented:

![grafik](https://github.com/copystring/ioBroker.roborock/assets/144626519/2c8b3fcd-d582-4a0c-9acc-b25c0442d825)

So we could close this Issue

**Comment by tritanium73** [comment]
please be so kind and close the issue
