### ISSUE TITLE
Fehlende Datenpunkte unter den "Objekten"

### ISSUE THREAD

**Issue by tritanium73** [copystring/ioBroker.roborock#373]
Guten Morgen,

da ich immer wieder (täglich, bei der fahrt vom Robi) am Ende der Reinigung, "Warnings" bekommen wied diese:

![grafik](https://github.com/copystring/ioBroker.roborock/assets/144626519/95057ab2-2175-4f95-87d2-c97b7d79bdba)

...wollte ich mal anregen, bei einem Adapter Update diese scheinbar fehlenden Datenpunkte einfach mal mit aufzunehmen, damit diese dann auch existieren.

Freue mich über Kritik :-)

lg Micha

**Comment by copystring** [comment]
Hi,
sowas kann vorkommen und passe ich sehr gern an. Ich brauche aber immer ein vollständiges debug log. Das bitte noch hier anhängen.
