### ISSUE TITLE
S7 Maxv Ultra

### ISSUE THREAD

**Issue by mproper23** [copystring/ioBroker.roborock#38]
Bei der Saugkraft Auswahl fehlt die MAX+ Stufe des S7 MAXv Ultra

**Comment by copystring** [comment]
OK. Bitte den Adapter auf debug einstellen. Dann den Roboter auf MAX+ einstellen und dann ein vollständiges log hier als Datei anhängen. Danke.

**Comment by mproper23** [comment]
Sprich Adapter Stoppen auf Debug stellen, Protokoll leeren, dann Adapter starten und Roboter via App auf MAX+ ans putzen schicken?

**Comment by mproper23** [comment]
Wenn ich es richtig sehe ist das dann die 108 bei fan_power
[Roborock_log.txt](https://github.com/copystring/ioBroker.roborock/files/10543874/Roborock_log.txt)

**Comment by copystring** [comment]
Stimmt. Das ist 108 bei dir. Dann ist es bei deinem Sauber möglicherweise ganz anders. Daher benötigte ich für jeden wert (101,102, etc) den entsprechenden Bezeichner. Bekommst du das mit dem logs hin? Dann würde ich das direkt einpflegen.

**Comment by mproper23** [comment]
Suction Power:
Quiet        101
Balanced   102
Turbo        103 
Max          104
MAX+      108

**Comment by copystring** [comment]
Alles klar. Besten Dank! Ich pflege das dann heute Abend ein und verlinke eine entsprechende branch zum Testen.

**Comment by mproper23** [comment]
Perfekt danke

**Comment by copystring** [comment]
Das mal bitte Testen.: https://github.com/copystring/ioBroker.roborock/tree/max_plus_fan_power_s7_maxv

Das mit es funktioniert muss roborock.0.Devices.YOUR_ID.commands.set_custom_mode und roborock.0.Devices.YOUR_ID.deviceStatus.fan_power gelöscht werden. Dann den Adapter über den Link aktualisieren und testen.

**Comment by mproper23** [comment]
Ich teste es morgen früh. Danke

**Comment by mproper23** [comment]
Funktioniert

**Comment by copystring** [comment]
https://github.com/copystring/ioBroker.roborock/pull/48

**Comment by copystring** [comment]
Danke fürs testen.
