### ISSUE TITLE
Nach längerer Adapter Laufzeit keine Reaktion auf Command app_segment_clean

### ISSUE THREAD

**Issue by DonToben** [copystring/ioBroker.roborock#39]
Nach längerer Laufzeit des Adapters keine Reaktion mehr auf Command app_segment_clean

Ich habe zwei Logs anghängt.
Log1: Hier hat app_segment_clean noch funktioniert
Log2: Hier wurde nicht mehr auf app_segment_clean reagiert
Umschalten der Modis (Saugen, Wischen) funktionierte aber noch.

[Part1.log](https://github.com/copystring/ioBroker.roborock/files/10536911/Part1.log)
[Part2.log](https://github.com/copystring/ioBroker.roborock/files/10536912/Part2.log)

Ein Neustart des Adapters löste das Problem. 

Adapter war noch 0.0.5

**Comment by copystring** [comment]
OK. Sehr merkwürdig. Der Befehl wird ausgelöst aber dann nicht weiter zum Roboter gegeben.
Ich habe hier zum Testen mal extra viel debug logging aktiviert. Bitte mal testen und ein neues Log schicken.: https://github.com/copystring/ioBroker.roborock/commits/extra_logging_for_room_cleaning

**Comment by copystring** [comment]
Habe für dich erstmal die Kartenupdates in dieser Branch deaktiviert.

**Comment by copystring** [comment]
Bitte https://github.com/copystring/ioBroker.roborock/commits/extra_logging_for_room_cleaning testen und den Fehler reproduzieren. Dann hier ein Log posten. Danke 👍😀

**Comment by copystring** [comment]
Naja da ist das extra logging nicht mit drin.

**Comment by copystring** [comment]
Es könnte sein, dass in der aktuellen Version auch das Problem von hier gelöst wurde. Wenn du das mal ausprobieren würdest wäre prima.
https://github.com/copystring/ioBroker.roborock

**Comment by DonToben** [comment]
> Es könnte sein, dass in der aktuellen Version auch das Problem von hier gelöst wurde. Wenn du das mal ausprobieren würdest wäre prima. https://github.com/copystring/ioBroker.roborock

Sehr gut. Das Problem scheint wirklich behoben zu sein.

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/pull/80
