### ISSUE TITLE
Keine Aktualisierung der Objekte

### ISSUE THREAD

**Issue by fuchs-1978** [copystring/ioBroker.roborock#399]
Ich habe zwei S7 über den Adapter eingebunden. Mir fällt in letzter zeit auf, dass die Werte nicht mehr regelmäßig aktualisiert werden. Bei Neustart des Adapters werden aktuelle werte geholt, dazwischen nicht. Ist jemandem ähnliches aufgefallen?

**Comment by copystring** [comment]
Hast du ein Debug Log?

**Comment by copystring** [comment]
Müsste in 0.4.3 gehoben sein.

**Comment by fuchs-1978** [comment]
Habe es aus dem GitHub installiert und beobachte

**Comment by fuchs-1978** [comment]
Der Test sieht gut aus, Werte werden wieder automatisch geschrieben

**Comment by fuchs-1978** [comment]
Erledigt

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/commit/2ecae4fb5d2c7889ddb0b2afd204f9fea02e04b9
