### ISSUE TITLE
0.0.6 Adapter startet ständig neu

### ISSUE THREAD

**Issue by DonToben** [copystring/ioBroker.roborock#40]
seit 0.0.6 startet der Adapter ständig neu. Mit der letzten 0.0.5 hatte ich die Probleme nicht.

Hier das
Log:
[0.0.6 Startet ständig neu.txt](https://github.com/copystring/ioBroker.roborock/files/10537034/0.0.6.Startet.standig.neu.txt)

![Screenshot 2023-01-30 195917](https://user-images.githubusercontent.com/61901880/215570332-edfa8142-5f5e-42b6-b816-1594bbcc6946.jpeg)

Nach Node und NPM update der gleiche Fehler

**Comment by copystring** [comment]
Passiert das nur beim Saugen oder auch dann wenn der Roboter gar nichts macht?
Es scheint etwas mit der Karte zu tun zu haben...

**Comment by DonToben** [comment]
Auch wenn er nichts macht und nur in der Ladestation steht.

**Comment by copystring** [comment]
Welcher RPi ist das? Kommt der nicht damit klar, dass die Karte jede Sekunde abgerufen wird?

**Comment by DonToben** [comment]
`pi@raspberrypi:~ $ free -ht
              total        used        free      shared  buff/cache
   available
Mem:          3,7Gi       606Mi        79Mi       200Mi       3,1Gi
       2,8Gi
Swap:          99Mi        13Mi        86Mi
Total:        3,8Gi       619Mi       166Mi
pi@raspberrypi:~ $ sudo apt update
OK:1 http://raspbian.raspberrypi.org/raspbian buster InRelease
OK:2 https://deb.nodesource.com/node_16.x buster InRelease
OK:3 http://archive.raspberrypi.org/debian buster InRelease
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Alle Pakete sind aktuell.
pi@raspberrypi:~ $`

Raspberry Pi 4 Modell B; 4 GB, ARM-Cortex-A72 4 x, 1,50 GHz, 4 GB RAM, WLAN-ac, Bluetooth 5, LAN, 4 x USB, 2 x Micro-HD

**Comment by copystring** [comment]
OK habe aber selber keinen RPi verfügbar. Bitte mal https://github.com/copystring/ioBroker.roborock/tree/update_map_every_30_seconds testen. Die Karte wird dann alle 30 Sekunden aktualisiert und nicht jede Sekunde (Ich hatte es zuvor bereits auf 2 Sekunden reduziert).

**Comment by copystring** [comment]
Wie oft tauchen die resets auf?
Dass die ObjektIDs identisch in den unterschiedlichen Karte sind ist normal. Das gibt die API so vor.

Ja, das war meine erste Idee als ich dieses Ticket hier gelesen habe.

**Comment by DonToben** [comment]
Jetzt ist mir iobroker total abgeschmirrt.

`pi@raspberrypi:~ $ df -h
Dateisystem    GrÃ¶ÃŸe Benutzt Verf. Verw% EingehÃ¤ngt auf
/dev/root        59G     57G     0  100% /
devtmpfs        1,8G       0  1,8G    0% /dev
tmpfs           1,9G       0  1,9G    0% /dev/shm
tmpfs           1,9G    8,6M  1,9G    1% /run
tmpfs           5,0M    4,0K  5,0M    1% /run/lock
tmpfs           1,9G       0  1,9G    0% /sys/fs/cgroup
/dev/mmcblk0p1  253M     49M  204M   20% /boot
tmpfs           384M       0  384M    0% /run/user/1000
pi@raspberrypi:~ $`

**Comment by copystring** [comment]
Mal bitte du -sh /* machen

**Comment by DonToben** [comment]
ja genau. Keine Ahnung warum. Habe nur den Adapter installiert. Etwas weiter oben habe ich ja df -h schon mal ausgeführt, da war noch alles in Ordnung.

**Comment by DonToben** [comment]
pi@raspberrypi:/ $ sudo du -sh /*
9,4M    /bin
49M     /boot
55M     /boot.bak
0       /dev
7,8M    /etc
3,0G    /home
634M    /lib
16K     /lost+found
8,0K    /media
4,0K    /mnt
2,9G    /opt
du: Zugriff auf '/proc/1799/task/1799/fd/4' nicht mÃ¶glich: Datei oder Verzeichnis nicht gefunden
du: Zugriff auf '/proc/1799/task/1799/fdinfo/4' nicht mÃ¶glich: Datei oder Verzeichnis nicht gefunden
du: Zugriff auf '/proc/1799/fd/3' nicht mÃ¶glich: Datei oder Verzeichnis nicht gefunden
du: Zugriff auf '/proc/1799/fdinfo/3' nicht mÃ¶glich: Datei oder Verzeichnis nicht gefunden
0       /proc
38M     /root
8,6M    /run
11M     /sbin
4,0K    /srv
0       /sys
44K     /tmp
4,3G    /usr
46G     /var
pi@raspberrypi:/ $

**Comment by copystring** [comment]
OK. Jetzt bitte `du -sh /var/*` Ich bin mir sicher, dass deine logs voll sind.

**Comment by DonToben** [comment]
pi@raspberrypi:/ $ sudo du -sh /var/*
4,7M    /var/backups
381M    /var/cache
169M    /var/lib
4,0K    /var/local
0       /var/lock
45G     /var/log
4,0K    /var/mail
4,0K    /var/opt
0       /var/run
36K     /var/spool
25M     /var/swap
24K     /var/tmp

**Comment by copystring** [comment]
`du -sh /var/log/*`

**Comment by DonToben** [comment]
pi@raspberrypi:/var/log $ sudo du -sh /var/log/*
8,0K    /var/log/alternatives.log
4,0K    /var/log/alternatives.log.1
4,0K    /var/log/alternatives.log.2.gz
4,0K    /var/log/alternatives.log.3.gz
4,0K    /var/log/alternatives.log.4.gz
4,0K    /var/log/alternatives.log.5.gz
4,0K    /var/log/alternatives.log.6.gz
4,0K    /var/log/alternatives.log.7.gz
368K    /var/log/apt
112K    /var/log/auth.log
52K     /var/log/auth.log.1
4,0K    /var/log/auth.log.2.gz
4,0K    /var/log/auth.log.3.gz
4,0K    /var/log/auth.log.4.gz
252K    /var/log/boot.log
0       /var/log/bootstrap.log
4,0K    /var/log/btmp
0       /var/log/btmp.1
68K     /var/log/cups
572K    /var/log/daemon.log
568K    /var/log/daemon.log.1
40K     /var/log/daemon.log.2.gz
36K     /var/log/daemon.log.3.gz
36K     /var/log/daemon.log.4.gz
12K     /var/log/debug
4,0K    /var/log/debug.1
4,0K    /var/log/debug.2.gz
4,0K    /var/log/debug.3.gz
4,0K    /var/log/debug.4.gz
196K    /var/log/dpkg.log
248K    /var/log/dpkg.log.1
4,0K    /var/log/dpkg.log.2.gz
8,0K    /var/log/dpkg.log.3.gz
12K     /var/log/dpkg.log.4.gz
8,0K    /var/log/dpkg.log.5.gz
16K     /var/log/dpkg.log.6.gz
4,0K    /var/log/dpkg.log.7.gz
4,0K    /var/log/dpkg.log.8.gz
4,0K    /var/log/dpkg.log.9.gz
8,0K    /var/log/faillog
4,0K    /var/log/firebird
8,0K    /var/log/fontconfig.log
4,0K    /var/log/haproxy.log
8,0K    /var/log/hp
23G     /var/log/kern.log
4,0K    /var/log/kern.log.1
4,0K    /var/log/kern.log.2.gz
4,0K    /var/log/kern.log.3.gz
12K     /var/log/kern.log.4.gz
12K     /var/log/lastlog
20K     /var/log/lightdm
224K    /var/log/messages
4,0K    /var/log/messages.1
4,0K    /var/log/messages.2.gz
4,0K    /var/log/messages.3.gz
4,0K    /var/log/messages.4.gz
644K    /var/log/motion
4,0K    /var/log/private
23G     /var/log/syslog
1,7M    /var/log/syslog.1
64K     /var/log/syslog.2.gz
68K     /var/log/syslog.3.gz
64K     /var/log/syslog.4.gz
64K     /var/log/syslog.5.gz
64K     /var/log/syslog.6.gz
64K     /var/log/syslog.7.gz
2,8M    /var/log/user.log
11M     /var/log/user.log.1
316K    /var/log/user.log.2.gz
316K    /var/log/user.log.3.gz
312K    /var/log/user.log.4.gz
48K     /var/log/vncserver-x11.log
32K     /var/log/vncserver-x11.log.bak
136K    /var/log/wtmp
8,0K    /var/log/Xorg.0.log
8,0K    /var/log/Xorg.0.log.old
44K     /var/log/xrdp.log
24K     /var/log/xrdp-sesman.log

**Comment by copystring** [comment]
Genau. Also 1x 23G /var/log/syslog und 23G /var/log/kern.log

**Comment by DonToben** [comment]
Kann ich den Inhalt vom Log Ordner löschen, oder brauchst du noch was?

**Comment by DonToben** [comment]
Fehler ist immer noch da.

[Issue40 Log.txt](https://github.com/copystring/ioBroker.roborock/files/10543282/Issue40.Log.txt)

**Comment by DonToben** [comment]
Mit https://github.com/copystring/ioBroker.roborock/issues/39#issuecomment-1409371138 läuft der Adapter wieder.

**Comment by copystring** [comment]
Ohne jetzt unhöflich zu wirken war diese branch nicht für dieses issue vorgesehen. Dass das jetzt damit läuft war mir fast klar da die Kartenfunktion deaktiviert ist.
Hier in diesem issue geht es aber darum zu gucken ob Abhängigkeiten vom Adapter fehlen.

**Comment by DonToben** [comment]
> Ohne jetzt unhöflich zu wirken war diese branch nicht für dieses issue vorgesehen. Dass das jetzt damit läuft war mir fast klar da die Kartenfunktion deaktiviert ist. Hier in diesem issue geht es aber darum zu gucken ob Abhängigkeiten vom Adapter fehlen.
> 
> Daher bitte ausschließlich https://github.com/copystring/ioBroker.roborock/commits/remove_crc_requirement testen.

Hast du hier die letzten sechs Stunden was geändert?
Falls nicht, hier das Logfile:

https://github.com/copystring/ioBroker.roborock/issues/40#issuecomment-1410117047

**Comment by copystring** [comment]
OK. Danke für das neue Log. Hier ein Update: https://github.com/copystring/ioBroker.roborock/tree/remove_crc_requirement

Dort ist die Abhängigkeit process, zlib und crypto hinzugefügt. Bitte nochmal testen: https://github.com/copystring/ioBroker.roborock/commits/remove_crc_requirement

**Comment by DonToben** [comment]
> OK. Danke für das neue Log. Hier ein Update: https://github.com/copystring/ioBroker.roborock/tree/remove_crc_requirement
> 
> Dort ist die Abhängigkeit process, zlib und crypto hinzugefügt. Bitte nochmal testen.

Problem besteht noch immer.
Hier das Log. Sorry für das PDF. Übers Smartphone die einfachste Lösung.

[192.168.178.57_8081_log_raspberrypi_file1_iobroker.2023-02-01.lo.pdf](https://github.com/copystring/ioBroker.roborock/files/10555391/192.168.178.57_8081_log_raspberrypi_file1_iobroker.2023-02-01.lo.pdf)

**Comment by copystring** [comment]
Aha. Wunderbares Log. Zumindest teilweise.
Dein Roboter musste erstmal gucken wo er sich befindet und konnte deshalb keine Karte erstellen. 2023-02-01 10:10:33.614 - error: roborock.0 (18033) Failed to creating canvas: locating
2023-02-01 10:10:35.348 - debug: roborock.0 (18033) dps debug: {"id":43,"result":["locating"]}

Leider hat das aber mit den abstürzen nichts nicht zu zu. Viele Ideen habe ich nicht mehr. Ich gucke nachher nochmal. Ich kann nur bestätigen, dass es von den erstellen der Karte kommt.

**Comment by DonToben** [comment]
Wäre super, wenn du bei den neuen Version das Map Feature "auswählbar" machen könntest. Da kann ich zumidest die neuen Versionen weiter testen.
Danke.

**Comment by copystring** [comment]
Klar. https://github.com/copystring/ioBroker.roborock/tree/make_map_creation_optional
Dort ist das erstellen/abrufen der Karte standardmäßig deaktiviert und muss manuell in den Optionen aktiviert werden. Dann sollte der Adapter bei dir wieder laufen.
Dadurch wird das eigentliche Problem natürlich nur umgangen. Um eine kurze Rückmeldung wäre ich dankbar.

**Comment by copystring** [comment]
Wenn die Karte aktiviert ist, steht dann irgendwas über die Abstürze in /var/log/syslog?
Möglicherweise steht auch etwas mehr in den Logs ioBroker wenn man bei den Protokolle in ioBroker alle Protokolle anzeigen lässt: 
![image](https://user-images.githubusercontent.com/1298861/216155851-ed61e222-0e79-4e38-9ebc-af3d5887a7db.png)

**Comment by DonToben** [comment]
> Klar. https://github.com/copystring/ioBroker.roborock/tree/make_map_creation_optional Dort ist das erstellen/abrufen der Karte standardmäßig deaktiviert und muss manuell in den Optionen aktiviert werden. Dann sollte der Adapter bei dir wieder laufen. Dadurch wird das eigentliche Problem natürlich nur umgangen. Um eine kurze Rückmeldung wäre ich dankbar.

Hi. Der Adapter läuft bei deaktivierter Map soweit.
Sobald ich Zeit habe, werde ich die Map wieder aktivieren und versuchen, dir sämtliche logs bereitzustellen.

**Comment by DonToben** [comment]
Hier die Logs.

Nach Aktivierung der Karte geht syslog und kernlog durch die Decke. Nur Deaktiviern der Karte und ein Reset des pi behebt das wieder. 

[kern nad syslog.zip](https://github.com/copystring/ioBroker.roborock/files/10576147/kern.nad.syslog.zip)
[iobroker log.txt](https://github.com/copystring/ioBroker.roborock/files/10576152/iobroker.log.txt)

**Comment by copystring** [comment]
Geht es vielleicht besser nach einem rpi-update?

**Comment by DonToben** [comment]
Ist auf aktuellen Stand.

`pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux
pi@raspberrypi:~ $ vcgencmd version
Jan  5 2023 10:46:54
Copyright (c) 2012 Broadcom
version 8ba17717fbcedd4c3b6d4bce7e50c7af4155cba9 (clean) (release) (start)
pi@raspberrypi:~ $ node -v
nodejs -v
v16.19.0
v16.19.0`

**Comment by copystring** [comment]
Ich weiß nicht genau wie ich hier weiter helfen kann. Ich habe mir extra für dieses Problem einen RPi 3B mit ioBroker eingerichtet und meinen Adapter direkt von der github Repo installiert inkl. Kartenaktualisierung. Die Karte wurde sauber erstellt.
Die Belegung vom RAM war ca 85mb. Er konnte dabei 5 mal die Karte nicht erstellen weil der Roboter die Daten dafür nicht abgegeben hat. Das kann ich jedoch nicht beeinflussen und lässt den Adapter auch nicht abstürzen.

**Comment by Black-Thunder** [comment]
Also das Problem mit der aktivierten Kartenerstellung und der Vollauslastung des Systems inkl. Vollaufen des Logs kann ich auch auf meinem RPi 4B 4GB auch bestätigen. Im kern.log und syslog findet sich dann (genau wie bei @DonToben)  teils bis zu 100 Mal pro Sekunde der Eintrag:

```
Unhandled prefetch abort: breakpoint debug exception (0x222) at 0x00000000
```

Und im iobroker-Log manchmal das:

```
error: host.raspberrypi-gang Caught by controller[1]: corrupted double-linked list
```

Teilweise wird das System so träge, dass der io.roborock-Prozess abgeschossen werden muss, um überhaupt wieder Kontrolle zu erlangen.

@copystring Hast du bei deinem Test ein 32- oder 64-Bit-OS verwendet? Ich meine mich nämlich dunkel zu erinnern, dass es schon beim mihome-vacuum-Adapter Probleme mit canvas und 32-Bit gab.

Nur der Vollständigkeit halber meine Systeminfos:

```
pi@raspberrypi-gang:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi-gang:~ $ vcgencmd version
Jan  5 2023 10:46:54
Copyright (c) 2012 Broadcom
version 8ba17717fbcedd4c3b6d4bce7e50c7af4155cba9 (clean) (release) (start)
pi@raspberrypi-gang:~ $  uname -a
Linux raspberrypi-gang 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux
pi@raspberrypi-gang:~ $ node -v
v16.19.0
pi@raspberrypi-gang:~ $ nodejs -v
v16.19.0
pi@raspberrypi-gang:~ $ npm -v
8.19.3
```

**Comment by copystring** [comment]
Mein Adapter nutzt für das Erstellen der Karten den selben Code wie der mihome-vacuum-Adapter. Daher die selben Probleme.

Das ist was ich installiert hab: 
![image](https://user-images.githubusercontent.com/1298861/217167579-9efeb75b-e656-4f59-aec8-6d494a21a67b.png)

Direkt nach dem installieren habe ich `curl -sLf https://iobroker.net/install.sh | bash -
` ausgeführt ohne irgendwelche updates davor durchzuführen und anschließend direkt in ioBroker über die Github Katze den Adapter installiert.

Hier auch meine Infos:
```cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
pi@raspberrypi2:~ $ vcgencmd version
Aug 26 2022 14:04:36
Copyright (c) 2012 Broadcom
version 102f1e848393c2112206fadffaaf86db04e98326 (clean) (release) (start)
pi@raspberrypi2:~ $ uname -a
Linux raspberrypi2 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux
pi@raspberrypi2:~ $ node -v
v16.19.0
pi@raspberrypi2:~ $  nodejs -v
-bash: nodejs: command not found
pi@raspberrypi2:~ $ npm -v
8.19.3
```

**Comment by Black-Thunder** [comment]
Hmm... OK, wundert mich, dass das bei dir dann so läuft. Nennenswerte Unterschiede sehe ich da keine.

Zu dem Problem an sich gab es [hier](https://forum.iobroker.net/topic/54012/iobroker-kernel-unhandled-prefetch-abort-breakpoint-debug) und [hier](https://forum.iobroker.net/topic/44669/mihome-vacuum-karte/52?_=1675760222005) schon mal Diskussionen, aber auch leider ohne wirkliches Ergebnis. Nur der Verdacht mit canvas und 32-/64-Bit steht da auch im Raum. Dagegen spricht aber, dass es bei deinem Testsystem läuft.
