### ISSUE TITLE
read out current coordinates 

### ISSUE THREAD

**Issue by tobsta** [copystring/ioBroker.roborock#416]
would be nice to read out the current coordinates of device to be able to script/trigger zonecleaning.
By the way - where can i find how to exactly use app_zoned_clean command?

**Comment by copystring** [comment]
Not sure what you mean with 
> would be nice to read out the current coordinates of device to be able to script/trigger zonecleaning. 


For this 
> By the way - where can i find how to exactly use app_zoned_clean command?

You can do this: 

To get the coordinates to clean a zone, you need to draw a zone in the web interface and check the console of the browser. There you can find the coordinates. Then you can send the coordinates via app_zoned_clean without having to draw a zone on the map.

**Comment by tobsta** [comment]
Thanks for the ideas! Since i use a raspberry, i dont have a webinterface (to my knowledge its not possible on rasp, isnt it?) to get coords...
app_zoned_clean i guess the first 4 numbers are coords to describe the zone - but how to use the last one?
by the way - i bought a q revo - if you need me to test something...

**Comment by copystring** [comment]
The last one is his many times the zone should be cleaned
