### ISSUE TITLE
Fehler im Adapter für Q7

### ISSUE THREAD

**Issue by andy61zuhause** [copystring/ioBroker.roborock#419]
Hallo,
Mein Adapter zeigt derzeit jede Minute folgende Fehlermeldung:

Nachricht
roborock.0
2023-10-21 21:57:02.489 error Unsported attribute: charge_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot.
roborock.0
2023-10-21 21:57:02.480 error Unsported attribute: switch_map_mode of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.

Ich habe den Adapter in Version 0.4.4
Ich habe einen Roborock Q7

**Comment by copystring** [comment]
Hallo,

hängst du bitte ein vollständiges log an? Danke.

**Comment by andy61zuhause** [comment]
Hallo copystring,
natürlich. Habe im debug-Modus kurz gestartet und den Verlauf aufgezeichnet.

[iobroker.current.log](https://github.com/copystring/ioBroker.roborock/files/13066409/iobroker.current.log)

Ich hoffe, das reicht Dir. LG

**Comment by copystring** [comment]
Hi, danke für das Log. Passt.
Der Fehler ist in der dev branch bereits behoben. Siehe hier: https://github.com/copystring/ioBroker.roborock/issues/131

**Comment by andy61zuhause** [comment]
Hallo copystring,
ich habe die dev eingespielt. Leider tritt der Fehler weiterhin auf. Habe die Struktur gelöscht und auch den iobroker neu gestartet. Leider kein positiver Effekt. Ich habe einen Q7, keinen Q7 max. Kann es daran liegen?

**Comment by copystring** [comment]
Nein, daran kann es nicht liegen. Beide Werte sind in der aktuellen dev hinterlegt. Bist du dir sicher, dass du die aktuelle dev installiert hast?

switch_map_mode: https://github.com/copystring/ioBroker.roborock/blob/dev/lib/genSpecs/gen7/q7/robot.js#L786
charge_status: https://github.com/copystring/ioBroker.roborock/blob/dev/lib/genSpecs/gen7/q7/robot.js#L791

**Comment by andy61zuhause** [comment]
ich habe über diesen Link installiert

https://github.com/copystring/ioBroker.roborock/tree/dev

Der Fehler tritt weiterhin auf. soll ich noch einmal ein log ziehen?

**Comment by copystring** [comment]
Ja, bitte.

**Comment by Banditpilot** [comment]
hier das logfile
[roborock.log](https://github.com/copystring/ioBroker.roborock/files/13170010/roborock.log)
Hoffe, das hilft. Danke schon einmal.

**Comment by copystring** [comment]
Der Fehler war bei mir. Ich habe die Attribute falsch einsortiert. Gefixt durch https://github.com/copystring/ioBroker.roborock/commit/f517d35d00b4a56982bdc2040007525bafe244da
Bitte teste die neue dev

**Comment by andy61zuhause** [comment]
gesagt, detan. Habe die neue dev installiert. Jetzt treten keine Fehler mehr auf. Vielen Dank für die tolle Arbeit. Das ist mir eine kleine Spende wert.

**Comment by copystring** [comment]
Super, dass es jetzt läuft. Herzlichen Dank für die großzügige Spende. Das motiviert nochmal zusätzlich 👍👍👍
Wenn noch etwas sein sollte, gerne wieder melden
