### ISSUE TITLE
Failed to get home details: TypeError: Cannot read properties of null (reading 'rrHomeId')

### ISSUE THREAD

**Issue by Tim0thY11** [copystring/ioBroker.roborock#421]
**Describe the bug**  
An error occurs when starting the adapter and no connection can be established to the robot vacuum.
"Failed to get home details: TypeError: Cannot read properties of null (reading 'rrHomeId')"

**To Reproduce**  
1. Start adapter and the green icon appears
2. No value is updated in the objects. Control of the robot is not possible. 
3. See the error in the logs

**Expected behavior**  
The connection to the robot vacuum cleaner should be established via the Xiaomi account, status values should be updated and it should be possible to control the robot.

**Screenshots & Logfiles**  
Logs while starting the adapter:

roborock.0 | 2023-10-24 09:48:54.032 | error | Failed to get home details: TypeError: Cannot read properties of null (reading 'rrHomeId')
-- | -- | -- | --
roborock.0 | 2023-10-24 09:48:53.587 | info | starting. Version 0.4.4 in /opt/iobroker/node_modules/iobroker.roborock, node: v18.18.2, js-controller: 5.0.12
roborock.0 | 2023-10-24 09:48:53.041 | debug | Plugin sentry Initialize Plugin (enabled=true)
roborock.0 | 2023-10-24 09:48:52.869 | debug | States connected to redis: 127.0.0.1:9000
roborock.0 | 2023-10-24 09:48:52.820 | debug | States create User PubSub Client
roborock.0 | 2023-10-24 09:48:52.819 | debug | States create System PubSub Client
roborock.0 | 2023-10-24 09:48:52.792 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
roborock.0 | 2023-10-24 09:48:52.742 | debug | Objects connected to redis: 127.0.0.1:9001
roborock.0 | 2023-10-24 09:48:52.734 | debug | Objects client initialize lua scripts
roborock.0 | 2023-10-24 09:48:52.651 | debug | Objects create User PubSub Client
roborock.0 | 2023-10-24 09:48:52.650 | debug | Objects create System PubSub Client
roborock.0 | 2023-10-24 09:48:52.647 | debug | Objects client ready ... initialize now
roborock.0 | 2023-10-24 09:48:52.587 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001

**Versions:**  
 - Adapter version: v0.4.4
 - JS-Controller version: js-controller: 5.0.12
 - Node version:  node: v18.18.2
 - Operating system: iobroker v6.10.1
 - robot: Roborock S7

**Additional context**  

I have also tried the adapter "mihome-vacuum". There, the adapter does not even turn green at startup, but the orange triangle comes.

In the summer, everything still worked fine. I have recently updated iobroker, node and the js-controller.

**Comment by copystring** [comment]
Hi, you need to post a full debug log. Thanks

**Comment by Tim0thY11** [comment]
Problem could be solved. After multiple reinstallations of the instance, the adapter connects to the robot again.
