### ISSUE TITLE
Support Heizmodul / Trockner

### ISSUE THREAD

**Issue by Trunks1982** [copystring/ioBroker.roborock#433]
Hi ist es möglich das Heizmodul bzw Trocknermodul zu unterstützen?
Anscheinend wird das Modul nur beim MaxV angezeigt und beim S7 Ultra pro nicht.

**Comment by copystring** [comment]
Hi, ich wusste nicht, dass der S7 Ultra Pro das kann. Häng bitte ein Debug log an. Dann kann ich einen fix machen.

**Comment by Trunks1982** [comment]
Das ist die frage ob er das kann oder wer das vorgibt.In den beschreibungen werden immer nur pro iltra und der maxv angezeigt aber nir beim maxv wird es im der app angezeigt beim pro ultra nicht.Ist die Frage ob du die daten lokal holst oder aus der cloud.Schötze die cloud gibts vor.

**Comment by copystring** [comment]
Nein. Ich muss jeden Saugroboter einzeln definieren. Die Cloud sagt mir nicht, was ein Roboter kann.

**Comment by Trunks1982** [comment]
[iobroker.2023-11-22.log](https://github.com/copystring/ioBroker.roborock/files/13440885/iobroker.2023-11-22.log)
Hi ich hoffe du kannst was damit anfangen.

**Comment by copystring** [comment]
OK. Sieht gut aus. Wird das Trocknermodul überhaupt in der App auf dem Handy angezeigt?

**Comment by Trunks1982** [comment]
Nein.Nur beim MaxV wohl.

**Comment by copystring** [comment]
Bist du dir sicher? Wenn es die App nicht kann, dann kann es der Adapter auch nicht.

**Comment by Trunks1982** [comment]
Beim MaxV wird es in der App abgefragt ob zugekauft worden ist.Bei mir nicht.
Also sagt doch die cloud was geht?!

**Comment by copystring** [comment]
Kommt die Frage beim S7 Ultra pro auch?

**Comment by Trunks1982** [comment]
Leider Nein.Wohl nur in china bzw chinesische Modelle.

**Comment by copystring** [comment]
OK. Dann kann man da auch nicht schummeln. Wenn es in der App nicht geht, kann ich es im Adapter nicht auf magische weise freischalten.

**Comment by Trunks1982** [comment]
Schade.Vielleicht meldet sich ja mal einer mit seinem Setup dann könnte man es ja mal versuchen so anzusteuern.

**Comment by copystring** [comment]
Vielleicht, halte ich aber für unwahrscheinlich. Hast du nicht eine trocknungseinheit, die du zum Testen umstecken könntest?

**Comment by Trunks1982** [comment]
Wie meinste umstecken?
Hab ja ein gekauft und drangebaut.

**Comment by copystring** [comment]
Kann man das nicht an den anderen bauen?

**Comment by Trunks1982** [comment]
Ja aber den maxv besitze ich nicht.
