### ISSUE TITLE
LOG Spam last_clean_t

### ISSUE THREAD

**Issue by Knallix** [copystring/ioBroker.roborock#434]
**Describe the bug**  
I have just installed the adapter. I'm running this on an S8 pro Ultra. Can I do something about that?
Here a photo
![image](https://github.com/copystring/ioBroker.roborock/assets/42406048/61b256b6-ff0a-4834-b218-381b06f54b3b)

**To Reproduce**  
Only start the adapter and wait

**Expected behavior**  

**Screenshots & Logfiles**  

**Versions:**  
 - Adapter version: v0.4.4
 - JS-Controller 5.0.16
 - Node version: v16.19.1
 - Operating system: debian

**Comment by copystring** [comment]
This has been fixed in dev a while ago.

See https://github.com/copystring/ioBroker.roborock/commit/266bc8392a3ba15526e9efcfe07e4cab96322537. Please use search before opening an issue.

Thank you.

**Comment by Knallix** [comment]
Ok wurde gefixed aber wie spiele ich das dann ein  ? Habe die neuste Version installiert oder muss ich am Adapter noch was machen ? 
Konnte so direkt nichts finden. 
Vielen Dank

**Comment by copystring** [comment]
Aktuell nur in der dev Version. Die hat aber Fehler und kann ich daher nicht empfehlen. Ich arbeite daran, die dev zum release zu machen.

**Comment by Knallix** [comment]
okay alles klar . dann warte ich :) DANKE

**Comment by copystring** [comment]
Wenn du magst, kannst du ab sofort die dev testen. https://github.com/copystring/ioBroker.roborock/tree/dev sollte stabil genug sein. Das wird dann der nächste Release, falls keine gravierenden Fehler auftauchen.
