### ISSUE TITLE
Parser bug error in RRMapParser

### ISSUE THREAD

**Issue by konqi** [copystring/ioBroker.roborock#435]
**Describe the bug**  
There is a little bug in lib/RRMapParser.js.
In method `PARSE` `data_length` (line 370) is read as a `UInt16`, when in reality it's a `UInt32`. Not sure if this value is used anywhere 🤷. You can verify the correctness of this statement when you sum up header_length and data_length, the sum should be equal to the length of the buffer. Thought I'd let you know ^^

Edit: Just realised that map_sequence and map_index must be UInt32 for the same reason, they would be bad pointers if the valid range can only address half of the payload

**Comment by copystring** [comment]
Hi,

thank you for looking into this. Have you locally applied your changes and tested the adapter after that? Does it correctly create a map?
For example, changing `data_length` from `UInt16` to `UInt32` would change the length in my example from `14338` to `407554` which does not seem quite correct.

I have noticed a while ago there is some more data after `data_length` I'm just not quite sure what it is. See https://github.com/copystring/ioBroker.roborock/blob/ba1f62ec738fb404838469da4225a2e96a8514ca/lib/RRMapParser.js#L268

Let me know what you think.

**Comment by copystring** [comment]
Looks like you're correct. I wonder what kind of data it contains. `407554` is a LOT longer than `14338` ...

**Comment by konqi** [comment]
Given that there is one byte for each pixel and mine is for example 393 by 415 = 163095 byte it makes sense that the number is higher 😉 .
Yupp, I believe the code simply ignores data_length and accesses the raw pixel data by iterating over width and height. That's why I said
> Not sure if this value is used anywhere 🤷
So parsing those values correctly doesn't do anything right now. It could help you in the future, if you start using it - possible save you from some headaches. You could use it to check if you're running out of bounds before accessing pixel data (x + y*width < data_length). Somewhat related: The last 20 bytes of the payload (aka digest) is a SHA-1 of all data in the payload up until the last 20 bytes (in case you want to check the integrity of the data before parsing it)

**Comment by copystring** [comment]
I implemented these changes: https://github.com/copystring/ioBroker.roborock/commit/e7b190e01f7ee6f73b6f8fd6d012c7194e71d2d3
