### ISSUE TITLE
Status / Commands - Automatische Entleerung 

### ISSUE THREAD

**Issue by SmarthomeEmmi** [copystring/ioBroker.roborock#440]
Ich habe den Q7 Max+ mit Absaugstation.

Leider kann ich keinen Status zur "Einstellung der automatischen Entleerung" finden.
Es wäre super den Status zu haben und auch über commands zu ändern um Zeitpläne dafür zu realisieren.
(Aktuell lässt sich über den DND-Modus der App zwar eine Zeit vorgeben in der nicht abgesaugt wird, leider nicht für welche Tage) 

Das command "Staubbehälter entleeren" fehlt leider ebenfalls.

Danke & Grüße

**Comment by copystring** [comment]
Welche von diesen sind bei dir verfügbar?![Screenshot_20231129-223343.png](https://github.com/copystring/ioBroker.roborock/assets/1298861/82e7c244-a877-4ef3-895b-f28d3c2830db)

**Comment by SmarthomeEmmi** [comment]
Der Schalter "Automatische Entleerung" und die Einstellung "Entleerungsmodus" sind beim Q7Max verfügbar.

**Comment by SmarthomeEmmi** [comment]
Einen "robot key" habe ich im gesamten Log leider gar nicht.
Du meinst nicht das "model":"roborock.vacuum.a38" ?
