### ISSUE TITLE
Support water_box_custom_mode and water_box_distance_off

### ISSUE THREAD

**Issue by copystring** [copystring/ioBroker.roborock#441]
Aber warum kann ich den DP set_mop_mode nicht ändern? Das sollte doch gehen oder?
In der Roborock App kann ich die Werte ändern.
Viele Grüße
![Bildschirmfoto 2023-11-25 um 09 11 12](https://github.com/copystring/ioBroker.roborock/assets/151871141/18ddc496-58c8-4e00-a1d4-0f57c9484aa5)

_Originally posted by @stefan206cc in https://github.com/copystring/ioBroker.roborock/issues/329#issuecomment-1826251741_

**Comment by copystring** [comment]
Hier gehts weiter. Teste bitte die aktuelle dev https://github.com/copystring/ioBroker.roborock/tree/dev
Dort gibt es jetzt water_box_custom_mode und water_box_distance_off

**Comment by stefan206cc** [comment]
Ja genau ich habe einen Roborock S6 MaxV. Werde ich heute Abend testen.

**Comment by copystring** [comment]
OK. Nur als Information. `mop_mode` gibt es beim S6 nicht und ist somit entfernt. Es wird aber bei dir weiterhin in den commands stehen. Den Befehl kannst du aber löschen.

**Comment by stefan206cc** [comment]
HI, ich habe die Version getestet. Funktioniert alles super!! Viele Dank!

**Comment by copystring** [comment]
Top.
