### ISSUE TITLE
Update von Datenpunkten

### ISSUE THREAD

**Issue by KoMa1978** [copystring/ioBroker.roborock#451]
Hallo,

wann und in welcher Frequenz werden denn die Datenpunkte aktualisiert?

Ich habe eben in der App beobachtet, wie mein Q Revo am laden ist und die Anzeige von 24% auf 25% umsprang.

In den ioBroker Datenpunkten steht aber immer noch 17% und er sagt als Zeitstempel der letzten Aktualisierung den Zeitpunkt als ich die Instanz neu gestartet habe.

![image](https://github.com/copystring/ioBroker.roborock/assets/57285166/27948c51-9355-41f5-8634-8cfd6f2943d9)

Dies nur als Beispiel, es scheint alle Werte zu betreffen, zumindest in "deviceStatus".

Ich nutze die DEV Version (siehe #439 ).

**Comment by copystring** [comment]
Hi, poste bitte eine Debuglog, in dem der Fehler zu sehen ist.

**Comment by KoMa1978** [comment]
Hi,

er ist ja leider nicht zu sehen. So wie es aussieht, startet der Adapter, dann wird nach ein paar Minuten alles ein Mal aktualisiert und dann ist Ruhe. Das kann ich aber nicht verifzieren, da er aktuell nicht reinigt. Daher ja auch die generelle Frage, in welcher Frequenz diese Daten aktualisiert werden.

Ich habe eben den Adapter im Debug neu gestartet und da wurden alle Datenpunkte einmal aktualisiert. Seitdem (~15 Min) ist Ruhe ... "homedata" wird jede Minute aktualisiert:

![image](https://github.com/copystring/ioBroker.roborock/assets/57285166/3b99e0f1-bd69-4f47-96bb-e24efa317ea1)

Als Vergleich:
![image](https://github.com/copystring/ioBroker.roborock/assets/57285166/917337ed-1f59-4631-8d93-ef4a76cd07da)

[debug.log](https://github.com/copystring/ioBroker.roborock/files/13624259/debug.log)

Ich lass das jetzt mal so laufen mit Debug, aber auch davor war das Verhalten ähnlich: Update erfolgte kurz nach Adapterstart, danach nicht mehr, auch wenn er gereinigt hat oder geladen wurde.

**Comment by copystring** [comment]
Ist das auch mit der aktuellsten Dev so?

**Comment by KoMa1978** [comment]
Sieht auf den ersten Blick besser aus, hab eben grad die DEV nochmal neu installiert ...

Werde es beobachten. Danke Dir!

**Comment by KoMa1978** [comment]
Leider Kommando zurück ...

Unterhalb von deviceStatus gibt es keine Updates (15:00 hab ich die Instanz aktualisiert und neu gestartet).
Man sieht aber im Log, dass die Infos ankommen, dass er losfährt und dass er zurückfährt.

ioBroker:
![image](https://github.com/copystring/ioBroker.roborock/assets/57285166/13348949-921e-46e2-98bd-a16061ff209f)

App:
![image](https://github.com/copystring/ioBroker.roborock/assets/57285166/5299ef22-1621-4696-8557-bd64f167707c)

Debug:
[debug.log](https://github.com/copystring/ioBroker.roborock/files/13624356/debug.log)

**Comment by copystring** [comment]
Merkwürdig. Zeig mal bitte dein homedata. Dort solle `online` `true` sein. Anhand dessen wird der Updater für die Daten gestartet.

**Comment by KoMa1978** [comment]
Hi,

hat ein wenig gedauert, unten findest du das homedata. Online ist true und das Merkwürdige ist ja, dass deviceInfo permanent aktualisiert wird, andere wie deviceStatus eben nicht ...

{"id":5159559,"name":"My Home","lon":null,"lat":null,"geoName":null,"products":[{"id":"xxxXXXxxx","name":"Roborock Q Revo","model":"roborock.vacuum.a75","iconUrl":null,"attribute":null,"capability":0,"category":"robot.vacuum.cleaner","schema":[{"id":"101","name":"rpc_request","code":"rpc_request","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"102","name":"rpc_response","code":"rpc_response","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"120","name":"错误代码","code":"error_code","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"121","name":"设备状态","code":"state","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"122","name":"设备电量","code":"battery","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"123","name":"清扫模式","code":"fan_power","mode":"rw","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"124","name":"拖地模式","code":"water_box_mode","mode":"rw","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"125","name":"主刷寿命","code":"main_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"126","name":"边刷寿命","code":"side_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"127","name":"滤网寿命","code":"filter_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"128","name":"额外状态","code":"additional_props","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"130","name":"完成事件","code":"task_complete","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"131","name":"电量不足任务取消","code":"task_cancel_low_power","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"132","name":"运动中任务取消","code":"task_cancel_in_motion","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"133","name":"充电状态","code":"charge_status","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"134","name":"烘干状态","code":"drying_status","mode":"ro","type":"RAW","property":null,"desc":null}]}],"devices":[],"receivedDevices":[{"duid":"xxxXXXxxx","name":"Robbie","attribute":null,"activeTime":1700987603,"localKey":"xxxXXXxxx","runtimeEnv":null,"timeZoneId":"Europe/Berlin","iconUrl":"","productId":"ldHlB6hwVPMvdm6AdkxJv","lon":null,"lat":null,"share":true,"shareTime":1700988017,"online":true,"fv":"02.16.98","pv":"1.0","roomId":15220223,"tuyaUuid":null,"tuyaMigrated":false,"extra":null,"setting":null,"sn":"xxxXXXxxx","featureSet":"2238601361260287","newFeatureSet":"00000000081AFFFE","deviceStatus":{"120":0,"121":8,"122":100,"123":102,"124":203,"125":86,"126":84,"127":72,"128":0,"133":1,"134":0},"silentOtaSwitch":false,"f":false}],"rooms":[]}

**Comment by copystring** [comment]
In den homedata scheint veraltet zu sein. Dort ist nur der geteilte Saugroboter zu sehen und nicht, der direkt in deinem Konto angemeldet ist. Wenn du homedata löschst und den Adapter neu startest, sollte es wieder laufen.
