### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by FlexerJR** [copystring/ioBroker.roborock#456]
Hi Copystring,

hier nochmal die aktuellen Fehler des Adapters im Debugmode

[roborock01.txt](https://github.com/copystring/ioBroker.roborock/files/13662107/roborock01.txt)

Beste Grüße

**Comment by copystring** [comment]
Hi,

und was ist das Problem?

**Comment by FlexerJR** [comment]
Ah sorry, 

also Roboter lässt sich nicht starten. Alle datenpunkte werden quasi nicht aktualisiert. Wenn er reinigt bleibt Batterie bei 100%. Bis gestern lief alles noch prima, auch aktualisierung der Karte usw. Seit heute morgen nichts mehr. Bin auf der letzten Dev version

**Comment by copystring** [comment]
Seit wann hast du das Problem?

**Comment by FlexerJR** [comment]
Habe das seit gestern morgen. War auf der Dev Version die eigentlich gut lief. Dann habe ich den Adapter deinstalliert und mal auf stable zurück. Auch kein Erfolg. 

Ich schätze dass das Problem seitens Roborock ist. Wlan Empfang liegt zwischen -66 bis -44. Ab und zu läd die App auch keine Daten. Muss nehrmals geöffnet und geschlossen werden. Ich beobachte das Verhalten mal. Evtl ist das nur temporär. Aktuell bin ich wieder auf Dev aber nichts geht.

**Comment by copystring** [comment]
Wenn es mit der stable auch nicht geht, würde ich mal den Adapter anhalten, den Saugroboter neu starten und anschließend den Adapter wieder starten. Ich hatte es auch schon ein paar Mal, dass da irgendwas im Roboter stecken geblieben ist.

**Comment by FlexerJR** [comment]
![image](https://github.com/copystring/ioBroker.roborock/assets/40354380/01af57da-1bfa-4252-badf-b842665f4c52)

Hier sieht man eigentlich ganz gut was passiert. Bei der Batterie bekomme ich am Anfang noch Daten. Doch dann bricht irgendwann die Verbindung ab. Zwischendurch aktualisiert sich der Datenpunkt mal wieder. Unten ist der WLAN Empfang zu sehen, der meiner Meinung nach vollkommen in Ordnung ist. Damit hatte ich eigentlich auch noch nie Probleme, seitdem ich den Roboter habe.

Ich schätze das seitens Roborock Probleme vorher herrschen bin mir aber nicht sicher. Werde das weiter beobachten und mit Dev und Stable testen und mich hier melden.

Viele Grüße

**Comment by copystring** [comment]
Sind das zufälligerweise genau 3 Stunden? Roborock verlangt nach 3 Stunden eine Neuverbindung. Dies sollte der Adapter automatisch machen

**Comment by FlexerJR** [comment]
So, habe jetzt etwas getestet. Aktueller Stand ich bin auf 0.4.4 im stable. Bekomme keine Verbindung hin
Dev deinstalliert. 
0.4.4. stabe installiert
Roborock neugestartet bzw stromlos gemacht. Über die App funktioniert alles. Über egal welche Version des Adapters keine Chance eine Verbindung herzustellen. Ob das mit den 3 Stunden zusammenhängt kann ich nicht sagen, bzw bestätigen. Sollte sich was ändern melde ich mich gerne hier oder auch im Forum.

**Comment by saint-hh** [comment]
Ich bin mit meinem Q8 mit den selben Problemen im Boot. 
Gibt keine Verbindung mehr zum Robby. Den Q8 neu gestartet, die Dev neu installiert, ganzes System neu gestartet - bringt alles nichts. Seit 2 Tagen wird nichts mehr aktualisiert. Commands habe ich wieder auf ack = false umgestellt.

Beim Start des Adapters kommt folgendes im Log:


```
2023-12-14 12:51:51.415 | warn | Failed to execute get_clean_summary on robot XX Error: Request with id 6826 with method get_clean_summary timed out after 10 seconds for response.102
-- | -- | --
roborock.0 | 2023-12-14 12:51:51.410 | warn | Failed to execute get_status on robot XX Error: Request with id 3157 with method get_status timed out after 10 seconds for response.102
roborock.0 | 2023-12-14 12:51:51.407 | warn | Failed to execute get_fw_features on robot XX Error: Request with id 3958 with method get_fw_features timed out after 10 seconds for response.102
roborock.0 | 2023-12-14 12:51:41.707 | info | State value to set for "roborock.0.Devices.XX.programs.1546411.items.0.finishDpIds" has to be type "string" but received type "object"
roborock.0 | 2023-12-14 12:51:41.704 | info | State value to set for "roborock.0.Devices.XX.programs.1546411.items.0.id" has to be type "string" but received type "number"
roborock.0 | 2023-12-14 12:51:40.920 | info | MQTT initialized
roborock.0 | 2023-12-14 12:51:39.751 | info | starting. Version 0.4.4 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.19.0, js-controller: 5.0.17
```
Danach wird dann das Log weiter mit Warnings geflutet, dass er nichts aktualisieren kann.

**Comment by copystring** [comment]
Also verstehe ich das richtig, dass es über stable auch nicht mehr läuft?

**Comment by saint-hh** [comment]
Die Frage richtet sich wohl nicht an mich, ich bin auf der Dev.
Mal ein frisches Debug Log:
[Debug_Log_Q8.txt](https://github.com/copystring/ioBroker.roborock/files/13673029/Debug_Log_Q8.txt)

**Comment by FlexerJR** [comment]
Also ich bin auf der letzten Stable 0.4.4. müsste es sein. Keine Chance auf eine Verbindung. Egal ob DEV oder Stable. Ging vor ca 2 Tagen los.

**Comment by copystring** [comment]
OK. Muss ich mir in Ruhe angucken. Dauer aber ein Weilchen. Muss dafür erstmal Zeit finden und es anschließend analysieren.

**Comment by copystring** [comment]
@FlexerJR  Ich habe den Fehler gestern Abend noch gesehen. Heute Morgen taucht er nicht mehr auf. Ist das bei dir auch so?

**Comment by FlexerJR** [comment]
Hallo nochmal @copystring, so jetzt aber richtiges Issue.

Also wie bereits erwähnt wr heute morgen alles perfekt. Jetzt bin ich wieder an dem Punkt, dass die Verbindung weg ist. 

Hier nochmal der Screenshot von Batterie und Empfang. 

Log sind wieder die selben Fehler wie oben in dem Log mit Failed to execute usw. 

![image](https://github.com/copystring/ioBroker.roborock/assets/40354380/fa4ccced-d86b-4785-b260-29127891e9d4)

**Comment by saint-hh** [comment]
> @FlexerJR Ich habe den Fehler gestern Abend noch gesehen. Heute Morgen taucht er nicht mehr auf. Ist das bei dir auch so?

Bei mit funktioniert wieder alles. 
Gab es Probleme von der Roborock Seite?

**Comment by FlexerJR** [comment]
Also bei mir gehts aktuell 11:49 nicht. Habe auch mein komplettes Netzwerk durchgestartet. Reboot tut gut. Seit 10:30 ist keine Verbindung mehr da. Hab dir das Log nochmal reingepackt im Debug. Ich verstehe es nicht, aus folgenden Gründen. 
Es lief wunderbar, habe nichts angefasst oder geändert und plötzlich klappt es nur sporadisch. Heute morgen lief es super für ca. 1-2 Stunden.

Die App funktioniert. Ab und zu muss man auf zurück und wieder auf eingabe klicken. Vielleicht 1-2 mal dann kommt die Karte mit den Informationen. Sonst steht dort Netzwerk ist langsam. 

Beste Grüße

**Comment by copystring** [comment]
Stimmt. Ist bei mir auch so. Roborock muss da irgendwas geändert haben.

**Comment by FlexerJR** [comment]
Habe eben gerade mal den Adapter 5 Stunden ausgehabt. Jetzt habe ich ihn wieder angemacht und alles ist fehlerfrei. Also meine Laienhafte Vermutung ist, dass was auf der Seite von Roborock falsch läuft... Mal schauen wie lange das jetzt anhält.

**Comment by flolee** [comment]
Habe auch Probleme seit 2 Tagen - bei mir wirkt sich das aber auch auf die App aus, also die App funktioniert im WLAN zu Hause ohne Probleme, von extern keine Chance auf Zugriff, weder lädt die Karte noch reagiert der S8 auf irgend einen Button in der App. Scheint wohl wirklich ein Roborock-Serverproblem zu sein?

```
roborock.0
2023-12-15 19:05:47.893	info	terminating

roborock.0
2023-12-15 19:05:47.392	warn	Terminated (UNCAUGHT_EXCEPTION): Without reason

roborock.0
2023-12-15 19:05:47.390	info	terminating

roborock.0
2023-12-15 19:05:47.358	error	Cannot read properties of null (reading 'devices')

roborock.0
2023-12-15 19:05:47.356	error	TypeError: Cannot read properties of null (reading 'devices') at roborock_mqtt_connector.initUser (/opt/iobroker/node_modules/iobroker.roborock/lib/roborock_mqtt_connector.js:90:22) at /opt/iobroker/node_modules/iobroker.roborock/main.js:184:25

roborock.0
2023-12-15 19:05:47.348	error	unhandled promise rejection: Cannot read properties of null (reading 'devices')

roborock.0
2023-12-15 19:05:47.347	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

roborock.0
2023-12-15 19:05:44.527	info	starting. Version 0.4.4 (non-npm: copystring/ioBroker.roborock#c3079a196965937179bf5be264d311976e1f58b2) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.17.1, js-controller: 5.0.17
```

**Comment by copystring** [comment]
Ich bin mir noch unsicher. Bisher konnte ich das Problem nicht eingrenzen. Es ist bei mir jedoch so, dass wenn der Adapter nicht geht, die App weiterhin läuft. 

@flolee ich glaube, du hast einen anderen Fehler. Wahrscheinlich den gleichen wie Bert. Siehe https://github.com/copystring/ioBroker.roborock/issues/458 klink dich dort bitte ein.

**Comment by saint-hh** [comment]
> Es ist bei mir jedoch so, dass wenn der Adapter nicht geht, die App weiterhin läuft.

So ist es bisher bei mir auch.

**Comment by saint-hh** [comment]
Das wird wirklich ein Problem bei den Roborock Servern sein. 
Nach dem abschließen ist er nicht automatisch (via Adapter) gestartet. Beim Zugriff auf die App (mit oder ohne VPN) kommt nun dies:
![IMG_2396](https://github.com/copystring/ioBroker.roborock/assets/25373251/5af3b190-b69a-470f-b49a-2be35ca6df44)

**Comment by copystring** [comment]
Wenn das Problem auftaucht, geht die Handy App wieder, nachdem du das Handy neu gestartet hast?

**Comment by saint-hh** [comment]
Problem besteht weiterhin und App abschießen als auch Telefon neu starten bringt nichts. 
Ich konnte aber den Q8 via App immerhin über das Programm „Vollreinigung“ starten.

**Comment by saint-hh** [comment]
![IMG_2408](https://github.com/copystring/ioBroker.roborock/assets/25373251/c7a467e4-72a9-46c2-ade4-f3fb3dcf2990)
Status wird auf der Seite auch angezeigt, offensichtlich hat er gereinigt (Akkustand). Auf der Seite mit der Karte geht aber weiter nichts.

**Comment by saint-hh** [comment]
Die App läuft seit einer Weile wie sie soll, der Adapter bekommt nach wie vor nix.

**Comment by copystring** [comment]
Ich konnte jetzt zwei Tage hintereinander feststellen, dass das Problem jedes Mal am nächsten Morgen verschwindet und dann im Laufe des Tages wieder auftaucht. Keiner meiner beiden Saugroboter reagiert dann. Ein geteilter Saugroboter jedoch schon. Sehr merkwürdiges Verhalten und ich bin bisher nicht dahintergekommen, was das sein kann.
Zum Testen habe ich in der dev qos: 1 für gesendete mqtt Nachrichten gesetzt. Ich meine, das ist bei der App auch so.

**Comment by saint-hh** [comment]
Hab gerade die aktuelle Dev installiert. Mal schauen. 
Aber auch die App zickt nach wie vor. Meldungen genau wie gestern (Netzwerk langsam + keine Map Daten). Jedoch fängt die App sich nach ein paar Minuten und zeigt dann doch die Daten. 
Nun, nach ein paar Minuten: kommt nach wie vor nix beim Adapter an. 

In welche Richtungen gehen denn deine Vermutungen? In Hinsicht auf die App Zickereien kommt es mir ja so vor, als ob Roborock aktuell Probleme mit deren Servern hat. Kickt da gerade vielleicht auch eine Priorisierung rein? Dass im aktuellen Ressourcen Bottleneck zuerst versucht wird die offizielle App zu beliefern, die API für Fremdanwendungen sich aber ganz hinten anstellen darf?

**Comment by jahnbes** [comment]
Mea culpa, habe gerade bemerkt, dass ich für einen ähnlichen, vielleicht sogar gleichen Fehler ein weiteres issue aufgemacht hatte:
https://github.com/copystring/ioBroker.roborock/issues/458
Dort stehen meine logs und Weiteres.

Die letzte, aktuelle Zusammenfassung des Fehlerbildes bei mir ist:
o immer kein Kontakt zum robo
o homeDATA voll, löschen userDATA bringt nichts (einige (?) Stunden)
o homeDATA „null“, löschen userDATA bringt nichts (einige (?) Stunden)
o Adapter abschalten, über Nacht warten
o homeDATA „null“, “, löschen userDATA, dann geht wieder alles
o aber nur für wenige (?) Stunden

**Comment by copystring** [comment]
Hallo Bert, dein Problem ist ein anderes. Bei dir meldet sich der Adapter gar nicht im Konto an wahren wir hier darüber reden, dass roborock nicht immer antworten über mqtt übermittelt.

**Comment by ckerfurt** [comment]
Geiches Problem bei mir auch. Keine Verbindung zum Robi und viele "Failed to execute"-Warnings.

**Comment by copystring** [comment]
Ich weiß, was ich tun muss, damit es wieder läuft. Gebt mir etwas Zeit. Sobald getestet werden kann, melde ich mich.

**Comment by copystring** [comment]
@ckerfurt 

Schreib mir mal eine E-Mail an copystring@gmail.com. Mein Arbeitskollege kennt dich. :)

**Comment by copystring** [comment]
Hallo Leute! Frohe Weihnachten euch allen! Hier mein Weihnachtsgeschenk an euch 🎁🎁🎁
Die neue dev ist da: https://github.com/copystring/ioBroker.roborock/tree/dev
In der wird ab sofort eine Verbindung direkt zu den Saugrobotern erstellt, anstatt über den Server von Roborock zu gehen. Also ohne Cloud. Nur die Karte wird über die Cloud abgerufen. Soweit ich weiß, ist es so, dass über die Cloud die Karte häufiger aktualisiert wird. Konnte das aber nicht testen, da bei mir die Cloud weiterhin gesperrt ist.

Sorry, dass es lange gedauert hat. Ich musste wirklich viel neuen Code schreiben und erstmal lernen, wie mal die TCP-Pakete zum und vom Roboter sauber mitschneiden, erstellen und korrekt senden kann.

Bei mir lief alles gut, aber es wird ganz sicherlich Bugs haben.

**Comment by saint-hh** [comment]
Ja geil, tausend Dank, direkte Verbindung ist ja Zucker!
Wie bekommst du das hin, via MQTT?

Allen entspannte Festtage!

**Comment by copystring** [comment]
@saint-hh 
Habe aus Versehen deinen Kommentar editiert. Habe das wieder rückgängig gemacht. Sorry :D

> Wie bekommst du das hin, via MQTT?

Nein. Das läuft über TCP. Deshalb hat es so lange gedauert. Habe noch nie etwas mit TCP gemacht.

**Comment by saint-hh** [comment]
Sehr cool. :)

Erster Testlauf:

`error	Failed to execute writing test.rrmap on robot XX Error: ENOENT: no such file or directory, open './test.rrmap' at Object.openSync (node:fs:596:3) at Object.writeFileSync (node:fs:2322:35) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:101:9) at processTicksAndRejections (node:internal/process/task_queues:95:5)`

Nach mehrmaligen durchholen des Adapters scheint er dann zu tun.

**Comment by copystring** [comment]
Oh, ja, den Fehler habe ich ganz vergessen. Hat aber erstmal nichts mit diesem Problem hier zu tun.

**Comment by FlexerJR** [comment]
Hallo @copystring 

Vielen lieben Dank für das Weihnachtsupdate, ich habe es heute morgen geladen und werde es testen. Am Anfang hatte ich wieder Failed to execute Errors. Die Fehler gingen aber nach einem Neustart des Adapters weg. 

Wie gesagt ich teste heute mal etwas und melde mich. 

Frohe Weihnachten an alle ;)

**Comment by FlexerJR** [comment]
Ho ho ho und guten Morgen. Habe eben mit der letzten Dev Version den Roborock gestartet. Aktuell keine Fehler. Sogar die Karte wird fleißig aktualisiert. 

Warten wir mal ab, denn wie unsere Erfahrung geheigt hat kann das ja auch nur temporär sein. 


![image](https://github.com/copystring/ioBroker.roborock/assets/40354380/129299d6-c47a-4202-a95b-fa2039da744b)

**Comment by saint-hh** [comment]
Nach der ersten Aktualisierung lief es eine zeitlang, dann hatte der Adapter wieder die Verbindung zum Q8 verloren. Gestern habe ich ihn dann wieder "manuell" über die App gestartet.
Jetzt nochmals die DEV aktualisiert und momentan hat er wieder die Verbindung - und auch wieder die letzten Reinigungen - die er lange nicht bekommen hat.
Nichts desto trotz gibt es ein paar Errors - ich hab dir mal ein Debug angehängt:
[2023_12_26_Debug_Log_Q8-1.txt](https://github.com/copystring/ioBroker.roborock/files/13771548/2023_12_26_Debug_Log_Q8-1.txt)

**Comment by saint-hh** [comment]
Nach kürzerem Test: sieht wohl recht gut aus - Gratulation! 
Gelegentlich Warnings, aber ansonsten scheint es zu laufen.
Ich hab mal ein längeres Debug erzeugt, falls du mal durchschauen möchtest, ob das alles so läuft, wie gewünscht. 
[2023_12_26_Debug_Log_Q8-2.txt](https://github.com/copystring/ioBroker.roborock/files/13772550/2023_12_26_Debug_Log_Q8-2.txt)

**Comment by copystring** [comment]
> Nach kürzerem Test: sieht wohl recht gut aus - Gratulation! Gelegentlich Warnings, aber ansonsten scheint es zu laufen. Ich hab mal ein längeres Debug erzeugt, falls du mal durchschauen möchtest, ob das alles so läuft, wie gewünscht. [2023_12_26_Debug_Log_Q8-2.txt](https://github.com/copystring/ioBroker.roborock/files/13772550/2023_12_26_Debug_Log_Q8-2.txt)

Das Log sieht für mich erstmal ganz gut aus. Ich denke da muss nichts weiter getan werden.

**Comment by FlexerJR** [comment]
Einen schönen guten Abend,

hier nun meine erste Rückmeldung. Ich habe den Adapter jetzt ein paar Tage nicht angefasst. Es läuft alles fast perfekt. Der Roboter war jeder Zeit über den Adapter ansprech- und steuerbar. Nur heute hat er die Karte nicht nehr aktualisiert. Nach einem Neustart des Adapters ist die Karte wieder aktuell. 

Keine Fehlermeldungen aktuell

Grüße

**Comment by saint-hh** [comment]
Guten Abend in die Runde,

> Es läuft alles fast perfekt. Der Roboter war jeder Zeit über den Adapter ansprech- und steuerbar.
> 
> Keine Fehlermeldungen aktuell

dem kann ich mich nur anschließen. Nicht ganz so eine lange Dauer (wegen Q8 Max spezifischer Fixes), aber nun auch schon paar Tage. Läuft aktuell absolut stabil (wie noch nie zuvor), macht einen richtig guten Eindruck. 
Direkte Verbindung ist natürlich auch erste Sahne auf diversen Ebenen, cool das du das hinbekommen hast, copystring! 
Wird ja ein ziemliches Knallerrelease!

Tausend Dank nochmals, viele Grüße und schon mal (in Erwartung dass es weiter super läuft) einen guten Rutsch!
Grüße

**Comment by copystring** [comment]
Danke an alle fürs testen. Ich denke es kann geschlossen werden.
