### ISSUE TITLE
Unknown block type: Block type is:34

### ISSUE THREAD

**Issue by Bart1909** [copystring/ioBroker.roborock#457]
Hi,

beim Roborock Q Revo meldet im Adapter immer:

```
Unknown block type! Please report this to the developer. Block type is:34
```

Installiert ist Version 0.4.4

**Comment by copystring** [comment]
Hi,

danke, aber das ist in der dev bereits gefixt.

**Comment by Bart1909** [comment]
Ah okay, dann teste ich das mal! :)

**Comment by FlexerJR** [comment]
Hallo und schönen guten Morgen,

habe vor 10 min die alte Instanz deinstalliert und den DEV frisch installiert. Roboter davor ausgeschaltet und alles sauber hoch gefahren. Im Debug Log habe ich nicht eine einzige Warnung oder irgendeinen Fehler. Daten kommen sauber rein. 

Sieht gut aus. Werde heute ausgiebig testen. 

@copystring Hast du eine Idee was das war?

**Comment by FlexerJR** [comment]
Ach sorry. Habe auf die falsche Email reagiert. Das andere Issue ist aber auch gelöst
