### ISSUE TITLE
keine Verbindung mehr zwischen dem Roborock und iobroker

### ISSUE THREAD

**Issue by jahnbes** [copystring/ioBroker.roborock#458]
Hi copystring, 
bei mir gibt es keine Verbindung mehr zwischen dem Roborock und iobroker, eine Steuerung und Werteübermittlung ist nicht mehr möglich. Die Steuerung und auch die Werteübermittlung funktionieren ohne Probleme zwischen der App (Android) und dem Roborock.
Die dev-Version des Adapter habe ich probehalber installiert, mit dem gleichen Fehler. Anschließend habe ich wieder die "normale" Version 0.4.4 installiert, klar, der Fehler blieb.
Alles steht.
Ich habe einen roborock S7 MaxV, der iobroker läuft auf einem raspberry 4, das log-file (mit der DEBUG-Einstellung) hänge ich an.
Viele Grüße, Bert.
[iobroker.2023-12-15.log.txt](https://github.com/copystring/ioBroker.roborock/files/13689044/iobroker.2023-12-15.log.txt)

**Comment by copystring** [comment]
Hallo Bert,
lange nichts gehört :)

Poste bitte mal dein homeData.

**Comment by jahnbes** [comment]
Hallo copystring,

stimmt, und es war nicht nur Urlaub. Wir wollten ja auch mal miteinander skypen oder so. Es wird werden. Der Robo und sein Adapter liefen bis zum Urlaub ohne Problme in der angegebenen Version, Als ich gestern wieder kam, ging gar nichts mehr.
Ich bin mir nicht im klaren, was Du mit homeData meinst. Wenn es meine persönlichen Kontaktdaten sind, die schicke ich Dir gleich (ich glaube, noch einmal) privat. Viele Grüße, Bert.

**Comment by jahnbes** [comment]
Hallo copystring,
Nun habe ich es gefunden und unter homeDATA des roborock-Adapters steht bei mir "null". ??
Viele Grüße, Bert.

**Comment by copystring** [comment]
Ja, genau da ist das Problem. Roborock gibt dem Adapter kein homedata. Das konnte ich bisher aber nicht reproduzieren. Du könntest aber Mal userdata löschen und gucken ob das hilft.

**Comment by jahnbes** [comment]
Problem gelöst, das Löschen von userdata hat geholfen. Danach den Adapter neu gestartet und alles ging wieder!
Danke!
Wann wollen wir wegen des Wiki und wie weiter mal skypen oder so? Morgen hätte ich Zeit, heute bin ich knapp drann.
Viele Grüße, Bert.

**Comment by jahnbes** [comment]
Problem gelöst, das Löschen von userdata hat geholfen. Danach den Adapter neu gestartet und alles ging wieder!
Danke!
Wann wollen wir wegen des Wiki und wie weiter mal skypen oder so? Morgen hätte ich Zeit, heute bin ich knapp drann.
Viele Grüße, Bert.

**Comment by copystring** [comment]
Morgen Abend könnte klappen. Aber erst spät. So um 10 Uhr abends. Passt dir das?

**Comment by jahnbes** [comment]
Passt, da muss ich blos wachbleiben ...
Viele Grüße, Bert.

**Comment by jahnbes** [comment]
Allein, die Freude währte nur einen halben Tag, schon wieder keine Verbindung. Diesmal sind homeDATA und userDATA mit Daten gefüllt. Ein Streichen von userDATA, wie beim letzten Mal, brachte keinen Erfolg.
homeDATA:
{"id":4052588,"name":"Schöneich","lon":null,"lat":null,"geoName":null,"products":[{"id":"42yfoQm5eOY3gARZw6xgU","name":"Roborock S7 MaxV","model":"roborock.vacuum.a27","iconUrl":null,"attribute":null,"capability":0,"category":"robot.vacuum.cleaner","schema":[{"id":"101","name":"rpc_request","code":"rpc_request","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"102","name":"rpc_response","code":"rpc_response","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"120","name":"错误代码","code":"error_code","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"121","name":"设备状态","code":"state","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"122","name":"设备电量","code":"battery","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"123","name":"清扫模式","code":"fan_power","mode":"rw","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"124","name":"拖地模式","code":"water_box_mode","mode":"rw","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"125","name":"主刷寿命","code":"main_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"126","name":"边刷寿命","code":"side_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"127","name":"滤网寿命","code":"filter_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"128","name":"额外状态","code":"additional_props","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"130","name":"完成事件","code":"task_complete","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"131","name":"电量不足任务取消","code":"task_cancel_low_power","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"132","name":"运动中任务取消","code":"task_cancel_in_motion","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"133","name":"充电状态","code":"charge_status","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"134","name":"烘干状态","code":"drying_status","mode":"ro","type":"RAW","property":null,"desc":null}]}],"devices":[{"duid":"1NmW0q7YbLpmdhMT2EIl5i","name":"Roborock S7 MaxV","attribute":null,"activeTime":1678280479,"localKey":"CCtulQ3pU7dC7vRy","runtimeEnv":null,"timeZoneId":"Europe/Berlin","iconUrl":"","productId":"42yfoQm5eOY3gARZw6xgU","lon":null,"lat":null,"share":false,"shareTime":null,"online":true,"fv":"02.58.40","pv":"1.0","roomId":null,"tuyaUuid":null,"tuyaMigrated":false,"extra":"{\"RRPhotoPrivacyVersion\": \"1\", \"RRMonitorPrivacyVersion\": \"1\"}","setting":null,"sn":"R21EES21001782","featureSet":"2234201184108543","newFeatureSet":"0000000000002F63","deviceStatus":{"120":0,"121":8,"122":100,"123":103,"124":201,"125":64,"126":46,"127":28,"128":0,"133":1},"silentOtaSwitch":true,"f":false}],"receivedDevices":[],"rooms":[{"id":12489554,"name":"Badezimmer"},{"id":11027619,"name":"Schlafzimmer"},{"id":11027611,"name":"Wohnzimmer"},{"id":11025727,"name":"Küche"},{"id":11021690,"name":"Arbeitszimmer"},{"id":11021680,"name":"Flur"}]}

**Comment by jahnbes** [comment]
Neuer Zustand: nun ist alles wieder so, wie am Anfang dieses issue beschrieben. Ein Löschen von userDATA brachte diesmal keine Abhilfe.

**Comment by copystring** [comment]
Skype?

**Comment by mproper23** [comment]
Habe das selbe Problem, wenn ich irgendwelchge Daten zu verfügung stellen kann mache ich das gerne

**Comment by jahnbes** [comment]
Das Fehlerbild sieht in etwa so aus:
o	immer kein Kontakt zum robo
o	homeDATA voll, löschen userDATA bringt nichts (einige Stunden(?))
o	homeDATA „null“, löschen userDATA bringt nichts (einige Stunden(?))
o	Adapter abschalten, über Nacht warten
o	homeDATA „null“, “, löschen userDATA, dann geht wieder alles
o	aber nur für wenige Stunden (?)

Kann das mit der neuen roborock-App zusammenhängen?

**Comment by jahnbes** [comment]
Hi mproper23,
kannst Du mal bitte schreiben, welchen Roborock Du hast und in welcher Version Deine Roborock-App läuft?
Danke, Bert.

**Comment by mproper23** [comment]
Hallo. 
mich habe den s7 maxv ultra.  App ist IOS 
Version 4.28.04 
Auf dem Robi selbst ist Firmware 2.58.40

**Comment by jahnbes** [comment]
Hi copystring, habe es eben erst bemerkt, es gibt schon ein issue zu einem ähnlichen oder gar gleichen Fehler: https://github.com/copystring/ioBroker.roborock/issues/456, machen wir dort weiter.

**Comment by copystring** [comment]
Hallo Bert,

das ist ein anderes Problem.

**Comment by copystring** [comment]
Hallo Bert, ist das Problem noch aktuell? Vielleicht magst du mal die neue dev testen, falls das Problem noch existiert.

**Comment by copystring** [comment]
Das Problem ist identisch zu https://github.com/copystring/ioBroker.roborock/issues/449.
Bitte dort fortsetzen, da dies zuerst erstellt wurde.

In der neuen dev wird `UserData` automatisch gelöscht, wenn auf die Anfrage von `homeDetail` nicht geantwortet wird. Dadurch wird ein neuer Login erzwungen und `UserData` neu erstellt.
