### ISSUE TITLE
State value to set for "roborock.0.Devices. ???? .deviceStatus.last_clean_t" has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by PLCHome** [copystring/ioBroker.roborock#461]
{
"type": "state",
"common": {
"name": "Last clean time",
"type": "number",
"role": "value",
"read": true,
"write": false
},

Is wrong if you want to write a string. It is better to add .time to the role.

{
"type": "state",
"common": {
"name": "Last clean time",
"type": "number",
"role": "value.time",
"read": true,
"write": false
},

However, the time can only be saved with .getTime() if number is specified.

Versions:

Adapter version: v0.4.4
JS-Controller version: 5.0.17
Node version: v18.19.0
Operating system: linux

**Comment by copystring** [comment]
Which robot do you have?

**Comment by PLCHome** [comment]
Roborock Q revo (A75)

**Comment by KallAdam** [comment]
beim S8 Pro Ultra ebenso

**Comment by PLCHome** [comment]
It's not stale, it's always not possible and even with several robots to exist. It's more like a bug

**Comment by copystring** [comment]
Have you tried the latest dev? This was fixed a long time ago. https://github.com/copystring/ioBroker.roborock/commit/266bc8392a3ba15526e9efcfe07e4cab96322537
I just did not have time to make a new, good release. You can try dev, but beware, it has bugs.
