### ISSUE TITLE
roborock.vacuum.a73 ist der Q8 Max+ (und weitere Klärung)

### ISSUE THREAD

**Issue by saint-hh** [copystring/ioBroker.roborock#462]
Wirklich minor, aber da ich gesehen habe, dass du die [README.md](https://github.com/copystring/ioBroker.roborock/blob/dev/README.md) mit den neuen Modellen aktualisiert hast, kann man es vielleicht vor dem Launch sauber ziehen und spätere Verwirrung vermeiden:
Bezogen auf https://github.com/copystring/ioBroker.roborock/issues/436
Da hatten wir ja Anfangs ein bisschen Konfusion, ob mein (`roborock.vacuum.a73`) ein Q8 Max oder ein Q8 Max+ ist und das dann aus den Augen verloren.
Inzwischen ist klar, der **a73** ist der **Q8 Max+** mit Absaugstation (wofür wir ja auch ein Feature implementiert haben `set_dust_collection_mode` https://github.com/copystring/ioBroker.roborock/pull/448 )
<img width="269" alt="Bildschirmfoto 2023-12-21 um 14 04 20" src="https://github.com/copystring/ioBroker.roborock/assets/25373251/eb0dec2c-95c6-4073-94ea-b6add6f91c1c">

Direkt von der Roborock Seite:
<img width="664" alt="Bildschirmfoto 2023-12-21 um 14 02 45" src="https://github.com/copystring/ioBroker.roborock/assets/25373251/41d54de8-b77e-4d79-8f9d-15dd71cd1b87">

Für den Q8 Max - also nur mit Lade- und nicht mit Absaugstation - habe ich leider noch nicht die _roborock.vacuum_ Nummer gefunden. Wird aber sicher früher oder später hier aufschlagen:
<img width="532" alt="Bildschirmfoto 2023-12-21 um 14 01 35" src="https://github.com/copystring/ioBroker.roborock/assets/25373251/cd903538-75fb-49e8-8415-9cc5131cc7cd">
Für dieses Modell könntest du dann einfach einen Klon des **+** erstellen und `set_dust_collection_mode` entfernen. Ansonsten kommt ja nix an einstellbaren oder überwachbaren Features von der Absaugstation. Der Dust collection mode ist das einzige, das man einstellen kann. 

Dann grundsätzlich zu der Kamera:
Der Q8 Max hat zwar das Feature "Reaktive-Hindernisumgehung", nutzt aber keine bildgebende Kamera dafür. Insofern könnte dieses Feature beim Q8 Max generell rausgenommen werden. 
![IMG_2415](https://github.com/copystring/ioBroker.roborock/assets/25373251/96e61104-168f-4689-b25e-110ebc1640f6)

Lass mich gerne wissen, wenn du mehr Infos brauchst oder ich etwas vergessen habe. 
Danke und Gruß!

**Comment by copystring** [comment]
> Für den Q8 Max - also nur mit Lade- und nicht mit Absaugstation - habe ich leider noch nicht die _roborock.vacuum_ Nummer gefunden. Wird aber sicher früher oder später hier aufschlagen: <img alt="Bildschirmfoto 2023-12-21 um 14 01 35" width="532" src="https://private-user-images.githubusercontent.com/25373251/292211540-cd903538-75fb-49e8-8415-9cc5131cc7cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NDA2OTIsIm5iZiI6MTcwMzU0MDM5MiwicGF0aCI6Ii8yNTM3MzI1MS8yOTIyMTE1NDAtY2Q5MDM1MzgtNzVmYi00OWU4LTg0MTUtOWNjNTEzMWNjN2NkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDIxMzk1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzOTZkZTA2ZTNlYjk3ZTk1OTUyZGRiZTFkNzY5NDBjNGNiMTBiMjY1NmI3NWMzNzFkYTQzMTQxZDYxNTQ3YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1PhZIEUAOnsMLDlEvWaN07025EOEQyT1aSPQkM1QbWE">

Nur damit ich es richtig verstehe, du denkst weiterhin, es gibt eine andere Nummer für den Q8 ohne Station?
Dem ist eben nicht so.
Ich habe jetzt nochmal ALLE bei Roborock bekannten Saugroboter direkt über die API abgefragt. Dort wird nur der Q8 gelistet. Dieser hat jedoch Untermodelle.
Hier das gekürzte JSON direkt von Roborock:

```
{
	"id": 82,
	"name": "Roborock Q8 Max",
	"model": "roborock.vacuum.a73",
	"packagename": "com.roborock.tanos",
	"ssid": "roborock-vacuum-a73",
	"picurl": "https://files.roborock.com/iot/product/6a38b4a5770d479ab60bc4219130b9df.png",
	"cardpicurl": "https://files.roborock.com/iot/product/3c381de53ce6445aa41ad43697440b8a.png",
	"mediumCardpicurl": "",
	"resetwifipicurl": "https://files.roborock.com/iot/product/f6cffed9a9814e518d49085af9d5fead.png",
	"resetwifitext": {},
	"tuyaid": "",
	"status": 1,
	"rriotid": "6cwszeXau9M2YrquXiSjJd",
	"cardspec": "...",
	"pictures": [{
			"id": 17,
			"productId": 82,
			"color": "E",
			"picUrl": "https://files.roborock.com/iot/product/c7ee59f57f8348ca86140a478f3a093c.png",
			"cardPicUrl": "https://files.roborock.com/iot/product/3f56e450bfb142bb92fac93ad51d6208.png",
			"mediumCardPicUrl": "",
			"wifiPicUrl": "https://files.roborock.com/iot/product/a9b71fcdfaa047678572f1679ab1592c.png",
			"pluginPicUrl": null,
			"createTime": "2023-07-31T03:28:17.995+00:00",
			"updateTime": "2023-07-31T03:28:17.995+00:00"
		}, {
			"id": 16,
			"productId": 82,
			"color": "H",
			"picUrl": "https://files.roborock.com/iot/product/26508f4fffd3425aad53ef3d5182b286.png",
			"cardPicUrl": "https://files.roborock.com/iot/product/47ca04076bdd4021a4663f5014619867.png",
			"mediumCardPicUrl": "",
			"wifiPicUrl": "https://files.roborock.com/iot/product/448ac85d4e224147ae5922a90a43e28d.png",
			"pluginPicUrl": null,
			"createTime": "2023-07-31T03:28:14.683+00:00",
			"updateTime": "2023-07-31T03:28:14.683+00:00"
		}, {
			"id": 15,
			"productId": 82,
			"color": "B",
			"picUrl": "https://files.roborock.com/iot/product/acd65af10c1d4e56a85e8c3f056da33e.png",
			"cardPicUrl": "https://files.roborock.com/iot/product/61161fc48efe4d9b9eedfc990319ec1e.png",
			"mediumCardPicUrl": "",
			"wifiPicUrl": "https://files.roborock.com/iot/product/5aa873f5693045ac98eecaacc82948b8.png",
			"pluginPicUrl": null,
			"createTime": "2023-07-31T03:28:11.408+00:00",
			"updateTime": "2023-07-31T03:28:11.408+00:00"
		}, {
			"id": 14,
			"productId": 82,
			"color": "C",
			"picUrl": "https://files.roborock.com/iot/product/754bfa19ebfd41f3be3d7f719d1904fa.png",
			"cardPicUrl": "https://files.roborock.com/iot/product/0750798b5874478199949e6871bf7e8f.png",
			"mediumCardPicUrl": "",
			"wifiPicUrl": "https://files.roborock.com/iot/product/6ef82b4193754156ab5933bd3fab487c.png",
			"pluginPicUrl": null,
			"createTime": "2023-07-31T03:28:08.507+00:00",
			"updateTime": "2023-07-31T03:28:08.507+00:00"
		}
	],
	...
```

Hier ist sichtbar, dass dieselbe ID für vier verschiedene Modelle verwendet wird. Ohne Station in Schwarz, ohne Station in Weiß, mit Station in Schwarz, mit Station in Weiß. Siehe die jeweilige `picUrl`

> Dann grundsätzlich zu der Kamera: Der Q8 Max hat zwar das Feature "Reaktive-Hindernisumgehung", nutzt aber keine bildgebende Kamera dafür. Insofern könnte dieses Feature beim Q8 Max generell rausgenommen werden. 

Das stimmt. Das war nur zum Testen und geht tatsächlich nicht. Ich habe bereits versucht die PIN direkt über die API zu setzen und somit die Kamera über den Adapter freizuschalten. Geht leider nicht.

Habe ich alles soweit richtig verstanden? 
Kannst mir gerne nochmal eine Rückmeldung geben. Ich werte jetzt die Funktion der Kamera für gen8 Geräte entfernen.

**Comment by saint-hh** [comment]
> Nur damit ich es richtig verstehe, du denkst weiterhin, es gibt eine andere Nummer für den Q8 ohne Station? Dem ist eben nicht so. Ich habe jetzt nochmal ALLE bei Roborock bekannten Saugroboter direkt über die API abgefragt. Dort wird nur der Q8 gelistet.

Nein, das denke ich nicht - es war eine reine Vermutung meinerseits. Vor allem genährt durch die Variable `set_dust_collection_mode` die nur bei dem Q8 mit Absaugstation greifen kann.
Wie dem auch sei - die Infos, die du abgreifen kannst, werden dann ja definitiv stimmen und alles ist gut.
Meine Intention war nur das sauber zu haben, falls die Modelle doch unterschieden werden. Dann wäre meiner, mit Absaugstation, dann halt der a73.


> 
> Das stimmt. Das war nur zum Testen und geht tatsächlich nicht. Ich habe bereits versucht die PIN direkt über die API zu setzen und somit die Kamera über den Adapter freizuschalten. Geht leider nicht.
> 
> Habe ich alles soweit richtig verstanden? Kannst mir gerne nochmal eine Rückmeldung geben. Ich werte jetzt die Funktion der Kamera für gen8 Geräte entfernen.

Ja, ich denke das ist alles richtig. Entschuldige bitte, sollte ich unnötig Verwirrung gestiftet haben. Dann mache ich hier mal dicht - danke!

**Comment by copystring** [comment]
Alles gut. Es hätte natürlich sein können, aber der Q8 ist anscheinend ein Sonderfall. Hätte ich aber auch nicht gesehen, wenn ich jetzt nicht nochmal geguckt hätte.

**Comment by saint-hh** [comment]
Beim entfernen der Kamera scheinen zwei Variablen flöten gegangen zu sein, die doch benötigt werden (auch im Debug von hier zu finden https://github.com/copystring/ioBroker.roborock/issues/456#issuecomment-1869519978 )

`error	Failed to execute get_status on robot XX Unsupported attribute: camera_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot.`

`error	Failed to execute get_status on robot XX Unsupported attribute: distance_off of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.`

**Comment by copystring** [comment]
Stimmt. Habe ich auch gerade festgestellt und direkt angepasst. Läuft jetzt wieder. Danke für das Log. Wäre mir sonst nie aufgefallen.

**Comment by saint-hh** [comment]
Prima, danke!
