### ISSUE TITLE
Iobroker - keine Verbindung zu Roborock S7

### ISSUE THREAD

**Issue by Pitri84** [copystring/ioBroker.roborock#463]
Beschreibung:
Nachdem ich den Roborock Adapter installiert habe und die LoginDaten hinterlegt hatte, verbindet sich der Adapter nicht mit Roborock.
Der S7 ist im WLAN verbunden und kann per App am Handy durch die Räume gesteuert werden.
In iObroker ist jedoch die Verbindung immer auf "rot". Und im Protokoll stehen einige Fehler Informationen.

Screenshot ist mit angefügt.

**Versions:**  
 - Adapter version: 0.4.4
 - JS-Controller version: 5.0.1
 - Node version: v20.10.0
 - Operating system: 6.1.0-rpi7-rpi-2712
- NPM: 10.2.3
- Raspberry Pi 5
- Linux IoBrokerPi5 6.1.0-rpi7-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

Vielen Dank vorab für Hilfe zur Behebung meines Problems.
![Protokoll](https://github.com/copystring/ioBroker.roborock/assets/135986707/54ff1c65-60df-43ee-943e-c1d108be4433)

**Comment by copystring** [comment]
Hi, da steht, dass dir die libnode.so fehlt. Das hat nichts mit dem Adapter zu tun, sondern mit deiner Installation.

**Comment by copystring** [comment]
Auch zu erwähnen ist, dass die Kartenerstellung auf einem Raspberry Pi nicht läuft. Ist die Kartenerstellung bei dir aktiviert?
