### ISSUE TITLE
Command values not sent

### ISSUE THREAD

**Issue by trollvottel** [copystring/ioBroker.roborock#473]
The command values don't synchronize with commands sent from the app for me. For example, adapter says set_custom_mode=102 ("Balanced"), when I now set it to "Turbo" in the app, the adapter doesn't update the local value. When I now want the adapter to switch back to "Balanced", nothing happens, probably because it assumes a NOOP.

=> Adapter must either update/sync the command values OR always send them. Other adapters, knx for example, always send when "control" value is used instead of "update" value, even if value won't change.

The issue is kinda frustrating because of this, the robot mops areas where it shouldn't or ignores other commands, especially load_multi_map and then things fuck up completely..

**Comment by copystring** [comment]
I don't know what you mean. The adapter always sends the command, regardless if it changed or not.

Regarding the sync. This is intentional because the command is just a command. The actual state is in deviceStatus and is requested directly after each command to keep it up to date at any time.

**Comment by trollvottel** [comment]
Did you also try to reproduce as described? Whenever I changed sth. via App to a different value, set_custom_mode or load_multi_map for example, the Adapter skips the command (at least the robot doesn't react) when it's the same value as the adapter had before. As soon as I send a different value with the command then what the adapter currently has, it's sent and robot reacts.

**Comment by copystring** [comment]
I think I found this issue. Please try the new dev and post a debug log. Thank you!
