### ISSUE TITLE
Commands set mode keine Funktion

### ISSUE THREAD

**Issue by frankyboy1973** [copystring/ioBroker.roborock#474]
Hi, leider funktionieren die commands set_costum_mode und set_water_box_costume_mode bei mir nicht. Ich kann zwar ne Reinigung und auch ne Einzelraumreinigung starten, aber leider nicht die Einstellungen ändern wie der Roboter reinigen soll.
Wenn ich was in die Datenpunkte commands set_costum_mode und set_water_box_costume_mode reinschreibe, werden diese Werte nicht übernommen und auch nicht bestätigt, zusätzlich gibts noch ne Warnmeldung.
`
2024-01-07 14:44:14.902 - warn: roborock.0 (741) Failed to execute set_custom_mode on robot 3H1RtzirmjxWDKKt6bcR9P Error: Local request with id 87791 with method 87792 timed out after 10 seconds for response.102
2024-01-07 14:46:02.244 - warn: roborock.0 (741) Failed to execute set_water_box_custom_mode on robot 3H1RtzirmjxWDKKt6bcR9P Error: Local request with id 87813 with method 87814 timed out after 10 seconds for response.102
`
Ich habe einen Roborock Q Revo, Adapterversion ist 0.4.4 bzw. neuste Dev.

Für eine induviduelle Raumreinigung habe ich mir erstmal damit beholfen, das ich für jeden Raum in der App verschiedene Programme angelegt habe, die ich dann per Adapter starten kann, nur leider lassen sich in der App nur 10 Programme anlegen. Das reicht leider nicht, wenn man 8 Räume hat und für jeden Raum zwischen wischen und nur saugen unterscheiden will. Daher wäre es schön wenn die Datenpunkte commands set_costum_mode und set_water_box_costume_mode funktionieren würden, dann kann ich die induviduelle Raumreinigung über ein Script lösen.

**Comment by trollvottel** [comment]
Die funktionieren schon, allerdings nicht immer (#473)

**Comment by copystring** [comment]
Sollte in der neuen dev gelöst sein. Teste das mal bitte.

**Comment by frankyboy1973** [comment]
Hi, ich kann die set_mode Datenpunkte jetzt setzen, sie werden übernommen und es kommt auch keine Warnmeldung. Nur wenn ich die beiden Datenpunkte gleichzeitig setze, wird einer der beiden manchmal nicht übernommen und es gibt auch ne entsprechende Warnmeldung. Ich habe jetzt einen Zeitversatz beim Setzen der beiden Datenpunkte von 200 ms in meinem Script, das funktioniert bis jetzt super. Habe jetzt 10 Reinigungen mit immer unterschiedlichen Einstellungen durch und es läuft, so wie ich es mir vorgestellt habe. Danke.
Das einzige was ein bisschen irritiert, ist das die set_mode Datenpunkte nicht als bestätigt angezeigt werden, wenn ich sie setze. Dagegen werden die Datenpunkte wie z.B. app_start, app_stop, app_segment_clean, usw. als bestätigt angezeigt

**Comment by copystring** [comment]
Wie meinst du das? Wo siehst du denn, dass etwas bestätigt wurde?

**Comment by frankyboy1973** [comment]
Ich meine in den Datenpunkten/Objekten. 
![Robo3](https://github.com/copystring/ioBroker.roborock/assets/46169800/be453496-d660-4329-8e61-c7825f57dd39)
![Robo4](https://github.com/copystring/ioBroker.roborock/assets/46169800/923adbab-e796-47fa-8333-17577cdb9905)

**Comment by copystring** [comment]
Ach so. Du meinst ack: true. Sicher, dass du das nicht selber setzt? Der Adapter setzt das nie.

**Comment by frankyboy1973** [comment]
Nein, das setze ich nicht selber. Aber wenn du sagst das der Adapter die commands nicht bestätigt, weiß ich Bescheid. Dann wird es wohl bei den bool Datenpunkten, wie z.B. app_segment_clean oder app_charge, als Bestätigt angezeigt, weil der Adapter die ja selber wieder auf false zurücksetzt. Danke für die Info.

**Comment by copystring** [comment]
Genau so ist. Went zurück auf false gesetzt wird, ist das bestätigt und bei denen, die sich nicht ändern, bleibt es unbestätigt
