### ISSUE TITLE
Unsported attribute

### ISSUE THREAD

**Issue by sebaboehm** [copystring/ioBroker.roborock#477]
**Expected behavior**  
Fehler im Log

**Screenshots & Logfiles**  
Unsported attribute: kct of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.

Model: Roborock Q Revo

**Comment by copystring** [comment]
Hi, this was fixed in the dev branch a long time ago.

https://github.com/copystring/ioBroker.roborock/commit/0050d3d6db7d0cf6c407d9943e82a7950f683a6f

**Comment by sebaboehm** [comment]
And how I can fix that?

**Comment by copystring** [comment]
Wait for the next release.

**Comment by sebaboehm** [comment]
When that will come?
