### ISSUE TITLE
Wartungsobjekte werden nicht aktualisiert

### ISSUE THREAD

**Issue by jahnbes** [copystring/ioBroker.roborock#478]
Ich habe den Eindruck, dass die Objekte der Wartung
0.Devices.1NmW0q7YbLpmdhMT2EIl5i.consumables.125 (Hauptbürste)
0.Devices.1NmW0q7YbLpmdhMT2EIl5i.consumables.126 (Seitenbürste)
0.Devices.1NmW0q7YbLpmdhMT2EIl5i.consumables.127 (Filter)
durch den Adapter nicht mehr aktualisiert werden, wohl aber durch die App.

Den Filter (127) hatte ich in der App unter "Wartung" zurückgesetzt, was in der App anschließend auch korrekt angezeigt wurde. Er ist dort wieder auf 100%. Nur im Objekt des Adapters wird er immer noch mit 21% angezeigt. Auf dem Wert steht er, wie die History zeigt, schon seit Monaten, trotz fleißiger Arbeit des Robo.

Testhalber habe ich auch die Hauptbürste (125) zurück gesetzt, mit dem gleichen Fehler, wie oben für die 127 beschreiben.

Gruß jahnbes
(Roborock S7 Max V)

**Comment by copystring** [comment]
Stimmt. Ich weiß nicht, wie das passiert ist, aber da muss mir ein Fehler unterlaufen sein.
Hab es in der dev behoben.
https://github.com/copystring/ioBroker.roborock/commit/905af269a087df722b528f1e591981aecaec2da9

**Comment by copystring** [comment]
Das ist mir wohl beim Migrieren zum neuen System passiert sein.
