### ISSUE TITLE
lange start-zeit

### ISSUE THREAD

**Issue by krobipd** [copystring/ioBroker.roborock#480]
Hallo 

ist weniger ein Bug, gleich vorne weg ;-)

aber ich habe mich gefragt warum der Adapter eigentlich so lange braucht zum starten. 2-3 Minuten bis er ready ist nur um quasi mqtt Kommandos zu senden und zu empfangen? 

ist wirklich nicht negativ oder so gemeint. aber würde mich interessieren wies kommt dass das soviel Ressourcen und zeit braucht. ich habe auch die karten Funktion deaktiviert.

**Comment by copystring** [comment]
Unstale

**Comment by copystring** [comment]
Hallo @krobipd,

das kommt daher, dass beim Start des Adapters einige Objekte erstellt/geprüft werden müssen. Ich habe bisher noch keinen Weg gefunden, dies zu optimieren. Hauptsächliche aus Zeitgründen.
