### ISSUE TITLE
Datenpunkte unter deviceStatus aktualisieren sich nicht

### ISSUE THREAD

**Issue by dvdkrtz** [copystring/ioBroker.roborock#482]
**Describe the bug**  
Der Titel beschreibt eigentlich alles, die Datenpunkte unter deviceStatus aktualisieren sich nicht.

**To Reproduce**  
1. tab-objects aufrufen
2. Roborock suchen
3. deviceStatus aufklappen
4. Aktualisierungsdatum der Datenpunkte anschauen

**Expected behavior**  

**Screenshots & Logfiles**  
Home data:
`{"id":3609045,"name":"My Home","lon":null,"lat":null,"geoName":null,"products":[{"id":"42yfoQm5eOY3gARZw6xgU","name":"Roborock S7 MaxV","model":"roborock.vacuum.a27","iconUrl":null,"attribute":null,"capability":0,"category":"robot.vacuum.cleaner","schema":[{"id":"101","name":"rpc_request","code":"rpc_request","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"102","name":"rpc_response","code":"rpc_response","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"120","name":"错误代码","code":"error_code","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"121","name":"设备状态","code":"state","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"122","name":"设备电量","code":"battery","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"123","name":"清扫模式","code":"fan_power","mode":"rw","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"124","name":"拖地模式","code":"water_box_mode","mode":"rw","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"125","name":"主刷寿命","code":"main_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"126","name":"边刷寿命","code":"side_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"127","name":"滤网寿命","code":"filter_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"128","name":"额外状态","code":"additional_props","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"130","name":"完成事件","code":"task_complete","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"131","name":"电量不足任务取消","code":"task_cancel_low_power","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"132","name":"运动中任务取消","code":"task_cancel_in_motion","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"133","name":"充电状态","code":"charge_status","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"134","name":"烘干状态","code":"drying_status","mode":"ro","type":"RAW","property":null,"desc":null}]}],"devices":[{"duid":"4QgxwtqqJ1HyWK9WUknNjo","name":"Roborock S7 MaxV","attribute":null,"activeTime":1682328354,"localKey":"EGOowaOZuVG9wONO","runtimeEnv":null,"timeZoneId":"Europe/Berlin","iconUrl":"","productId":"42yfoQm5eOY3gARZw6xgU","lon":null,"lat":null,"share":false,"shareTime":null,"online":true,"fv":"02.58.40","pv":"1.0","roomId":null,"tuyaUuid":null,"tuyaMigrated":false,"extra":"{\"RRPhotoPrivacyVersion\": \"1\", \"RRMonitorPrivacyVersion\": \"1\"}","setting":null,"sn":"R21ETS23503273","featureSet":"2234201184108543","newFeatureSet":"0000000000002F63","deviceStatus":{"120":0,"121":8,"122":89,"123":104,"124":202,"125":42,"126":13,"127":66,"128":0,"133":1},"silentOtaSwitch":false,"f":false}],"receivedDevices":[],"rooms":[{"id":15203354,"name":"HWR"},{"id":11670237,"name":"Badezimmer"},{"id":11670233,"name":"Jungs"},{"id":11670231,"name":"Jenny"},{"id":11670229,"name":"Ankleide"},{"id":11670227,"name":"Schlafzimmer"},{"id":11670220,"name":"Marlene"},{"id":11670213,"name":"Arbeitszimmer"},{"id":11670209,"name":"WC"},{"id":11670206,"name":"Raum unter Treppe"},{"id":11670198,"name":"Flur"},{"id":11670196,"name":"Eingangsbereich"},{"id":11670193,"name":"Hauswirtschaftsraum"},{"id":11670189,"name":"Esszimmer"},{"id":11670187,"name":"Küche"},{"id":11670169,"name":"Wohnzimmer1"},{"id":10976153,"name":"Flu"},{"id":10975470,"name":"Wohnzimmer"}]}`

![grafik](https://github.com/copystring/ioBroker.roborock/assets/5826328/2685c763-9d0f-4b49-847e-dbbe6f9ca27c)

**Versions:**  
 - Adapter version: 0.5.1
 - JS-Controller version: 5.0.16
 - Node version: v18.18.2
 - Operating system: 9.8.1

**Additional context**

**Comment by copystring** [comment]
0.5.1 funktioniert nicht richtig und wurde deshalb von mir zurückgezogen. Du müsstest die dev testen oder auf einen neuen Release warten.

**Comment by dvdkrtz** [comment]
Ich habe das hier über die Katze installiert: https://github.com/copystring/ioBroker.roborock/tree/dev
Das ist doch die dev, oder?

**Comment by dvdkrtz** [comment]
Ich hoffe, du kannst damit was anfangen:

[roborock.log](https://github.com/copystring/ioBroker.roborock/files/14048368/roborock.log)

**Comment by dvdkrtz** [comment]
Habe eben beim Neustart nach dem Installieren folgenden Fehler bekommen. Vielleicht hilft das:

[roborock_2.log](https://github.com/copystring/ioBroker.roborock/files/14049232/roborock_2.log)

**Comment by copystring** [comment]
Unstale

**Comment by copystring** [comment]
Unstale...

**Comment by copystring** [comment]
Würdest du bitte nochmal die aktuelle dev laden und testen? Dort sind einige Fehler behoben.

**Comment by dvdkrtz** [comment]
Die Datenpunkte werden leider weiterhin nicht gefüllt.

**Comment by copystring** [comment]
Okay. Schade. Steht im Debug wieder das gleiche wie davor? Würdest du ein neues Debuglog anhängen? Die Codezeilen haben sich geändert und passen nicht mehr zu dem aktuellen Code.

**Comment by copystring** [comment]
Kann es sein, dass dein ioBroker im Docker läuft? Dann kann der Adapter leider nicht funktionieren.

**Comment by dvdkrtz** [comment]
Nein, in einem LXC Container unter Proxmox. Die Version aus dem stable
repository läuft auch, allerdings benötige ich die Steuerung der Programme.

**Comment by copystring** [comment]
OK. Vielleicht ein VLAN oder etwas anderes wie z.B. zwei getrennte Netze? Der Saugroboter und ioBroker müssen im selben Netzwerk sein, damit dein Saugroboter gefunden werden kann.
Im ersten Log steht, dass kein Saugroboter gefunden wurde: `2024-01-25 08:26:14.979 - debug: roborock.0 (171185) localDevices: {}`

Oder ist dein Saugroboter von einem anderen Konto geteilt?

**Comment by dvdkrtz** [comment]
Message ID: ***@***.***
comGGrGrundsätzlich funktioniert es ja. Ich kann Programme starten. Also
wird er in meinen Augen auch gefunden. Ich bekomme quasi nur die Rückinfo
vom Sauger nicht. Und wie gesagt, die Stable Version funktioniert auch.
ioBroker und Roboter befinden sich in dem selben Netz.

**Comment by copystring** [comment]
> Ich bekomme quasi nur die Rückinfo vom Sauger nicht

Du bekommst keine Rückinfo, weil `localDevices` leer ist. `localDevices` ist leer, weil kein Saugroboter im Netzwerk gefunden werden konnte und deshalb keine Befehle herausgeschickt werden. Es gibt einen ähnlichen Fall, in dem jemand ioBroker in Docker laufen ließ.
Ich kann mir nur vorstellen, dass es ein Netzwerkproblem ist.

**Comment by ssc80** [comment]
Ich habe ein ähnliches Problem. Es ist die aktuelle dev installiert. Im Log im Debug Modus sehe ich 
localDevices: {}
Der Object Tree wird aufgebaut, enthält aber keine Werte, auch eine Steuerung ist so natürlich nicht möglich.
iobroker läuft auch in Proxmox als LXC. Der Roboter ist aber in einem anderen Subnet als Biobroker (10.0.2.255 vs. 10.0.1.255). Von iobroker aus kann ich aber ganz normal den Roboter anpingen.


Mit 0.4.4 ging's.

**Comment by copystring** [comment]
0.4.4 hat ganz andere Probleme. Deshalb muss die Umstellung auf lokale Verbindung anstatt die Verbindung über die Cloud laufen zu lassen.
Das bedingt jedoch, dass ioBroker und Saugroboter im selben Netz sind, damit über Broadcast die Saugroboter gefunden werden können. Es gibt da leider keine Alternative.

**Comment by ssc80** [comment]
Ok, ich werde mal den Roboter ins gleiche Netz geben wie iobroker. Schön zu lesen dass es nun direkte Kommunikation und nicht über die Cloud ist. 
Zwei Verständnisfragen hätte ich aber noch: 
* Wird er Objektbaum aus Informationen von der roborock Cloud API aufgebaut
* Prinzipiell wäre die IP des Roboters ja unter networkInfo bekannt. Warum muss ein Broadcast gemacht werden?


Danke auch für den echt coolen Adapter!

**Comment by copystring** [comment]
@dvdkrtz wie sieht es bei dir aus? Läuft es bei dir wieder?

**Comment by dvdkrtz** [comment]
DeviceInfo ist in der aktuellen DEV wieder gefüllt. DeviceStatus leider noch nicht.

**Comment by copystring** [comment]
OK. Dann wird es weiterhin so sein, dass `localDevices` leer ist. Ich weiß nicht, wie ich dir da helfen kann. Der Adapter sendet wie immer ein Broadcast ins Netzwerk und kein Saugroboter antwortet darauf. Es muss ein Netzwerkproblem sein.
