### ISSUE TITLE
Fehlerprotokoll 

### ISSUE THREAD

**Issue by steini1503** [copystring/ioBroker.roborock#492]
Im Fehlerprotokoll erscheint immer wieder diese Meldung. Vielen Dank.

Model Roborock Q Revo Version 02.17.78

roborock.0 | 2024-02-06 15:37:56.325 | info | State value to set for "roborock.0.Devices.7fAUBzEPHFpEm1XFw91pCL.deviceStatus.last_clean_t" has to be type "number" but received type "string"

roborock.0 | 2024-02-06 15:37:56.321 | error | Unsported attribute: kct of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.

**Comment by copystring** [comment]
Mit welcher Version?

**Comment by steini1503** [comment]
0.4.4

**Comment by copystring** [comment]
Teste bitte 0.5.4 aus der latest repository

**Comment by steini1503** [comment]
Ah ok, ich dachte das mir im ioBroker immer angezeigt wird das es ein Update gibt. Deswegen dachte ich das die 0.4.4 die aktuellste ist, habe jetzt die 0.5.4 manuell installiert. Ich berichte.
