### ISSUE TITLE
MQTT Error

### ISSUE THREAD

**Issue by LastPerfectTobi** [copystring/ioBroker.roborock#496]
Seit einiger Zeit kommt folgender Hinweis regelmäßig in den Logs:

```
2024-02-24 00:27:01.230 - warn: roborock.0 (25200) Reconnecting mqtt client!
2024-02-24 00:27:01.273 - warn: roborock.0 (25200) MQTT connection close.
2024-02-24 00:27:01.274 - warn: roborock.0 (25200) MQTT connection reconnect.
```

Node.JS 18.19.0
NPM 10.2.3
Roborock Adapter 0.5.4

Adapter ist Grün und funktioniert auch wie gewohnt. 
Finde keine MQTT Einstellung im Adapter.

**Comment by copystring** [comment]
Passiert das alle drei Stunden oder ständig?

**Comment by LastPerfectTobi** [comment]
Ganz genau alle 3 Stunden.

**Comment by copystring** [comment]
Dann ist alles gut. Das muss so sein. Ansonsten würde Roborock den Adapter für dich komplett sperren.

**Comment by LastPerfectTobi** [comment]
Okay.. dann stell ich die Log-Stufe auf Error. Dann wirds zumindest wieder ruhiger 🙂
