### ISSUE TITLE
Roborock adapter sorgt für 100% CPU Auslastung im ioBroker

### ISSUE THREAD

**Issue by pixelschubse** [copystring/ioBroker.roborock#498]
**Describe the bug**  
Nach einigen Stunden Laufzeit verursacht der Roborock adapter in der Version 0.5.4 eine CPU-Auslastung von 100%. Wenn der Adapter gestoppt wird, fällt die Last wenige Sekunden später auf die normalen 30%. Die hohe Last führt dazu, dass sowohl Admin-Interface als auch die VIS und insbesondere NodeRED-Automationen extrem langsam reagieren (aufgefallen ist es wegen des Bewegungsmelders im Flur der ca. 10 Sekunden braucht nach dem Klacken das Licht anzuschalten, ohne Roborock-Adapter läuft das wieder wie geschmiert).

**To Reproduce**  
1. Aktiviere den Roborock adapter in den Instanzen
2. Warte einige Stunden
3. Rufe die VIS auf dem Tablet neu auf
4. Rufe das Admininterface auf

**Expected behavior**  
1. Die VIS ist innerhalb von  max. 2 Sekunden einsatzbereit
2. Das Admin-Interface ist in wenigen Sekunden einsatzbereit

*Actual behavior**
1. Ich habe 20 Sekunden warten müssen bis alle Grafiken die die VIS geladen waren
2. Das Admin-Interface läuft in einen Timeout und ist erst nach 30 Sekunden nutzbar, Grafiken werden dann teilweise noch immer nachgeladen - z.b. Icons in der Admin-Oberfläche.

**Screenshots & Logfiles**  
- während der Adapter im ioBroker lief habe ich keine Errors in den Logs gefunden

**Versions:**  
- Plattform: linux, Betriebssystem: linux
- Architektur: arm, CPUs: 4. Geschwindigkeit: 1800 MHz, RAM: 7.6 GB
- System-Betriebszeit: 21:29:15
- Node.js: v18.17.1, NPM: 9.6.7
- Adapter-Anzahl: 535, Aktive Instanzen: 27 
- Datenträgergröße: 14.4 GB, Freier Festplattenspeicher: 7.9 GB
- Adapter version: 0.5.4
- JS-Controller version: 5.0.17

**Additional context**  
- Was ich noch beobachten konnte: Das Steuern der Raumreinigung über die VIS klappt plötzlich nicht mehr. Der Roborock fährt nicht mehr los. Lediglich meine eigenen Datenpunkte werden angepasst (Screenshot zur Logik-Umsetzung in NodeRED: 
<img width="762" alt="Bildschirmfoto 2024-02-25 um 10 02 37" src="https://github.com/copystring/ioBroker.roborock/assets/139559867/4dbb9f08-5a62-4a74-946d-3be365a8a3ea">
)
- Beim Beenden des Adapters sind mir die Logs vollgelaufen mit immer dem gleichen Fehler: 
[iobroker-error-roborock.txt](https://github.com/copystring/ioBroker.roborock/files/14395822/iobroker-error-roborock.txt)

Davon abgesehen: DANKE für deine Mühe und Zeit, die du hier reinsteckst! Bis zu dem Verhalten jetzt macht sich super in unserer VIS!

**Comment by copystring** [comment]
Läuft der Adapter auch dann auf 100%, wenn du keine Befehle ausführst? Wenn ja, dann wäre interessant welcher Befehl das Problem verursacht.

**Comment by copystring** [comment]
Wärst du so nett und hängst bitte ein Debuglog mit dem Fehler an? Das Errorlog reicht leider nicht aus. Ich brauche die Debugmeldungen.

**Comment by copystring** [comment]
Deine Logs sind leider nicht so hilfreich.
Was ich benötigte ist, ein vollständiges Debuglog vom Start des Adapters bis zum Absturz.

**Comment by copystring** [comment]
Ja. du kannst es an copystring@gmail.com schicken

**Comment by copystring** [comment]
Top!
