### ISSUE TITLE
Q5 Pro + Datenpunkt Absaugung fehlt hier auch und diverse Fehlermeldungen

### ISSUE THREAD

**Issue by BK-Konz** [copystring/ioBroker.roborock#499]
Installiert ist die 0.5.4

Datenpunkt absaugung nicht vorhanden und folgende Datenpunkte fehlen wohl ?
1.
Failed to execute get_status on robot 361GIgWZrPmX2DTm23Mba3 Unsupported attribute: common_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.

2.
Failed to execute get_status on robot 361GIgWZrPmX2DTm23Mba3 Unsupported attribute: in_warmup of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.

**Comment by copystring** [comment]
Hi,

teste bitte die aktuelle dev. Dort sind bereits einige fehlende Parameter eingebaut.
https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by BK-Konz** [comment]
Mit der aktuellen Dev gehts hab nur noch folgende Warnungen
"roborock.0.Devices.361GIgWZrPmX2DTm23Mba3.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-03-06 18:41:41.633 | warn | State  "roborock.0.Devices.361GIgWZrPmX2DTm23Mba3.deviceStatus.common_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-03-06 18:41:41.630 | warn | State  "roborock.0.Devices.361GIgWZrPmX2DTm23Mba3.deviceStatus.in_warmup" has  no existing object, this might lead to an error in future versions

Danke

**Comment by copystring** [comment]
Teste bitte die neue dev. Dort sind wirklich viele neue Parameter und Attribute eingebaut.
Falls es weiterhin nicht läuft, brauche ich ein Debuglog vom Start des Adapters.
