### ISSUE TITLE
neu hinzugefügter Raum taucht nicht auf

### ISSUE THREAD

**Issue by tobsta** [copystring/ioBroker.roborock#506]
Adapter Version 0.5.4

Gerät: Q Revo

Ich habe einen neuen Raum hinzugefügt. Dieser taucht aber nicht im Objektbaum auf (bzw. der neue Raum schon, dafür ein "alter" nicht mehr)

roborock.0 | 2024-03-12 11:36:56.470 | debug | Mapped room matched: 14335617 with name: Essbereich
roborock.0 | 2024-03-12 11:36:56.470 | debug | Mapped room matched: 14335610 with name: Klavierecke
roborock.0 | 2024-03-12 11:36:56.470 | debug | Mapped room matched: 14335618 with name: Küche
roborock.0 | 2024-03-12 11:36:56.470 | debug | Mapped room matched: 17266602 with name: Gäste WC
roborock.0 | 2024-03-12 11:36:56.470 | debug | Mapped room matched: 14335576 with name: Schlafzimmer
roborock.0 | 2024-03-12 11:36:56.470 | debug | Mapped room matched: 14335573 with name: Badezimmer
roborock.0 | 2024-03-12 11:36:56.469 | debug | Mapped room matched: 14335621 with name: Sofaecke
roborock.0 | 2024-03-12 11:36:56.469 | debug | Mapped room matched: 14335578 with name: Kinderzimmer

roborock.0 | 2024-03-12 11:36:56.469 | debug | All mapped rooms: [[16,"14335578",1],[17,"14335621",6],[18,"14335573",15],[19,"14335576",1],[20,"17266602",12],[21,"14335618",14],[22,"14335610",6],[23,"14335617",13]]

roborock.0 | 2024-03-12 11:36:56.424 | debug | Length of message queue: 0
roborock.0 | 2024-03-12 11:36:56.377 | debug | Length of message queue: 0
roborock.0 | 2024-03-12 11:36:56.322 | debug | getParameter for 2sjZoFOhoGlRU0koXPcO0E: get_room_mapping

roborock.0 | 2024-03-12 11:28:25.904 | debug | RoomIDs debug: {"14335573":"Badezimmer","14335576":"Schlafzimmer","14335577":"Flur","14335578":"Kinderzimmer","14335610":"Klavierecke","14335617":"Essbereich","14335618":"Küche","14335621":"Sofaecke","17266602":"Gäste WC"}

**Comment by copystring** [comment]
Um welche Räume geht es?

**Comment by tobsta** [comment]
debug RoomID gibt alle 9 Räume (wie in der App) an, aber "all mapped rooms" nur die 8, die dann auch in den objects auftauchen. Also konkret fehlt in diesem Beispiel "Flur" in de objects

**Comment by copystring** [comment]
Ah ja. Das habe ich schon mal gesehen. Das Ding ist, dass die Werte so direkt von Roborock kommen. Meistens passiert das dann, wenn Räume nachträglich bearbeitet werden. Ich muss mir das mal angucken. Aktuell fehlt mir aber die Zeit, den Datenverkehr mitzuschneiden.
Wäre es ein großes Problem für dich die Karte mit dem passenden Raum neu zu erstellen? Sollte dann klappen, wenn der Raum beim ersten Speichern der Karte direkt mit eingefügt wird.

**Comment by tobsta** [comment]
korrekt - Raum nachträglich hinzugefügt. Eilt auch nicht.
Meinst du "neu Erstellen/neu Einlesen" mit dem Robo? Oder irgendwie im Adapter "neu erstellen" (wenn ja, wie?))?  - erste Variante wäre derzeit zu aufwändig - aber eilt ja auch wie gesagt nicht.

**Comment by copystring** [comment]
Unstale
