### ISSUE TITLE
Kommandos und Räume Roborock S8 tauchen nicht mehr in den Objekten auf

### ISSUE THREAD

**Issue by pixelschubse** [copystring/ioBroker.roborock#508]
**Describe the bug**  
Die Ordner "commands" und "floors" tauchen nicht mehr auf, in den Logs gibt es eine Fehlermeldung die besagt, dass die Home details nicht bezogen werden können. 

**To Reproduce**  
1. den bisherigen Adapter deinstallieren
2. den latest dev build aus dem repo installieren
3. Zugangsdaten eingeben und Adapter neu starten
4. Den Objektbaum für das Device checken
5. Das Log checken

**Expected behavior**  
Der Verzeichnisbaum enthält die Möglichkeit die Steuerungskommandos und Raumliste zu sehen.

**Screenshots & Logfiles**  
Raumliste und Steuerungskommandos fehlen.

**Versions:**  
 - Adapter version: dev build vom 15.03.2024; 09:00
 - JS-Controller version: 5.0.17
 - Node version: v18.17.1
 - Operating system: linux
 - Device: Roborock S6 Max

**Additional context**  
<img width="1271" alt="Bildschirmfoto 2024-03-16 um 09 13 43" src="https://github.com/copystring/ioBroker.roborock/assets/139559867/e2ba792e-ff41-4c00-8f19-de397a96bc40">

**Comment by copystring** [comment]
Hi.
Ja, in der dev sind noch Fehler. Bin mit der dev halt noch nicht fertig für einen Release.
Jetzt ist Wochenende. Da hab ich wieder etwas Zeit für weitere Verbesserungen.

**Comment by copystring** [comment]
Ich würde mich freuen, wenn du die neue dev testen würdest. Ich bin dabei, diese für den kommenden Release vorzubereiten und Fehler auszumerzen.
https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by copystring** [comment]
OK. Gucke ich mir nachher nochmal an. Sind deine Räume alle benannt?

**Comment by copystring** [comment]
Zeigt mal bitte dein HomeData

**Comment by copystring** [comment]
> Kommt per Mail.

Testest du bitte die neue dev? Müsste jetzt laufen.

> 
> Btw.: folgendes sehe ich jetzt im Sekundentakt in den Logs: <img alt="Bildschirmfoto 2024-03-29 um 11 04 04" width="1285" src="https://private-user-images.githubusercontent.com/139559867/318019200-26dc7774-c766-410f-b408-a94088ae5061.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MzA5NzgsIm5iZiI6MTcxMTczMDY3OCwicGF0aCI6Ii8xMzk1NTk4NjcvMzE4MDE5MjAwLTI2ZGM3Nzc0LWM3NjYtNDEwZi1iNDA4LWE5NDA4OGFlNTA2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOVQxNjQ0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWI3YzYyOTY5Yzc5ZGZkNDFmYzQyYmU2NTY0OGQ5N2MwN2E4N2IyOGY0YzY1MTY1ZWE3NmEzZWYyOThjZTExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LJT_r0_U43mS969iMYvoXjaKjlbl76BtciQ_DxbjuQA">

Ja, ich weiß. Das behebe ich demnächst.

**Comment by copystring** [comment]
Die Warnungen sollten nun nicht mehr auftauchen.

**Comment by copystring** [comment]
Okay, bei dem RAM-Problem weiß ich nicht weiter. Vielleicht kann ich es reproduzieren, wenn du den Saugroboter mit mir über die App teilst. Mein Konto ist copystring@gmail.com
