### ISSUE TITLE
Fehlerhafte Anzeige bei roborock.0.Devices.ID.cleaningInfo.Records

### ISSUE THREAD

**Issue by mproper23** [copystring/ioBroker.roborock#51]
State "begin" und State "end" haben bei mir den selben Wert
Duration wird korrekt dargestellt

**Comment by copystring** [comment]
Bitte immer ein Log anhängen genau so sie bei allen anderen issues.

**Comment by mproper23** [comment]
[export-8db05c62dba10db.csv](https://github.com/copystring/ioBroker.roborock/files/10577370/export-8db05c62dba10db.csv)

**Comment by copystring** [comment]
https://github.com/copystring/ioBroker.roborock/issues/52
