### ISSUE TITLE
Fehler nach Update von 0.2 auf 0.5.4 für den Roborock S4 Max

### ISSUE THREAD

**Issue by Reddingo** [copystring/ioBroker.roborock#513]
Hallo,

ich hab den Adapter für meinen Roborock S4 Max von 0.2.? auf 0.4.4 hochgezogen und dann weiter auf 0.5.4.

Bekomme nun aber die Fehlermeldungen:

Erst das hier:
**Error: DB closed at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:184:25) at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:151:20) at Object.onceWrapper (node:events:628:26) at Socket.emit (node:events:513:28) at Socket.emit (node:domain:489:12) at TCP.<anonymous> (node:net:758:14)**

Hab zum Testen mal den kompletten Object-Tree roborock.0 gelöscht und nun bekomme ich:
**Failed to get home details: TypeError: Cannot read properties of null (reading 'slice') at deviceFeatures.getFeatureList (/opt/iobroker/node_modules/iobroker.roborock/lib/deviceFeatures.js:503:81) at deviceFeatures.processSupportedFeatures (/opt/iobroker/node_modules/iobroker.roborock/lib/deviceFeatures.js:691:29) at Roborock.createDevices (/opt/iobroker/node_modules/iobroker.roborock/main.js:286:4) at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:230:6)**

Ein Teil der Objekte wurden auch angelegt, leider fehlen alle commands

Hier ein aktueller Log-Auszug:

| Adapter| Zeit|Level|Text|
| --- | --- | --- | --- |
roborock.0 | 2024-03-27 16:25:55.632 | debug | homedata successfully updated
roborock.0 | 2024-03-27 16:25:55.148 | debug | Updating HomeData with homeId: 1496917
roborock.0 | 2024-03-27 16:24:39.820 | debug | tcp client for 2ZLJdONaaaaaoIEWLPdcf connected
roborock.0 | 2024-03-27 16:24:38.815 | debug | tcp client for 2ZLJdONaaaaaoIEWLPdcf disconnected, attempting to reconnect...
roborock.0 | 2024-03-27 16:24:38.814 | debug | error on tcp client for 2ZLJdONoIEWLBpNjPOPdcf. read ECONNRESET
roborock.0 | 2024-03-27 16:22:55.496 | debug | homedata successfully updated
roborock.0 | 2024-03-27 16:22:55.146 | debug | Updating HomeData with homeId: 1496917
roborock.0 | 2024-03-27 16:19:55.616 | debug | homedata successfully updated
roborock.0 | 2024-03-27 16:19:55.147 | debug | Updating HomeData with homeId: 1496917
| roborock.0 | 2024-03-27 16:16:56.694 | error | Failed to get home details: TypeError: Cannot read properties of null (reading 'slice')     at deviceFeatures.getFeatureList (/opt/iobroker/node_modules/iobroker.roborock/lib/deviceFeatures.js:503:81)     at deviceFeatures.processSupportedFeatures (/opt/iobroker/node_modules/iobroker.roborock/lib/deviceFeatures.js:691:29)     at Roborock.createDevices (/opt/iobroker/node_modules/iobroker.roborock/main.js:286:4)     at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:230:6)|
| roborock.0 | 2024-03-27 16:16:56.225 | debug | Robot key: roborock.vacuum.a19)|
| roborock.0 | 2024-03-27 16:16:56.223 | info | Starting adapter finished. Lets go!!!!!!!)|
|roborock.0 | 2024-03-27 16:16:55.544 | debug | homedata successfully updated)|
|roborock.0 | 2024-03-27 16:16:55.160 | debug | Made ./lib/go2rtc/go2rtc_linux_amd64 executable)|
roborock.0 | 2024-03-27 16:16:55.146 | debug | Updating HomeData with homeId: 1496917
roborock.0 | 2024-03-27 16:16:38.032 | debug | MQTT  connection connected  {"cmd":"connack","retain":false,"qos":0,"dup":false,"length":2,"topic":null,"payload":null,"sessionPresent":false,"returnCode":0}.
roborock.0 | 2024-03-27 16:16:37.736 | debug | tcp client for 2ZLJdONoIEWLBpNjPOPdcf connected
roborock.0 | 2024-03-27 16:16:37.661 | debug | Old file lib/go2rtc/go2rtc_linux_amd64 has been deleted.
roborock.0 | 2024-03-27 16:16:37.658 | debug | System type: go2rtc_linux_amd64
roborock.0 | 2024-03-27 16:16:37.658 | debug | platform: linux
roborock.0 | 2024-03-27 16:16:37.658 | debug | arch:  x64
roborock.0 | 2024-03-27 16:16:37.657 | debug | Processing scene []
roborock.0 | 2024-03-27 16:16:37.656 | debug | RoomIDs debug: {}
roborock.0 | 2024-03-27 16:16:37.656 | info | MQTT initialized
roborock.0 | 2024-03-27 16:16:37.601 | debug | localDevices: {"2ZLJdONaaaaaoIEWLPdcf":"192.168.109.36"}
roborock.0 | 2024-03-27 16:16:37.599 | debug | getLocalDevices localKey: moHalctM1xQ73vM8
roborock.0 | 2024-03-27 16:16:37.598 | debug | getLocalDevices parsedDecodedMessage: {"duid":"2ZLJdONaaaaaoIEWLPdcf","ip":"192.168.109.36"}
roborock.0 | 2024-03-27 16:16:30.533 | silly | States  system redis pmessage  system.adapter.roborock.0.logLevel/system.adapter.roborock.0.logLevel:{"val":"silly","ack":true,"ts":1711552512340,"q":0,"from":"system.adapter.roborock.0","lc":1711552512340}
roborock.0 | 2024-03-27 16:16:30.514 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-03-27 16:16:30.481 | info | starting.  Version 0.5.4 (non-npm: copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v18.7.0,  js-controller: 4.0.24
roborock.0 | 2024-03-27 16:16:30.181 | debug | Plugin sentry Initialize Plugin (enabled=true)
roborock.0 | 2024-03-27 16:16:30.071 | silly | statesDB connected
roborock.0 | 2024-03-27 16:16:30.069 | debug | States connected to redis: 127.0.0.1:9000
roborock.0 | 2024-03-27 16:16:29.976 | debug | States create User PubSub Client
roborock.0 | 2024-03-27 16:16:29.974 | debug | States create System PubSub Client
roborock.0 | 2024-03-27 16:16:29.946 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
roborock.0 | 2024-03-27 16:16:29.941 | silly | objectDB connected
roborock.0 | 2024-03-27 16:16:29.922 | silly | redis psubscribe cfg.o.enum.*
roborock.0 | 2024-03-27 16:16:29.901 | silly | redis psubscribe cfg.o.system.user.*
roborock.0 | 2024-03-27 16:16:29.898 | debug | Objects connected to redis: 127.0.0.1:9001
roborock.0 | 2024-03-27 16:16:29.893 | debug | Objects client initialize lua scripts
roborock.0 | 2024-03-27 16:16:29.843 | debug | Objects create User PubSub Client
roborock.0 | 2024-03-27 16:16:29.843 | debug | Objects create System PubSub Client
roborock.0 | 2024-03-27 16:16:29.841 | debug | Objects client ready ... initialize now
roborock.0 | 2024-03-27 16:16:28.888 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
roborock.0 | 2024-03-27 16:16:25.759 | info | Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
roborock.0 | 2024-03-27 16:16:25.754 | debug | Plugin sentry destroyed
roborock.0 | 2024-03-27 16:16:25.349 | silly | States  system redis pmessage  system.adapter.roborock.0.logLevel/system.adapter.roborock.0.logLevel:{"val":"silly","ack":true,"ts":1711552512340,"q":0,"from":"system.adapter.roborock.0","lc":1711552512340}
roborock.0 | 2024-03-27 16:16:25.284 | info | starting.  Version 0.5.4 (non-npm: copystring/ioBroker.roborock#dev) in  /opt/iobroker/node_modules/iobroker.roborock, node: v18.7.0,  js-controller: 4.0.24
roborock.0 | 2024-03-27 16:16:24.929 | debug | Plugin sentry Initialize Plugin (enabled=true)
roborock.0 | 2024-03-27 16:16:24.700 | silly | statesDB connected
roborock.0 | 2024-03-27 16:16:24.699 | debug | States connected to redis: 127.0.0.1:9000
roborock.0 | 2024-03-27 16:16:24.551 | debug | States create User PubSub Client
roborock.0 | 2024-03-27 16:16:24.550 | debug | States create System PubSub Client
roborock.0 | 2024-03-27 16:16:24.529 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
roborock.0 | 2024-03-27 16:16:24.526 | silly | objectDB connected
roborock.0 | 2024-03-27 16:16:24.520 | silly | redis psubscribe cfg.o.enum.*
roborock.0 | 2024-03-27 16:16:24.503 | silly | redis psubscribe cfg.o.system.user.*
roborock.0 | 2024-03-27 16:16:24.500 | debug | Objects connected to redis: 127.0.0.1:9001
roborock.0 | 2024-03-27 16:16:24.494 | debug | Objects client initialize lua scripts
roborock.0 | 2024-03-27 16:16:24.445 | debug | Objects create User PubSub Client
roborock.0 | 2024-03-27 16:16:24.444 | debug | Objects create System PubSub Client
roborock.0 | 2024-03-27 16:16:24.442 | debug | Objects client ready ... initialize now
roborock.0 | 2024-03-27 16:16:23.595 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
roborock.0 | 2024-03-27 16:16:18.973 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2024-03-27 16:16:18.972 | info | terminating

**Comment by copystring** [comment]
Ist das mit der aktuellen dev weiterhin so?
https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Reddingo** [comment]
Ich habe den Adapter nun einmal komplett gelöscht und die 0.6.2 neu installiert.

In den Objekten fehlt irgendwas:
![grafik](https://github.com/copystring/ioBroker.roborock/assets/32964022/80d38d8d-5c6a-4f9f-ab29-a2ac0158c822)

Hier der Log-Auszug:

| Adapter| Zeit|Level|Text|
| --- | --- | --- | --- |
roborock.0 | 2024-04-10 12:58:35.041 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:58:34.986 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:58:34.930 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:58:34.734 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:58:34.584 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:57:35.029 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:57:34.974 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:57:34.917 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:57:34.702 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:57:34.625 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:56:35.003 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:56:34.942 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:56:34.885 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:56:34.694 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:56:34.592 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:55:35.005 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:55:34.945 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:55:34.889 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:55:34.685 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:55:34.593 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:54:35.014 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:54:34.955 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:54:34.893 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:54:34.714 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:54:34.585 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:53:35.065 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:53:35.005 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:53:34.949 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:53:34.743 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:53:34.599 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:52:34.988 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:52:34.934 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:52:34.878 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:52:34.687 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:52:34.583 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:51:34.981 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:51:34.926 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:51:34.869 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:51:34.690 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:51:34.584 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:37.007 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.cleaningInfo.JSON" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:35.216 | info | State  value to set for  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_custom_mode"  has to be type "number" but received type "string"
roborock.0 | 2024-04-10 12:50:35.151 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:35.075 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.876 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-10 12:50:34.697 | warn | State   "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.691 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.13" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.690 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.12" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.690 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.11" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.690 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.10" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.668 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.9" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.668 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.8" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.667 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.7" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.666 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.6" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.666 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.5" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.665 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.4" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.664 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.3" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.664 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.2" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.657 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.1" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:34.656 | warn | State  "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.firmwareFeatures.0" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-04-10 12:50:14.348 | info | Starting adapter finished. Lets go!!!!!!!
roborock.0 | 2024-04-10 12:50:13.485 | info | MQTT initialized

**Comment by Reddingo** [comment]
Bezüglich der Firmware Features sieht es so aus als ob beim Init was noch nicht so passt

![grafik](https://github.com/copystring/ioBroker.roborock/assets/32964022/128967d5-bde7-4f29-97ce-135af2aaf0c7)

**Comment by Reddingo** [comment]
Mit dem Update auf die 0.6.4 sind nun wieder die ganzen Objekte da, aber unter consumables sind noch Indizes (125, 126 und 127) statt Variablennamen.

![grafik](https://github.com/copystring/ioBroker.roborock/assets/32964022/f68d62f1-77d8-4d1a-9431-abc9730d8b49)

Und im Log stehen noch diefolgenden Warnings:

```
Failed to execute get_status on robot AAAAAONoaaaaNjPOPdcf Error: Local request with id 2 with method get_status timed out after 10 seconds

State "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions

State "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions

State "roborock.0.Devices.AAAAAONoaaaaNjPOPdcf.deviceStatus.water_box_status" has no existing object, this might lead to an error in future versions
```
