### ISSUE TITLE
Sekündliche Aktualisierung des DP nach Änderung eines commands DP

### ISSUE THREAD

**Issue by Norb1204** [copystring/ioBroker.roborock#515]
Hallo,

nach senden eines Befehls per commands Datenpunkt, aktualisiert sich dieser Datenpunkt danach sekündlich.
Erst wenn ich den Adapter neu starte, wird die sekündliche Aktualisierung beendet.

Aktuell verwende ich die letzte DEV-Version (29.03.2024), der Saugroboter ist ein ROBOROCK Qrevo MaxV.

**Comment by copystring** [comment]
Hi, poste bitte ein Debuglog.

**Comment by Norb1204** [comment]
<img width="911" alt="image" src="https://github.com/copystring/ioBroker.roborock/assets/132662785/5a470806-5b2d-43a0-be73-8562d77bab51">

<img width="541" alt="image" src="https://github.com/copystring/ioBroker.roborock/assets/132662785/d9b7a72d-1227-4bde-a032-8416582e2174">

**Comment by copystring** [comment]
Bitte keine Screenshots, aber dafür ein vollständiges Debuglog als .txt anhängen. Erst dann kann ich mir das richtig angucken.

**Comment by Norb1204** [comment]
Alles klar, als Anhang das LOG.

[DebugLog.txt](https://github.com/copystring/ioBroker.roborock/files/14816535/DebugLog.txt)

Befehl gesendet, danach permanente Aktualisierung des DP:
2024-03-31 17:29:53.028	debug	onStateChange: app_charge with value: true

**Comment by copystring** [comment]
In dem Debuglog taucht nur ein mal `onStateChange` auf. Sollte es nicht ständig auftauchen oder ist das Debuglog nicht vollständig?

**Comment by copystring** [comment]
Ich konnte den Fehler reproduzieren. Ich schaue mir das an. Brauche kein neues Debuglog.

**Comment by copystring** [comment]
Ist in der neuen dev behoben. Bitte testen. https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Norb1204** [comment]
funktioniert, Danke
