### ISSUE TITLE
"bestimmte Version installieren" funktioniert nicht 

### ISSUE THREAD

**Issue by jahnbes** [copystring/ioBroker.roborock#523]
Seit Febrauar dieses Jahres betreibe ich den Adapter nach langer Fehlersuche (zusammen mit copystring) den Adapter in der damals gültigen dev-Version, das ohne Probleme, ohne Abstürze.

Leider ließ ich mich verleiten, gestern die Version 0.6.1. zu installieren. Seitdem läuft der Adapter nicht mehr, permanente Abstürze, wie gehabt. Eine Installation der aktuellen dev-Version brachte keine Änderung, ebenso der eben getätigte Versuch, Version 0.6.2. zu nutzen. 

Die damalige dev-Version kann ich nicht mehr erreichen, der Versuch, die damalige runtime-Version (0.5.4) zu installieren, scheiterte daran, dass diese über den iobroker (Expert-Einstellung) nicht zu erreichen ist. Die verfügbaren Versionen enden dort bei 0.4.4..

Gibt es ein Lösung? Kann ich irgendwie auf die alte dev-Version zurück? Die lief, wie gesagt, seit Februar ohne einen einzigen Absturz.

Viele Grüße, Bert.
(Ich meine natürlich "verfügbare Versionen".)

10:41:
Habe jetzt 0.5.4 installieren können, Instanzt ist jetzt längere Zeit grün, es gibt aber keine Verbindung mehr zwischen dem iobroker und dem roborock, es kommen keine Befehle vom Webinterface zum roborock durch.
0.5.4 läuft jetzt wieder, hoffentlich länger. Wenn ich was mit der 0.6.1 machen soll, sage mir bitte was, copystring.
Viele Grüße, Bert.

**Comment by copystring** [comment]
Hallo Bert,

> permanente Abstürze

Magst du mir dazu ein Debuglog anhängen, in dem die Abstürze zu sehen sind?

> Eine Installation der aktuellen dev-Version brachte keine Änderung

Die dev und 0.6.2 haben aktuell den gleichen Stand. Daher logischerweise keine Änderung am Verhalten.

> Kann ich irgendwie auf die alte dev-Version zurück?

An sich geht das. Von wann im Februar war die denn? Dann kann ich den Link hier einfügen.

> Wenn ich was mit der 0.6.1 machen soll, sage mir bitte was, copystring.

Am liebste wäre es mir, wenn du die 0.6.2 testest, da es seit 0.4.4 keinen stabilen Release gibt und ich einen neuen stabilen Release bereitstellen möchte.
0.6.2 hat einen entscheidenden Vorteil, dass neue Modelle von Saugrobotern automatisch erkannt und unterstützt werden.

**Comment by jahnbes** [comment]
Hallo copystring, momentan habe ich etwas wenig Zeit, aber ich habe es auf der to-do-Liste. Dein Adapter läuft nach den kürzlichen Irretationen seit eineigen Tagen wieder ohne Probleme unter der Version 0.5.4.
Viele Grüße, jahnbes.

**Comment by jahnbes** [comment]
Hallo copystring, ich habe den Adapter 48 Stunden im debug-Modus unter der Version 0.6.2 laufen gehabt, ohne dass ein Fehler auftrat. Immer OHNE "Kartendarstellung aktivieren".
Ich habe den Modus jetzt auf "info" zurückgestellt, werde weiter beobachten und mich gegebenenfalls melden, falls Fehler auftreten.
Ein schönes Wochenende, Gruß Bert.
