### ISSUE TITLE
Support für Roborock Qrevo MaxV

### ISSUE THREAD

**Issue by Gustlwasser** [copystring/ioBroker.roborock#524]
Hallo zusammen,

wird es für den Adapter eine Unterstützung für den neuen Roborock Qrevo MaxV geben?
LG
Gustlwasser

**Comment by copystring** [comment]
Moin,

Hast du die Version 0.6.2 installiert?

**Comment by Gustlwasser** [comment]
Ja habe ich. 
Mir fehlt z.B. der komplette Ordner Consumables mit den Rückmeldungen der Filter und Sensoren.
Auch unter dem Ordner Command wird nichts aktualisiert.
Unter DeviceInfo sieht es hingegen gar nicht schlecht aus, hier habe ich viele aktuelle Zeitstempel.

**Comment by copystring** [comment]
OK. Erstellst du bitte ein Debuglog vom Start des Adapters und lässt ihn dann so 2–3 Minuten laufen. Das Debuglog dann hier anhängen.
Außerdem brauche ich den Inhalt vom HomeData.

**Comment by Gustlwasser** [comment]
[iobroker.2024-04-10.log](https://github.com/copystring/ioBroker.roborock/files/14936340/iobroker.2024-04-10.log)

**Comment by Gustlwasser** [comment]
HomeData

{"id":404273,"name":"My Home","lon":null,"lat":null,"geoName":null,"products":[{"id":"42qYXusGAhtBh5L2Sa4SMV","name":"Roborock S5 Max","model":"roborock.vacuum.s5e","iconUrl":null,"attribute":null,"capability":0,"category":"robot.vacuum.cleaner","schema":[{"id":"101","name":"rpc_request","code":"rpc_request","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"102","name":"rpc_response","code":"rpc_response","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"120","name":"错误代码","code":"error_code","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"121","name":"设备状态","code":"state","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"122","name":"设备电量","code":"battery","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"123","name":"清扫模式","code":"fan_power","mode":"rw","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"124","name":"拖地模式","code":"water_box_mode","mode":"rw","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"125","name":"主刷寿命","code":"main_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"126","name":"边刷寿命","code":"side_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"127","name":"滤网寿命","code":"filter_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"128","name":"额外状态","code":"additional_props","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"130","name":"完成事件","code":"task_complete","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"131","name":"电量不足任务取消","code":"task_cancel_low_power","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"132","name":"运动中任务取消","code":"task_cancel_in_motion","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"133","name":"充电状态","code":"charge_status","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"134","name":"烘干状态","code":"drying_status","mode":"ro","type":"RAW","property":null,"desc":null}]},{"id":"7HYigCZR9rr0vBtYPvch90","name":"Roborock Qrevo MaxV","model":"roborock.vacuum.a87","iconUrl":null,"attribute":null,"capability":0,"category":"robot.vacuum.cleaner","schema":[{"id":"101","name":"rpc_request","code":"rpc_request","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"102","name":"rpc_response","code":"rpc_response","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"120","name":"错误代码","code":"error_code","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"121","name":"设备状态","code":"state","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"122","name":"设备电量","code":"battery","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"123","name":"清扫模式","code":"fan_power","mode":"rw","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"124","name":"拖地模式","code":"water_box_mode","mode":"rw","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"125","name":"主刷寿命","code":"main_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"126","name":"边刷寿命","code":"side_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"127","name":"滤网寿命","code":"filter_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"128","name":"额外状态","code":"additional_props","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"130","name":"完成事件","code":"task_complete","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"131","name":"电量不足任务取消","code":"task_cancel_low_power","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"132","name":"运动中任务取消","code":"task_cancel_in_motion","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"133","name":"充电状态","code":"charge_status","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"134","name":"烘干状态","code":"drying_status","mode":"ro","type":"RAW","property":null,"desc":null}]}],"devices":[{"duid":"3KcxHPDUl8TUVIBqBEAJoo","name":"Rocky","attribute":null,"activeTime":1710601952,"localKey":"kHqSg5J3PefnsnoW","runtimeEnv":null,"timeZoneId":"Europe/Berlin","iconUrl":"","productId":"7HYigCZR9rr0vBtYPvch90","lon":null,"lat":null,"share":false,"shareTime":null,"online":true,"fv":"02.28.08","pv":"1.0","roomId":null,"tuyaUuid":null,"tuyaMigrated":false,"extra":"{\"RRPhotoPrivacyVersion\": \"1\"}","setting":null,"sn":"R73EBD34701907","featureSet":"4499197267967999","newFeatureSet":"500A177F7EFEFFFF","deviceStatus":{"120":0,"121":8,"122":100,"123":104,"124":203,"125":94,"126":90,"127":87,"128":0,"133":1,"134":0},"silentOtaSwitch":true,"f":false},{"duid":"7cJDug8YoFmqcyNpWliOF5","name":"Staubhexe","attribute":null,"activeTime":1635586047,"localKey":"rFzos1UaXFemwCEl","runtimeEnv":null,"timeZoneId":"Europe/Berlin","iconUrl":"","productId":"42qYXusGAhtBh5L2Sa4SMV","lon":null,"lat":null,"share":false,"shareTime":null,"online":true,"fv":"02.16.62","pv":"1.0","roomId":null,"tuyaUuid":"stsj4bac738b491455de","tuyaMigrated":true,"extra":"{\"xxxx\": \"xxxx\"}","setting":null,"sn":"R0517S02201048","featureSet":"0","newFeatureSet":"0000000000002000","deviceStatus":{"120":0,"121":8,"122":100,"123":104,"124":203,"125":73,"126":59,"127":46},"silentOtaSwitch":false,"f":false}],"receivedDevices":[],"rooms":[{"id":17847169,"name":"Schlafzimmer1"},{"id":17838498,"name":"Eingangstur"},{"id":17477011,"name":"Arbeitszimmer"},{"id":17477007,"name":"Flur"},{"id":17477005,"name":"Badezimmer"},{"id":16331031,"name":"Gang EG"},{"id":16331025,"name":"Sophia"},{"id":16331024,"name":"Gang OG"},{"id":16331021,"name":"Bad OG"},{"id":16331018,"name":"Jakob"},{"id":16331011,"name":"Gang UG"},{"id":16331008,"name":"Büro"},{"id":16331007,"name":"Waschraum"},{"id":16331003,"name":"Bad UG"},{"id":16331000,"name":"Schlafzimmer"},{"id":10882088,"name":"Klo"},{"id":10882085,"name":"Kammerl"},{"id":10882079,"name":"Gang"},{"id":10882075,"name":"Küche"},{"id":707773,"name":"Wohnzimmer"}]}

**Comment by copystring** [comment]
Installiert bitte die dev https://github.com/copystring/ioBroker.roborock/tree/dev. Die meisten Fehler sollten weg sein. Bitte genau wie zuvor ein neues Debuglog erstellen und die consumables checken.

**Comment by Gustlwasser** [comment]
Hallo,
die consumables sehen schon besser aus, gleichwohl fehlen noch Werte wie z.B. filter_life.

[iobroker.2024-04-12.log](https://github.com/copystring/ioBroker.roborock/files/14961107/iobroker.2024-04-12.log)

**Comment by copystring** [comment]
Ich kann mir nicht vorstellen, dass `filter_life` fehlt. Wie Parameter werden hier heraus direkt abgerufen und abgelegt:
![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/fda366fb-119d-42c1-8453-8dbb6a8b4f34)

**Comment by Gustlwasser** [comment]
<img width="1060" alt="Bildschirmfoto 2024-04-14 um 10 42 20" src="https://github.com/copystring/ioBroker.roborock/assets/166304000/902dea9e-231d-4382-bfb5-5a2555163f1a">

**Comment by copystring** [comment]
Da ist mir ein Fehler unterlaufen. Um das zu beheben, müsstest du folgendes tun:
- Adapter stoppen
- Die neue dev einspielen
- Ordner consumables löschen
- Adapter wieder starten


`main_brush_life`, `side_brush_life`, `filter_life` werden von Roborock als Nummern dargestellt. Also `125`, `126`, `127`

`Commands` werden grundsätzlich nie aktualisiert, es sein denn, du sendest ein Befehl los. Der Zeitstempel müsste vom ersten Starten des Adapters stammen bzw. vom Erstellen der Objekte, nachdem der Saugroboter erkannt wurde.

**Comment by Gustlwasser** [comment]
Hallo copystring,

leider aktualisiert er die life Wertre weiterhin nicht.

<img width="1302" alt="iobroker_consumbles" src="https://github.com/copystring/ioBroker.roborock/assets/166304000/6ff4adfc-bcf6-4b1d-86f2-8a7c25a57e1f">


[iobroker.2024-04-19.log](https://github.com/copystring/ioBroker.roborock/files/15036518/iobroker.2024-04-19.log)

**Comment by Gustlwasser** [comment]
Die Zeilen 125 - 127 sind nun da jedoch ohne Werte?

<img width="1302" alt="iobroker_consumbles" src="https://github.com/copystring/ioBroker.roborock/assets/166304000/f9b2f2b0-be0e-4b13-b8a1-2cf3b2d8e368">

[iobroker.2024-04-19.log](https://github.com/copystring/ioBroker.roborock/files/15036817/iobroker.2024-04-19.log)

**Comment by Gustlwasser** [comment]
Jetzt sind die Werte da ... hat wohl etwas gedauert bis es synchronisiert war. DANKE

**Comment by copystring** [comment]
Super 👍
