### ISSUE TITLE
Unsported attribute

### ISSUE THREAD

**Issue by misanorot** [copystring/ioBroker.roborock#526]
Mit dem Revo Modell erhalte ich folgende Info im Log:

`<html>
<body>

roborock.0 | 2024-04-14 20:06:09.794 | error | Unsported attribute: kct of get_status with value 0. Please contact the dev to add the newly found attribute of your robot.
-- | -- | -- | --

</body>
</html>`

**Comment by copystring** [comment]
Bitte 0.6.2 installieren.

**Comment by misanorot** [comment]
okay, sorry
