### ISSUE TITLE
Problem Map - Port 6824

### ISSUE THREAD

**Issue by anthopocket** [copystring/ioBroker.roborock#528]
hi

my roborock is S6 MaxV

I have a problem with the map server. i have no data.
![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/42f426dc-ae94-44e3-bec0-4b1787ae5188)

i have opened the port 6824 in my container.
![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/c0d5fd58-8415-465d-be96-04ca99a3d266)

**Versions:**  
 - Adapter version: 0.4.4
 - JS-Controller version: v18.20.2
 - Node version: 10.5.2
 - Operating system: Débian 11

i have enabled the write card in the app.

the log error is

`<html>
<body>

roborock.0 | 2024-04-15 22:55:31.558 | warn | Failed to execute get_clean_record_map on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Request with id 2928 timed out after 10 seconds for response.102
-- | -- | -- | --
roborock.0 | 2024-04-15 22:55:16.826 | info | MQTT initialized
roborock.0 | 2024-04-15 22:55:16.296 | info | starting. Version 0.4.4 in /opt/iobroker/node_modules/iobroker.roborock, node: v18.20.2, js-controller: 5.0.19
roborock.0 | 2024-04-15 22:55:13.042 | info | terminating
roborock.0 | 2024-04-15 22:55:12.541 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2024-04-15 22:55:12.541 | info | terminating
roborock.0 | 2024-04-15 22:55:12.540 | info | Got terminate signal TERMINATE_YOURSELF
roborock.0 | 2024-04-15 22:54:37.012 | warn | Failed to execute load_multi_map on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: There was an error processing the request with id 6201 error: {"code":-10003,"message":"action locked"}

</body>
</html>`

thanks you for you help

**Comment by copystring** [comment]
Hi. Please try 0.6.2 instead of 0.4.4

**Comment by copystring** [comment]
You also need node 18 for 0.6.2. Node 10 is not supported for years

**Comment by anthopocket** [comment]
how many install 0.6.2?
![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/037ab4c5-123d-450b-9ddf-db3d198ef246)

it's no disponible.

**Comment by anthopocket** [comment]
it 's same with 0.6.2
![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/cfcfba69-183e-4567-8f28-645ff7d7de81)


![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/a6037add-bea7-4bf5-85b7-f78a86581403)

**Comment by anthopocket** [comment]
![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/13fce15d-20eb-4f58-bca6-d8d10a61b9eb)

**Comment by copystring** [comment]
Please post a full debug log

**Comment by anthopocket** [comment]
with V0.6.2 Roborock is ko

> <html>
<body>

orock.0 | 2024-04-16 20:04:15.270 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 260 with method get_network_info timed out after 10 seconds
-- | -- | -- | --
roborock.0 | 2024-04-16 20:04:05.268 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 259 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 20:03:55.265 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 258 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:03:45.221 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 257 with method get_status timed out after 10 seconds
admin.0 | 2024-04-16 20:03:17.026 | info | ==> Connected system.user.admin from ::ffff:192.168.1.27
admin.0 | 2024-04-16 20:03:16.585 | info | <== Disconnect system.user.admin from ::ffff:192.168.1.27 admin
roborock.0 | 2024-04-16 20:03:15.300 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 256 with method get_network_info timed out after 10 seconds
roborock.0 | 2024-04-16 20:03:05.223 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 255 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 20:02:55.221 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 254 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:02:45.219 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 253 with method get_status timed out after 10 seconds
admin.0 | 2024-04-16 20:02:36.925 | info | ==> Connected system.user.admin from ::ffff:192.168.1.27
roborock.0 | 2024-04-16 20:02:15.267 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 252 with method get_network_info timed out after 10 seconds
roborock.0 | 2024-04-16 20:02:05.265 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 251 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 20:01:55.220 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 250 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:01:45.218 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 249 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:01:15.268 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 248 with method get_network_info timed out after 10 seconds
roborock.0 | 2024-04-16 20:01:05.265 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 247 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 20:00:55.219 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 246 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:00:45.217 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 245 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:00:19.354 | warn | MQTT connection reconnect.
roborock.0 | 2024-04-16 20:00:19.354 | warn | MQTT connection close.
roborock.0 | 2024-04-16 20:00:19.331 | warn | Reconnecting mqtt client!
roborock.0 | 2024-04-16 20:00:15.349 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 244 with method get_network_info timed out after 10 seconds
roborock.0 | 2024-04-16 20:00:05.305 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 243 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 19:59:55.261 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 242 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 19:59:45.218 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 241 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 19:59:15.313 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 240 with method get_network_info timed out after 10 seconds
roborock.0 | 2024-04-16 19:59:05.270 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 239 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 19:58:55.220 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 238 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 19:58:45.217 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 237 with method get_status timed out after 10 seconds


</body>
</html>

**Comment by anthopocket** [comment]
with V0.6.2 roborock is KO

`
<html>
<body>

2024-04-16 18:46:02.212 - warn: roborock.0 (56320) Failed to execute get_fw_features on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 0 with method get_fw_features timed out after 10 seconds
--
2024-04-16 18:46:02.254 - warn: roborock.0 (56320) Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 1 with method get_status timed out after 10 seconds

2024-04-16 18:46:02.296 - warn: roborock.0 (56320) Failed to execute get_clean_summary on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 2 with method get_clean_summary timed out after 10 seconds
2024-04-16 18:46:03.842 - warn: roborock.0 (56320) Failed to execute get_map_v1 on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 4 with method get_room_mapping timed out after 10 seconds

2024-04-16 18:46:12.298 - warn: roborock.0 (56320) Failed to execute get_multi_maps_list on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 5 with method get_multi_maps_list timed out after 10 seconds

2024-04-16 18:46:12.346 - warn: roborock.0 (56320) Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 6 with method get_status timed out after 10 seconds

2024-04-16 18:46:12.756 - error: host.c6a32fad35d6 Invalid request getRepository. "callback"(false) or "from"(true) is null
2024-04-16 18:46:22.394 - warn: roborock.0 (56320) Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 7 with method get_consumable timed out after 10 seconds

2024-04-16 18:46:32.398 - warn: roborock.0 (56320) Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 8 with method get_network_info timed out after 10 seconds


</body>
</html>


`

**Comment by anthopocket** [comment]
<html>
<body>

roborock.0 | 2024-04-16 20:32:43.288 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 39 with method get_consumable timed out after 10 seconds
-- | -- | -- | --
roborock.0 | 2024-04-16 20:32:33.242 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 38 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:32:23.196 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 37 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:31:53.250 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 36 with method get_network_info timed out after 10 seconds
roborock.0 | 2024-04-16 20:31:43.246 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 35 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 20:31:33.243 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 34 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:31:23.196 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 33 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:30:53.294 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 32 with method get_network_info timed out after 10 seconds
roborock.0 | 2024-04-16 20:30:43.289 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 31 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 20:30:33.243 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 30 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:30:23.195 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 29 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:29:53.265 | warn | Failed to execute get_network_info on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 28 with method get_network_info timed out after 10 seconds
roborock.0 | 2024-04-16 20:29:43.260 | warn | Failed to execute get_consumable on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 27 with method get_consumable timed out after 10 seconds
roborock.0 | 2024-04-16 20:29:33.258 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 26 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-16 20:29:23.224 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request


</body>
</html>

**Comment by copystring** [comment]
If you run iobroker in docker, you need it to run in the host network. Otherwise the adapter can't find the robot in the network.

**Comment by anthopocket** [comment]
yes iodocker run in docker

the docker and roborok is in the network 192.168.1.

Docker : 192.168.1.138
Roborock : 192.168.1.95


in version 0.4.4, it's ok exept maps and caméra

**Comment by anthopocket** [comment]
roborock is connected no?

'
roborock.0 | 2024-04-16 21:16:44.038 | info | Starting adapter finished. Lets go!!!!!!!
-- | -- | -- | --
roborock.0 | 2024-04-16 21:16:43.884 | info | MQTT initialized
roborock.0 | 2024-04-16 21:16:38.270 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-04-16 21:16:38.263 | info | starting. Version 0.6.2 in /opt/iobroker/node_modules/iobroker.roborock, node: v18.20.2, js-controller: 5.0.19
host.c6a32fad35d6 | 2024-04-16 21:16:37.335 | info | instance system.adapter.roborock.0 started with pid 619


</body>
</html>`

**Comment by copystring** [comment]
Please post the output of `ip addr` of your host

**Comment by anthopocket** [comment]
1) i have installed V0.4.4
all cde is ok exept maps and camera

for exemple 
![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/340a3ae7-5180-4494-9b20-7a7bbe5fec21)

i have no log error, warm exept maps

2) i have installe V0.6.2 now
none command is ok

the log have many errors

Ip addr in console

root@IoBroker:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e6:6c:c8:fa:bd:fd brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.138/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::e46c:c8ff:fefa:bdfd/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:5e:1c:3a:9a brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:5eff:fe1c:3a9a/64 scope link 
       valid_lft forever preferred_lft forever
7: veth1d74acd@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 1e:b3:d7:fe:f7:88 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::1cb3:d7ff:fefe:f788/64 scope link 
       valid_lft forever preferred_lft forever
21: veth6ac028d@if20: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 66:86:6a:a1:f1:58 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::6486:6aff:fea1:f158/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by copystring** [comment]
OK. I also need the output of `docker inspect YOUR_CONTAINER_NAME -f "{{json .NetworkSettings.Networks }}"` replace YOUR_CONTAINER_NAME with the name of your container. Maybe iobroker.

**Comment by anthopocket** [comment]
hi,

root@IoBroker:~# docker inspect iobroker -f "{{json .NetworkSettings.Networks }}"
{"bridge":{"IPAMConfig":{},"Links":null,"Aliases":null,"MacAddress":"02:42:ac:11:00:02","NetworkID":"b8960e319f7c74361307615d8c0e6fc22c7611ed5bb6019135c4e4be6d17a2eb","EndpointID":"9826863761ad8e845830836eec698fdee59eac36cce468cae3ce75c9d819e8e6","Gateway":"172.17.0.1","IPAddress":"172.17.0.2","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"DriverOpts":null,"DNSNames":null}}

**Comment by copystring** [comment]
Thank you. Your ioBroker is not running in the host network. See `"IPAddress":"172.17.0.2"`. To make this work, you need to run ioBroker in the host network. Otherwise, the adapter cannot find the robot in the network via UDP discovery.

**Comment by anthopocket** [comment]
ok thanksyou

i search how many change the ip adress to 192.168.1......

**Comment by copystring** [comment]
No problem :)

**Comment by anthopocket** [comment]
i have install iobroker for the documentation iobroker
it's ok
