### ISSUE TITLE
MQTT connection restart every minute

### ISSUE THREAD

**Issue by trollvottel** [copystring/ioBroker.roborock#529]
Hmm. Again I see MQTT connection restarts,. almost exactly every minute, without obvious reason. Sadly I have nothing in the log to tell when this started.

I'll restart the adapter now and keep watching to hopefully get anything useful in the log when it starts this reconnection loop.

**Comment by copystring** [comment]
Hi,

I have observed this myself sometimes. Restarting the adapter fixed the issue every single time I had the issue. Very hard to reproduce. Not sure where to take it from here. If I ever find a way to debug this, I'll fix this. Closing this because of the tiny chance to fix this.
