### ISSUE TITLE
Failed to execute app_start on robot XXX Unknown parameter: ["ok"]

### ISSUE THREAD

**Issue by manny4566** [copystring/ioBroker.roborock#530]
**Describe the bug**  
The Roborock Adapter always crashes and do a restart  after using the start button on the webpage.

**To Reproduce**  
1. Go to 'http://ip:6824/map.html'
2. Click on 'Start button'

**Expected behavior**  
No crash ;)

**Screenshots & Logfiles**  

roborock.0 | 2024-04-17 15:37:19.329 | info | Starting adapter finished. Lets go!!!!!!!
roborock.0 | 2024-04-17 15:37:17.558 | info | MQTT initialized
roborock.0 | 2024-04-17 15:37:11.924 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-04-17 15:37:11.916 | info | starting.  Version 0.6.2 (non-npm: copystring/ioBroker.roborock) in  /opt/iobroker/node_modules/iobroker.roborock, node: v18.19.0,  js-controller: 5.0.19
roborock.0 | 2024-04-17 15:37:11.824 | info | Plugin sentry Sentry Plugin disabled for this process because sending of statistic data is disabled for the system
roborock.0 | 2024-04-17 15:36:40.057 | warn | redis get roborock.0.HomeData, error - Connection is closed.
roborock.0 | 2024-04-17 15:36:40.048 | info | terminating
roborock.0 | 2024-04-17 15:36:39.618 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-04-17 15:36:39.618 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-04-17 15:36:39.609 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-04-17 15:36:39.608 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-04-17 15:36:39.548 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
roborock.0 | 2024-04-17 15:36:39.547 | info | terminating
roborock.0 | 2024-04-17 15:36:39.545 | error | Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-04-17 15:36:39.545 | error | TypeError:  Cannot read properties of undefined (reading 'captureException')    at  Roborock.catchError  (/opt/iobroker/node_modules/iobroker.roborock/main.js:1236:44)
roborock.0 | 2024-04-17 15:36:39.545 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-04-17 15:36:39.545 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
roborock.0 | 2024-04-17 15:36:39.542 | error | Failed to execute app_start on robot XXX Unknown parameter: ["ok"]

**Versions:**  
 - Adapter version: 0.6.2
 - JS-Controller version: 5.0.19
 - Node version: v18.19.0
 - Operating system: Debian 12

**Comment by copystring** [comment]
Hi,

I reproduced the bug. Does the robot start anyway?

**Comment by copystring** [comment]
Thank you for the report. This is fixed via https://github.com/copystring/ioBroker.roborock/commit/e00d7eaeb775424e1130f4fe7564d95ebf9b7bc2

**Comment by manny4566** [comment]
Yes, the command was successful. But only the return seems to lead to the error.
Thank you for the fix.
