### ISSUE TITLE
Roboter sind nicht bedienbar, DPs werden nicht aktualisiert

### ISSUE THREAD

**Issue by Schnuckman79** [copystring/ioBroker.roborock#531]
Moin Copystring,

mit der aktuellen Release-Version funktioniert der Adapter nicht mehr mit meinen beiden Robotern (S7 Maxv Ultra und Q Revo). Befehle werden nicht bestätigt und nicht umgesetzt, und Akkustände etc. werden nicht ausgelesen. Dafür ist das Protokoll voll mit Fehlermeldungen:

`roborock.0
2024-04-17 15:57:29.978	info	starting. Version 0.6.1 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.18.2, js-controller: 5.0.19

roborock.0
2024-04-17 15:57:30.018	info	Starting adapter. This might take a few minutes depending on your setup. Please wait.

roborock.0
2024-04-17 15:57:35.942	info	MQTT initialized

roborock.0
2024-04-17 15:57:38.047	info	Starting adapter finished. Lets go!!!!!!!

roborock.0
2024-04-17 15:58:18.422	warn	Failed to execute get_fw_features on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 0 with method get_fw_features timed out after 10 seconds

roborock.0
2024-04-17 15:58:18.425	warn	Failed to execute get_status on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 1 with method get_status timed out after 10 seconds

roborock.0
2024-04-17 15:58:18.465	warn	Failed to execute get_clean_summary on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 2 with method get_clean_summary timed out after 10 seconds

roborock.0
2024-04-17 15:58:28.473	warn	Failed to execute get_multi_maps_list on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 3 with method get_multi_maps_list timed out after 10 seconds

roborock.0
2024-04-17 15:58:28.516	warn	Failed to execute get_room_mapping on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 4 with method get_status timed out after 10 seconds

roborock.0
2024-04-17 15:58:38.575	warn	Failed to execute get_consumable on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 5 with method get_consumable timed out after 10 seconds

roborock.0
2024-04-17 15:58:47.438	warn	Failed to execute get_fw_features on robot 67ocXOx7crdmpcwJSAU4U8 Error: Local request with id 6 with method get_fw_features timed out after 10 seconds

roborock.0
2024-04-17 15:58:47.482	warn	Failed to execute get_status on robot 67ocXOx7crdmpcwJSAU4U8 Error: Local request with id 7 with method get_status timed out after 10 seconds

roborock.0
2024-04-17 15:58:47.486	warn	Failed to execute get_clean_summary on robot 67ocXOx7crdmpcwJSAU4U8 Error: Local request with id 8 with method get_clean_summary timed out after 10 seconds
`

Was kann ich tun?

VG
Schnuckman79

**Comment by Schnuckman79** [comment]
Ja, tut er tatsächlich. Schon immer, und hat auch mal funktioniert…Am 17.04.2024 um 19:29 schrieb copystring ***@***.***>:﻿
Läuft dein ioBroker in Docker?

**Comment by copystring** [comment]
Okay. Leider gab es eine zwingende Änderung am Adapter. Dadurch funktioniert dieser nur noch ohne Docker, oder wenn der Docker Container sich im host Netzwerk befindet. Dafür müsstest du das Netzwerk des Containers umstellen

**Comment by Schnuckman79** [comment]
irgendwelche Ports reinreichen reicht nicht? Würde ungern auf Docker verzichten, und hab keine Ahnung, wie ich Docker umkonfigurieren müsste

**Comment by copystring** [comment]
Leider reicht das nicht aus.

**Comment by Schnuckman79** [comment]
ey, ich hab dir Geld gespendet für einen funktionierenden Adapter, der dann auf einmal nicht mehr funktionierte :-) Wie bekomme ich das jetzt ans Laufen?

**Comment by copystring** [comment]
Hallo @Schnuckman79,

vielen Dank für deine Unterstützung und Spende.

Leider stammt die Änderung nicht von mir, sondern von Roborock. Die haben den Datenverkehr über MQTT eingeschränkt. Dies geht so weit, dass eine stabile Verbindung über MQTT nicht mehr möglich ist. Deshalb war die Umstellung direkt mit dem Saugroboter zu kommunizieren notwendig. Dies funktioniert jedoch nur dann, wenn sich der Saugroboter und ioBroker im selben Netz befinden. Dies ist technisch bedingt durch docker nur dann möglich, wenn das Netzwerk des Containers in Docker auf host oder macvlan umgestellt wird.

Wobei mir gerade eine Idee kommt, wie man das auch anders umsetzen könnte. Vielleicht kann ich mir am Wochenende dafür Zeit nehmen. Mal schauen, ob das was wird.

Nochmals vielen Dank für deine Unterstützung und die Spende. Dies trägt zur Motivation der Weiterentwicklung des Adapters bei. Trotz der Motivation, kann ich keine Garantie darauf geben, dass der Adapter für jeden Nutzer in jeder Situation zu 100 % zuverlässig funktioniert. Ich gebe mein Bestes den Adapter in meiner Freizeit neben dem Beruf, Familie, Haus, Garten, etc. weiterzuentwickeln.

Viele Grüße

copystring

**Comment by Schnuckman79** [comment]
Moin Copystring,

freut mich, dass die Entwicklung weitergeht :) Ich glaube, dass mein Szenario gar nicht so unüblich ist „da draußen“, von daher freut es vielleicht auch andere mal. Und es gibt einige Adapter, die direkt mit anderen Netzwerkgeräten lokal kommunizieren, ich bin guter Dinge, dass du einen Weg findest. Wenn ich irgendwie weiter unterstützen und helfen kann (zB durch Testen), lass es mich gern wissen. Am Ende fehlt auch noch eine Doku für Einsteiger, vielleicht kann ich mich da einbringen. Hat ne Weile gedauert, bis ich rausgefunden habe, welche DPs ich anfassen muss, dass Fiffi losfährt :)


LG
Schnuckman79

**Comment by copystring** [comment]
Ich habe den code gerade eben mit meiner neuen Idee angepasst und getestet. Bei mir war der Test erfolgreich. In Docker habe ich es aber nicht getestet. Würdest du das bitte für mich tun? Bitte diese Version installieren: https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Schnuckman79** [comment]
Moin Copystring,

sie reden wieder miteinander, besten Dank!

Im Protokoll habe ich aber dutzende Warnungen wie "State roborock.0.Devices.5C6feZA6a9g5JPwOSPkJy1.deviceStatus.corner_clean_mode" has no existing object, this might lead to an error in future versions"

Hängt das auch noch mit der Umstellung zusammen, oder ist das ein neues Problem? Oder ist das vielleicht egal? Dann blende ich es gedanklich aus.

VG
Schnuckman79

**Comment by copystring** [comment]
Hey, schön, dass es läuft.
Um die Warnung mit `corner_clean_mode` zu beheben, benötige ich dein `HomeData`.

**Comment by Schnuckman79** [comment]
Na, dann mal los:
[HomeData.txt](https://github.com/copystring/ioBroker.roborock/files/15071306/HomeData.txt)

betrifft deviceStatus.camera_status, deviceStatus.rdt, deviceStatus.corner_clean_mode, deviceStatus.distance_off, Gerät ist ein Q Revo.

VG
Schnuckman79

**Comment by copystring** [comment]
Hi,
würdest du bitte die neue dev testen? Müsste jetzt passen. https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Schnuckman79** [comment]
Leider nicht ganz:

<html>
<body>

roborock.0 | 2024-04-28 09:02:08.852 | info | starting. Version 0.6.4 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.20.2, js-controller: 5.0.19
-- | -- | -- | --
roborock.0 | 2024-04-28 09:02:08.870 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-04-28 09:02:09.529 | info | MQTT initialized
roborock.0 | 2024-04-28 09:03:15.603 | info | Starting adapter finished. Lets go!!!!!!!
roborock.0 | 2024-04-28 09:03:25.796 | warn | Failed to execute get_fw_features on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 2 with method get_fw_features timed out after 10 seconds
roborock.0 | 2024-04-28 09:03:25.798 | warn | Failed to execute get_status on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 3 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-28 09:04:15.676 | warn | State "roborock.0.Devices.5C6feZA6a9g5JPwOSPkJy1.deviceStatus.distance_off" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-28 09:04:15.682 | warn | State "roborock.0.Devices.5C6feZA6a9g5JPwOSPkJy1.deviceStatus.camera_status" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-28 09:04:15.686 | warn | State "roborock.0.Devices.5C6feZA6a9g5JPwOSPkJy1.deviceStatus.rdt" has no existing object, this might lead to an error in future versions


</body>
</html>

**Comment by copystring** [comment]
OK. Ich habe weitere Werte hinzugefügt. Testest du bitte nochmal? Timeouts sind übrigens normal. Der Roborockserver antwortet halt nicht jedes Mal.
https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Schnuckman79** [comment]
Moin Copystring,

hier ein Auszug aus dem Log. Die fehlenden Werte sind erledigt, dafür ein neues Problem (optisch?):

<html>
<body>

roborock.0 | 2024-05-08 15:27:47.914 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string"
-- | -- | -- | --
roborock.0 | 2024-05-08 15:28:48.172 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string"
roborock.0 | 2024-05-08 15:29:47.958 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string"
roborock.0 | 2024-05-08 15:30:48.110 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string"
roborock.0 | 2024-05-08 15:31:48.002 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string"
roborock.0 | 2024-05-08 15:32:47.950 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string"
roborock.0 | 2024-05-08 15:33:47.963 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string"


</body>
</html>

**Comment by Jeeperat** [comment]
Auch bei mir funktioniert seit dem letzten Update der Adapter nicht mehr. Ich habe IOBroker nicht in einem Container. Allerdings ist der Roboter im Fritz Gastnetz, die IOBroker Installation im normalen Netz. Ist das ein Problem? War es ja nie, weil der Adapter ja eh auf den Roborockaccount zugreift.

**Comment by copystring** [comment]
> weil der Adapter ja eh auf den Roborockaccount zugreift

Ja, aber nein. Über den Account werden nur die nötigsten Daten des Roboters abgeholt. Danach kommuniziert der Adapter direkt mit dem Saugroboter über das Netzwerk.

**Comment by copystring** [comment]
> Moin Copystring,
> 
> hier ein Auszug aus dem Log. Die fehlenden Werte sind erledigt, dafür ein neues Problem (optisch?):
> 
> roborock.0 | 2024-05-08 15:27:47.914 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string" -- | -- | -- | -- roborock.0 | 2024-05-08 15:28:48.172 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string" roborock.0 | 2024-05-08 15:29:47.958 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string" roborock.0 | 2024-05-08 15:30:48.110 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string" roborock.0 | 2024-05-08 15:31:48.002 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string" roborock.0 | 2024-05-08 15:32:47.950 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string" roborock.0 | 2024-05-08 15:33:47.963 | info | State value to set for "roborock.0.Devices.67ocXOx7crdmpcwJSAU4U8.deviceStatus.events" has to be type "number" but received type "string"

Bitte die neue dev testen. Dort sollte jetzt alles passen.

**Comment by Jeeperat** [comment]
> > weil der Adapter ja eh auf den Roborockaccount zugreift
> 
> Ja, aber nein. Über den Account werden nur die nötigsten Daten des Roboters abgeholt. Danach kommuniziert der Adapter direkt mit dem Saugroboter über das Netzwerk.

ok, das ist also neu. Ich habe den Adapter nur zum starten und stoppen des Roboters benutzt. Das wird also im Gastnetz nicht mehr klappen?

**Comment by copystring** [comment]
Teste bitte die neue dev https://github.com/copystring/ioBroker.roborock/tree/dev. Wenn du weitere Probleme haben solltest, eröffne bitte ein neues Issue, da dies nichts mit dem Problem von @Schnuckman79 zu tun hat. Danke!

**Comment by copystring** [comment]
@Schnuckman79 ist das Problem noch aktuell?

**Comment by Schnuckman79** [comment]
Nein, ist behoben, kannst schließen :-)
