### ISSUE TITLE
begin und end werden nicht upgedated

### ISSUE THREAD

**Issue by jahnbes** [copystring/ioBroker.roborock#532]
Hallo copystring,

ich habe den Eindruck, das seit dem update auf die Version 0.6.2

Start cleaning time (cleaning time [roborock.0.Devices.....cleaningInfo.Records.0.begin]
und 
End cleaning time (cleaning time [roborock.0.Devices.....cleaningInfo.Records.0.end]

nicht mehr auf aktuelle Werte gesetzt werden. Jedenfalls stehen seit diesem update diese Werte fest auf
Fri Apr 12 2024 08:43:18 GMT+0200 (Central European Summer Time)
und werden nicht geändert, obwohl der Roborock mehrfach gelaufen ist und läuft.
Viele Grüße, jahnbes.
(Roborock S7 MaxV)

**Comment by jahnbes** [comment]
Ich habe eben testhalber die 0.5.4 installiert und da funktioniert es! Werde die 0.5.4 erst mal weiter laufen lassen.
Woll ich weiter testen? Und wenn ja, wie? Kannst Du den Fehler reproduzieren?
Viele Grüße, jahnbes.

**Comment by copystring** [comment]
Hallo Bernd,

testest du bitte die neue dev? https://github.com/copystring/ioBroker.roborock/tree/dev müsste jetzt passen.

Viele Grüße und Danke fürs Testen!

**Comment by copystring** [comment]
OK. Schade. Das habe mir das jetzt mal genauer angucken können. Ich denke, dass ich es lösen konnte. Das Problem war in Verbindung mit TCP Verbindung direkt zum Saugrober ziemlich tief versteckt. Mein Test mit https://github.com/copystring/ioBroker.roborock/tree/dev war erfolgreich.

**Comment by jahnbes** [comment]
Hallo copystring,

ich habe es heute wieder einmal mit der obigen dev wirklich lang versucht, ohne Erfolg. Da ich in einem Script auf "begin" triggere, musste ich wieder zurück zur  0.5.4 gehen, wo dann wieder alle sohne Probleme lief.
Viele Grüße, jahnbes.

**Comment by copystring** [comment]
OK. Dann weiß ich nicht, wo es hängt. Erstell bitte mit der neuesten dev ein Debuglog für mich.

**Comment by jahnbes** [comment]
Mache ich, dauert aber einen kleinen Moment. Ein schönes Wochenende, Bert.

**Comment by jahnbes** [comment]
[roborock_log_bert_20240522.pdf](https://github.com/copystring/ioBroker.roborock/files/15402129/roborock_log_bert_20240522.pdf)
Hier das log-file. Ich habe folgendes getan:

1. bookworm erfolgreich installiert
2. roborock Adapter dev Version (0.6.4) installiert
3. auf "debug" gestellt
4. Flur gereinigt über den Adapter (ohne Erfolg)
5. Version 0.5.4 installiert
6. Flur gereinigt über den Adapter (begin und end funktioniert)
7. auf "info" gestellt
8. log download und hier eingestellt.

Es gibt dabei noch einen interessanten Punkt, den ich in der folgenden Antwort mit Bild beschreibe.

**Comment by jahnbes** [comment]
Ablauf siehe voriger Eintrag hier. Interssant ist, dass nachdem der roborock mit dem Adapter 0.5.4 den Raum gereinigt hat, ALLE Reinigungsfahrten, auch die unter 0.6.4 in der Liste erscheinen.
![roborock_debug_20240522](https://github.com/copystring/ioBroker.roborock/assets/82932280/624368ae-38fb-4233-9011-5447c5d7588b)
Bei Nutzung der 0.6.4 blieben [begin] und [end] immer auf den alten Eintrag (8:30 Uhr) stehen, obwohl die Reinigung 12:21 Uhr und 12:31 Uhr erfolgte.
Nach der anschließenden Reinigung mit 0.5.4 (12:43 Uhr) angezeigt, das heisst [begin] und [end] geändert. Es werden unmittelbar davor aber auch die Werte der Reinigungen mit 0.6.4 in den Record [0] geschrieben und erst danach der aktuelle von der Reinigung mit 0.5.4.
Aus dem Grund erscheinen die Reinigungen mit der 0.6.4 bei mir nun auch in der Liste, nachdem ich mit 0.5.4 gereinigt habe.

Ich hoffe, ich konnte einigermaßen verständlich mitteilen, was mir aufgefallen ist.
Viele Grüße, Bert.

**Comment by copystring** [comment]
Hallo Bert,

ich weiß leider nicht, wie ich dir helfen kann. Ich habe gerade eben eine Reinigung gestartet und darauf gewartet, dass der Saugroboter fertig wird. `Begin` und `End` wurden bei mir sauber direkt nach dem Beenden des Reinigungsvorgangs geschrieben.
Siehe die Zeitstempel in den Screenshots.
In den Logs ist ebenfalls nichts Hilfreiches zu sehen. Dein Debuglog habe ich nach `error` durchsucht. Es sind nur ein paar Timeouts vorhanden. Nichts Wildes und sollte nichts mit dem besagten Fehler zu tun haben.

Würdest du mal die Timestamps in den Objekten in deinem ioBroker checken?

Ich wüsste spontan nicht, warum mein Code bei dir nicht läuft und bei mir aber ohne Fehler läuft.
Vielleicht hast du eine alte nodejs installiert?

![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/f6fba969-1ce6-48e4-81a4-399154e50780)

![image](https://github.com/copystring/ioBroker.roborock/assets/1298861/d1535a84-0a8d-4a24-81e3-5b3dbf0cd60b)

**Comment by jahnbes** [comment]
Danke für die Antwort. Auf die Schnelle, die Zeitstempel stimmen! Die zeigen die korrekte Zeit an, nur [begin] und [end] nicht. Ich forsche weiter.
Viele Grüße, Bert.

**Comment by copystring** [comment]
Kann es sein, dass du eine alte Version installiert hast? Das war das mal so.

**Comment by jahnbes** [comment]
Wovon eine alte Version? iobroker, robo-Adapter, nodejs oder npm?
Momentan bin ich total am Boden, habe mir beim Testen (node-Versionen?) den ssh-Zugriff auf den Raspberrry gekillt, komme nicht mehr drauf. Wird eine Weile dauern, ehe ich das hingebogen habe.
Es wäre mir ein Hilfe, wenn Du mir schreiben könntest, welche  Rasbian, iobroker, robo-Adapter, nodejs oder npm - Versionen Du nutzt. Bei Dir läuft es ja. Ich könnte diese dann mit meinen vergleichen.

**Comment by copystring** [comment]
Ich meinte damit, dass du eventuell eine alte Version vom Roborock Adapter haben könntest.

**Comment by bruesche** [comment]
Hallo. Ich habe das Problem bei mir auch beobachtet. Die kompletten Daten unter "CleaningInfos/Records/0/" werden nicht aktualisiert. Ich habe etwas experimentiert. Adapter neu starten bringt nichts. Aber was den Adapter triggert neue Daten zu lesen ist, wenn ich in der Config des Adapters was ändere und dann speichere. Nach jedem Speichern ließt er wohl alle Reinigungsfahrten und aktualisiert alles. Von alleine macht der Adapter das leider nicht. Die neue DEV Variante habe ich nicht getestet.

**Comment by bruesche** [comment]
Habe jetzt gerade mal die DEV Version über die Expertenfunktion mit Angabe der URL installiert. Eine kurze Reinigungsfahrt. Es scheint automatisch aktualisiert zu haben. Werde das noch ein zwei Tage testen und dann berichten, wenn das ok ist.

**Comment by bruesche** [comment]
Also habe jetzt mein Script zur Probe auf Minuten runter gedreht, da ich auf Reiniungsdauer und Completion trigger. Hat nun wieder immer nach dem Reinigen alles aktualisiert. Funktioniert für mich. Bitte in den "originalen" Adapter integrieren. 
wenn ich noch helfen kann, gerne melden

**Comment by copystring** [comment]
Danke fürs Testen. Sobald ich die letzten Fehler in der dev Version behoben habe, kommt ein neuer Release. Dauert leider noch ein bisschen. Bin aktuell zeitlich ziemlich eingespannt.
