### ISSUE TITLE
command to add - roborock S6 MaxV

### ISSUE THREAD

**Issue by anthopocket** [copystring/ioBroker.roborock#535]
hi,

In version 0.4.4, i have commande ok
but in version 0.6.2 two or three command have disappeared

Log :

'
roborock.0 | 2024-04-21 13:34:28.755 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.mop_forbidden_enable" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
roborock.0 | 2024-04-21 13:34:28.755 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_carriage_status" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-21 13:34:28.755 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-21 13:34:28.621 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_status" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-21 13:33:28.664 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.mop_forbidden_enable" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-21 13:33:28.664 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_carriage_status" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-21 13:33:28.664 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-21 13:33:28.616 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_status" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-21 13:32:28.695 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.mop_forbidden_enable" has no existing object, this might lead to an error in future versions

</body>
</html>

`

**Comment by copystring** [comment]
Hi, thanks for the log.

Should be fixed in the latest dev: https://github.com/copystring/ioBroker.roborock/tree/dev would be great if you could confirm the fix.

**Comment by anthopocket** [comment]
it's the same log with 0.6.4

`
roborock.0 | 2024-04-28 11:00:42.844 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.mop_forbidden_enable" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
roborock.0 | 2024-04-28 11:00:42.844 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_carriage_status" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-28 11:00:42.843 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-28 11:00:42.759 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_status" has no existing object, this might lead to an error in future versions


</body>
</html>`

**Comment by anthopocket** [comment]
With this version maps,mqtt is down (KO)

**Comment by copystring** [comment]
How did you install the dev?

**Comment by anthopocket** [comment]
![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/b3aae7e3-f6c1-423a-810b-beab1be608d9)


change beta to iobroker

**Comment by copystring** [comment]
Ok. That's not how this works.
https://github.com/copystring/ioBroker.roborock/tree/dev is not the same as the beta.
So you need to install via the link provided above. You can do that by clicking the GitHub cat in iobroker and then pasting the dev link.

**Comment by anthopocket** [comment]
sorry i don't understand to install the  dev branch
i have :
![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/513f7037-8c5f-4fc0-9781-0229910c81f5)

i don't have roborock to dev branch

**Comment by copystring** [comment]
Try this but it's in German: https://www.smarthome-tricks.de/software-iobroker/adapter-von-github-installieren/

**Comment by anthopocket** [comment]
ok thanks you

for Dev version, it's the same log

`
roborock.0 | 2024-04-29 18:49:11.438 | warn | Failed to execute get_room_mapping on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 5 with method get_status timed out after 10 seconds
-- | -- | -- | --
roborock.0 | 2024-04-29 18:49:01.428 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.mop_forbidden_enable" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-29 18:49:01.428 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_carriage_status" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-29 18:49:01.428 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-29 18:49:01.418 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.deviceStatus.water_box_status" has no existing object, this might lead to an error in future versions


</body>
</html>`

**Comment by copystring** [comment]
Please download the new dev to try again

**Comment by anthopocket** [comment]
Maps is already KO.

the log is différent :
`
roborock.0 | 2024-04-29 19:20:09.002 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
-- | -- | -- | --
roborock.0 | 2024-04-29 19:19:08.979 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-29 19:18:18.915 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-04-29 19:18:18.790 | warn | Failed to execute get_status on robot 7aTL79f4Fx1iyTSXB82Yk6 Error: Local request with id 2 with method get_status timed out after 10 seconds
roborock.0 | 2024-04-29 19:18:08.826 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.cleaningInfo.2" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-29 19:18:08.825 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.cleaningInfo.1" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-29 19:18:08.824 | warn | State "roborock.0.Devices.7aTL79f4Fx1iyTSXB82Yk6.cleaningInfo.0" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-04-29 19:18:08.724 | info | Starting adapter finished. Lets go!!!!!!!


</body>
</html>`

![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/d64b2138-f0c2-41ea-81b9-2c132d984d8d)

**Comment by anthopocket** [comment]
maps is ok

![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/96bc17d4-7bd3-41bc-b467-700ff8e5d6fc)

**Comment by anthopocket** [comment]
the zone is not in the maps.

![image](https://github.com/copystring/ioBroker.roborock/assets/62506538/005a3d11-595a-4813-b5c5-dd957e43f458)

**Comment by copystring** [comment]
Please record a video to see the problem.

**Comment by anthopocket** [comment]
Video
![Uploading 192.168.1.35_6824_map.html - Google Chrome 2024-05-08 12-14-56.gif…]()

**Comment by anthopocket** [comment]
again error in the log

`
roborock.0 | 2024-05-08 12:26:47.050 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
-- | -- | -- | --



</body>
</html>`

**Comment by copystring** [comment]
> Video
> 
> ![video](https://private-user-images.githubusercontent.com/62506538/328851327-e880209b-3363-4661-824c-baf67f64cda7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjY4NTIsIm5iZiI6MTcxNjAyNjU1MiwicGF0aCI6Ii82MjUwNjUzOC8zMjg4NTEzMjctZTg4MDIwOWItMzM2My00NjYxLTgyNGMtYmFmNjdmNjRjZGE3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjk5YjRmZmE0MzdhN2ZjODJhNWI0NTQwZjM3ZGFlNTI3ZWMxNDA0MzQ1OWYwZDY2ZjJjYzQxMWQxNjRlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._khy3wp0tFDqiWJ2tmlv0kJjOFlM23QYR6NiUUUuxYA) [ ![video](https://private-user-images.githubusercontent.com/62506538/328851327-e880209b-3363-4661-824c-baf67f64cda7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjY4NTIsIm5iZiI6MTcxNjAyNjU1MiwicGF0aCI6Ii82MjUwNjUzOC8zMjg4NTEzMjctZTg4MDIwOWItMzM2My00NjYxLTgyNGMtYmFmNjdmNjRjZGE3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjk5YjRmZmE0MzdhN2ZjODJhNWI0NTQwZjM3ZGFlNTI3ZWMxNDA0MzQ1OWYwZDY2ZjJjYzQxMWQxNjRlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._khy3wp0tFDqiWJ2tmlv0kJjOFlM23QYR6NiUUUuxYA) ](https://private-user-images.githubusercontent.com/62506538/328851327-e880209b-3363-4661-824c-baf67f64cda7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjY4NTIsIm5iZiI6MTcxNjAyNjU1MiwicGF0aCI6Ii82MjUwNjUzOC8zMjg4NTEzMjctZTg4MDIwOWItMzM2My00NjYxLTgyNGMtYmFmNjdmNjRjZGE3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjk5YjRmZmE0MzdhN2ZjODJhNWI0NTQwZjM3ZGFlNTI3ZWMxNDA0MzQ1OWYwZDY2ZjJjYzQxMWQxNjRlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._khy3wp0tFDqiWJ2tmlv0kJjOFlM23QYR6NiUUUuxYA) [ ](https://private-user-images.githubusercontent.com/62506538/328851327-e880209b-3363-4661-824c-baf67f64cda7.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjY4NTIsIm5iZiI6MTcxNjAyNjU1MiwicGF0aCI6Ii82MjUwNjUzOC8zMjg4NTEzMjctZTg4MDIwOWItMzM2My00NjYxLTgyNGMtYmFmNjdmNjRjZGE3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjk5YjRmZmE0MzdhN2ZjODJhNWI0NTQwZjM3ZGFlNTI3ZWMxNDA0MzQ1OWYwZDY2ZjJjYzQxMWQxNjRlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._khy3wp0tFDqiWJ2tmlv0kJjOFlM23QYR6NiUUUuxYA)

I don't see a problem. Everything is working as intended. But your map is weird. That is not something I can change. Did you to clean a zone? Does it work as intended?



> again error in the log
> 
> `
> 
> roborock.0	2024-05-08 12:26:47.050	warn	Failed to map rooms. You need to name your rooms via the mobile app on your phone.`

Did you read the message? You have some rooms not named. If you want the adapter to work correctly, you need to name all your rooms.
