### ISSUE TITLE
Warn- und Fehlermeldungen Roborock Qrevo MaxV

### ISSUE THREAD

**Issue by Norb1204** [copystring/ioBroker.roborock#539]
Bei meinem Roborock Qrevo MaxV kommen einige Warn- und Fehlermeldungen (siehe Log).
Beim wechseln der Map kommt u.a. eine Fehlermeldung.
Ist für mich kein Problem, wollte nur mal darauf hinweisen. Evtl. kann man den Adapter noch verbessern.
[LOG Roborock Qrevo MaxV.txt](https://github.com/copystring/ioBroker.roborock/files/15129145/LOG.Roborock.Qrevo.MaxV.txt)

**Comment by copystring** [comment]
Hallöchen,

teste bitte die neue dev und häng anschließend ein neues Log an. Ich denke ich habe alle oder die meisten Warnungen ausfindig machen können. https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Norb1204** [comment]
Hallo,
als Anhang das Log
[log.txt](https://github.com/copystring/ioBroker.roborock/files/15141069/log.txt)

**Comment by copystring** [comment]
OK. Das hat geholfen. Wenn du den Inhalt von `HomeData` hier hinzufügen kannst, kann ich auch die letzten fehlenden Werte hinzufügen.

**Comment by Norb1204** [comment]
[HomeData.txt](https://github.com/copystring/ioBroker.roborock/files/15209929/HomeData.txt)

**Comment by copystring** [comment]
Testest du bitte die neue dev und machst damit ein neues Debuglog? https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Norb1204** [comment]
[log 15.05.2024.txt](https://github.com/copystring/ioBroker.roborock/files/15213468/log.15.05.2024.txt)

**Comment by copystring** [comment]
Da ist mir ein Fehler unterlaufen. Die neue dev müsste jetzt passen.

**Comment by Norb1204** [comment]
kein Problem, als Anhang das neue Log
[log 15.05.2024_Ver2.txt](https://github.com/copystring/ioBroker.roborock/files/15213581/log.15.05.2024_Ver2.txt)

**Comment by copystring** [comment]
Danke fürs Berichten und Testen. Jetzt passt alles.
