### ISSUE TITLE
Neueste /dev (1.5.2024) installiert: Fehlermeldungen "fehlende DPs"

### ISSUE THREAD

**Issue by tritanium73** [copystring/ioBroker.roborock#545]
**Describe the bug**  
Alle 15 - 20 Sekunden Fehlermeldungen über fehlende Datenpunkte

**To Reproduce**  
Ich muss nur den Adapter starten und ca. 20 Sekunden warten, dann gehts los.

**Expected behavior**  
Keine Fehlermeldungen :-)

**Screenshots & Logfiles**  
```
roborock.0 | 2024-05-01 22:02:31.868 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.rdt" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:31.866 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.camera_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:31.865 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:31.777 | warn | State  "roborock.0.Devices.5kt1jy0ATJPgji5k0hJAZg.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:16.908 | warn | State  "roborock.0.Devices.5kt1jy0ATJPgji5k0hJAZg.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:16.811 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.rdt" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:16.789 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.camera_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:16.788 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:01.834 | warn | State  "roborock.0.Devices.5kt1jy0ATJPgji5k0hJAZg.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:01.820 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.rdt" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:01.805 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.camera_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:02:01.804 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:46.926 | warn | State  "roborock.0.Devices.5kt1jy0ATJPgji5k0hJAZg.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:46.830 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.rdt" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:46.807 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.camera_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:46.804 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:31.913 | warn | State  "roborock.0.Devices.5kt1jy0ATJPgji5k0hJAZg.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:31.812 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.rdt" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:31.793 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.camera_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:31.790 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:16.892 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.rdt" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:16.847 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.camera_status"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:16.846 | warn | State  "roborock.0.Devices.4Si5s3DNcsl0ATAl8e5UdI.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-05-01 22:01:16.750 | warn | State  "roborock.0.Devices.5kt1jy0ATJPgji5k0hJAZg.deviceStatus.distance_off"  has no existing object, this might lead to an error in future versions
```

**Versions:**  
 - Adapter version: 0.6.4 /dev am 1.5.2024 installiert
 - JS-Controller version: v5.0.19
 - Node version: v18.19.1
 - Operating system: linux lts 22.04

**Additional context**  

Device 5kt...... roborock.vacuum.a38   Q7 Max+
Device 4Si...... roborock.vacuum.a75   Q Revo

Wenn du noch mehr Infos / Logs , etc. benötigst gib Bescheid...

**Comment by copystring** [comment]
Bist du so nett in fügst hier dein `HomeData` hinzu?

**Comment by tritanium73** [comment]
So, hier nun mein "HomeData".

Hoffe es hilft:

`
{"id":4521038,"name":"Weber Home","lon":null,"lat":null,"geoName":null,"products":[{"id":"7kamVau2Xpgoj0dCdS7230","name":"Roborock Q7 Max","model":"roborock.vacuum.a38","iconUrl":null,"attribute":null,"capability":0,"category":"robot.vacuum.cleaner","schema":[{"id":"101","name":"rpc_request","code":"rpc_request","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"102","name":"rpc_response","code":"rpc_response","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"120","name":"错误代码","code":"error_code","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"121","name":"设备状态","code":"state","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"122","name":"设备电量","code":"battery","mode":"ro","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"123","name":"清扫模式","code":"fan_power","mode":"rw","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"124","name":"拖地模式","code":"water_box_mode","mode":"rw","type":"ENUM","property":"{\"range\": []}","desc":null},{"id":"125","name":"主刷寿命","code":"main_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"126","name":"边刷寿命","code":"side_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"127","name":"滤网寿命","code":"filter_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": null, \"scale\": 1}","desc":null},{"id":"128","name":"额外状态","code":"additional_props","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"130","name":"完成事件","code":"task_complete","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"131","name":"电量不足任务取消","code":"task_cancel_low_power","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"132","name":"运动中任务取消","code":"task_cancel_in_motion","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"133","name":"充电状态","code":"charge_status","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"134","name":"烘干状态","code":"drying_status","mode":"ro","type":"RAW","property":null,"desc":null}]},{"id":"ldHlB6hwVPMvdm6AdkxJv","name":"Roborock Qrevo","model":"roborock.vacuum.a75","iconUrl":null,"attribute":null,"capability":0,"category":"robot.vacuum.cleaner","schema":[{"id":"101","name":"rpc_request","code":"rpc_request","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"102","name":"rpc_response","code":"rpc_response","mode":"rw","type":"RAW","property":null,"desc":null},{"id":"120","name":"错误代码","code":"error_code","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"121","name":"设备状态","code":"state","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"122","name":"设备电量","code":"battery","mode":"ro","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"123","name":"清扫模式","code":"fan_power","mode":"rw","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"124","name":"拖地模式","code":"water_box_mode","mode":"rw","type":"ENUM","property":"{\"range\": [\"\"]}","desc":null},{"id":"125","name":"主刷寿命","code":"main_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"126","name":"边刷寿命","code":"side_brush_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"127","name":"滤网寿命","code":"filter_life","mode":"rw","type":"VALUE","property":"{\"max\": 100, \"min\": 0, \"step\": 1, \"unit\": \"null\", \"scale\": 1}","desc":null},{"id":"128","name":"额外状态","code":"additional_props","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"130","name":"完成事件","code":"task_complete","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"131","name":"电量不足任务取消","code":"task_cancel_low_power","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"132","name":"运动中任务取消","code":"task_cancel_in_motion","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"133","name":"充电状态","code":"charge_status","mode":"ro","type":"RAW","property":null,"desc":null},{"id":"134","name":"烘干状态","code":"drying_status","mode":"ro","type":"RAW","property":null,"desc":null}]}],"devices":[{"duid":"5kt1jy0ATJPgji5k0hJAZg","name":"J.A.R.V.I.S","attribute":null,"activeTime":1703226476,"localKey":"pEXoK6R9hdS8Eoxg","runtimeEnv":null,"timeZoneId":"Europe/Berlin","iconUrl":"","productId":"7kamVau2Xpgoj0dCdS7230","lon":null,"lat":null,"share":false,"shareTime":null,"online":true,"fv":"02.09.18","pv":"1.0","roomId":null,"tuyaUuid":null,"tuyaMigrated":false,"extra":"{}","setting":null,"sn":"R28EHS20902854","featureSet":"347440152772095","newFeatureSet":"0000000000000040","deviceStatus":{"120":0,"121":8,"122":100,"123":102,"124":203,"125":75,"126":63,"127":50,"128":0,"133":1},"silentOtaSwitch":false,"f":false},{"duid":"4Si5s3DNcsl0ATAl8e5UdI","name":"F.R.I.D.A.Y","attribute":null,"activeTime":1701809671,"localKey":"q72zeng3nPjDNVy1","runtimeEnv":null,"timeZoneId":"Europe/Berlin","iconUrl":"","productId":"ldHlB6hwVPMvdm6AdkxJv","lon":null,"lat":null,"share":false,"shareTime":null,"online":true,"fv":"02.18.30","pv":"1.0","roomId":null,"tuyaUuid":null,"tuyaMigrated":false,"extra":null,"setting":null,"sn":"R62MES33801727","featureSet":"2238601361260543","newFeatureSet":"1000004008DEFFFE","deviceStatus":{"120":0,"121":8,"122":100,"123":102,"124":202,"125":92,"126":69,"127":84,"128":0,"133":1,"134":0},"silentOtaSwitch":false,"f":false}],"receivedDevices":[],"rooms":[{"id":15575357,"name":"Treppe"},{"id":15575279,"name":"Max"},{"id":15575277,"name":"Schlafzimmer"},{"id":15575273,"name":"Zoe"},{"id":15575268,"name":"Badezimmer"},{"id":12866239,"name":"Gästebad"},{"id":12866083,"name":"Küche1"},{"id":12866080,"name":"Flur"},{"id":12827157,"name":"Flur EG"},{"id":12827153,"name":"Esszimmer"},{"id":12827149,"name":"Wohnzimmer"},{"id":12827142,"name":"Küche"}]}
`

**Comment by copystring** [comment]
Danke. Ich glaube, ich konnte jetzt einiges in Bezug der Erkennung, welche Kamerafunktionen und Mikrofonfunktionen unterstützt werden verbessern. In der neuen dev sind die Änderungen einbaut, würdest du das mal testen? https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by tritanium73** [comment]
Krass :-)

Nach einem kurzen crash nach dem Update, startete der Adapter neu.

-> Nun kam vereinzelnd noch folgende Meldungen:

![grafik](https://github.com/copystring/ioBroker.roborock/assets/144626519/ff8d4063-ee95-456e-8866-6ff0df39dedb)

Aber nun läuft er störungsfrei, ohne DP Meldungen, das DPs fehlen.... das ist doch schon mal was :-D

-> Ober diese Version alles andere auch normal durch führt würde ich über den Tag feststellen, wenn meine Scripte anlaufen...

Jetzt manuelles sauen anzustossen würde zum Ehekrach führen, da die Kids und die Frau schon schlafen ....

Soweit bist jetzt aber keine "Meldung" mehr ..... TOP !!

**Comment by copystring** [comment]
Gern. Wenn alles läuft, bitte auf close hier im Issue drücken. Danke!

**Comment by tritanium73** [comment]
Kein Problem, ich berichte morgen Abend :-)

-> Dann weiß ich mehr und natürlich mache ich dann auch das Issue zu ;-)

lg Micha

**Comment by tritanium73** [comment]
Aaaalsooo:

- Keine Fehlermeldungen heute über den Tag
- Jede Stunde eine MQTT disconnect / reconnect (das ja normal)
- Blockly Scripte funktionieren normal mit den von mir verwendeten DPs
  (Raumreinigung starten, CleaningInfosJSON, Sprachsteuerung, etc.)

Einzige Fehlermeldung die heute Abend kam, nachdem meine Frau am Q7 Max+ war:

`
<html><body>

roborock.0 | 2024-05-06 20:06:05.083 | error | Failed  to execute get_map_v1 on robot 5kt1jy0ATJPgji5k0hJAZg TypeError: The  "chunk" argument must be of type string or an instance of Buffer or  Uint8Array. Received an instance of Array    at new NodeError  (node:internal/errors:405:5)    at _write  (node:internal/streams/writable:315:13)    at Gzip.Writable.end  (node:internal/streams/writable:612:17)    at zlibBuffer  (node:zlib:128:10)    at Object.asyncBufferWrapper [as gzip]  (node:zlib:817:12)    at vacuum.getMap  (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10)    at  processTicksAndRejections (node:internal/process/task_queues:95:5)
-- | -- | -- | --



</body>
</html>
`

Ich denke das können wir aber auf eine "Frauenfehlbedienung" zurückführen :-D

-> Insofern: DANKE fürs fixen, meinetwegen kann du die /dev freigeben.

Falls noch was sein sollte, lass es mich wissen :-)

-> Ich mache den Issue dann jetzt zu ...
