### ISSUE TITLE
Kartenerstellung läuft nicht

### ISSUE THREAD

**Issue by Schnuckman79** [copystring/ioBroker.roborock#546]
**Describe the bug**  
Die Karte unter http://IP:6824/map.html bleibt leer, das Auswahlfeld fürs Gerät auch

**Expected behavior**  
Karte sollte angezeigt werden

**Screenshots & Logfiles**  
![image](https://github.com/copystring/ioBroker.roborock/assets/153268381/4ad8f667-cde5-4137-8fb8-140e7835d298)
![image](https://github.com/copystring/ioBroker.roborock/assets/153268381/09935b3b-4b0f-4908-b1ab-df717d6ba103)

**Versions:**  
 - Adapter version: akt. DEV
 - JS-Controller version: <js-controller-version> 5.0.19 
 - Node version: <node-version> v18.20.2
 - Operating system: Ubuntu/Docker (liegts am Docker? Habe den Port 6824 in den Container reingereicht)

VG Schnuckman79

**Comment by copystring** [comment]
Kein Debuglog?

**Comment by Schnuckman79** [comment]
was genau brauchst du aus dem Log? Wenn ich die Map-Seite öffne, werden keine Log-Einträge erzeugt.

Hier mal ein Log nach einem Instanz-Neustart:

<html>
<body>

roborock.0 | Zeit | info | Nachricht
-- | -- | -- | --
roborock.0 | 2024-05-10 09:13:39.668 | info | Got terminate signal TERMINATE_YOURSELF
roborock.0 | 2024-05-10 09:13:39.671 | info | terminating
roborock.0 | 2024-05-10 09:13:39.673 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2024-05-10 09:13:46.203 | info | starting. Version 0.6.4 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v18.20.2, js-controller: 5.0.19
roborock.0 | 2024-05-10 09:13:46.219 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-05-10 09:13:46.832 | info | MQTT initialized
roborock.0 | 2024-05-10 09:14:53.278 | info | Starting adapter finished. Lets go!!!!!!!
roborock.0 | 2024-05-10 09:15:03.676 | warn | Failed to execute get_fw_features on robot 5C6feZA6a9g5JPwOSPkJy1 Error: Local request with id 2 with method get_fw_features timed out after 10 seconds Local connect state: true
roborock.0 | 2024-05-10 09:15:03.681 | warn | Failed to execute get_status on robot 67ocXOx7crdmpcwJSAU4U8 Error: Local request with id 7 with method get_prop timed out after 10 seconds Local connect state: true
roborock.0 | 2024-05-10 09:15:03.682 | warn | Failed to execute get_clean_summary on robot 67ocXOx7crdmpcwJSAU4U8 Error: Local request with id 8 with method get_clean_summary timed out after 10 seconds Local connect state: true


</body>
</html>

VG
Schnuckman79

**Comment by copystring** [comment]
Versuch es bitte nochmal neu mit der aktuellen dev

**Comment by Schnuckman79** [comment]
die Logs laufen nicht mehr mit Fehlermeldungen voll (nur noch ein paar MQTT Reconnects, das sagtest du ja schon, dass das passieren kann, stört nicht weiter), aber Kartendarstellung hab ich immer noch nicht. Das Dropdown mit den Geräten bleibt leer, ebenso die grafische Karte.

**Comment by copystring** [comment]
OK. Schade, aber gut. Dein Log von oben ist leider kein Debuglog. Stellst du bitte den Adapter auf Debug um, und erstellst damit ein neues Log? Ich brauche ein komplettes Log vom Start des Adapters inkl. der ersten 1–2 Minuten Laufzeit.

**Comment by Schnuckman79** [comment]
OK, verstanden :-) Debug Log kommt:
[Roborock Debug Log.txt](https://github.com/copystring/ioBroker.roborock/files/15362855/Roborock.Debug.Log.txt)

VG
Schnuckman79

**Comment by copystring** [comment]
Schade. Da steht nichts Hilfreiches drin. Würdest du bitte die Konsole des Browsers öffnen und die Seite mit der Karte neu laden? Das, was dann in der Konsole steht, bitte ebenfalls hier einfügen.

**Comment by Schnuckman79** [comment]
OK, wir kommen der Sache näher:
[Roborock Browser Console.txt](https://github.com/copystring/ioBroker.roborock/files/15367627/Roborock.Browser.Console.txt)

VG Schnuckman79

**Comment by Schnuckman79** [comment]
...und ich kann zwar ein Zonen-Quadrat anlegen, aber weder verschieben noch verändern:
[Roborock Browser Console.txt](https://github.com/copystring/ioBroker.roborock/files/15367841/Roborock.Browser.Console.txt)

**Comment by copystring** [comment]
> OK, wir kommen der Sache näher:
> [Roborock Browser Console.txt](https://github.com/copystring/ioBroker.roborock/files/15367627/Roborock.Browser.Console.txt)
> 
> Es funktioniert in dem Moment, wenn ich Port 7906 in den Docker-Container reinreiche. Eingestellt im Adapter ist 6824. Der Adapter scheint also die Ports durcheinanderzuwirbeln.
> 
> VG Schnuckman79
> 
> 

Nein. Das stimmt so. Du brauchst beide Ports. 6824 ist das Webinterface und 7906 ist dafür da damit auch das Webinterface mit dem Adapter über websocket verbinden kann.

**Comment by Schnuckman79** [comment]
Den Punkt hab ich dann in der Doku überlesen :-) Es bleibt das Problem mit den Zonen, die nicht verschoben und vergrößert/verkleinert werden können. Und ein paar neue Fehlermeldungen im Log, dazu mache ich aber einen neuen Issue auf.

VG
Schnuckman79

**Comment by copystring** [comment]
Alles klar. Dann geht es im neuen Issue weiter.

**Comment by Schnuckman79** [comment]
Neeeiiin, nur wenn wir da auch die Zonenproblematik angehen :-)

**Comment by copystring** [comment]
Ach so. Das habe ich falsch verstanden.

**Comment by copystring** [comment]
Was steht in den logs vom Browser wenn du eine Zone verschieben willst?

**Comment by Schnuckman79** [comment]
Bin gerade unterwegs, ist aber im letzten Log enthalten gewesen…

**Comment by copystring** [comment]
OK. Dann gucke ich mir das heute Abend mal an.

**Comment by copystring** [comment]
Moment. Im letzten Log war websocket nicht verbunden. Dann kann es nicht laufen. Deshalb benötige ich ein neues Log. Wenn websocket nicht verbunden ist, gibt es keine Karte auf die eine Zone gezeichnet werden kann.

**Comment by Schnuckman79** [comment]
Dann hier nochmal frisch:
[Roborock Browser Console Zone.txt](https://github.com/copystring/ioBroker.roborock/files/15374781/Roborock.Browser.Console.Zone.txt)

**Comment by copystring** [comment]
Testest du bitte die neue dev? Sollte jetzt passen. Konnte den Fehler reproduzieren und bei mir beheben.

**Comment by Schnuckman79** [comment]
Dickes Danke, jetzt kann ich zeichnen. Habe aber während er lief zwischen meinen beiden Robotern umgeschaltet, und ich hatte das Gefühl, das Rechteck wurde von einer auf die andere Karte übertragen. Und er ist definitiv nicht da gefahren, wo er sollte. Auf jeden Fall kann ich nicht in beiden Karten unterschiedlich zeichnen und starten. Aber das kann ich erst Mittwoch ausgiebig testen, dann melde ich mich etwas konkreter. 

VG
Schnuckman79

**Comment by copystring** [comment]
Ja, ich denke es macht Sinn beim Wechsel der Saugroboter die Zonen zu löschen. Sonst würde er nicht da fahren wo das Kästchen ist.

**Comment by Schnuckman79** [comment]
So, hatte ein paar Minuten für mich mit wachen Kindern (seltene Kombination, aber wichtig für Roboter-Tests):

Ich habe die Küche als Zone markiert in der Map (oben links), hier hast du Log und das Ergebnis laut Roborock-App, das passt hinten und vorne nicht zueinander:
![24-05-21 15-46-38 3259](https://github.com/copystring/ioBroker.roborock/assets/153268381/8028ec82-d324-4337-aae5-904a4d7a1d26)
[Roborock falsche Zone.txt](https://github.com/copystring/ioBroker.roborock/files/15390859/Roborock.falsche.Zone.txt)
![Roborock Adapter Map](https://github.com/copystring/ioBroker.roborock/assets/153268381/7ca35d39-886d-43e4-8d11-67352386e4a6)

Kann es daran liegen, dass ich in der offiziellen App die Karten gedreht habe?

VG
Schnuckman79

**Comment by copystring** [comment]
Nein. Kartendrehung ist egal. Habe den Fehler bei mir aber auch. Muss ich mir angucken. Wäre mir ohne dich erstmal gar nicht aufgefallen.
