### ISSUE TITLE
Unknown block type messages in Logfile

### ISSUE THREAD

**Issue by kschwar** [copystring/ioBroker.roborock#547]
**Describe the bug**  
Unknown block type messages in Logfile

**Screenshots & Logfiles**  
[iobroker.2024-05-10.log.txt](https://github.com/copystring/ioBroker.roborock/files/15272526/iobroker.2024-05-10.log.txt)

**Versions:**  
 - Adapter version: v0.6.4
 - JS-Controller version: 5.0.19
 - Node version: v18.17.1
 - Operating system: Debian 5.10.179-1

Roborock S8 MaxV Ultra

**Comment by copystring** [comment]
Thank you for the report. To fix this, I need a debug log. Please change the logging of the adapter for Debug and attach a new log.

**Comment by kschwar** [comment]
as HTML, pls rename

[iobroker.2024-05-12.log](https://github.com/copystring/ioBroker.roborock/files/15287505/iobroker.2024-05-12.log)

**Comment by copystring** [comment]
Thank you. Unfortunately, the beginning of the log is missing.

**Comment by Decoppo** [comment]
I also have the same problem.

Adapter v0.6.4
JS 5.0.19
Node.js: v18.20.2

Roborock Qrevo MaxV

Html File:  
[iobroker.2024-05-22a.log](https://github.com/copystring/ioBroker.roborock/files/15408415/iobroker.2024-05-22a.log)

I hope that it helps.
I know there is a problem with the rooms clean_time and cleaned_area which I have been adding manually. I just haven't gotten to all of them yet.

**Comment by copystring** [comment]
Thank you for the log. I checked the config stored on the official roborock server and added the missing values to my code. Not all new values are processed. The missing blocks reported in the log are from the map. If you're missing anything in particular in the map, please let me know.

If you want, you can try out the new dev to see if it works out for you https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Decoppo** [comment]
After trying the new DEV for the last couple of days, the error messages have not returned. Just the dropped MQTT and the corresponding reconnects, but that has nothing to do with this issue. Thank you.

**Comment by copystring** [comment]
Thank you for testing!
