### ISSUE TITLE
Abtrennung von Issue 531. Dev Version lässt sich nicht installieren.

### ISSUE THREAD

**Issue by Jeeperat** [copystring/ioBroker.roborock#548]
Hallo Copystring,

ich wollte wie von dir vorgeschlagen die aktuelle DEV unter  https://github.com/copystring/ioBroker.roborock/tree/dev installieren.
Ich bekomme allerdings einen Fehler.
Log ist im Anhang.

Mein System:
Plattform: Windows
Betriebssystem: win32
Architektur: x64
CPUs: 16
Geschwindigkeit: 3194 MHz
Modell: AMD Ryzen 7 5800H with Radeon Graphics
RAM: 31.4 GB
System-Betriebszeit: 33 T. 13:15:58
Node.js: v18.19.0
time: 1715615237223
timeOffset: -120
NPM: 10.2.3
Adapter-Anzahl: 539
Aktive Instanzen: 27
Pfad: C:\ioBroker\
Betriebszeit: 33 T. 13:16:26
aktiv:

[2024-05-13T15_33_56_929Z-debug-0.log](https://github.com/copystring/ioBroker.roborock/files/15296952/2024-05-13T15_33_56_929Z-debug-0.log)

Vielen lieben Dank für deine Unterstützung und die Arbeit mit dem Adapter.
lg
Günther

**Comment by copystring** [comment]
Starte mal deinen PC/Server neu. Das hat so definitiv erstmal nichts mit dem Adapter selbst zu tun.

**Comment by Jeeperat** [comment]
Hallo, hat nichts geholfen. Aber kein Problem, wenn es nicht vom Adapter kommen kann halte dich nicht damit auf. Ich schließe mal das Ticket.
