### ISSUE TITLE
Fehlermeldung: Failed to execute get_status on...

### ISSUE THREAD

**Issue by Schnuckman79** [copystring/ioBroker.roborock#550]
**Describe the bug**  

Failed to execute get_status on robot 5C6feZA6a9g5JPwOSPkJy1 TypeError: Cannot read properties of null (reading 'send') at vacuum.getParameter (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:297:28) at Roborock.getStatus (/opt/iobroker/node_modules/iobroker.roborock/main.js:677:4)

Kommt etwa 2x pro Sekunde ins Log, Funktionseinschränkungen konnte ich erstmal nicht beobachten...

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.
[Roborock Fehlermeldung Log.txt](https://github.com/copystring/ioBroker.roborock/files/15369054/Roborock.Fehlermeldung.Log.txt)

**Versions:**  
s. Log
 - Operating system: Ubuntu / iobroker im Docker-Container

VG
Schnuckman79

**Comment by copystring** [comment]
Ja, das geht mir der aktuellen dev nicht richtig. Ich habe einen fix vorbereitet aber noch nicht hochgeladen

**Comment by copystring** [comment]
Duplicate of https://github.com/copystring/ioBroker.roborock/issues/549

**Comment by Schnuckman79** [comment]
das beruhigt mich. Solange lege ich den Adapter mal tot, weil er anscheinend irgendwie iobroker mitreißt (nach wenigen Minuten nicht mehr erreichbar).

VG
Schnuckman79
