### ISSUE TITLE
Please fix issues reported by adapterchecker / JS-CONTROLLER 6 requirments

### ISSUE THREAD

**Issue by mcm1957** [copystring/ioBroker.roborock#552]
❗ [E033] @iobroker/adapter-core 3.0.4 specified. 3.1.4 is required as minimum, 3.1.4 is recommended. Please update dependencies at [package.json](https://github.com/copystring/ioBroker.roborock/blob/master/package.json)
 ❗ [E035] @iobroker/testing 4.1.0 specified. 4.1.3 is required as minimum, 4.1.3 is recommended. Please update devDependencies at [package.json](https://github.com/copystring/ioBroker.roborock/blob/master/package.json)
 👀 [W184] "common.main" is deprecated and ignored. Please remove from [io-package.json](https://github.com/copystring/ioBroker.roborock/blob/master/io-package.json). Use "main" at [package.json](https://github.com/copystring/ioBroker.roborock/blob/master/package.json) instead.

js-controller 6 requires adaptercore 3.1.4 or newer although there are several measurements implement to try to ensure compatibility with older adapter cores. But please plan to adapt the dependency to avoid any problems.

**Comment by copystring** [comment]
Unstale

**Comment by mcm1957** [comment]
Semms to be still open

**Comment by copystring** [comment]
I fixed this a while ago here https://github.com/copystring/ioBroker.roborock/commit/8e3919c5e88b06892abdfa200aa203f1cb6ea399, but I've been really busy the past weeks to really take care of this adapter. Thank you for the patience.
