### ISSUE TITLE
Lots of warnings and errors in iobroker logs after enabling map creation

### ISSUE THREAD

**Issue by straussmarkus** [copystring/ioBroker.roborock#558]
**Describe the bug**  
iobroker log is full of warnings and entries after enabling map creation. Cannot send commans to Roborock S6, but objects appear in iobroker.

**To Reproduce**  
1. Install new instance
2. Add user and password
3. Tick enable map creation
4. hit save and check logs
5. try to send command "app_start"

**Expected behavior**  
Log does not get spammed and does not show errors. Can send commands to Roborock S6.

**Screenshots & Logfiles**  
![image](https://github.com/copystring/ioBroker.roborock/assets/116552533/39f19e2d-15b3-424b-b93c-e4aa8989cb14)
![image](https://github.com/copystring/ioBroker.roborock/assets/116552533/bfc0d765-87b7-4a2e-9fed-dedce4ae69fe)
![image](https://github.com/copystring/ioBroker.roborock/assets/116552533/46f1b14d-fd41-4486-9904-74d336733f91)

**Versions:**  
 - Adapter version: 0.6.4
 - JS-Controller version: 5.0.19
 - Node version: 18.20.2
 - Operating system: docker

**Comment by copystring** [comment]
Hi,

do these errors persist with the dev version? https://github.com/copystring/ioBroker.roborock/tree/dev
