### ISSUE TITLE
Failed to execute get_map_v1 on robot

### ISSUE THREAD

**Issue by soulfire89** [copystring/ioBroker.roborock#564]
**Describe the bug**  
Please see the log-entry below. Happens sometimes when roborock starts cleaning and sometimes by accident.

**To Reproduce**  
1. 'Start cleanup'

See error:
<html>
<body>

Failed to execute get_map_v1 on robot 3jKCp7FPqKZcaSZlOi2krL TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received an instance of Array at new NodeError (node:internal/errors:405:5) at _write (node:internal/streams/writable:315:13) at Gzip.Writable.end (node:internal/streams/writable:612:17) at zlibBuffer (node:zlib:128:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:800:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)
--

</body>
</html>
**Expected behavior**  

**Screenshots & Logfiles**  
![image](https://github.com/copystring/ioBroker.roborock/assets/75139519/1ae7724b-a834-44a2-8f91-a5c0e6476bec)

**Versions:**  
 - Adapter version: <v0.6.4>
 - JS-Controller version: <5.0.19> 
 - Node version: <v18.18.2> 
 - Operating system: Docker

**Additional context**

**Comment by steini1503** [comment]
I have the same problem with the Roborock Q Revo.

**Comment by JackDaniel007** [comment]
ich auch

Failed to execute get_map_v1 on robot 2t7w2Fu7NQgiuZTRbEgxWa TypeError: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array at _write (node:internal/streams/writable:474:13) at Gzip.Writable.end (node:internal/streams/writable:814:17) at zlibBuffer (node:zlib:130:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:819:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:67:10) at processTicksAndRejections (node:internal/process/task_queues:95:5)

Adapter version: v0.6.4
JS-Controller version: 6.0.6
Node version: v20.15.0
Operating system: Linux auf NUC

**Comment by copystring** [comment]
Wäre klasse, wenn ihr die dev testen könnten. Den Fehler habe ich bei mir reproduziert und behoben.
https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by steini1503** [comment]
Sieht gut aus, hab grad mal ne kleine Probefahrt gemacht, keine Fehlereinträge und kein Adapterabsturz

**Comment by copystring** [comment]
Danke fürs testen!
