### ISSUE TITLE
Funktion "Roborock weiß welchen Raum er schon gereinigt ist"

### ISSUE THREAD

**Issue by bruesche** [copystring/ioBroker.roborock#565]
Gibt es eine Funktion / Methode damit der Roborock nach Stop /Pause nur noch die Räum reinigt, die vor den Stop noch nicht bearbeitet wurden? 
Jetzt stoppe ich ihn aber er fängt immer von vorne an zu reinigen.

Danke für Hilfe

**Comment by copystring** [comment]
Nein. Sowas geht nicht.
