### ISSUE TITLE
Adaper crashes after start

### ISSUE THREAD

**Issue by inidona** [copystring/ioBroker.roborock#57]
ich habe meine credentials angegeben und jetzt stürzt der adapter immer ab.

<html>
<body>

roborock.0 | 56865 | 2023-02-04 15:32:00.745 | error | Cannot set properties of undefined (setting 'Authorization')
-- | -- | -- | -- | --
roborock.0 | 56865 | 2023-02-04 15:32:00.743 | error | TypeError: Cannot set properties of undefined (setting 'Authorization') at /opt/iobroker/node_modules/iobroker.roborock/main.js:133:43 at async Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:160:15)
roborock.0 | 56865 | 2023-02-04 15:32:00.740 | error | unhandled promise rejection: Cannot set properties of undefined (setting 'Authorization')
roborock.0 | 56865 | 2023-02-04 15:32:00.739 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>

**Comment by copystring** [comment]
Hallo. Es gab gerade eben noch ein Update. Ist das jetzt immer noch so?

**Comment by inidona** [comment]
Hi, ja es tritt weiterhin auf

**Comment by copystring** [comment]
OK. Habe dafür mal eine neue branch erstellt. Damit läuft es weiterhin nicht aber ich bekomme dann einen entsprechenden Fehler anstatt des Absturzes. https://github.com/copystring/ioBroker.roborock/tree/catch_errors_on_initialization
Bitte testen. Falls es nicht läuft mal bitte den Router neu starten oder irgendwie anders eine neue IP holen.

**Comment by D-Hunt3r** [comment]
Bei mir gibt es zu dem neuen Debug keine Meldung

**Comment by copystring** [comment]
> Bei mir gibt es zu dem neuen Debug keine Meldung

Ich dachte Adapter bei dir? Die Meldung kommt nur dann wenn es nicht läuft.

**Comment by D-Hunt3r** [comment]
Es läuft nicht und es kommt keine Meldung

**Comment by D-Hunt3r** [comment]
https://pastebin.com/dVCt69Fc

**Comment by inidona** [comment]
@D-Hunt3r  solche screenshots finde ich ungünstig weil nach 6 Tagen weiß niemand mehr was dein letzter Beitrag bedeutet

**Comment by copystring** [comment]
OK. Ich habe mehr logging hinzugefügt. Bitte ein neues log anhängen.

**Comment by inidona** [comment]
ich hab auch getestet, sieht gleich aus

**Comment by copystring** [comment]
Da müsste etwas mit `Init debug: SOMETHING` stehen

**Comment by inidona** [comment]
kommt nicht, die letzte Debug Message ist
<html>
<body>


debug | States connected to redis: 127.0.0.1:9000
-- | --



</body>
</html>

**Comment by copystring** [comment]
Die aktuelle branch von gerade eben hast du dir aber geholt?

**Comment by inidona** [comment]
ja, aber der crash ist ist zeile 134, deine logausgabe in 135, da kommt er nicht mehr hin

**Comment by copystring** [comment]
OK. Komme erst heute Abend dazu das anzupassen.

**Comment by inidona** [comment]
ich muss jetzt auch weg, hab aber nochmal gegoogled, ich glaube es das config.header.common ist bei dir null

die hier machen das so

https://stackoverflow.com/questions/43051291/attach-authorization-header-for-all-axios-requests
// Add a request interceptor
axios.interceptors.request.use(function (config) {
    const token = store.getState().session.token;
    config.headers.Authorization =  token;
     
    return config;
});

**Comment by copystring** [comment]
Anstatt `config.headers.common["Authorization"]` lieber `config.headers["Authorization"]`? Habe ich mal so eingestellt und bei mir getestet. Funktioniert (funktionierte aber auch schon vorher). Mal bitte testen.
Habe auch das debug log entsprechend angepasst.
https://github.com/copystring/ioBroker.roborock/tree/catch_errors_on_initialization

**Comment by D-Hunt3r** [comment]
Läuft bei mir

**Comment by copystring** [comment]
Wunderbar. Dann warte ich noch auf Rückmeldung von @inidona.

**Comment by inidona** [comment]
geht bei mir jetzt auch

**Comment by copystring** [comment]
fixed via https://github.com/copystring/ioBroker.roborock/pull/59

**Comment by copystring** [comment]
Danke fürs testen!

**Comment by copystring** [comment]
Nur als Erinnerung für mich. Das wurde hier auch so gemacht: https://gist.github.com/rovo89/dff47ed19fca0dfdda77503e66c2b7c7?permalink_comment_id=4399906#gistcomment-4399906
