### ISSUE TITLE
Diverse Fehlermeldungen

### ISSUE THREAD

**Issue by SlipKoRn88** [copystring/ioBroker.roborock#577]
Hallo,

ich habe folgende Warnungen im Log:

Failed to execute get_map_v1 on robot 2yVvvguONJ8cj0POqihvH8 Error: Local request with id 134 with method get_room_mapping timed out after 10 seconds

Failed to execute get_clean_summary on robot 2yVvvguONJ8cj0POqihvH8 Error: Local request with id 96 with method get_clean_record timed out after 10 seconds

Failed to execute get_status on robot 2yVvvguONJ8cj0POqihvH8 Error: Local request with id 12 with method get_status timed out after 10 seconds

Adapterversion v0.6.4

Weiter wird bei mir im Adapter alles abgeschnitten angezeigt:

![Roborock](https://github.com/user-attachments/assets/655a89bf-0e79-4d9f-ad47-76000cf67695)

**Comment by copystring** [comment]
Benutzt du Chrome? Wenn ja, ist der Fehler in Firefox auch so?

**Comment by SlipKoRn88** [comment]
Ich benutze Chrome. Habe es testweise im Edge getestet. Hier ist es auch so. Firefox habe ich nicht

**Comment by copystring** [comment]
Chrome und Edge nutzen die gleiche Engine. Natürlich sieht es gleich aus.

**Comment by SlipKoRn88** [comment]
Gut zu wissen. Wieder was Neues erfahren.

**Comment by copystring** [comment]
Kein Problem.

Wie oft kommen die timeouts vor? Wenn die nicht ständig auftauchen, sind die erstmal normal. Nicht alle Anfragen werden von den Server von Roborock beantwortet.

**Comment by SlipKoRn88** [comment]
Ich habe nun mal testweise Firefox installiert. Auch hier ist der Fehler im Adapter mit dem Abschneiden vorhanden.

Die Warnungen kommen manchmal nur sporadisch. Aber öfter über mehrere Tage im Sekundentakt mit 1000en Einträgen im Protokoll.

**Comment by copystring** [comment]
Stimmt. Mittlerweile ist es da auch so.
Mir ist das Problem bekannt. Siehe https://github.com/ioBroker/ioBroker.admin/issues/2013
Bisher ist das nicht gelöst. Deshalb müsste ich einen Workaround einbauen. Ich werde mich demnächst darum kümmern.

**Comment by copystring** [comment]
Würdest du bitte dir bitte https://github.com/copystring/ioBroker.roborock/tree/dev installieren und mir eine Rückmeldung geben? Müsste jetzt passen.

**Comment by SlipKoRn88** [comment]
Die Warnungen im Log scheinen nun nicht mehr aufzutauchen. Die abgeschnittenen Einstellungen im Adapter bleiben aber.

Ich habe die Browserdaten gelöscht. Adapter neu gestartet. Adapter Upload durchgeführt.

**Comment by copystring** [comment]
Sicher, dass du die aktuelle dev installiert hast?
Bei mir sieht in Chrome (links) und Firefox (rechts) alles gut aus.

![image](https://github.com/user-attachments/assets/21a5e49b-1b6b-4cda-87fb-dddee029f89a)
