### ISSUE TITLE
neue fehler meldung während dem reinigen

### ISSUE THREAD

**Issue by JackDaniel007** [copystring/ioBroker.roborock#578]
version 0.6.6 mit qrevo

roborock.0 | 2024-07-17 08:55:47.656 | error | Failed to execute get_map_v1 on robot 2t7w2Fu7NQgiuZTRbEgxWa TypeError: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array at _write (node:internal/streams/writable:474:13) at Gzip.Writable.end (node:internal/streams/writable:814:17) at zlibBuffer (node:zlib:130:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:819:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:68:11) at processTicksAndRejections (node:internal/process/task_queues:95:5)

roborock.0 | 2024-07-17 08:55:46.647 | error | Failed to execute get_map_v1 on robot 2t7w2Fu7NQgiuZTRbEgxWa TypeError: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array at _write (node:internal/streams/writable:474:13) at Gzip.Writable.end (node:internal/streams/writable:814:17) at zlibBuffer (node:zlib:130:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:819:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:68:11) at processTicksAndRejections (node:internal/process/task_queues:95:5)

roborock.0 | 2024-07-17 08:55:45.639 | error | Failed to execute get_map_v1 on robot 2t7w2Fu7NQgiuZTRbEgxWa TypeError: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array at _write (node:internal/streams/writable:474:13) at Gzip.Writable.end (node:internal/streams/writable:814:17) at zlibBuffer (node:zlib:130:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:819:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:68:11) at processTicksAndRejections (node:internal/process/task_queues:95:5)

roborock.0 | 2024-07-17 08:55:44.710 | error | Failed to execute get_map_v1 on robot 2t7w2Fu7NQgiuZTRbEgxWa TypeError: The "chunk" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Array at _write (node:internal/streams/writable:474:13) at Gzip.Writable.end (node:internal/streams/writable:814:17) at zlibBuffer (node:zlib:130:10) at Object.asyncBufferWrapper [as gzip] (node:zlib:819:12) at vacuum.getMap (/opt/iobroker/node_modules/iobroker.roborock/lib/vacuum.js:68:11) at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by copystring** [comment]
Neue Fehler? Ist doch das gleiche wie das hier: https://github.com/copystring/ioBroker.roborock/issues/564

**Comment by JackDaniel007** [comment]
ok sorry übersehen :(

**Comment by copystring** [comment]
Der Fehler besteht anscheinend weiterhin. Würdest du bitte https://github.com/copystring/ioBroker.roborock/tree/dev installieren und ein neues Debuglog hier anhängen, nachdem der Fehler erneut aufgetreten ist? Ich habe zusätzliches Debuglogging eingefügt, um dem Problem näherzukommen.

**Comment by JackDaniel007** [comment]
Kann zur Zeit leider nicht, bin auf Dienstreise in Südafrika

**Comment by copystring** [comment]
@JackDaniel007 alles klar. Kein Problem. Falls der Fehler doch wieder auftaucht, meld dich einfach hier nochmal und ich schaue mir das nochmal an und öffne das Issue wieder.
