### ISSUE TITLE
deviceStatus.camera_status"" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by cmdrtom** [copystring/ioBroker.roborock#582]
Bei meinem S7 Max Ultra werden regelmäßig Fehler gemeldet. Offenbar versucht der Adapter auf die nicht vorhandene Kamerafunktion zu zugreifen. Das geht meines Erachtens nur bei den S8 Modellen.

`roborock.0.Devices.XXXXXXXXXXXXXXXXXXXXXX.deviceStatus.rdt"" has no existing object, this might lead to an error in future versions
roborock.0.Devices.XXXXXXXXXXXXXXXXXXXXXX.deviceStatus.camera_status"" has no existing object, this might lead to an error in future versions`

**Comment by copystring** [comment]
Welche Version hast du installiert? 0.6.6?

**Comment by cmdrtom** [comment]
Aktuell ist 0.6.4 installiert.

**Comment by copystring** [comment]
Teste doch bitte mal die 0.6.6. Dort sind einige solcher Fehler behoben. Falls es bleiben sollte, bitte ein Debuglog einfügen.

**Comment by copystring** [comment]
Das macht erstmal nichts. Manchmal kommt vom Roborockserver die Karte nicht korrekt an. In diesen Fall handelt es sich ohnehin nur um die Karte vom Verlauf der Reinigungen. Es hat also nichts mit der normalen Karte zu tun.
Da das eigentliche Problem gelöst ist, schließe ich das hier.
