### ISSUE TITLE
dss Status - Dock Status Meldungen implementieren

### ISSUE THREAD

**Issue by cmdrtom** [copystring/ioBroker.roborock#583]
Ich habe im Adapter gesehen, dass der dss Parameter offenbar nicht ausgewertet wird, weil dieser unbekannt ist.

Der dss Parameter gibt die Dock Statusmeldungen der App wieder.

Der Standardstatus ischeint 2729, der Status „kein klares Wasser“ ist 2725, das Problem mit schmutzigem Wasser ist 2713, 1705 – kein Reinigungsmittel usw. Wenn man diese Werte in Binärwerte umwandelt, erhält man einen 12-Byte-Wert, z. B.:

2729 = 1010 1010 1001

Daraus folgt:

Die ersten beiden Bytes geben den Reinigungsmittelstatus an (10 – OK, 01 – Fehler)
die nächsten zwei Bytes – Wasserfilterzustand (10 – OK, 01 – Fehler)
die nächsten zwei Bytes – Staubschutzstatus (10 – OK, 01 – Fehler)
nächste zwei Bytes - Schmutzwasserzustand (10 - OK, 01 - Fehler)
nächste zwei Bytes – Zustand des sauberen Wassers (10 – OK, 01 – Fehler)
letzte zwei Bytes - keine Ahnung, da hier immer Status 01 - vielleicht aktuell nicht verwendet

Eventuell kann man das in einem späteren Release einbauen.

**Comment by copystring** [comment]
Das ist wirklich interessant. Da werde ich auf jeden Fall implantieren!

**Comment by copystring** [comment]
Würdest du für mich die neue dev testen? Die kannst du hier finden: https://github.com/copystring/ioBroker.roborock/tree/dev
Bei mir kann ich nicht testen, da ich keinen Saugroboter mit `dss` als Parameter habe.

**Comment by Matzebhv** [comment]
Bezugnehmend auf https://github.com/copystring/ioBroker.roborock/issues/584
Mit der neuen dev sind die vielen Fehlermeldungen weg.
Es verbleiben:

`2024-08-06 22:47:49.707 | warn | State "roborock.0.Devices.1npIChxxx7HKiw8gTDEyc.cleaningInfo.2" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-08-06 22:47:49.655 | warn | State "roborock.0.Devices.1npIChxxxx7HKiw8gTDEyc.cleaningInfo.1" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-08-06 22:47:49.607 | warn | State "roborock.0.Devices.1npIChxxxx47HKiw8gTDEyc.cleaningInfo.0" has no existing object, this might lead to an error in future versions`

Bei den neuen Features kann ich leider nicht mit testen, mein Sauger hat die nicht.
Gruß
Matze

**Comment by copystring** [comment]
@Matzebhv das sind aber ganz andere Meldungen, als du in anderen issue hattest. Es geht also um etwas ganz anderes.

**Comment by Matzebhv** [comment]
@copystring die waren in dem anderen issue auch mit dabei. War auch nur für dich als Merker gedacht, der Adapter funktioniert so ja wieder einwandfrei.

**Comment by c-hum** [comment]
Mit der neuesten DEV Version bekomme ich nun minütlich diese Meldungen:
```
roborock.0	2024-08-07 00:25:02.692	info	State value to set for "roborock.0.Devices.ABC.dockingStationStatus.unknown" has to be type "number" but received type "string"
 
roborock.0	2024-08-07 00:25:02.691	info	State value to set for "roborock.0.Devices.ABC.dockingStationStatus.clean_water" has to be type "number" but received type "string"
 
roborock.0	2024-08-07 00:25:02.691	info	State value to set for "roborock.0.Devices.ABC.dockingStationStatus.dirty_water" has to be type "number" but received type "string"
 
roborock.0	2024-08-07 00:25:02.691	info	State value to set for "roborock.0.Devices.ABC.dockingStationStatus.dust_container" has to be type "number" but received type "string"
 
roborock.0	2024-08-07 00:25:02.648	info	State value to set for "roborock.0.Devices.ABC.dockingStationStatus.water_filter" has to be type "number" but received type "string"
 
roborock.0	2024-08-07 00:25:02.647	info	State value to set for "roborock.0.Devices.ABC.dockingStationStatus.cleaning_solution" has to be type "number" but received type "string"
```

**Comment by copystring** [comment]
OK. Habe ich in der neuen dev behoben. Dann müsstest du unter dockingStationStatus die Werte der Dockingstation sehen. Magst du mir davon mal einen Screenshot schicken, damit ich besser einschätzen kann, ob mein Code wie erwartet funktioniert?

**Comment by c-hum** [comment]
Klaro, Screenshot anbei:
![iobroker_screen1](https://github.com/user-attachments/assets/0988de6a-f47c-40e7-b82d-660ac4eeff6d)

**Comment by copystring** [comment]
OK. Danke für das Bild. Mir gefällt nicht, wie das dargestellt wird. Ich habe die dev so angepasst, dass die Binärwerte als dezimal interpretiert werden. Dadurch lässt sich der Status besser darstellen. `{"0":"UNKNOWN", "1": "ERROR", "2": "OK"},`
Würdest du das mal eben für mich testen und einen neuen Screenshot anhängen? Das wäre echt klasse.

**Comment by c-hum** [comment]
Gerne:
![iobroker_screen2](https://github.com/user-attachments/assets/7b3546be-bd34-4725-9116-e82fd6d0016e)

**Comment by copystring** [comment]
OK. Das sieht besser aus. Denkst du, das passt so? Bei dir steht bei `water_filter` und `cleaning_solution` `UNKNOWN`, weil du die wahrscheinlich nicht in der Station hast, oder?

**Comment by c-hum** [comment]
Ja, aus meiner sicht passt es so. Danke.
Korrekt, meine Station hat keine Reinigungskartusche und - soweit ich weiß - auch keinen Wasserfilter.

**Comment by copystring** [comment]
Alles klar. Danke fürs Testen und überhaupt, das Herausfinden welche Logik hinter `dss` steht. Wäre ich lange nicht drauf gekommen. Dachte, es hat irgendwas mit einer Signalstärke zu tun 😅

**Comment by copystring** [comment]
Hallo @cmdrtom,

ich habe in der App von Roborock folgenden Code gefunden.
```
this.isUpdownWaterReady = 2 == (3 & t.dss),
this.clearWaterBoxStatus = t.dss >> 2 & 3,
this.dirtyWaterBoxStatus = t.dss >> 4 & 3,
this.dustBagStatus = t.dss >> 6 & 3,
this.waterBoxFilterStatus = t.dss >> 8 & 3,
this.cleanFluidStatus = t.dss >> 10 & 3),
```
Wenn ich mir das so angucken, sind die letzten beiden unbekannten Bytes `cleanFluidStatus`

Es stimmt aber nicht ganz zu dem, was du geschrieben hast:

```
Die ersten beiden Bytes geben den Reinigungsmittelstatus an (10 – OK, 01 – Fehler)
die nächsten zwei Bytes – Wasserfilterzustand (10 – OK, 01 – Fehler)
die nächsten zwei Bytes – Staubschutzstatus (10 – OK, 01 – Fehler)
nächste zwei Bytes - Schmutzwasserzustand (10 - OK, 01 - Fehler)
nächste zwei Bytes – Zustand des sauberen Wassers (10 – OK, 01 – Fehler)
letzte zwei Bytes - keine Ahnung, da hier immer Status 01 - vielleicht aktuell nicht verwendet
```

Ich habe so einen Saugroboter nicht, aber würdest du das nochmal mit deinem Saugroboter prüfen und mir eine Rückmeldung geben?

**Comment by copystring** [comment]
Ich habe die Werte hier mal angepasst: https://github.com/copystring/ioBroker.roborock/commit/7418c67116579d6fe898683b2183e04bf3b2ad24
Leider ein kleiner breaking change, da sich die Namen geändert haben, aber so entspricht es auch der Roborock App und wir kennen nun den unbekannten wert `isUpdownWaterReady`. Dieser steht sehr wahrscheinlich dafür, ob die Station bereit ist den Wischmop zu waschen.
