### ISSUE TITLE
Adapter funktioniert nach einigen Stunden nicht mehr

### ISSUE THREAD

**Issue by Matzebhv** [copystring/ioBroker.roborock#584]
Moin,
seit der letzten Adapterversion funktioniert der Adapter nach einer gewissen Zeit nicht mehr.
Den genauen Zeitraum habe ich leider noch nicht herausgefunden, bewegt sich aber im Bereich von wenigen Stunden.
Nach einem Adapterneustart geht es dann erstmal wieder bis zum nächsten Ausfall.

Sauger ist der S6 MaxV, Adapter inzwischen die letzte Version von Git.

`roborock.0 | 2024-07-31 22:42:03.793 | warn | Failed to execute find_me on robot 1np234DN2342442348gTDEyc Error: Local request with id 8 with method find_me timed out after 10 seconds Local connect state: undefined`

Matze

**Comment by c-hum** [comment]
Gleicher Verhalten bei mir. Adapterversion 0.6.6 über ioBroker Adapter installiert.
Sauger ist ein Qrevo Pro.
`<html>
<body>

Failed to execute find_me on robot XXX Error: Local request with id 18 with method find_me timed out after 10 seconds Local connect state: undefined
--



</body>
</html>`

**Comment by copystring** [comment]
Passiert das mit der neue dev weiterhin? Die könnt ihr hier finden: https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Matzebhv** [comment]
Moin, ich teste.

**Comment by Matzebhv** [comment]
Weiterhin wirft der Adapter jetzt die folgenden Fehler:

`roborock.0 | 2024-08-04 22:42:47.163 | warn | State "roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.cleaningInfo.2" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-08-04 22:42:47.115 | warn | State "roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.cleaningInfo.1" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-08-04 22:42:47.059 | warn | State "roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.cleaningInfo.0" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-08-04 22:42:46.628 | info | Starting adapter finished. Lets go!!!!!!!
roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.dockingStationStatus.5 is invalid: obj.common.type has an invalid value (unknown) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.dockingStationStatus.4 is invalid: obj.common.type has an invalid value (clean_water) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.dockingStationStatus.3 is invalid: obj.common.type has an invalid value (dirty_water) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.dockingStationStatus.2 is invalid: obj.common.type has an invalid value (dust_container) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.dockingStationStatus.1 is invalid: obj.common.type has an invalid value (water_filter) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1npIChDNC47HKiw8gTDEyc.dockingStationStatus.0 is invalid: obj.common.type has an invalid value (cleaning_solution) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!`

**Comment by copystring** [comment]
Ja, das macht erstmal nichts. Wird im release behoben.

**Comment by Matzebhv** [comment]
Weiterhin wirft der Adapter jetzt die folgenden Fehler:
`roborock.0 | 2024-08-04 22:42:47.163 | warn | State "roborock.0.Devices.1xxxNC47HKiw8gTDEyc.cleaningInfo.2" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-08-04 22:42:47.115 | warn | State "roborock.0.Devices.1xxxC47HKiw8gTDEyc.cleaningInfo.1" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-08-04 22:42:47.059 | warn | State "roborock.0.Devices.1xxx47HKiw8gTDEyc.cleaningInfo.0" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-08-04 22:42:46.628 | info | Starting adapter finished. Lets go!!!!!!!
roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1xxxNC47HKiw8gTDEyc.dockingStationStatus.5 is invalid: obj.common.type has an invalid value (unknown) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1xxxC47HKiw8gTDEyc.dockingStationStatus.4 is invalid: obj.common.type has an invalid value (clean_water) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1xxxHKiw8gTDEyc.dockingStationStatus.3 is invalid: obj.common.type has an invalid value (dirty_water) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1xxxNC47HKiw8gTDEyc.dockingStationStatus.2 is invalid: obj.common.type has an invalid value (dust_container) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1xxxC47HKiw8gTDEyc.dockingStationStatus.1 is invalid: obj.common.type has an invalid value (water_filter) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!
roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1xxx7HKiw8gTDEyc.dockingStationStatus.0 is invalid: obj.common.type has an invalid value (cleaning_solution) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!`

**Comment by copystring** [comment]
> Weiterhin wirft der Adapter jetzt die folgenden Fehler: `roborock.0 | 2024-08-04 22:42:47.163 | warn | State "roborock.0.Devices.1xxxNC47HKiw8gTDEyc.cleaningInfo.2" has no existing object, this might lead to an error in future versions roborock.0 | 2024-08-04 22:42:47.115 | warn | State "roborock.0.Devices.1xxxC47HKiw8gTDEyc.cleaningInfo.1" has no existing object, this might lead to an error in future versions roborock.0 | 2024-08-04 22:42:47.059 | warn | State "roborock.0.Devices.1xxx47HKiw8gTDEyc.cleaningInfo.0" has no existing object, this might lead to an error in future versions roborock.0 | 2024-08-04 22:42:46.628 | info | Starting adapter finished. Lets go!!!!!!! roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1xxxNC47HKiw8gTDEyc.dockingStationStatus.5 is invalid: obj.common.type has an invalid value (unknown) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0! roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1xxxC47HKiw8gTDEyc.dockingStationStatus.4 is invalid: obj.common.type has an invalid value (clean_water) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0! roborock.0 | 2024-08-04 22:42:15.801 | warn | Object roborock.0.Devices.1xxxHKiw8gTDEyc.dockingStationStatus.3 is invalid: obj.common.type has an invalid value (dirty_water) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0! roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1xxxNC47HKiw8gTDEyc.dockingStationStatus.2 is invalid: obj.common.type has an invalid value (dust_container) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0! roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1xxxC47HKiw8gTDEyc.dockingStationStatus.1 is invalid: obj.common.type has an invalid value (water_filter) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0! roborock.0 | 2024-08-04 22:42:15.800 | warn | Object roborock.0.Devices.1xxx7HKiw8gTDEyc.dockingStationStatus.0 is invalid: obj.common.type has an invalid value (cleaning_solution) but has to be one of number, string, boolean, array, object, mixed, json This will throw an error up from js-controller version 7.0.0!`

OK. Das hat aber erstmal nichts mit diesem Problem zu tun. Ich kümmere natürlich darum.

**Comment by copystring** [comment]
Konntest du schon weiter testen? Ist der eigentliche Fehler behoben?

**Comment by Matzebhv** [comment]
Hi, war gestern nicht online, konnte daher nicht antworten. Der Sauger ist gefahren, der Fehler scheint behoben zu sein. Ich melde mich heute Abend aber nochmal ob das kein Zufall war.

**Comment by c-hum** [comment]
Hi, bei mir hat jetzt der Aufruf "find_me" diesmal nach 12 Stunden noch funktioniert. Ich probiere es auch später nochmal, da die genaue Zeitspanne, bis es nicht mehr ging, ja nicht klar war. 

Ich bekomme nun allerdings minütlich diese Fehlermeldungen (auch wenn es wahrscheinlich hiermit nichts zu tun hat):
``` 
roborock.0	2024-08-06 08:53:02.628	warn	State "roborock.0.Devices.ABC.dockingStationStates.unknown" has no existing object, this might lead to an error in future versions
 
roborock.0	2024-08-06 08:53:02.627	warn	State "roborock.0.Devices.ABC.dockingStationStates.clean_water" has no existing object, this might lead to an error in future versions
 
roborock.0	2024-08-06 08:53:02.627	warn	State "roborock.0.Devices.ABC.dockingStationStates.dirty_water" has no existing object, this might lead to an error in future versions
 
roborock.0	2024-08-06 08:53:02.627	warn	State "roborock.0.Devices.ABC.dockingStationStates.dust_container" has no existing object, this might lead to an error in future versions
 
roborock.0	2024-08-06 08:53:02.627	warn	State "roborock.0.Devices.ABC.dockingStationStates.water_filter" has no existing object, this might lead to an error in future versions
 
roborock.0	2024-08-06 08:53:02.583	warn	State "roborock.0.Devices.ABC.dockingStationStates.cleaning_solution" has no existing object, this might lead to an error in future versions

```

**Comment by Matzebhv** [comment]
Das Problem scheint erledigt, der Sauger hat auch heute seine Runden gezogen. Bleiben die Fehlermeldungen im Log.
Gruß
Matze

**Comment by copystring** [comment]
Die Warnungen gehören zu diesem Issue https://github.com/copystring/ioBroker.roborock/issues/583. Dafür brauche ich noch Tester, da ich keinen Saugroboter mit dieser Funktion habe. Wenn du magst, kannst du dich gerne dort einklinken und die aktuelle dev neu laden. Dort habe ich einen Schreibfehler behoben und sollte jetzt ohne Warnungen durchlaufen.
