### ISSUE TITLE
fehlende Objekte Roborock QRevo Pro

### ISSUE THREAD

**Issue by sebaboehm** [copystring/ioBroker.roborock#596]
Ich habe den QRevo Pro im Einsatz und bekomme minütlich folgende Meldungen:

<img width="1337" alt="image" src="https://github.com/user-attachments/assets/81d7b3bc-c909-4578-abb2-c51d76722bbe">

**Comment by copystring** [comment]
Welche Version hast du installiert?

**Comment by sebaboehm** [comment]
0.6.4

**Comment by sebaboehm** [comment]
<img width="265" alt="image" src="https://github.com/user-attachments/assets/fdabfb73-a2d6-4f6c-a976-5e14952c4ea2">

**Comment by copystring** [comment]
Ok. Alle Fehler bezüglich des QRevo Pro sind in 0.6.6 behoben. 0.6.6 ist aber fehlerhaft. Warte bitte auf 0.6.7.
