### ISSUE TITLE
some error logs

### ISSUE THREAD

**Issue by vaaarg** [copystring/ioBroker.roborock#597]
starting. Version 0.6.6 in /opt/iobroker/node_modules/iobroker.roborock, node: v20.16.0, js-controller: 6.0.10

iobroker
Plattform: linux
RAM: 7.8 GB
Node.js: v20.16.0
NPM: 10.8.1

`<html>
<body>

roborock.0 | Zeit | debug |  
-- | -- | -- | --
roborock.0 | 2024-08-15 06:09:27.851 | warn | MQTT connection reconnect.
roborock.0 | 2024-08-15 06:09:27.850 | warn | MQTT connection close.
roborock.0 | 2024-08-15 06:09:27.837 | warn | Reconnecting mqtt client!
roborock.0 | 2024-08-15 05:09:27.851 | warn | MQTT connection reconnect.
roborock.0 | 2024-08-15 05:09:27.850 | warn | MQTT connection close.
roborock.0 | 2024-08-15 05:09:27.837 | warn | Reconnecting mqtt client!
roborock.0 | 2024-08-15 04:55:58.709 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":69,"random":264660,"timestamp":1723690558,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,116,114,117,101,125]},"crc32":2111064786}
roborock.0 | 2024-08-15 04:55:36.235 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":11,"random":688154,"timestamp":1723690536,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,102,97,108,115,101,125]},"crc32":894164302}
roborock.0 | 2024-08-15 04:51:51.229 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":75,"random":998109,"timestamp":1723690311,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,116,114,117,101,125]},"crc32":4222913258}
roborock.0 | 2024-08-15 04:51:50.723 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":79,"random":444815,"timestamp":1723690310,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,102,97,108,115,101,125]},"crc32":2731923726}
roborock.0 | 2024-08-15 04:48:44.380 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":52,"random":367511,"timestamp":1723690124,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,116,114,117,101,125]},"crc32":863922782}
roborock.0 | 2024-08-15 04:48:43.839 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":73,"random":202985,"timestamp":1723690123,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,102,97,108,115,101,125]},"crc32":3206265612}
roborock.0 | 2024-08-15 04:09:27.856 | warn | MQTT connection reconnect.
roborock.0 | 2024-08-15 04:09:27.855 | warn | MQTT connection close.
roborock.0 | 2024-08-15 04:09:27.837 | warn | Reconnecting mqtt client!
roborock.0 | 2024-08-15 03:35:04.038 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":46,"random":738547,"timestamp":1723685704,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,116,114,117,101,125]},"crc32":3447157281}
roborock.0 | 2024-08-15 03:35:02.548 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":40,"random":424372,"timestamp":1723685702,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,102,97,108,115,101,125]},"crc32":2106372568}
roborock.0 | 2024-08-15 03:09:57.251 | info | Starting adapter finished. Lets go!!!!!!!
roborock.0 | 2024-08-15 03:09:32.473 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":77,"random":322456,"timestamp":1723684172,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,116,114,117,101,125]},"crc32":896922896}
roborock.0 | 2024-08-15 03:09:27.837 | info | MQTT initialized
roborock.0 | 2024-08-15 03:09:27.383 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-08-15 03:09:27.373 | info | starting. Version 0.6.6 in /opt/iobroker/node_modules/iobroker.roborock, node: v20.16.0, js-controller: 6.0.10
roborock.0 | 2024-08-15 03:08:55.028 | info | terminating
roborock.0 | 2024-08-15 03:08:54.527 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
roborock.0 | 2024-08-15 03:08:54.526 | info | terminating
roborock.0 | 2024-08-15 03:08:54.519 | error | Exception-Code: ECONNREFUSED: connect ECONNREFUSED 192.168.178.28:58867
roborock.0 | 2024-08-15 03:08:54.519 | error | Error: connect ECONNREFUSED 192.168.178.28:58867 at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
roborock.0 | 2024-08-15 03:08:54.519 | error | unhandled promise rejection: connect ECONNREFUSED 192.168.178.28:58867
roborock.0 | 2024-08-15 03:08:54.519 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
roborock.0 | 2024-08-15 03:08:53.841 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":70,"random":943513,"timestamp":1723684133,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,102,97,108,115,101,125]},"crc32":3138761092}
roborock.0 | 2024-08-15 02:39:44.297 | warn | Unable to decode message for 6JjS9OuGMvnyj9WHHsYT53. The the device is most likely offline. data: {"version":"1.0","seq":55,"random":956126,"timestamp":1723682384,"protocol":500,"payload":{"type":"Buffer","data":[123,34,111,110,108,105,110,101,34,58,116,114,117,101,125]},"crc32":1642790994}
roborock.0 | 2024-08-15 02:39:42.659 | warn | MQTT connection reconnect.
roborock.0 | 2024-08-15 02:39:41.658 | warn | MQTT connection close.

</body>
</html>`

**Comment by copystring** [comment]
Same as this one maybe? https://github.com/copystring/ioBroker.roborock/issues/584
