### ISSUE TITLE
Nahezu sekündliche Fehlermeldung "Error writing map file"

### ISSUE THREAD

**Issue by c-hum** [copystring/ioBroker.roborock#598]
**Describe the bug**  
Aktuell bekomme ich nach Start einer Zimmerreinigung nahezu sekündlich folgende Fehlermeldung:
```
roborock.0 2024-08-17 21:10:41.913	error	Error writing map file Error: ENOENT: no such file or directory, open './test.rrmap.gz'
roborock.0 2024-08-17 21:10:39.888	error	Error writing map file Error: ENOENT: no such file or directory, open './test.rrmap.gz'
```

**To Reproduce**  
Zimmerreinigung starten.

**Versions:**  
 Ich nutze die aktuellste DEV Version von Github.

**Comment by copystring** [comment]
Hi, anscheinend hast du ein Berechtigungsproblem mit.
Die Datei wird so geschrieben: `fs.writeFile("./test.rrmap.gz", buffer, (error)`. Falls die Datei nicht existiert, wird diese damit auch automatisch erstellt. Es sei denn, die entsprechende Berechtigung fehlt.

**Comment by c-hum** [comment]
Could not reproduce it any more.

**Comment by c-hum** [comment]
Habe den Task geschlossen, nachdem keine Fehlermeldung bei der Zimmerreinigung kam und prompt eine Minute später ging es wieder los.

**Comment by copystring** [comment]
Welches Betriebssystem? Ich bin mir sehr sicher, dass es ein Problem mit den Berechtigungen ist. Das wäre dann ein Fehler in deinem System.

**Comment by c-hum** [comment]
Proxmoxx Container mit Debian GNU/Linux. Habe jetzt ganz frisch nochmal den iob fix durchgeführt Jetzt kamen bei der gleichen Zimmerreinigung keine Fehlermeldungen mehr. Vermutlich doch etwas bei mir im System. Danke.
