### ISSUE TITLE
Raumnamen werden nicht angezeigt und stündliche Warnung

### ISSUE THREAD

**Issue by bambi-arch** [copystring/ioBroker.roborock#600]
Hallo,
in der Karte werden keine Raumnamen angezeigt. In der App sind alle ersichtlich
V0.6.5 mit der neuen dev. Roborock S7

![image](https://github.com/user-attachments/assets/90ba51b7-5b95-421f-ace8-bab4d4b70a67)

Die vielen Warnmeldungen kommen jetzt nicht mehr. Jedoch jede Stunde kommen folgende Warnmeldungen
![image](https://github.com/user-attachments/assets/7513a971-4c97-458f-8a3e-9f87a777aec4)

**Comment by copystring** [comment]
Hallo,

bist du so nett in lädst die dev nochmal neu? Wir sind bei 0.6.6 in der dev. Nicht 0.6.5.

**Comment by bambi-arch** [comment]
Hallo, 
bin auf jetzt 0.6.6 dev .
Es kommen weiterhin diese Meldungen
![image](https://github.com/user-attachments/assets/53f8188f-36c9-4b8e-a0a1-9852e268b8d9)
Raumnamen weiter undefiniert.

**Comment by copystring** [comment]
Die Warnungen habe ich in https://github.com/copystring/ioBroker.roborock/commit/fc13e02ace62153e0fcffef94e079a08fd54594b auf info angepasst. Da andere Problem konnte ich mir noch nicht weiter anschauen.

**Comment by copystring** [comment]
@bambi-arch hängst du mir bitte ein Debuglog an? Dafür den Adapter auf Debug umstellen, 3 Minuten laufen lassen und das Debuglog dann hier als .txt anhängen.
