### ISSUE TITLE
Error Message beim Start von Segment Clean

### ISSUE THREAD

**Issue by mickemup** [copystring/ioBroker.roborock#601]
**Describe the bug**  
Starten von Segmentclean => Fehlermeldung

**To Reproduce**  
Starting Segment Clean

**Screenshots & Logfiles**  
![image](https://github.com/user-attachments/assets/c2e597b9-32af-4764-bf58-4d549bd3ec99)

Wie gewünscht der Log im Anhang

**Versions:**  
 - Adapter version: 0.6.6 dev
 - JS-Controller version: 6.0.9
 - Node version:  v20.16.0
 - Operating system: linux on proxmox

[log.pdf](https://github.com/user-attachments/files/16650478/log.pdf)

**Comment by copystring** [comment]
Bei den Saugrobotern, welcher Wert steht im Ordner `deviceStatus` beim Wert `map_status`? Gibt es `map_status` da überhaupt?

**Comment by mickemup** [comment]
existiert mit (Null) bei beiden Saugern.

Im Adapter habe ich " Kartenerstellung aktivieren" nicht aktiviert.
Für Segment Cleaning sollte das aber nicht einschärnkend sein, sonder nur
für Zone cleaning oder?


Am So., 18. Aug. 2024 um 21:07 Uhr schrieb copystring <
***@***.***>:

**Comment by copystring** [comment]
OK. Interessant. Gibts es noch andere Werte mit null?

**Comment by mickemup** [comment]
Jenste "Null"

![image](https://github.com/user-attachments/assets/3f580c44-ac1b-48e7-a43b-3fc15f830144)

**Comment by copystring** [comment]
Wann wurde der Wert von `state` zuletzt geschrieben?

**Comment by mickemup** [comment]
state scheint sich bei beiden Geräten brav zu aktualisieren:
![state](https://github.com/user-attachments/assets/e95c461b-1966-476b-a76b-cfeee7b82e43)

**Comment by copystring** [comment]
Würdest du dir bitte ein mal diese branch installieren? https://github.com/copystring/ioBroker.roborock/tree/Issue-%23601

Anschließend ein neues Debuglog erstellen, aber bitte als .txt anstatt .pdf. Das ist als .pdf extrem unleserlich.

**Comment by mickemup** [comment]
Guten Abend

Hier das LOG
[LOG.txt](https://github.com/user-attachments/files/16664810/LOG.txt)


Merci für deinen Support

**Comment by copystring** [comment]
Hm. Das sieht so aus, als würden alle Werte korrekt abgearbeitet. Zumindest taucht keine Fehlermeldung auf.
Besteht der Fehler mit weiterhin? Hast du vielleicht mal deinen PC, auf dem ioBroker läuft, neu gestartet?

**Comment by mickemup** [comment]
IOB gestoppt
Dann reboot vom lxc container auf proxmox
IOB gestartet

Fehler:
![image](https://github.com/user-attachments/assets/2b2f572f-b252-4546-ae48-2734c4e0fa1e)

**Comment by mickemup** [comment]
Soo habe bin nun mal zurück auf die 0.6.4 und o Wunder da funktioniert das Ganze ohne Fehlermeldung :-)

**Comment by copystring** [comment]
> Soo habe bin nun mal zurück auf die 0.6.4 und o Wunder da funktioniert das Ganze ohne Fehlermeldung :-)

Sobald ich etwas mehr Zeit habe, schaue ich mir das genauer an. Aktuell komme ich nicht dazu. Ich melde mich, wenn ich was gefunden habe.

**Comment by mickemup** [comment]
Hier das LOG:
Mit der Fehlermeldung bei "app segment clean"

![image](https://github.com/user-attachments/assets/61326cbd-4318-4d71-bdae-6fd5160fbf2c)
[LOG31.txt](https://github.com/user-attachments/files/16823708/LOG31.txt)

resume segment clean ist in dieser Version nun wieder vorhanden.

Grüsse

**Comment by copystring** [comment]
Danke für das neue Log. Ich habe besseres Logging in hochgeladen. Wärest du so nett und lädst https://github.com/copystring/ioBroker.roborock/tree/Issue-%23601 nochmal und erstellt wieder ein Debuglog der ersten drei Minuten?

**Comment by copystring** [comment]
Der Fehler ist eventuell auch behoben.

**Comment by mickemup** [comment]
[LOG9_01.txt](https://github.com/user-attachments/files/16827554/LOG9_01.txt)

Voila hier das LOG
Der Fehler ist tatsächlich nicht mehr aufgetreten :-)

**Comment by copystring** [comment]
Werden jetzt alle Werte ausgefüllt?

**Comment by mickemup** [comment]
sieht so aus:
![image](https://github.com/user-attachments/assets/b2cfe177-14eb-4728-84ad-f6188a1f042f)

**Comment by mickemup** [comment]
und hier noch ein paar fehler die ich aber mal ignoriere ;-)

![image](https://github.com/user-attachments/assets/56369313-df22-4f9b-86ba-d04d0704bd25)

**Comment by copystring** [comment]
Diese Fehler wurden nie angezeigt da genau dort der Fehler lag. Jetzt sieht man die fehlenden Attribute. Genau so hätte es vorher sein sollen. Ist also erstmal so richtig und von mir beabsichtigt. Die fehlenden Attribute kann so später implementieren. Alle anderen Werte können natürlich null sein, da nicht alle Attribute von deinem Modell unterstützt werden.

**Comment by copystring** [comment]
Ok. Wenn das eigentliche Problem gelöst ist, könnte ich deine Hilfe gebrauchen bei einem anderen Problem, welches mir in den Logs aufgefallen ist.
Wie du siehst, werden unbekannte Attribute als Error angezeigt. Das ist so gewollt, damit Nutzer des Adapters das entsprechend melden.
Leider vergaß ich, das Logging dafür korrekt zu implementieren. Dies ist der neuen Version nun umgesetzt. Wärst du so nett und lädst https://github.com/copystring/ioBroker.roborock/tree/Issue-%23601 nochmal neu und erstellst nochmal ein Debuglog für mich? Das wäre echt klasse.

**Comment by mickemup** [comment]
Gerne doch:

Voila
[LOG9_01_2.txt](https://github.com/user-attachments/files/16830273/LOG9_01_2.txt)

**Comment by copystring** [comment]
Ich denke, ich habe jetzt alles neuen Werte erwischt. Lädst du nochmal neu?

**Comment by mickemup** [comment]
Also nochmals neu installieren plus wieder ein LOG für dich?

**Comment by copystring** [comment]
Ja, bitte.

**Comment by mickemup** [comment]
Es zickt....
![image](https://github.com/user-attachments/assets/1716a4ee-17f1-46b5-9b5c-38248276897d)

**Comment by copystring** [comment]
Das kommt manchmal vor, wenn den Adapter zu oft neu startet. Warte 5 oder 10 Minuten. Ist eine Sperre der Server von Roborock..

**Comment by mickemup** [comment]
voila :-)

[LOG.txt](https://github.com/user-attachments/files/16830425/LOG.txt)

**Comment by copystring** [comment]
Ok. Da hat immer noch was gefehlt. Jetzt müsste alles passen.

**Comment by mickemup** [comment]
OK hier nochmal das neueste LOG:

[LOG9_2.txt](https://github.com/user-attachments/files/16832667/LOG9_2.txt)

**Comment by copystring** [comment]
Danke für das neue Debuglog. Leider muss ich dich nochmal beten die neue Version von https://github.com/copystring/ioBroker.roborock/tree/Issue-%23601 zu laden und nochmal ein Debuglog zu erstellen.
Du hast einen S6 Pure und einen S5 Max, richtig? Beide sind ein Sonderfall, wenn es um den Reinigungsverlauf geht. Ich möchte das sauber umsetzen, brauche aber dafür weiter deine Hilfe mit neuen Debuglogs.

**Comment by mickemup** [comment]
Voila

[LOGG.txt](https://github.com/user-attachments/files/16840853/LOGG.txt)

Ja hab die zwei genannten Typen

**Comment by copystring** [comment]
Ist im Ordner `records` unter `cleaningInfo` etwas ausgefüllt, so wie hier bei mir?
![image](https://github.com/user-attachments/assets/8567d7e3-dd25-4594-87aa-8331e78948c5)

**Comment by copystring** [comment]
Wenn nicht, versuchs bitte nochmal mit der neuen Version, aber starte sicherheitshalber mal den PC neu, auf dem ioBroker läuft. Ich habe das Gefühl, dass die neue Version nicht richtig geladen wurde.

**Comment by mickemup** [comment]
Ist bei beiden nur ein JSON drin:
![image](https://github.com/user-attachments/assets/64dc9be3-ce6e-4031-8a7f-4481e09041a3)

OK: in lösche mal den adapter, mache denn reboot und installiere nochmals...log folgt in paar mins...

**Comment by mickemup** [comment]
Voila:
[LOG09_03.txt](https://github.com/user-attachments/files/16845591/LOG09_03.txt)

Cleaning Info hat nun auch Inhalt:
![image](https://github.com/user-attachments/assets/274590b1-efd5-45cd-97dc-3947afdf24e9)

**Comment by copystring** [comment]
Top! Das Debuglog gefällt mir. Danke für das geduldige Mithelfen! Damit hast du mir sehr geholfen, den Adapter nochmal zu verbessern.
