### ISSUE TITLE
[BUG] Sind die MQTT Meldungen im Level "warn" notwendig?

### ISSUE THREAD

**Issue by Erwin40** [copystring/ioBroker.roborock#619]
### Bug Description

Hi.
Kann leider nur ein Bug-Issue aufmachen.
Die MQTT Meldungen als Warnung hauen mir das Log etwas voll.
Meiner Meinung nach sind das eigentlich Info Meldungen, da ich ja hier nichts unternehmen muss/kann :-)
Wärst du so nett und änderst das bei Gelegenheit? 😁

Anmerkung:
Zur Zeit bin ich noch beta Tester für Jarvis, und da gibt es noch viele echte Fehlermeldungen, auf die ich evt. eingehen muss.

### Steps to Reproduce

Im Stundentakt

### Expected Behavior

Verbesserungsvorschlag

### Debug Log

![grafik](https://github.com/user-attachments/assets/a5a93b57-7178-4691-8a55-989d7bfa5a9c)

### Adapter Version

beta.0.6.6

### JS-Controller Version

6.0.9

### Node.js Version

20.16.0

### Operating System

Debian GNU/Linux (Bookworm)

**Comment by copystring** [comment]
Ja, ich habe mir vor einigen Tagen vorgenommen, das auf Info zu ändern. Ich komme als nicht dazu. Vielleicht klappt's am Wochenende.

**Comment by copystring** [comment]
Fixed in https://github.com/copystring/ioBroker.roborock/commit/fc13e02ace62153e0fcffef94e079a08fd54594b. Kommt dann im neuen Release. Dauert aber noch ein bisschen. Es müssen noch ein paar Bugs behoben werden, wofür ich aktuell leider kaum Zeit habe.
