### ISSUE TITLE
[BUG] beta-0.6.6 Diverse Cleaning DP werden nicht gesetzt

### ISSUE THREAD

**Issue by Erwin40** [copystring/ioBroker.roborock#620]
### Bug Description

Datenpunkte unter `cleaningInfo` werden nicht mehr gefüllt.
![grafik](https://github.com/user-attachments/assets/2ac2744e-bc66-4e96-bf13-8f0b8ae80df2)

Der DP `roborock.0.Devices.73bFdmT97kAlNsmA7Xa5sL.consumables.dust_collection_work_times` scheint auch betroffen zu sein.

### Steps to Reproduce

Adapter neu gestartet, Raspi neu gestartet und Roboter neu gestartet.
Keine Änderung...

### Expected Behavior

Das die Werte aktualisiert werden ;-)

### Debug Log

Liegt es vielleicht auch daran?

`<html><body>

roborock.0 | 2024-08-23 12:45:31.172 | warn | State  "roborock.0.Devices.73bFdmT97kAlNsmA7Xa5sL.cleaningInfo.2" has no  existing object, this might lead to an error in future versions
-- | -- | -- | --
roborock.0 | 2024-08-23 12:45:31.118 | warn | State  "roborock.0.Devices.73bFdmT97kAlNsmA7Xa5sL.cleaningInfo.1" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-08-23 12:45:31.103 | warn | State  "roborock.0.Devices.73bFdmT97kAlNsmA7Xa5sL.cleaningInfo.0" has no  existing object, this might lead to an error in future versions
 

</body>
</html>`

### Adapter Version

beta-0.6.6

### JS-Controller Version

6.0.9

### Node.js Version

v20.17.0

### Operating System

Debian GNU/Linux (Bookworm)

**Comment by copystring** [comment]
Würdest du mal unter Records die 0 aufklappen und einen Screenshot davon hier hochladen?

**Comment by Erwin40** [comment]
Aber gerne doch:
![grafik](https://github.com/user-attachments/assets/8bdb57e9-44cd-4568-9993-b8e52044d7f4)

**Comment by copystring** [comment]
Interessant. Gab es vielleicht in der letzten Zeit für dieses Modell ein neues Firmware Update?

**Comment by Erwin40** [comment]
Nein, Firmwarestand ist 02.62.46
Ich bekomme schon lange keine Updates mehr.

**Comment by Erwin40** [comment]
Beim Start des Adapters bekomme ich übrigens noch:
![grafik](https://github.com/user-attachments/assets/87b8c2d9-ff27-4a3b-8d75-3cda3c70bb25)

**Comment by copystring** [comment]
@Erwin40 das sind die gleichen Warnungen wie vom Eröffnen des Issues?
Gibts es noch weitere Warnungen?

**Comment by copystring** [comment]
Testest du bitte die neue dev? https://github.com/copystring/ioBroker.roborock/tree/dev
Dort habe ich eine Sonderkonfiguration für den S6 MaxV erstellt. Am besten wäre es, wenn du den Adapter und Instanz löscht, dann über die dev neu installierst, während das Logging auf Debug eingestellt ist. Kommen weiterhin Fehler, dann bitte das Debuglog der ersten drei Minuten hier anhängen.

**Comment by Erwin40** [comment]
Suppi, die ersten 3 Minuten sehen gut aus. 👍 
Ich lass das mal bis morgen Früh laufen und melde mich dann noch Mal

**Comment by Erwin40** [comment]
So, mittlerweile bin ich wieder auf Info-Level.
Die Cleaninginfo 0-2 werden jetzt sauber gefüllt.
Und ich habe nur noch zwei Warn-Meldung entdeckt:
`Reconnecting mqtt client!`
Und ab und zu: `Failed to execute get_map_v1 on robot 73bFdmT97kAlNsmA7Xa5sL Error: Local request with id 8588 with method get_map_v1 timed out after 10 seconds Local connect state: true`
![grafik](https://github.com/user-attachments/assets/4fe7eb75-db63-40cb-b892-997ba3482890)

Ansonsten passt bis jetzt alles.

**Comment by copystring** [comment]
Ah ja. Da habe ich nicht daran gedacht auch `Reconnecting mqtt client!` auf Info umzustellen. Ist in der neuen dev erledigt.
`Failed to execute get_map_v1 on robot 73bFdmT97kAlNsmA7Xa5sL Error: Local request with id 8588 with method get_map_v1 timed out after 10 seconds Local connect state: true` sind erstmal normal, wenn davon nicht allzu viele auftreten. Das passiert dann, wenn der Saugroboter nicht antwortet. Solche Probleme liegen aber in der Regel am Netzwerk. Ist halt WLAN. Da kann es mal sein, dass ein Paket nicht ankommt.

**Comment by copystring** [comment]
Ich denke, wir können das hier schließen. Falls doch nochmal Probleme auftauchen sollten, eröffne doch bitte ein neues Issue. Danke für deinen Betrag, diesen Adapter weiter zu verbessern!

**Comment by Erwin40** [comment]
Immer wieder gerne. 👍 
Und ich habe zu danken, dass du dir für sowas Zeit nimmst, und auch noch unentgeltlich.
