### ISSUE TITLE
[BUG] QRevo Pro - DP "state" bleibt auf Charging(8)

### ISSUE THREAD

**Issue by holofury** [copystring/ioBroker.roborock#621]
### Bug Description

Moin,

bei meinem QRevo Pro bleibt der DP "state" auf Charging(8) stehen.
Die App sagt aber vollständig geladen.
Eigentlich sollte der DP dann doch auf Sleeping(2) springen, oder? 

### Steps to Reproduce

.

### Expected Behavior

.

### Debug Log

.

### Adapter Version

0.6.6

### JS-Controller Version

6.0.11

### Node.js Version

20.17.0

### Operating System

Ubuntu

**Comment by copystring** [comment]
Tach,

ohne Debuglog kann ich dir nicht helfen. Das ist nicht optional.

**Comment by copystring** [comment]
Unabhängig davon, kommt sleeping nur dann, wenn der Saugroboter nicht geladen wird und längere Zeit so stehen bleibt. Irgendwann geht er dann in den Energiesparmodus.

**Comment by holofury** [comment]
Wie oben geschrieben, ist der Saugroboter vollständig geladen und dies seit mehreren Stunden.
Der DP bleibt immer auf Charging(8).

Ich ergänze nach dem nächsten Reinigungs- und Ladevorgang das Debuglog...

**Comment by copystring** [comment]
> Wie oben geschrieben, ist der Saugroboter vollständig geladen und dies seit mehreren Stunden.
> Der DP bleibt immer auf Charging(8).

Natürlich bleibt das so, weil der Saugroboter weiterhin am aufladen ist. `Sleeping` kommt nur dann, wenn der Saugroboter länger nicht in der Station steht.

**Comment by holofury** [comment]
Danke, jetzt hab ich meinen Fehler gefunden.
Hatte in Jarvis Charging(8) bei meinem alten Saugroboter falsch übersetzt...
Tatsächlich bleibt der auch auf Charging(8) stehen...

Ich mach dann hier mal zu, sorry 🤦‍♂️
