### ISSUE TITLE
[BUG] 0.6.7 -> Fehlender Parameter (Debug Log anbei)

### ISSUE THREAD

**Issue by tritanium73** [copystring/ioBroker.roborock#630]
### Bug Description

Nach Adapter Start, kommen ERROR Logs mit fehlenden Parametern.

### Steps to Reproduce

ein einfacher Adapter Start reicht

### Expected Behavior

keine Fehlermeldungen ? :-)

### Debug Log

[roborock.txt](https://github.com/user-attachments/files/16880729/roborock.txt)

### Adapter Version

0.6.7

### JS-Controller Version

6.0.11

### Node.js Version

20.17.0

### Operating System

ubuntu

**Comment by copystring** [comment]
0.6.8 kommt jetzt. Da müsste es behoben sein. Gibst du mir bitte eine Rückmeldung?

**Comment by tritanium73** [comment]
Mit 0.6.8 ist das Verhalten verschwunden.. !
