### ISSUE TITLE
Unsported attributes bei Roborock S8 MaxV Ultra (roborock.vacuum.a97)

### ISSUE THREAD

**Issue by seh-len** [copystring/ioBroker.roborock#643]
### Bug Description

Bei der aktuellen Version 0.6.11 tauchen eine Menge error message bzgl. "unsupported attributes" auf.
Der Roboter unterstützt auch eine RGB-Kamera, es gibt im Objektbaum jedoch kein Kamera-Attribut.
Ich hoffe das angehängte Debug-Log hilft dir bei der Implementierung.
[roborock.log](https://github.com/user-attachments/files/16923325/roborock.log)

### Steps to Reproduce

siehe oben

### Expected Behavior

siehe oben

### Debug Log

siehe oben

### Adapter Version

0.6.11

### JS-Controller Version

6.0.11

### Node.js Version

20.17.0

### Operating System

Debian 6.1.99-1

**Comment by seh-len** [comment]
btw. muss das eigentlich wirklich mit log-level "error" reported werden? Ich hätte das viel lieber als Warnung, der Adapter läuft ja weiter...
Aktuell bleibt mir leider nur, den Adapter zu beenden, da es mir ansonsten das Log mit unzähligen Meldungen "verstopft".

**Comment by copystring** [comment]
Bisher hatte ich niemanden, der den S8 MaxV hatte. Jetzt konnte ich mit deinem Log einfache Unterstützung für diesen Saugroboter einbauen.
Wäre klasse, wenn du dir mal die dev von hier installieren würdest: https://github.com/copystring/ioBroker.roborock/tree/dev

Um auf deine Frage zurückzukommen: Ich habe mich bewusst für Error anstatt Warnung entschieden, da ich glaube, dass ansonsten kaum jemand sich hier bezüglich neuer Parameter melden würde.

**Comment by seh-len** [comment]
Das ging ja schnell, vielen Dank.
Ich habe die dev-Version installiert.
Ich habe weiterhin unsupported attributes. Anbei ein neues debug.log.
[roborock.log](https://github.com/user-attachments/files/16923593/roborock.log)

> Ich habe mich bewusst für Error anstatt Warnung entschieden, da ich glaube, dass ansonsten kaum jemand sich hier bezüglich neuer Parameter melden würde.
Ich glaube, dass das eher dazu führt, dass sich noch mehr User wünschen, für bestimmte Adapter das Logging komplett zu unterbinden, wenn man ihnen die Möglichkeit nimmt, das Logging temporär zu filtern.
Das Standardloglevel für Adapter ist Info, mit Warn sollten die Meldungen also immer noch präsent genug sein.

**Comment by copystring** [comment]
OK. Ich kann deine Argumentation nachvollziehen. Ich habe das Logging auf warn umgestellt.
Neue Fixes für deinen Saugroboter sind ebenfalls hochgeladen.
Nur für `home_sec_status` und `home_sec_enable_password` noch nicht. Dafür brauche ich ein mal den Inhalt von deinem `HomeData`

**Comment by seh-len** [comment]
> Nur für home_sec_status und home_sec_enable_password noch nicht. Dafür brauche ich ein mal den Inhalt von deinem HomeData

Ich finde kein Objekt mit dem Namen HomeData, was brauchst du da genau?

**Comment by copystring** [comment]
Das kannst du hier finden: 
![image](https://github.com/user-attachments/assets/cf8ea7c0-f2ea-4fc6-976b-4d0286e26f8b)

**Comment by seh-len** [comment]
Ich hab ihn dir als PN geschickt

**Comment by copystring** [comment]
Das mit `home_sec_status` und `home_sec_enable_password` funktioniert doch anders als ich dachte. Ich habe meinen Code angepasst. Hast du jetzt noch Warnungen oder Error im Log?

**Comment by seh-len** [comment]
nein, vielen Dank!

**Comment by copystring** [comment]
Top. Danke für deinen Beitrag den Adapter zu verbessern!

**Comment by seh-len** [comment]
[roborock.0.log](https://github.com/user-attachments/files/17330810/roborock.0.log)
