### ISSUE TITLE
Please fix testing and node requirements

### ISSUE THREAD

**Issue by mcm1957** [copystring/ioBroker.roborock#657]
### Bug Description

- [x] Testing must be performed at ALL supported platforms (linux, windows, macos). So please add macos to testing matrix (#656).
If macos cannot be supported (tests at PR fail), please state this restriction at README.md and add list of supported os at io-package.json:
https://github.com/ioBroker/ioBroker.js-controller/blob/4e8189ae010aadbff9fb35ee4b3861b5e29992c4/schemas/io-package.json#L1335

- [x] Testing includes nodeJs 18 while package.json states node 20 minimum. Please fix (remove node 18 from tests)
https://github.com/copystring/ioBroker.roborock/blob/f386a193146cbdecb0f1b889055134bbd9d89b9b/package.json#L23

- [x] Please note that encreasing the need for a higher nodJs version should be reflected by an minor version bump at least.

- [x] Please add requirment encrease to nodeJs 20 to README.md

### Steps to Reproduce

see description

### Expected Behavior

see description

### Debug Log

n/a

### Adapter Version

Github f386a193146cbdecb0f1b889055134bbd9d89b9b

### JS-Controller Version

n/a

### Node.js Version

n/a

### Operating System

n/a

**Comment by copystring** [comment]
Hi,

I have changed the requirement of Node.js 20 while ago in 0.6.6. See this: https://github.com/copystring/ioBroker.roborock/commit/dee4b758b77d9893148faabeaf3e4deb1c401051#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
Is this sufficient in the changelog, or do I need to mention the requirement of Node.js 20.x elsewhere in the README?
I did not bump the minor version back then. How should I handle the situation now?

I removed Node.js 18.x from tests: https://github.com/copystring/ioBroker.roborock/commit/6cef36e855f6ea8663ab993bd43a88e54410fccf

**Comment by mcm1957** [comment]
The note at changelog is sufficient. I did not check back so long. My Fault sorry.

Changin minor after so many releases does not make sense. 

So everything is finde after Adaption nodejs at Tests.

**Comment by copystring** [comment]
Does this look ok? https://github.com/copystring/ioBroker.roborock/blob/dev/.github/workflows/test-and-release.yml
18.x can stay for lint and deploy? I tried it with 20.x but it fails missing some libraries.

**Comment by mcm1957** [comment]
I'll check later. I'm just leasing for about 5 days of holiday. Normally lintcand deploy should work with all node versions. Butckeep it as it is for now.  Please post a link of the failed run if available.

**Comment by copystring** [comment]
I fixed lint and deploy by changing the canvas lib to @napi-rs/canvas. I wanted to change the canvas lib a while ago anyway. Also, canvas didn't seem to work with node 22.x and the [3.0.0-rc2](https://www.npmjs.com/package/canvas/v/3.0.0-rc2) wasn't working on Windows.
See this run: https://github.com/copystring/ioBroker.roborock/pull/660
I guess all issues are solved. Waiting for your feedback when you have time. I don't mind waiting for after your holiday!

**Comment by mcm1957** [comment]
unstale

**Comment by copystring** [comment]
Am I missing something here? Please let me know. Unfortunately this adapter cannot work with node 18.x because of some library dependencies.

**Comment by mcm1957** [comment]
Ok, just realised that you asked me to check your changes. I missed this. I only reacted to the stale bot.

Will come back soon.

**Comment by mcm1957** [comment]
OK,
Test pass at linux and windows at node 20 and node 22.
engines clause is set to >= 20 --> OK

So the only thing I would recommend is to add a sall not to README.md that macos is not supportrted.
