### ISSUE TITLE
[BUG] Lot of warn messages and no camera stream working

### ISSUE THREAD

**Issue by TPPTim** [copystring/ioBroker.roborock#661]
### Bug Description

Hello and first of all,
Thank you so much for this great adapter - it's really impressive!

In the loggin file I receive a lot and also different warning messages.

### Steps to Reproduce

I installed the adapter and set it up with my app login details and local IP address for 'Hostname/IP for camera stream'.
All data points are created and I can basically control my Roborock S8.

### Expected Behavior

1.) I do not expect too many warnings. Some data points are missing.
2.) None of the 4 camera streams work. Not via PC browser, mobile browser or rtsp via VLC player. 

### Debug Log

[iobroker.2024-09-25.log](https://github.com/user-attachments/files/17129083/iobroker.2024-09-25.log)

### Adapter Version

0.6.4

### JS-Controller Version

6.0.9

### Node.js Version

 v18.19.0

### Operating System

Debian 11

**Comment by copystring** [comment]
Hi, please Install 0.6.15 from the latest repo and install nodejs 20.x. nodejs 18.x isn't supported by this adapter anymore.
If you still see errors, let me know.

**Comment by copystring** [comment]
Also, did you enter the pin in the options of the adapter? The pin you assigned in the app on your phone.

**Comment by copystring** [comment]
You need to set the pin in your phone app, then enter the pin you set there in the options of the adapter.
![image](https://github.com/user-attachments/assets/1c396636-39cb-4574-b0e6-27e440de10ef)

**Comment by TPPTim** [comment]
Thanks for your fast responce. I checked the whole app and I can´t find the option to set the PIN.
Are we talking about the 'Roborock' or the 'Xiaomi Home' app?

**Comment by copystring** [comment]
The roborock app. Which robot do you have?

**Comment by TPPTim** [comment]
That is strange. I have the Roborock S8.

**Comment by copystring** [comment]
S8 doesn't have a camera usable by the adapter.

**Comment by TPPTim** [comment]
Oh OK 🤦🏻‍♂️ That is the reason for.
Do you know what the camera in front of the robot is for?

**Comment by copystring** [comment]
It's used to detect obstacles.

**Comment by TPPTim** [comment]
OK, thank you very much!
One more thing. I installed now the newest Version JS 20x as you mentioned.
I still receive those two errors.

<html><body>

roborock.0 | 2024-09-30 15:36:27.370 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.repeat" has no  existing object, this might lead to an error in future versions
-- | -- | -- | --
roborock.0 | 2024-09-30 15:36:27.370 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.replenish_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-09-30 15:35:27.325 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.repeat" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-09-30 15:35:27.325 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.replenish_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-09-30 15:34:27.303 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.repeat" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-09-30 15:34:27.302 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.replenish_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-09-30 15:33:27.389 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.repeat" has no  existing object, this might lead to an error in future versions
roborock.0 | 2024-09-30 15:33:27.389 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.replenish_mode"  has no existing object, this might lead to an error in future versions
roborock.0 | 2024-09-30 15:32:27.303 | warn | State  "roborock.0.Devices.mxdkyM82nKK10fsZ6U0HG.deviceStatus.repeat" has no  existing object, this might lead to an error in future versions


</body>
</html>
