### ISSUE TITLE
[BUG] Adapter lässt sich nicht mehr Updaten oder Installieren

### ISSUE THREAD

**Issue by KallAdam** [copystring/ioBroker.roborock#662]
### Bug Description

Adapter lässt sich nicht mehr Updaten oder Installieren. 
siehe Debug Log

### Steps to Reproduce

Adapter komplett gelöscht... selbes Problem. Apadter lässt sich nicht mehr installieren. Probiert bis Version 0.6.9

### Expected Behavior

...

### Debug Log

$ iobroker upgrade roborock@0.6.15 --debug

Update roborock from @0.6.14 to @0.6.15

NPM version: 10.8.2

Installing iobroker.roborock@0.6.15... (System call)

> canvas@3.0.0-rc2 install> prebuild-install -r napi || node-gyp rebuild

prebuild-install warn install No prebuilt binaries found (target=7 runtime=napi arch=arm64 libc= platform=linux)

gyp info it worked if it ends with ok

gyp info using node-gyp@10.1.0

gyp info using node@20.17.0 | linux | arm64

gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3

gyp info spawn args [gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',

gyp info spawn args 'binding.gyp',gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/canvas/build/config.gypi',gyp info spawn args '-I',gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',gyp info spawn args '-I',gyp info spawn args '/home/iobroker/.cache/node-gyp/20.17.0/include/node/common.gypi',gyp info spawn args '-Dlibrary=shared_library',gyp info spawn args '-Dvisibility=default',gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/20.17.0',gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/20.17.0/<(target_arch)/node.lib',gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/canvas',gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]

gyp info spawn make

SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node

COPY Release/canvas-postbuild.node

CXX(target) Release/obj.target/canvas/src/backend/Backend.o

CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o

CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o

CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o

CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o

CXX(target) Release/obj.target/canvas/src/Backends.o

CXX(target) Release/obj.target/canvas/src/Canvas.o

In file included from /home/iobroker/.cache/node-gyp/20.17.0/include/node/node.h:76, from /home/iobroker/.cache/node-gyp/20.17.0/include/node/node_buffer.h:25, from ../src/Canvas.cc:23:/home/iobroker/.cache/node-gyp/20.17.0/include/node/node_version.h:103: warning: "NAPI_VERSION" redefined 103 | #define NAPI_VERSION 9 | In file included from /home/iobroker/.cache/node-gyp/20.17.0/include/node/node_api.h:12, from ../../node-addon-api/napi.h:13, from ../src/backend/Backend.h:6, from ../src/Canvas.h:7, from ../src/Canvas.cc:3:/home/iobroker/.cache/node-gyp/20.17.0/include/node/js_native_api.h:20: note: this is the location of the previous definition 20 | #define NAPI_VERSION 8 |

CXX(target) Release/obj.target/canvas/src/CanvasGradient.o

CXX(target) Release/obj.target/canvas/src/CanvasPattern.o

CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o

CXX(target) Release/obj.target/canvas/src/closure.o

CXX(target) Release/obj.target/canvas/src/color.o

CXX(target) Release/obj.target/canvas/src/Image.o

In file included from /home/iobroker/.cache/node-gyp/20.17.0/include/node/node.h:76, from /home/iobroker/.cache/node-gyp/20.17.0/include/node/node_buffer.h:25, from ../src/Image.cc:11:

/home/iobroker/.cache/node-gyp/20.17.0/include/node/node_version.h:103: warning: "NAPI_VERSION" redefined 103 | #define NAPI_VERSION 9 | In file included from /home/iobroker/.cache/node-gyp/20.17.0/include/node/node_api.h:12, from ../../node-addon-api/napi.h:13, from ../src/CanvasError.h:4, from ../src/Image.h:6, from ../src/Image.cc:3:/home/iobroker/.cache/node-gyp/20.17.0/include/node/js_native_api.h:20: note: this is the location of the previous definition 20 | #define NAPI_VERSION 8 |

../src/Image.cc: In member function ‘cairo_status_t Image::loadSVGFromBuffer(uint8_t*, unsigned int)’:../src/Image.cc:1141:3: error: ‘rsvg_handle_get_intrinsic_size_in_pixels’ was not declared in this scope; did you mean ‘rsvg_handle_get_intrinsic_dimensions’? 1141 | rsvg_handle_get_intrinsic_size_in_pixels(_rsvg, &d_width, &d_height); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | rsvg_handle_get_intrinsic_dimensions

make: *** [canvas.target.mk:161: Release/obj.target/canvas/src/Image.o] Error 1make: Leaving directory '/opt/iobroker/node_modules/canvas/build'

gyp ERR! build error

gyp ERR! System Linux 6.1.21-v8+

gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"gyp ERR! cwd /opt/iobroker/node_modules/canvasgyp ERR! node -v v20.17.0gyp ERR! node-gyp -v v10.1.0gyp ERR! not ok

npm error code 1

npm error path /opt/iobroker/node_modules/canvasnpm error command failednpm error command sh -c prebuild-install -r napi || node-gyp rebuild

npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-09-25T18_19_56_925Z-debug-0.log

upload [13] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [12] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/en/translations.json i18n/en/translations.json application/json

upload [11] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/es/translations.json i18n/es/translations.json application/json

upload [10] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/fr/translations.json i18n/fr/translations.json application/json

upload [9] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/it/translations.json i18n/it/translations.json application/json

upload [8] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/nl/translations.json i18n/nl/translations.json application/json

upload [7] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/pl/translations.json i18n/pl/translations.json application/json

upload [0] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/words.js words.js application/javascript

Process exited with code 0

### Adapter Version

0.6.15

### JS-Controller Version

6.0.11

### Node.js Version

v20.17.0

### Operating System

Raspberry Pi 4 Model B

**Comment by DonToben** [comment]
Same problem with update from 0.6.14 to 0.6.15 on my side 
`iobroker upgrade roborock@0.6.15 --debug

Update roborock from @0.6.14 to @0.6.15

NPM version: 10.8.1

Installing iobroker.roborock@0.6.15... (System call)

> canvas@3.0.0-rc2 install> prebuild-install -r napi || node-gyp rebuild

prebuild-install warn install No prebuilt binaries found (target=7 runtime=napi arch=arm libc= platform=linux)

gyp info it worked if it ends with ok

gyp info using node@20.16.0 | linux | arm

gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"

gyp info spawn /usr/bin/python3

gyp info spawn args [gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',gyp info spawn args 'binding.gyp',

gyp info spawn args '-f',gyp info spawn args 'make',gyp info spawn args '-I',gyp info spawn args '/opt/iobroker/node_modules/iobroker.roborock/node_modules/canvas/build/config.gypi',gyp info spawn args '-I',gyp info spawn args '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',gyp info spawn args '-I',gyp info spawn args '/home/iobroker/.cache/node-gyp/20.16.0/include/node/common.gypi',gyp info spawn args '-Dlibrary=shared_library',gyp info spawn args '-Dvisibility=default',gyp info spawn args '-Dnode_root_dir=/home/iobroker/.cache/node-gyp/20.16.0',gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',gyp info spawn args '-Dnode_lib_file=/home/iobroker/.cache/node-gyp/20.16.0/<(target_arch)/node.lib',gyp info spawn args '-Dmodule_root_dir=/opt/iobroker/node_modules/iobroker.roborock/node_modules/canvas',gyp info spawn args '-Dnode_engine=v8',gyp info spawn args '--depth=.',gyp info spawn args '--no-parallel',gyp info spawn args '--generator-output',gyp info spawn args 'build',gyp info spawn args '-Goutput_dir=.'gyp info spawn args ]

gyp info spawn make

SOLINK_MODULE(target) Release/obj.target/canvas-postbuild.node

COPY Release/canvas-postbuild.node

CXX(target) Release/obj.target/canvas/src/backend/Backend.o

CXX(target) Release/obj.target/canvas/src/backend/ImageBackend.o

CXX(target) Release/obj.target/canvas/src/backend/PdfBackend.o

CXX(target) Release/obj.target/canvas/src/backend/SvgBackend.o

CXX(target) Release/obj.target/canvas/src/bmp/BMPParser.o

../src/bmp/BMPParser.cc: In member function ‘void BMPParser::Parser::parse(uint8_t*, int, uint8_t*)’:../src/bmp/BMPParser.cc:186:16: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare] 186 | E(ptr - data > imgdOffset, "image data overlaps with another structure"); | ~~~~~~~~~~~^~~~~~~~~~~~../src/bmp/BMPParser.cc:10:25: note: in definition of macro ‘E’ 10 | #define E(cond, msg) if(cond) return setErr(msg) | ^~~~

../src/bmp/BMPParser.cc:201:27: warning: comparison of integer expressions of different signedness: ‘uint32_t’ {aka ‘unsigned int’} and ‘int’ [-Wsign-compare] 201 | E(ptr - data + imgdSize > len, "not enough image data"); | ~~~~~~~~~~~~~~~~~~~~~~^~~~~../src/bmp/BMPParser.cc:10:25: note: in definition of macro ‘E’ 10 | #define E(cond, msg) if(cond) return setErr(msg) | ^~~~

CXX(target) Release/obj.target/canvas/src/Backends.o

CXX(target) Release/obj.target/canvas/src/Canvas.o

In file included from /home/iobroker/.cache/node-gyp/20.16.0/include/node/node.h:76, from /home/iobroker/.cache/node-gyp/20.16.0/include/node/node_buffer.h:25, from ../src/Canvas.cc:23:/home/iobroker/.cache/node-gyp/20.16.0/include/node/node_version.h:103: warning: "NAPI_VERSION" redefined 103 | #define NAPI_VERSION 9 | In file included from /home/iobroker/.cache/node-gyp/20.16.0/include/node/node_api.h:12, from ../../../../node-addon-api/napi.h:13, from ../src/backend/Backend.h:6, from ../src/Canvas.h:7, from ../src/Canvas.cc:3:/home/iobroker/.cache/node-gyp/20.16.0/include/node/js_native_api.h:20: note: this is the location of the previous definition 20 | #define NAPI_VERSION 8 |

CXX(target) Release/obj.target/canvas/src/CanvasGradient.o

CXX(target) Release/obj.target/canvas/src/CanvasPattern.o

CXX(target) Release/obj.target/canvas/src/CanvasRenderingContext2d.o

CXX(target) Release/obj.target/canvas/src/closure.o

CXX(target) Release/obj.target/canvas/src/color.o

CXX(target) Release/obj.target/canvas/src/Image.o

In file included from /home/iobroker/.cache/node-gyp/20.16.0/include/node/node.h:76, from /home/iobroker/.cache/node-gyp/20.16.0/include/node/node_buffer.h:25,

from ../src/Image.cc:11:/home/iobroker/.cache/node-gyp/20.16.0/include/node/node_version.h:103: warning: "NAPI_VERSION" redefined 103 | #define NAPI_VERSION 9 | In file included from /home/iobroker/.cache/node-gyp/20.16.0/include/node/node_api.h:12, from ../../../../node-addon-api/napi.h:13, from ../src/CanvasError.h:4, from ../src/Image.h:6, from ../src/Image.cc:3:/home/iobroker/.cache/node-gyp/20.16.0/include/node/js_native_api.h:20: note: this is the location of the previous definition 20 | #define NAPI_VERSION 8 |

../src/Image.cc: In member function ‘cairo_status_t Image::loadSVGFromBuffer(uint8_t*, unsigned int)’:../src/Image.cc:1141:3: error: ‘rsvg_handle_get_intrinsic_size_in_pixels’ was not declared in this scope; did you mean ‘rsvg_handle_get_intrinsic_dimensions’? 1141 | rsvg_handle_get_intrinsic_size_in_pixels(_rsvg, &d_width, &d_height); | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | rsvg_handle_get_intrinsic_dimensions

make: *** [canvas.target.mk:161: Release/obj.target/canvas/src/Image.o] Fehler 1make: Verzeichnis „/opt/iobroker/node_modules/iobroker.roborock/node_modules/canvas/build“ wird verlassen

gyp ERR! build error

gyp ERR! stack Error: `make` failed with exit code: 2gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)

gyp ERR! System Linux 6.1.21-v8+

gyp ERR! cwd /opt/iobroker/node_modules/iobroker.roborock/node_modules/canvasgyp ERR! node -v v20.16.0gyp ERR! node-gyp -v v10.1.0

gyp ERR! not ok

npm error code 1

npm error path /opt/iobroker/node_modules/iobroker.roborock/node_modules/canvas

npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-09-27T04_56_05_599Z-debug-0.log

upload [13] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [0] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/words.js words.js application/javascript

Process exited with code 0`

**Comment by copystring** [comment]
Ja, das liegt an der canvas 3.0.0-rc2 Bibliothek. Ich habe in der dev bereits eine alternative gefunden. Diese konnte ich bisher nur unter Windows testen. Dort lief die canvas 3.0.0-rc2 ebenfalls nicht.
Die Bibliothek ist für die Kartenerstellung notwendig. Also wenn ihr die dev testen würdet, wäre echt klasse. Ich suche Tester mit amd64 Linux und arm Linux (Raspberry Pi etc.) https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by KallAdam** [comment]
Leider kommt folgende Fehlermeldung:
Raspberry Pi 4 Model B


$ iobroker url https://github.com/copystring/ioBroker.roborock/tree/dev --host raspberrypi --debug

install copystring/ioBroker.roborock#dev

NPM version: 10.8.2

Installing copystring/ioBroker.roborock#dev... (System call)

npm error code 128npm error An unknown git error occurred

npm error command git --no-replace-objects ls-remote ssh://git@github.com/copystring/ioBroker.roborock.gitnpm error ssh: Could not resolve hostname github.com: No address associated with hostnamenpm error fatal: Could not read from remote repository.npm errornpm error Please make sure you have the correct access rightsnpm error and the repository exists.

npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-09-29T00_57_08_443Z-debug-0.log

npm error code 128npm error An unknown git error occurrednpm error command git --no-replace-objects ls-remote ssh://git@github.com/copystring/ioBroker.roborock.gitnpm error ssh: Could not resolve hostname github.com: No address associated with hostnamenpm error fatal: Could not read from remote repository.npm errornpm error Please make sure you have the correct access rightsnpm error and the repository exists.npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-09-29T00_57_08_443Z-debug-0.loghost.raspberrypi Cannot install copystring/ioBroker.roborock#dev: 128

ERROR: Process exited with code 25

**Comment by copystring** [comment]
Hast du kein Internet?

**Comment by DonToben** [comment]
Bei mir hat der Update jetzt mit dem Dev funktioniert.

iobroker url https://github.com/copystring/ioBroker.roborock/tree/dev --host raspberrypi --debug

install copystring/ioBroker.roborock#dev

NPM version: 10.8.1

Installing copystring/ioBroker.roborock#dev... (System call)

> esbuild@0.23.1 postinstall> node install.js

120 packages are looking for funding run `npm fund` for details

upload [13] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/de/translations.json i18n/de/translations.json application/json

upload [4] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/uk/translations.json i18n/uk/translations.json application/json

upload [3] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/i18n/zh-cn/translations.json i18n/zh-cn/translations.json application/json

upload [2] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/jsonConfig.json jsonConfig.json application/json

upload [1] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/roborock.png roborock.png image/png

upload [0] roborock.admin /opt/iobroker/node_modules/iobroker.roborock/admin/words.js words.js application/javascript

Update "system.adapter.roborock.0"

Process exited with code 0

**Comment by copystring** [comment]
@DonToben läuft bei dir die Kartenerstellung?

**Comment by DonToben** [comment]
Ja scheint jetzt zu funktionieren. Das ging in der Vergangenheit mit meinem Pi 4 nie ...

**Comment by KallAdam** [comment]
> https://github.com/copystring/ioBroker.roborock/tree/dev

Unangenehm, das kann sogar sein das der Router zufällig genau nach versuchten Adapter Update einen Neustart machte.  
Hab es leider im Halbschlaf nicht bemerkt da der Adapter auf V15 am ende stand. 

Heute morgen nun nochmal den Adapter gelöscht und versucht über: dev zu installieren. 
Adapter wird aber leider nicht installiert. 


$ iobroker url https://github.com/copystring/ioBroker.roborock/tree/dev --host raspberrypi --debug

install copystring/ioBroker.roborock#dev

NPM version: 10.8.2

Installing copystring/ioBroker.roborock#dev... (System call)

npm warn deprecated npmlog@7.0.1: This package is no longer supported.

npm warn deprecated are-we-there-yet@4.0.2: This package is no longer supported.

npm warn deprecated gauge@5.0.2: This package is no longer supported.

> go2rtc-static@1.9.4 install> node dist/install.js

> esbuild@0.23.1 postinstall> node install.js

added 2 packages, removed 16 packages, and changed 286 packages in 1m

251 packages are looking for funding run `npm fund` for details

npm warn deprecated npmlog@7.0.1: This package is no longer supported.npm warn deprecated are-we-there-yet@4.0.2: This package is no longer supported.npm warn deprecated gauge@5.0.2: This package is no longer supported.

host.raspberrypi Cannot install copystring/ioBroker.roborock#dev: 0

ERROR: Process exited with code 25

**Comment by copystring** [comment]
Welche nodejs Version hast du?

**Comment by KallAdam** [comment]
Node.js: v20.17.0
NPM: 10.8.2

**Comment by copystring** [comment]
Ok. Daran kann es nicht liegen. Leider geht aus dem Log nicht hervor, woran es liegt. Ich habe an der dev noch etwas angepasst, magst du es nochmal probieren?

**Comment by KallAdam** [comment]
leider keine Veränderung. 
User DonToben hatte NPM: 10.8.1 node.js20.16.0  mal sehen wenn einige User ebenfalls bei NPM: 10.8.2 Node.js: v20.17.0 sind und auch Probleme melden. 

Problem trat plötzlich ohne Änderung an meinem System auf.

**Comment by copystring** [comment]
Lässt sich die 0.6.16 installieren?

**Comment by KallAdam** [comment]
Leider alles wie bei den älteren Versionen. 
Unter dem Reiter Adapter ist dieser scheinbar installiert. 
Aber unter Instanzen ist weiterhin nichts vorhanden.
Wieder beides probiert: 1. Update von V15 auf V16 2. Neuinstallation des Adapters.   
![Adapter](https://github.com/user-attachments/assets/2b6132d7-883b-4ea3-9043-6c6d5339d1f7)
![Instanzen](https://github.com/user-attachments/assets/06a87998-db2d-4cfc-a275-486184a7fee3)

@DonToben wenn du Lust und Zeit hast, kannst du ja eventuell mal den Adapter komplett löschen und neu installieren ob es dann auch funktioniert.

**Comment by copystring** [comment]
Was passiert, wenn du über die drei Punkte eine neue Instanz hinzufügst?

**Comment by KallAdam** [comment]
Nochmal alles gelöscht ... nun ist er unter Instanzen vorhanden!

**Comment by copystring** [comment]
Problem ist also gelöst?

**Comment by KallAdam** [comment]
Grade eben nochmals zur Sicherheit gelöscht und installiert ... funktioniert! 
Danke dir für deinen Support. Ich sende dir eine kleine PayPal donation :-)

**Comment by copystring** [comment]
Alles klar. Danke fürs Testen und die Spende! Falls was sein sollte, meld dich gern nochmal.
