### ISSUE TITLE
[BUG] Roborock Qrevo S hinzufügen

### ISSUE THREAD

**Issue by seaspotter** [copystring/ioBroker.roborock#664]
### Bug Description

Hi,
ich hab einen neuen Roborock Qrevo S und er wirft mir aus "This robot roborock.vacuum.a104 is not fully supported just yet. " Helfe gerne mit Logs und Testen beim Hinzufügen.
Habe mal die dev Versions des Adapters installiert und unten Debug Log und HomeData mit hinzugefügt. Wenn du noch was brauchst einfach bescheid geben

### Steps to Reproduce

-

### Expected Behavior

-

### Debug Log

[HomeData.txt](https://github.com/user-attachments/files/17174289/HomeData.txt)
[debug_log.txt](https://github.com/user-attachments/files/17174290/debug_log.txt)

### Adapter Version

v0.6.15 (dev)

### JS-Controller Version

 6.0.11

### Node.js Version

v20.16.0

### Operating System

Ubuntu server

**Comment by copystring** [comment]
Danke für das Debuglog. Testest du bitte https://github.com/copystring/ioBroker.roborock/tree/dev und lädst ein neues Debuglog hoch?

**Comment by seaspotter** [comment]
Ja na klar, hier mit aktuellem dev der Debug Log:

[debug_log_20240929.txt](https://github.com/user-attachments/files/17180815/debug_log_20240929.txt)

**Comment by copystring** [comment]
Da war ein Fehler in meinem Code. Würdest du dev bitte nochmal neu laden? Leider hat der Adapter zum Saugroboter keine Verbindung hergestellt. Sollte jetzt aber klappen.

**Comment by seaspotter** [comment]
Kein Ding, hier nochmal das Log, ich hab den Start vllt nicht ganz mitbekommen, reicht das, wenn nicht muss ich ihn nochmal machen den log.
[debug_log_20240929_02.txt](https://github.com/user-attachments/files/17180884/debug_log_20240929_02.txt)

**Comment by copystring** [comment]
OK. Sieht besser aus. Ich denke, dass ich alle oder die meisten Werte eingebaut hat. Tauchen noch Warnungen im Debuglog der neuen dev auf?

**Comment by seaspotter** [comment]
Schaut gut aus, anbei nochmal n Debuglog.

Die einzigen Warnungen sind noch in den einzelnen cleaninginfo records


roborock.0
2024-09-29 21:38:03.407	warn	State "roborock.0.Devices.N3Y835WXR9z18xOKqTDA6.cleaningInfo.records.0.map_flag" has no existing object, this might lead to an error in future versions

roborock.0
2024-09-29 21:38:03.412	warn	State "roborock.0.Devices.N3Y835WXR9z18xOKqTDA6.cleaningInfo.records.0.cleaned_area" has no existing object, this might lead to an error in future versions

Und dann noch eine:

	State "roborock.0.Devices.N3Y835WXR9z18xOKqTDA6.dockingStationStatus.isUpdownWaterReady" has no existing object, this might lead to an error in future versions

[debug_log_20240929_03.txt](https://github.com/user-attachments/files/17180945/debug_log_20240929_03.txt)

**Comment by copystring** [comment]
Jetzt müsste alles da sein. Schaust du nochmal nach?

**Comment by seaspotter** [comment]
Schaut bestens aus, ich hab keine Warnungen mehr, Map geht auch :)
Ich danke dir für die schnelle Umsetzung.

[debug_log_20240929_04.txt](https://github.com/user-attachments/files/17180982/debug_log_20240929_04.txt)

**Comment by copystring** [comment]
Danke auch! Falls noch etwas ein sollte, meld dich gerne nochmal.
