### ISSUE TITLE
ERROR: Process exited with code 12

### ISSUE THREAD

**Issue by MischaI** [copystring/ioBroker.roborock#67]
$ iobroker add roborock auto --host raspberrypi --debug
host.raspberrypi Unknown packetName roborock. Please install packages from outside the repository using npm!
ERROR: Process exited with code 12
ERROR: Process exited with code 12

![image](https://user-images.githubusercontent.com/34452995/217025946-31660d7d-5b43-43bc-acef-01efb091648a.png)
```
host.raspberrypi | 2023-02-06 17:22:40.120 | info | iobroker exit 12
host.raspberrypi | 2023-02-06 17:22:39.085 | error | iobroker host.raspberrypi Unknown packetName roborock. Please install packages from outside the repository using npm!
host.raspberrypi | 2023-02-06 17:22:36.513 | info | iobroker add roborock auto --host raspberrypi --debug
host.raspberrypi | 2023-02-06 17:22:36.513 | debug | Incoming Host message cmdExec
```

**Comment by copystring** [comment]
Okay. What are you trying to tell me with this issue?

**Comment by MischaI** [comment]
1. Adapter mit URL installieren
2. Adapter löschen
3. Adapter installieren aus dem Reiter Adapter
4. Kommt dann diese Meldung.
Erst nach dem Neustart findet man unter Reiter Adapter Roborock nicht mehr. Eventuell ein Bug von meiner Installation.

Anscheinend war irgend ein Bug, dass es mit erlaubt hat, Adapter zu installieren.

Somit erledigt und kann geschlossen werden.
