### ISSUE TITLE
[BUG] Q Revo und S7 Max Ultra: Objekte bekommen keine Updates mehr, keine Steuerung möglich

### ISSUE THREAD

**Issue by Schnuckman79** [copystring/ioBroker.roborock#672]
### Bug Description

Moin!

Seit Umstellung meines Internetanschlusses auf DS Lite bekommt der Adapter keine Verbindung mehr zu meinen beiden Robotern. iobroker läuft in einem Docker-Container auf einem Ubuntu Server, der wiederum hängt im gleichen lokalen Netz wie die Roboter. Bis zur Umstellung auf DS Lite hat alles funktioniert. Adapter-Reinstall hat nichts gebracht,

Anbei das Log ab Adapter-Start:

### Steps to Reproduce

Umstellung des Internetanschlusses auf DS Lite

### Expected Behavior

Adapter sollte sich mit den Robotern verbinden können.

### Debug Log

`<html>
<body>

roborock.0 | 2024-10-02 16:39:55.442 | debug | Updating HomeData with homeId: 3087582
-- | -- | -- | --
roborock.0 | 2024-10-02 16:39:55.451 | debug | Latest data requested
roborock.0 | 2024-10-02 16:39:55.504 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_status request!
roborock.0 | 2024-10-02 16:39:55.504 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:55.537 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_consumable request!
roborock.0 | 2024-10-02 16:39:55.537 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:55.539 | debug | homedata successfully updated
roborock.0 | 2024-10-02 16:39:55.594 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_carpet_mode request!
roborock.0 | 2024-10-02 16:39:55.594 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:55.652 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_carpet_clean_mode request!
roborock.0 | 2024-10-02 16:39:55.653 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:55.731 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_water_box_custom_mode request!
roborock.0 | 2024-10-02 16:39:55.731 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:58.788 | debug | Latest data requested
roborock.0 | 2024-10-02 16:39:58.796 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_status request!
roborock.0 | 2024-10-02 16:39:58.796 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:58.844 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_consumable request!
roborock.0 | 2024-10-02 16:39:58.844 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:58.934 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_carpet_mode request!
roborock.0 | 2024-10-02 16:39:58.935 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:58.986 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_carpet_clean_mode request!
roborock.0 | 2024-10-02 16:39:58.987 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:39:59.037 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_water_box_custom_mode request!
roborock.0 | 2024-10-02 16:39:59.037 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:01.022 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_prop request!
roborock.0 | 2024-10-02 16:40:01.022 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:01.109 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_prop request!
roborock.0 | 2024-10-02 16:40:01.109 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:19.742 | debug | Cloud message with protocol 102 and id undefined received. Result: undefined
roborock.0 | 2024-10-02 16:40:55.443 | debug | Updating HomeData with homeId: 3087582
roborock.0 | 2024-10-02 16:40:55.451 | debug | Latest data requested
roborock.0 | 2024-10-02 16:40:55.510 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_status request!
roborock.0 | 2024-10-02 16:40:55.511 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:55.538 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_consumable request!
roborock.0 | 2024-10-02 16:40:55.539 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:55.540 | debug | homedata successfully updated
roborock.0 | 2024-10-02 16:40:55.605 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_carpet_mode request!
roborock.0 | 2024-10-02 16:40:55.605 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:55.656 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_carpet_clean_mode request!
roborock.0 | 2024-10-02 16:40:55.656 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:55.707 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_water_box_custom_mode request!
roborock.0 | 2024-10-02 16:40:55.707 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:58.789 | debug | Latest data requested
roborock.0 | 2024-10-02 16:40:58.801 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_status request!
roborock.0 | 2024-10-02 16:40:58.802 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:58.856 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_consumable request!
roborock.0 | 2024-10-02 16:40:58.856 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:58.908 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_carpet_mode request!
roborock.0 | 2024-10-02 16:40:58.909 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:58.971 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_carpet_clean_mode request!
roborock.0 | 2024-10-02 16:40:58.971 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:40:59.028 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_water_box_custom_mode request!
roborock.0 | 2024-10-02 16:40:59.028 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:41:01.004 | debug | Adapter not connect locally to robot 5C6feZA6a9g5JPwOSPkJy1. Not sending for method get_prop request!
roborock.0 | 2024-10-02 16:41:01.005 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:41:01.007 | debug | Adapter not connect locally to robot 67ocXOx7crdmpcwJSAU4U8. Not sending for method get_prop request!
roborock.0 | 2024-10-02 16:41:01.007 | debug | Size of message queue: 0
roborock.0 | 2024-10-02 16:41:53.333 | info | Got terminate signal TERMINATE_YOURSELF
roborock.0 | 2024-10-02 16:41:53.335 | info | terminating
roborock.0 | 2024-10-02 16:41:53.337 | debug | Plugin sentry destroyed
roborock.0 | 2024-10-02 16:41:53.337 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2024-10-02 16:41:53.839 | info | terminating
roborock.0 | 2024-10-02 16:42:03.811 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
roborock.0 | 2024-10-02 16:42:03.852 | debug | Objects client ready ... initialize now
roborock.0 | 2024-10-02 16:42:03.853 | debug | Objects create System PubSub Client
roborock.0 | 2024-10-02 16:42:03.854 | debug | Objects create User PubSub Client
roborock.0 | 2024-10-02 16:42:03.935 | debug | Objects client initialize lua scripts
roborock.0 | 2024-10-02 16:42:03.940 | debug | Objects connected to redis: 127.0.0.1:9001
roborock.0 | 2024-10-02 16:42:03.991 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
roborock.0 | 2024-10-02 16:42:04.013 | debug | States create System PubSub Client
roborock.0 | 2024-10-02 16:42:04.014 | debug | States create User PubSub Client
roborock.0 | 2024-10-02 16:42:04.098 | debug | States connected to redis: 127.0.0.1:9000
roborock.0 | 2024-10-02 16:42:04.158 | debug | Plugin sentry Initialize Plugin (enabled=true)
roborock.0 | 2024-10-02 16:42:04.540 | info | starting. Version 0.6.15 (non-npm: copystring/ioBroker.roborock#f386a193146cbdecb0f1b889055134bbd9d89b9b) in /opt/iobroker/node_modules/iobroker.roborock, node: v20.16.0, js-controller: 6.0.11
roborock.0 | 2024-10-02 16:42:04.554 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-10-02 16:42:05.131 | info | MQTT initialized
roborock.0 | 2024-10-02 16:42:05.132 | debug | RoomIDs debug: {"7475877":"Schlafzimmer","7475878":"Schlafzimmer1","7475879":"Badezimmer","7475884":"Küche","7475888":"Wohnzimmer","7475901":"Arbeitszimmer","7475908":"Gästebad","7475913":"Gästezimmer","7475919":"Hauswirtschaftsraum","7475945":"Flur","7482841":"Kinderzimmer","13289571":"Levke","13291302":"Zimmerchen","13291309":"HWR"}
roborock.0 | 2024-10-02 16:42:05.133 | debug | Processing scene [{"id":982383,"name":"Vollreinigung","param":"{\"triggers\":[],\"action\":{\"type\":\"S\",\"items\":[{\"id\":1,\"type\":\"CMD\",\"name\":\"\",\"entityId\":\"5C6feZA6a9g5JPwOSPkJy1\",\"param\":\"{\\\"id\\\":1,\\\"method\\\":\\\"do_scenes_app_start\\\",\\\"params\\\":[{\\\"fan_power\\\":102,\\\"water_box_mode\\\":202,\\\"mop_mode\\\":300,\\\"mop_template_id\\\":300,\\\"repeat\\\":0,\\\"source\\\":101}]}\",\"finishDpIds\":[130]}]},\"matchType\":\"NONE\"}","enabled":true,"extra":null,"type":"WORKFLOW"},{"id":150673,"name":"Vollreinigung","param":"{\"triggers\":[],\"action\":{\"type\":\"S\",\"items\":[{\"id\":1,\"type\":\"CMD\",\"name\":\"\",\"entityId\":\"67ocXOx7crdmpcwJSAU4U8\",\"param\":\"{\\\"id\\\":1,\\\"method\\\":\\\"do_scenes_app_start\\\",\\\"params\\\":[{\\\"fan_power\\\":102,\\\"water_box_mode\\\":202,\\\"mop_mode\\\":300,\\\"mop_template_id\\\":300,\\\"repeat\\\":0,\\\"source\\\":101}]}\",\"finishDpIds\":[130]}]},\"matchType\":\"NONE\"}","enabled":true,"extra":null,"type":"WORKFLOW"}]
roborock.0 | 2024-10-02 16:42:05.134 | debug | Processing scene param {"triggers":[],"action":{"type":"S","items":[{"id":1,"type":"CMD","name":"","entityId":"5C6feZA6a9g5JPwOSPkJy1","param":"{\"id\":1,\"method\":\"do_scenes_app_start\",\"params\":[{\"fan_power\":102,\"water_box_mode\":202,\"mop_mode\":300,\"mop_template_id\":300,\"repeat\":0,\"source\":101}]}","finishDpIds":[130]}]},"matchType":"NONE"}
roborock.0 | 2024-10-02 16:42:05.135 | debug | Updating HomeData with homeId: 3087582
roborock.0 | 2024-10-02 16:42:05.169 | debug | Processing scene param {"triggers":[],"action":{"type":"S","items":[{"id":1,"type":"CMD","name":"","entityId":"67ocXOx7crdmpcwJSAU4U8","param":"{\"id\":1,\"method\":\"do_scenes_app_start\",\"params\":[{\"fan_power\":102,\"water_box_mode\":202,\"mop_mode\":300,\"mop_template_id\":300,\"repeat\":0,\"source\":101}]}","finishDpIds":[130]}]},"matchType":"NONE"}
roborock.0 | 2024-10-02 16:42:05.196 | debug | homedata successfully updated
roborock.0 | 2024-10-02 16:42:05.205 | debug | MQTT connection connected {"cmd":"connack","retain":false,"qos":0,"dup":false,"length":2,"topic":null,"payload":null,"sessionPresent":false,"returnCode":0}.
roborock.0 | 2024-10-02 16:42:12.267 | debug | Robot key: roborock.vacuum.a75
roborock.0 | 2024-10-02 16:42:12.661 | debug | Supported features of robot 5C6feZA6a9g5JPwOSPkJy1 - roborock.vacuum.a75: {"isWashThenChargeCmdSupported":1,"isDustCollectionSettingSupported":true,"isSupportedDrying":1,"isShakeMopSetSupported":true,"isVideoMonitorSupported":true,"isVideoSettingSupported":true,"isCarpetSupported":true,"isPhotoUploadSupported":false,"isAvoidCollisionSupported":true,"isCornerCleanModeSupported":true,"isCameraSupported":false,"isSupportSetSwitchMapMode":true,"isMopForbiddenSupported":true,"isShakeMopStrengthSupported":true,"isWaterBoxSupported":true,"isCustomWaterBoxDistanceSupported":true,"isBackChargeAutoWashSupported":true,"isAvoidCarpetSupported":true,"isVoiceControlSupported":["roborock.vacuum.a27"],"isElectronicWaterBoxSupported":[],"isCleanRouteFastModeSupported":true,"isVideoLiveCallSupported":false}
roborock.0 | 2024-10-02 16:42:50.206 | debug | Robot key: roborock.vacuum.a27
roborock.0 | 2024-10-02 16:42:50.485 | debug | Supported features of robot 67ocXOx7crdmpcwJSAU4U8 - roborock.vacuum.a27: {"isWashThenChargeCmdSupported":1,"isDustCollectionSettingSupported":true,"isSupportedDrying":1,"isShakeMopSetSupported":true,"isVideoMonitorSupported":true,"isVideoSettingSupported":true,"isCarpetSupported":true,"isPhotoUploadSupported":true,"isAvoidCollisionSupported":true,"isCornerCleanModeSupported":false,"isCameraSupported":true,"isSupportSetSwitchMapMode":true,"isMopForbiddenSupported":true,"isShakeMopStrengthSupported":true,"isWaterBoxSupported":true,"isCustomWaterBoxDistanceSupported":false,"isBackChargeAutoWashSupported":false,"isAvoidCarpetSupported":true,"isVoiceControlSupported":["roborock.vacuum.a27"],"isElectronicWaterBoxSupported":[],"isCleanRouteFastModeSupported":true,"isVideoLiveCallSupported":true}

</body>
</html>`

### Adapter Version

0.6.15

### JS-Controller Version

6.0.11

### Node.js Version

20.16.0

### Operating System

Ubuntu

**Comment by copystring** [comment]
Würdest du mal die dev testen? Den Link dazu kannst du hier finden: https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by Schnuckman79** [comment]
der Dev-Link ergab einen 404 error, hab aber das neue Release .16 gesehen und installiert. Damit läuft es wieder, besten Dank!

VG
Schnuckman79

**Comment by copystring** [comment]
Ja, habe die dev gestern im Zuge des neuen Release gelöscht.
