### ISSUE TITLE
vis adapter Roborock 0.6.16

### ISSUE THREAD

**Issue by Sandweier** [copystring/ioBroker.roborock#675]
### Bug Description

Now I`m a owner of a Roborock S8. Trying to use the VIS adapter, roborock 0.6.16, was at first succesfull, but now I´m getting after a interval time of 60sec. always the following warning: 
![Screenshot 2024-10-14 144303](https://github.com/user-attachments/assets/04aab3a2-5814-4dd6-88d2-a6509e716d49)
Since that time I`m not able to control the robot in the right direction.

### Steps to Reproduce

Due that the failure comes over night don`t know?

### Expected Behavior

I assume if the failure gones, as it was at once, everything works fine

### Debug Log

![Screenshot 2024-10-14 144303](https://github.com/user-attachments/assets/58d98910-c8e7-4de6-a896-dddcc05d5613)

### Adapter Version

0.6.16

### JS-Controller Version

6.0.11

### Node.js Version

20.18.0

### Operating System

IObroker

**Comment by copystring** [comment]
Hi,

thanks for the report. Does the problem go away when you restart your router?

**Comment by Sandweier** [comment]
Hi copystring, many thanks for your fast response.
This morning I tried to use the Robo . What should I say. It works!!!
A look in the protocol view shows  the described bug no longer exists.
Don‘t ask me why, seems that over night something reloaded or as you mentioned receiving a new rooter Ip solve these problem?!. Many thanks

**Comment by copystring** [comment]
This is rate limiting of the roborock server. IPs get blocked if too many requests are made.
