### ISSUE TITLE
Missing States

### ISSUE THREAD

**Issue by freakyfreaky** [copystring/ioBroker.roborock#677]
### Bug Description

Hallo zusammen,

ich habe den Adapter von mihome-vacuum zu Roborock gewechselt.
Hierbei ist mir aufgefallen dass einige Status Variablen fehlen

Aktuell verfügbare Statis (mihome-vacuum adapter)
![image](https://github.com/user-attachments/assets/47b3493e-9bb9-4642-95e0-c3b68f65b943)

Betroffen Saugertypen:
QRevo S
S8 Pro Ultra

### Steps to Reproduce

Install Adapter
Config Instanz
Look at Objects

### Expected Behavior

Alle Status Meldungen sind verfügbar

### Debug Log

N/A

### Adapter Version

0.6.16

### JS-Controller Version

7.0

### Node.js Version

v20.18.0

### Operating System

Linux

**Comment by copystring** [comment]
Hast du hier mal geguckt?
![image](https://github.com/user-attachments/assets/4d3203fa-48f8-48b6-a2d1-edae6776a077)

**Comment by freakyfreaky** [comment]
Ja habe Ich. Aber wie du sieht fehlen folgende Angaben:

- Water Filter Lifetime
- Sensors Lifetime

**Comment by copystring** [comment]
Ok. Lädst du bitte dein HomeData hoch?

**Comment by freakyfreaky** [comment]
Wenn du mir verrätst wo Ich den finde, lässt sich das sicher arrangieren

**Comment by copystring** [comment]
Das kannst du hier finden
![image](https://github.com/user-attachments/assets/fb0bfa36-2a6e-4dbc-ad54-0b7b6c7ff2c1)

**Comment by freakyfreaky** [comment]
[HomeData.json](https://github.com/user-attachments/files/17384266/HomeData.json)

**Comment by copystring** [comment]
Der ioBroker.mihome-vacuum arbeitet anders als meiner. Beide werte sind vorhanden, aber ich reiche die Namen, die von Roborock kommen einfach nur durch und verändere diese nicht, während ioBroker.mihome-vacuum die Namen ändert.

Water Filter Lifetime: filter_work_time
Sensors Lifetime: sensor_dirty_time

Die Werte kommen so als Stunden direkt vom Server von Roborock. Man könnte jetzt eine Logik einbauen, mit der eine Prozentzahl ausgerechnet werden könnte.
Vielleicht hast du gesehen, dass in der Handyapp für diese beiden Werte keine Prozentzahlen angezeigt werden. Das ist deshalb so, weil der Server dafür keine Prozentzahlen bereitstellt, sondern nur die Betriebsstunden.

**Comment by freakyfreaky** [comment]
Alles klar. Danke für die Klarstellung.
Welcher Datenpunkt wäre der für die "Reinigungsbürste vom Dock"

> Die Werte kommen so als Stunden direkt vom Server von Roborock. Man könnte jetzt eine Logik einbauen, mit der eine Prozentzahl ausgerechnet werden könnte.

Wenn das zu kompliziert wird, dann kann ich das auch per script als eigenen Datenpunkt anlegen.
Denn aktuell würde die VIS "Blödsinn" anzeigen, da die Werte steigen, statt fallen ;)
![image](https://github.com/user-attachments/assets/9de257b3-2ca9-45ea-8017-1bb2d733eb71)

**Comment by copystring** [comment]
Hast du einen Ordner `dockingStationStatus` unter den Objekten vom Adapter? Dort wären die Werte der Dockingstation. Falls nicht, bitte ein Debuglog vom Start des Adapters und die ersten 3 Minuten danach hier als .txt-Datei anhängen.

**Comment by fL4sH3r** [comment]
Hallo zusammen, mir werden leider auch nicht alle Datenpunkte mit Inhalt gefüllt. 
Die Prozente fehlen und der Wassertankfilter wird mir leider auch nicht angezeigt.
![image](https://github.com/user-attachments/assets/96219cf3-00b1-4867-9d93-45da0addd949)
