### ISSUE TITLE
[BUG] Reset Consumables

### ISSUE THREAD

**Issue by freakyfreaky** [copystring/ioBroker.roborock#678]
### Bug Description

Beim Klick auf die Buttons oder beim Setzen deren Status lassen sich die Verbrauchsmaterialien nicht zurücksetzen.

Betroffen Saugertypen:
QRevo S
S8 Pro Ultra

### Steps to Reproduce

Click Button to Reset

### Expected Behavior

Consunambles lassen sich zurücksetzen

### Debug Log

Keiner Verfügbar

### Adapter Version

0.6.16

### JS-Controller Version

7.0

### Node.js Version

v20.18.0

### Operating System

Linux

**Comment by copystring** [comment]
![image](https://github.com/user-attachments/assets/8c535d02-826b-4a57-b783-f39dee318924)

**Comment by freakyfreaky** [comment]
Ja habe Ich.
Der Wert wird hierbei nicht zurückgesetzt

**Comment by copystring** [comment]
Habe den Fehler gefunden und behoben. Siehe https://github.com/copystring/ioBroker.roborock/commit/551debc9626817edbf83effec4123e99911ec04c.
Fix kommt dann im neuen Release.
