### ISSUE TITLE
Warning shower due to missing object

### ISSUE THREAD

**Issue by Sandweier** [copystring/ioBroker.roborock#680]
### Bug Description

Hi copystring,
using the new version 0.6.17 I receive after restart of the Roborock IOB adapter and after Roborock is back in the charging station the following warning shower in my Log-file!? Is there any reason  and/or did I a mistake during parametrization?
![Screenshot 2024-10-16 112618](https://github.com/user-attachments/assets/19f56263-2792-43f7-a5f4-0f808dd7428e)

### Steps to Reproduce

1) restart IOB broker adapter
2)give the command to Robot move back to Dockand wait up to 5sec.
Have the a look to the log file

### Expected Behavior

No longer warnings to fill up my log

### Debug Log

![Screenshot 2024-10-16 112618](https://github.com/user-attachments/assets/c5ca7794-49bb-4fda-a3c0-bfd213981cea)

### Adapter Version

0.6.17

### JS-Controller Version

6.0.11

### Node.js Version

20.18.0

### Operating System

IOBroker

**Comment by copystring** [comment]
Hi,

where is the debug log?

**Comment by Sandweier** [comment]
Here we go!
[iobroker.2024-10-16.log](https://github.com/user-attachments/files/17394845/iobroker.2024-10-16.log)

**Comment by copystring** [comment]
Thanks. Fixed via https://github.com/copystring/ioBroker.roborock/commit/a4c7d38b4e300bddfdc0f10893f6a8f869977f28. Coming in the next release soon. Thanks for your help to make this adapter better!

**Comment by Sandweier** [comment]
Mandy thanks for your support, for me it was a pleasure helping to improve these adapter
