### ISSUE TITLE
[BUG] Get Map Error

### ISSUE THREAD

**Issue by seaspotter** [copystring/ioBroker.roborock#681]
### Bug Description

Ich bekomme mit dem aktuellen 0.6.17 Adapter immer folgende Fehlermeldungen zu der Map, die waren vorher nicht da.

![log](https://github.com/user-attachments/assets/b7086fdf-6241-4863-a012-89e85414fb0b)

### Steps to Reproduce

Latest Adapter

### Expected Behavior

no error

### Debug Log

![log](https://github.com/user-attachments/assets/5fb748e8-d52c-4107-8593-cfcfa5a9575d)

### Adapter Version

v0.6.17

### JS-Controller Version

7.0.0

### Node.js Version

v20.16.0

### Operating System

Ubuntu server

**Comment by copystring** [comment]
Hi,

mit welcher Version waren die Warnungen nicht da?
Wo ist das Debuglog?

**Comment by seaspotter** [comment]
Mit der 0.6.16 und vorher hatte ich diese Warnungen nicht, erst seit gestern seit dem Update auf die 0.6.17

[debuglog.txt](https://github.com/user-attachments/files/17394697/debuglog.txt)

**Comment by copystring** [comment]
In dem Debuglog sind keine dieser Warnungen zu sehen.

**Comment by seaspotter** [comment]
Das ist richtig aber sie kommen unregelmäßig über den Tag verteilt immer wieder, heute verteilt teilweise auch nicht nur die Map Warnungen sondern auch andere. Die hatte ich die letzten Tage nicht.

**Comment by copystring** [comment]
Eine Unregelmäßigkeit kommt sehr wahrscheinlich nicht vom Adapter. Hattest du die 0.6.16 nochmal getestet?

**Comment by copystring** [comment]
Es gibt Konstellationen, bei denen deine IP gesperrt wird. Die ID in der Regel nicht.
Dann würden aber gar keine Anfragen mehr herausgehen und nicht nur sporadisch die für die Karte.

**Comment by seaspotter** [comment]
Also ich habs jetzt mal ein paar Tage beobachtet, es gibt Tage da kommen gar keine Warnmeldungen, dann gibt es immer wieder Warnmeldungen mit dem Hinweis vorher das das Gerät offline ist und dann kommen Warnmeldungen wo der Hinweis das Gerät offline ist, nicht dabei ist.
Ich kann es nicht nachvollziehen, aber ist offenbar sehr random alles ohne wirklich nachvollziehen zu können woher.

Vor dem letzten Update ist es mir bewusst zumindest so nicht aufgefallen, aber da ich sonst auch keine weiteren Anhaltspunkte sehe, mach das Issue gerne zu.

**Comment by copystring** [comment]
Mir ist durch dieses Issue wieder eingefallen, was ich schon lange mal umsetzen wollte: die Erneuerung des Logins. Das habe ich in der aktuellen dev-Version umgesetzt und kann über diesen Link getestet werden: https://github.com/copystring/ioBroker.roborock/tree/dev
Wärst du so nett, und testest das mal die nächsten Tage? Ich denke, dass dein Problem dadurch eventuell behoben wird. Aktuell wird alle 12 Stunden der Login erneuert.

**Comment by seaspotter** [comment]
Jap, hab mal die dev Version installiert und berichte :)

**Comment by fL4sH3r** [comment]
Moin zusammen, ich habe ebenfalls das Problem bei meinem Roborock S6, dass die Multimap nicht gewechselt werden kann. Wenn ich die Karte im iobroker ändere, wird mir diese auch in der Roborock-App geändert aber die Karte wird nicht im iobroker aktualisiert. Adapterversion ist die aktuelle v0.6.17 DEV

roborock.0 | 2024-11-05 08:01:25.968 | warn | Failed to execute load_multi_map on robot 5ruG34p60WBnmi9qM5iqmW (roborock.vacuum.s6): Error: Local request with id 88 with method load_multi_map timed out after 10 seconds Local connect state: true
-- | -- | -- | --
roborock.0 | 2024-11-05 08:01:25.967 | debug | Size of message queue: 0
roborock.0 | 2024-11-05 08:01:16.854 | debug | Size of message queue: 1
roborock.0 | 2024-11-05 08:01:16.854 | debug | Local message with protocol 4 and id 92 received. Result: [{"enable":1,"current_integral":450,"current_high":500,"current_low":400,"stall_time":10}]
roborock.0 | 2024-11-05 08:01:16.854 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:16.854 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:16.852 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:16.852 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:16.850 | debug | Sent payload for 5ruG34p60WBnmi9qM5iqmW with {"dps":{"4":"{\"id\":92,\"method\":\"get_carpet_mode\",\"params\":[]}"},"t":1730790076} using local connection
roborock.0 | 2024-11-05 08:01:16.764 | debug | Size of message queue: 1
roborock.0 | 2024-11-05 08:01:16.764 | debug | Local message with protocol 4 and id 91 received. Result: [{"main_brush_work_time":143521,"side_brush_work_time":143521,"filter_work_time":1435,"filter_element_work_time":88286,"sensor_dirty_time":0}]
roborock.0 | 2024-11-05 08:01:16.764 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:16.764 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:16.762 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:16.762 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:16.759 | debug | Sent payload for 5ruG34p60WBnmi9qM5iqmW with {"dps":{"4":"{\"id\":91,\"method\":\"get_consumable\",\"params\":[]}"},"t":1730790076} using local connection
roborock.0 | 2024-11-05 08:01:16.712 | debug | Cloud message with protocol 102 and id 2945456 received. Result: undefined
roborock.0 | 2024-11-05 08:01:16.665 | debug | Mapped room matched: 21957691 with name: Küche
roborock.0 | 2024-11-05 08:01:16.664 | debug | Mapped room matched: 21957670 with name: Esszimmer
roborock.0 | 2024-11-05 08:01:16.664 | debug | Mapped room matched: 21957703 with name: HAR
roborock.0 | 2024-11-05 08:01:16.664 | debug | Mapped room matched: 21957695 with name: HWR
roborock.0 | 2024-11-05 08:01:16.664 | debug | Mapped room matched: 21957676 with name: Wohnzimmer
roborock.0 | 2024-11-05 08:01:16.664 | debug | Mapped room matched: 21957706 with name: Flur
roborock.0 | 2024-11-05 08:01:16.664 | debug | Mapped room matched: 21957711 with name: Gäste-WC
roborock.0 | 2024-11-05 08:01:16.664 | debug | Size of message queue: 1
roborock.0 | 2024-11-05 08:01:16.664 | debug | Local message with protocol 4 and id 90 received. Result: [[16,"21957711"],[17,"21957706"],[20,"21957676"],[21,"21957695"],[22,"21957703"],[23,"21957670"],[24,"21957691"]]
roborock.0 | 2024-11-05 08:01:16.664 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:16.663 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:16.662 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:16.662 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:16.659 | debug | Sent payload for 5ruG34p60WBnmi9qM5iqmW with {"dps":{"4":"{\"id\":90,\"method\":\"get_room_mapping\",\"params\":[]}"},"t":1730790076} using local connection
roborock.0 | 2024-11-05 08:01:16.616 | debug | Size of message queue: 1
roborock.0 | 2024-11-05 08:01:16.616 | debug | Local message with protocol 4 and id 89 received. Result: [{"msg_ver":2,"msg_seq":684,"state":8,"battery":100,"clean_time":814,"clean_area":11255000,"error_code":0,"map_present":1,"in_cleaning":0,"in_returning":0,"in_fresh_state":1,"lab_status":3,"water_box_status":0,"fan_power":104,"dnd_enabled":0,"map_status":3,"is_locating":0,"lock_status":0,"mop_forbidden_enable":0,"debug_mode":0}]
roborock.0 | 2024-11-05 08:01:16.616 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:16.616 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:16.614 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:16.614 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:16.611 | debug | Sent payload for 5ruG34p60WBnmi9qM5iqmW with {"dps":{"4":"{\"id\":89,\"method\":\"get_status\",\"params\":[]}"},"t":1730790076} using local connection
roborock.0 | 2024-11-05 08:01:16.566 | debug | Latest data requested
roborock.0 | 2024-11-05 08:01:16.526 | debug | Cloud message with protocol 102 and id 158236158 received. Result: undefined
roborock.0 | 2024-11-05 08:01:16.505 | debug | Cloud message with protocol 102 and id 88 received. Result: ["ok"]
roborock.0 | 2024-11-05 08:01:16.394 | debug | Cloud message with protocol 102 and id 272285034 received. Result: undefined
roborock.0 | 2024-11-05 08:01:16.212 | debug | Cloud message with protocol 102 and id 276535999 received. Result: undefined
roborock.0 | 2024-11-05 08:01:16.193 | debug | Cloud message with protocol 102 and id 8160555 received. Result: undefined
roborock.0 | 2024-11-05 08:01:15.997 | debug | Cloud message with protocol 102 and id 193574023 received. Result: undefined
roborock.0 | 2024-11-05 08:01:15.970 | debug | Chunk buffer data is complete. Processing...
roborock.0 | 2024-11-05 08:01:15.970 | debug | new chunk started
roborock.0 | 2024-11-05 08:01:15.967 | debug | Sent payload for 5ruG34p60WBnmi9qM5iqmW with {"dps":{"4":"{\"id\":88,\"method\":\"load_multi_map\",\"params\":[0]}"},"t":1730790075} using local connection
roborock.0 | 2024-11-05 08:01:15.965 | debug | onStateChange: load_multi_map with value: 0
roborock.0 | 2024-11-05 08:01:09.343 | warn | Failed to execute load_multi_map on robot 5ruG34p60WBnmi9qM5iqmW (roborock.vacuum.s6): Error: Local request with id 86 with method load_multi_map timed out after 10 seconds Local connect state: true

**Comment by csowada** [comment]
Ich habe ähnliches Problem beim nutzen des Adapters, hier ist scheinbar der Timeout mit 10 Sekunden einfach zu klein. Ich habe das auf 30 Sekunden geändert und alle nachfolgende Befehle werden sauber ausgeführt. Siehe ``lib\messageQueueHandler.js`` Zeile 3

**Comment by copystring** [comment]
> Ich habe ähnliches Problem beim nutzen des Adapters, hier ist scheinbar der Timeout mit 10 Sekunden einfach zu klein. Ich habe das auf 30 Sekunden geändert und alle nachfolgende Befehle werden sauber ausgeführt. Siehe ``lib\messageQueueHandler.js`` Zeile 3

Das könnte natürlich sein. Wie hast du das getestet? Oft tritt der ursprünglich beschriebene Fehler erst nach 1-2 Tagen auf. Hast du es so lange getestet?

**Comment by csowada** [comment]
@copystring Ich nutze diesen tollen Adapter Standalone, daher habe ich den Code nun schon ein ganzes Stück analysiert und teste gerade sehr aktiv. Schau mal hier [rr2mqtt](https://github.com/csowada/rr2mqtt). Ich wollte mich dazu aber grundsätzlich nochmal melden :-) . Mir ist das gerade beim wechseln der Maps aufgefallen.

**Comment by copystring** [comment]
@csowada was hältst du davon, vielleicht gemeinsam, den relevanten code für die Kommunikation zwischen Server und Client in eine eigene Bibliothek zu packen, welche dann von rr2mqtt, iobroker.roborock und anderen Projekten verwendet werden könnte? Dadurch könnten Verbesserungen direkt in beide Projekte einfließen.

Frage zu rr2mqtt: Welchen Plan hast du, den Nutzern die Unmöglichkeit zu geben, Koordinaten auf der Karte für z.B. `app_zoned_clean` oder `app_goto_target` herauszufinden?

**Comment by copystring** [comment]
> Ich habe ähnliches Problem beim nutzen des Adapters, hier ist scheinbar der Timeout mit 10 Sekunden einfach zu klein. Ich habe das auf 30 Sekunden geändert und alle nachfolgende Befehle werden sauber ausgeführt. Siehe `lib\messageQueueHandler.js` Zeile 3

https://github.com/copystring/ioBroker.roborock/commit/62035f487ef2cd98c5c72b5c195a433d3fe964c7

**Comment by seaspotter** [comment]
Also ich hab gestern Abend direkt die neue dev mit dem höheren Timeout installiert und bis jetzt nicht mehr eine Warnmeldung. Sieht ziemlich vielversprechend aus. Ich hab vom Roborock Adapter nur einmal jede Stunde den MQTT Reconnect, sonst keine anderen Meldungen mehr.

**Comment by csowada** [comment]
> @csowada was hältst du davon, vielleicht gemeinsam, den relevanten code für die Kommunikation zwischen Server und Client in eine eigene Bibliothek zu packen, welche dann von rr2mqtt, iobroker.roborock und anderen Projekten verwendet werden könnte? Dadurch könnten Verbesserungen direkt in beide Projekte einfließen.

Um diesen Bug nicht zu sprengen, habe ich mal eine Diskussion gestartet. https://github.com/copystring/ioBroker.roborock/discussions/704

**Comment by copystring** [comment]
Scheint ja gelöst zu sein. Andernfalls gerne nochmal melden.
