### ISSUE TITLE
[bug] Does not work with all Node.js and/or npm versions.

### ISSUE THREAD

**Issue by ShadoVV1982** [copystring/ioBroker.roborock#682]
### Bug Description

The following error message occurred during installation.

`$ .... add roborock --host ....
NPM version: 10.7.0
Installing .....roborock@0.6.16... (System call)
host.... Cannot install iobroker.roborock@0.6.16: 1
ERROR: Process exited with code 25`

### Steps to Reproduce

install the latest version of the adapter

### Expected Behavior

install the latest version of the adapter

### Debug Log

$ .... add roborock --host ....
NPM version: 10.7.0
Installing .....roborock@0.6.16... (System call)
host.... Cannot install iobroker.roborock@0.6.16: 1
ERROR: Process exited with code 25

### Adapter Version

0.6.16

### JS-Controller Version

6.0.11

### Node.js Version

v18.20.4

### Operating System

linux

**Comment by copystring** [comment]
Hi,

this adapter cannot work with Node.js 18 anymore. Sorry.
