### ISSUE TITLE
[BUG] Unsupported attribute

### ISSUE THREAD

**Issue by Croxxii** [copystring/ioBroker.roborock#685]
### Bug Description

Hallo und erst mal ein riesengroßes DANKE für den Adapter :)

Ich habe einen Roborock Qrevo Curv

Nun zum Problem. Nachdem Adapter start, kommen zwar ein paar Fehlermeldungen, aber diese beiden Fehler treten minütlich auf! Die anderen nur kurz nach dem start!

Unsupported attribute: dss of get_status with value 168. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a135
Unsupported attribute: extra_time of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a135

![23-10-_2024_17-47-49](https://github.com/user-attachments/assets/53eb8036-f9c2-4887-abef-d3da8078edf2)

### Steps to Reproduce

Adapter starten und kurz warten

### Expected Behavior

No Error

### Debug Log

[debuglog.txt](https://github.com/user-attachments/files/17494988/debuglog.txt)

### Adapter Version

0.6.17

### JS-Controller Version

6.0.11

### Node.js Version

v20.18.0

### Operating System

Synology DSM 7.2.2-72806 (Linux)

**Comment by copystring** [comment]
Hallo!
Erstmal möchte ich mich für dein Debuglog bedanken.
Ich habe die notwendigen Änderungen vorgenommen. Im kommenden Release 0.6.18 ist das entsprechend behoben.

**Comment by Croxxii** [comment]
Perfekt vielen Dank!

**Comment by copystring** [comment]
Falls doch nochmal Probleme auftauchen, schreib mir gerne nochmal.
