### ISSUE TITLE
[BUG] QRevo - Failed to execute get_map_v1 on robot on Version  0.6.16 &  0.6.17

### ISSUE THREAD

**Issue by psg1** [copystring/ioBroker.roborock#686]
### Bug Description

Nach Erstinstallation des Adapters (0.6.16) - diese Version wurde im ioBroker angezeigt - erhielt ich im Log die Meldung
`Failed to execute get_map_v1 on robot`

Im Einsatz ist ein Roborock QRevo

Danach fand ich folgendes issue [564](https://github.com/copystring/ioBroker.roborock/issues/564) und habe den Adapter manuell auf die 0.6.17 geupdated. Der Fehler besteht weiterhin.

### Steps to Reproduce

-

### Expected Behavior

-

### Debug Log

[roborock.log](https://github.com/user-attachments/files/17496383/roborock.log)

### Adapter Version

0.6.16 &  0.6.17

### JS-Controller Version

7.0.0

### Node.js Version

20.16.0

### Operating System

linux

**Comment by psg1** [comment]
Ich habe den Adapter nun neu gestartet, während der QRevo "unterwegs" war. Nun konnte die Karte geladen werden. Warum dies vorher nicht funktioniert hat kann ich mir nicht erklären. Natürlich war bereits eine vollständige Kartierung erfolgt und der Roborock auch schon vor der Installation oft unterwegs.

**Comment by copystring** [comment]
Roborock blockiert manchmal neue Anfragen, wenn davon zu viele in zu kurzen Zeitraum verschickt werden. Beim Neustart wird das zurückgesetzt.
