### ISSUE TITLE
[BUG] Device not supported - roborock.vacuum.a117

### ISSUE THREAD

**Issue by A1uca2d** [copystring/ioBroker.roborock#687]
### Bug Description

The new Roborock Qrevo Master is not supported by the adapter.

### Steps to Reproduce

try to use the exact device I mantioned here

### Expected Behavior

using the adapter for my new device

### Debug Log

roborock.0 | 2024-10-28 15:52:37.842 | warn | setTimeout called, but adapter is shutting down
-- | -- | -- | --
roborock.0 | 2024-10-28 15:52:37.794 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:37.742 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:37.733 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:37.729 | warn | setInterval called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:37.729 | warn | setInterval called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:37.455 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:37.388 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
roborock.0 | 2024-10-28 15:52:37.384 | error | Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-10-28 15:52:37.384 | error | TypeError: Cannot read properties of undefined (reading 'captureException') at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:1234:44) at deviceFeatures.processSupportedFeatures (/opt/iobroker/node_modules/iobroker.roborock/lib/deviceFeatures.js:913:18) at Roborock.createDevices (/opt/iobroker/node_modules/iobroker.roborock/main.js:275:38) at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:181:17) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-10-28 15:52:37.384 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-10-28 15:52:37.384 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
roborock.0 | 2024-10-28 15:52:37.380 | error | Failed to execute null on robot null (roborock.vacuum.a117): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!
roborock.0 | 2024-10-28 15:52:00.818 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.818 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:52:00.770 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.769 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:52:00.720 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.719 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.dust_collection_work_times" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:52:00.719 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.sensor_dirty_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:52:00.718 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.filter_element_work_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:52:00.718 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.filter_work_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:52:00.718 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.side_brush_work_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:52:00.718 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.main_brush_work_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:52:00.671 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.668 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-10-28 15:52:00.622 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.571 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.515 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.507 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.503 | warn | setInterval called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.503 | warn | setInterval called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.407 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:52:00.340 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
roborock.0 | 2024-10-28 15:52:00.337 | error | Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-10-28 15:52:00.337 | error | TypeError: Cannot read properties of undefined (reading 'captureException') at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:1234:44) at deviceFeatures.processSupportedFeatures (/opt/iobroker/node_modules/iobroker.roborock/lib/deviceFeatures.js:913:18) at Roborock.createDevices (/opt/iobroker/node_modules/iobroker.roborock/main.js:275:38) at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:181:17) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-10-28 15:52:00.336 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-10-28 15:52:00.336 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
roborock.0 | 2024-10-28 15:52:00.333 | error | Failed to execute null on robot null (roborock.vacuum.a117): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!
roborock.0 | 2024-10-28 15:51:23.506 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.505 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:51:23.458 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.457 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:51:23.411 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.410 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.dust_collection_work_times" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:51:23.410 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.sensor_dirty_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:51:23.410 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.filter_element_work_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:51:23.410 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.filter_work_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:51:23.410 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.side_brush_work_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:51:23.409 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.consumables.main_brush_work_time" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 15:51:23.362 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.361 | warn | Failed to map rooms. You need to name your rooms via the mobile app on your phone.
roborock.0 | 2024-10-28 15:51:23.314 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.267 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.220 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.212 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.208 | warn | setInterval called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.208 | warn | setInterval called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.117 | warn | setTimeout called, but adapter is shutting down
roborock.0 | 2024-10-28 15:51:23.041 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
roborock.0 | 2024-10-28 15:51:23.037 | error | Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-10-28 15:51:23.037 | error | TypeError: Cannot read properties of undefined (reading 'captureException') at Roborock.catchError (/opt/iobroker/node_modules/iobroker.roborock/main.js:1234:44) at deviceFeatures.processSupportedFeatures (/opt/iobroker/node_modules/iobroker.roborock/lib/deviceFeatures.js:913:18) at Roborock.createDevices (/opt/iobroker/node_modules/iobroker.roborock/main.js:275:38) at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:181:17) at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
roborock.0 | 2024-10-28 15:51:23.037 | error | unhandled promise rejection: Cannot read properties of undefined (reading 'captureException')
roborock.0 | 2024-10-28 15:51:23.036 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
roborock.0 | 2024-10-28 15:51:23.033 | error | Failed to execute null on robot null (roborock.vacuum.a117): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!

### Adapter Version

0.6.17

### JS-Controller Version

6.0.11

### Node.js Version

20.17.0

### Operating System

Linux-Ubuntu

**Comment by copystring** [comment]
Hi,

thanks for your log!
Would try out https://github.com/copystring/ioBroker.roborock/tree/dev and post a new log? There will be more warnings and errors which need to be addressed.
Thank you!

**Comment by A1uca2d** [comment]
> Hi,
> 
> thanks for your log! Would try out https://github.com/copystring/ioBroker.roborock/tree/dev and post a new log? There will be more warnings and errors which need to be addressed. Thank you!

The Log after installing the "tree/dev" Version:

`roborock.0 | 2024-10-28 21:25:00.565 | warn | Unsupported attribute: last_clean_t of get_status with value 1730141602. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
-- | -- | -- | --
roborock.0 | 2024-10-28 21:25:00.565 | warn | Unsupported attribute: switch_status of get_status with value 16. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.564 | warn | Unsupported attribute: kct of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.564 | warn | Unsupported attribute: common_status of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.563 | warn | Unsupported attribute: dss of get_status with value 168. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.563 | warn | Unsupported attribute: rss of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.563 | warn | Unsupported attribute: clean_percent of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.562 | warn | Unsupported attribute: charge_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.560 | warn | Unsupported attribute: in_warmup of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.559 | warn | Unsupported attribute: water_shortage_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.558 | warn | Unsupported attribute: monitor_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.558 | warn | Unsupported attribute: home_sec_enable_password of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.557 | warn | Unsupported attribute: home_sec_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.557 | warn | Unsupported attribute: mop_forbidden_enable of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.556 | warn | Unsupported attribute: water_box_carriage_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.556 | warn | Unsupported attribute: water_box_mode of get_status with value 209. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:25:00.554 | warn | Unsupported attribute: water_box_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:10.517 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:24:10.470 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:24:00.501 | warn | Unsupported attribute: last_clean_t of get_status with value 1730141602. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.500 | warn | Unsupported attribute: switch_status of get_status with value 16. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.500 | warn | Unsupported attribute: kct of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.500 | warn | Unsupported attribute: common_status of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.500 | warn | Unsupported attribute: dss of get_status with value 168. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.499 | warn | Unsupported attribute: rss of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.499 | warn | Unsupported attribute: clean_percent of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.498 | warn | Unsupported attribute: charge_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.497 | warn | Unsupported attribute: in_warmup of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.496 | warn | Unsupported attribute: water_shortage_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.495 | warn | Unsupported attribute: monitor_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.495 | warn | Unsupported attribute: home_sec_enable_password of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.495 | warn | Unsupported attribute: home_sec_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.494 | warn | Unsupported attribute: mop_forbidden_enable of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.494 | warn | Unsupported attribute: water_box_carriage_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.494 | warn | Unsupported attribute: water_box_mode of get_status with value 209. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:24:00.493 | warn | Unsupported attribute: water_box_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:10.509 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:23:10.463 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:23:00.445 | warn | Unsupported attribute: last_clean_t of get_status with value 1730141602. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.445 | warn | Unsupported attribute: switch_status of get_status with value 16. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.444 | warn | Unsupported attribute: kct of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.444 | warn | Unsupported attribute: common_status of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.443 | warn | Unsupported attribute: dss of get_status with value 168. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.443 | warn | Unsupported attribute: rss of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.443 | warn | Unsupported attribute: clean_percent of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.442 | warn | Unsupported attribute: charge_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.441 | warn | Unsupported attribute: in_warmup of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.440 | warn | Unsupported attribute: water_shortage_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.439 | warn | Unsupported attribute: monitor_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.439 | warn | Unsupported attribute: home_sec_enable_password of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.438 | warn | Unsupported attribute: home_sec_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.438 | warn | Unsupported attribute: mop_forbidden_enable of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.437 | warn | Unsupported attribute: water_box_carriage_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.437 | warn | Unsupported attribute: water_box_mode of get_status with value 209. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:23:00.436 | warn | Unsupported attribute: water_box_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:10.513 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:22:10.467 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:22:00.391 | warn | Unsupported attribute: last_clean_t of get_status with value 1730141602. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.390 | warn | Unsupported attribute: switch_status of get_status with value 16. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.390 | warn | Unsupported attribute: kct of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.389 | warn | Unsupported attribute: common_status of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.389 | warn | Unsupported attribute: dss of get_status with value 168. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.388 | warn | Unsupported attribute: rss of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.388 | warn | Unsupported attribute: clean_percent of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.387 | warn | Unsupported attribute: charge_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.385 | warn | Unsupported attribute: in_warmup of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.384 | warn | Unsupported attribute: water_shortage_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.383 | warn | Unsupported attribute: monitor_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.383 | warn | Unsupported attribute: home_sec_enable_password of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.382 | warn | Unsupported attribute: home_sec_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.382 | warn | Unsupported attribute: mop_forbidden_enable of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.381 | warn | Unsupported attribute: water_box_carriage_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.381 | warn | Unsupported attribute: water_box_mode of get_status with value 209. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:22:00.380 | warn | Unsupported attribute: water_box_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:10.516 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:21:10.461 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:21:00.339 | warn | Unsupported attribute: last_clean_t of get_status with value 1730141602. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.338 | warn | Unsupported attribute: switch_status of get_status with value 16. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.338 | warn | Unsupported attribute: kct of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.338 | warn | Unsupported attribute: common_status of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.337 | warn | Unsupported attribute: dss of get_status with value 168. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.337 | warn | Unsupported attribute: rss of get_status with value 2. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.337 | warn | Unsupported attribute: clean_percent of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.335 | warn | Unsupported attribute: charge_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.332 | warn | Unsupported attribute: in_warmup of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.330 | warn | Unsupported attribute: water_shortage_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.330 | warn | Unsupported attribute: monitor_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.329 | warn | Unsupported attribute: home_sec_enable_password of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.329 | warn | Unsupported attribute: home_sec_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.328 | warn | Unsupported attribute: mop_forbidden_enable of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.327 | warn | Unsupported attribute: water_box_carriage_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.327 | warn | Unsupported attribute: water_box_mode of get_status with value 209. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:21:00.324 | warn | Unsupported attribute: water_box_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a117
roborock.0 | 2024-10-28 21:20:11.505 | warn | Unknown block type buffer data: undefined {"type":"Buffer","data":[46,0,12,0,0,0,0,0,0,0,0,0]}
roborock.0 | 2024-10-28 21:20:11.505 | warn | Unknown block type hex data: undefined 2e000c000000000000000000
roborock.0 | 2024-10-28 21:20:11.505 | warn | Unknown block type! Please report this to the developer. Block type is: 46 and a length of 0
roborock.0 | 2024-10-28 21:20:11.086 | warn | Unknown block type buffer data: undefined {"type":"Buffer","data":[46,0,12,0,0,0,0,0,0,0,0,0]}
roborock.0 | 2024-10-28 21:20:11.086 | warn | Unknown block type hex data: undefined 2e000c000000000000000000
roborock.0 | 2024-10-28 21:20:11.085 | warn | Unknown block type! Please report this to the developer. Block type is: 46 and a length of 0
roborock.0 | 2024-10-28 21:20:10.956 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.cleaningInfo.records.1.task_id" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:20:10.954 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.cleaningInfo.records.1.cleaned_area" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:20:10.953 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.cleaningInfo.records.1.map_flag" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:20:10.836 | warn | Unknown block type buffer data: undefined {"type":"Buffer","data":[46,0,12,0,0,0,0,0,0,0,0,0]}
roborock.0 | 2024-10-28 21:20:10.836 | warn | Unknown block type hex data: undefined 2e000c000000000000000000
roborock.0 | 2024-10-28 21:20:10.836 | warn | Unknown block type! Please report this to the developer. Block type is: 46 and a length of 0
roborock.0 | 2024-10-28 21:20:10.766 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.cleaningInfo.records.0.task_id" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:20:10.764 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.cleaningInfo.records.0.cleaned_area" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:20:10.763 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.cleaningInfo.records.0.map_flag" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:20:10.613 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_clean_mode" has no existing object, this might lead to an error in future versions
roborock.0 | 2024-10-28 21:20:10.565 | warn | State "roborock.0.Devices.12DZR4q2i1HOwjO0IYf7pP.deviceStatus.carpet_mode" has no existing object, this might lead to an error in future versions`

**Comment by copystring** [comment]
Thanks. I think I implemented all new attributes. Please check the new dev and post a new log.
Fun fact: There is a block type on the map with value 46 which is not documented in roborocks own files 😅

**Comment by A1uca2d** [comment]
> Thanks. I think I implemented all new attributes. Please check the new dev and post a new log. Fun fact: There is a block type on the map with value 46 which is not documented in roborocks own files 😅

There are no messages in the log-window by using the newest dev version.
I haven't had the time to test all funktions, but for now It looks good.

Thank you so far.
