### ISSUE TITLE
Unsupported attribute: water_box_status of get_status with value 1

### ISSUE THREAD

**Issue by H-a-m-i** [copystring/ioBroker.roborock#697]
### Bug Description

Hallo. Seit Update auf v0.6.16 erhalte ich im Log die Warnung:
Unsupported attribute: water_box_status of get_status with value 1. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.s6

LG Hami

### Steps to Reproduce

fehlendes Attribut

### Expected Behavior

fehlendes Attribut

### Debug Log

[iobroker.log](https://github.com/user-attachments/files/17618794/iobroker.log)

### Adapter Version

v0.6.16

### JS-Controller Version

6.0.11

### Node.js Version

v20.18.0

### Operating System

Debian 12

**Comment by copystring** [comment]
Danke. Gefixt via https://github.com/copystring/ioBroker.roborock/commit/03875f5696822a84353d6e1ee84b0fa5abc486ef.
Kommt dann im nächsten Release.

**Comment by fL4sH3r** [comment]
Funktioniert! Vielen Dank.

**Comment by H-a-m-i** [comment]
Super, danke!
