### ISSUE TITLE
[BUG] Unsupported attribute: water_box_status of get_status with value 0 Roborock S6"

### ISSUE THREAD

**Issue by fL4sH3r** [copystring/ioBroker.roborock#699]
### Bug Description

Mir wird im Protokoll ein Warnhinweis angezeigt.

### Steps to Reproduce

Der Warnhinweis wird kontinuierlich im Protokoll angezeigt.

### Expected Behavior

Keine Fehlermeldung

### Debug Log

roborock.0 | 2024-11-05 06:27:00.796 | warn | Unsupported attribute: water_box_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.s6
-- | -- | -- | --
roborock.0 | 2024-11-05 06:26:00.737 | warn | Unsupported attribute: water_box_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.s6
roborock.0 | 2024-11-05 06:25:00.679 | warn | Unsupported attribute: water_box_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.s6
roborock.0 | 2024-11-05 06:24:00.624 | warn | Unsupported attribute: water_box_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.s6
roborock.0 | 2024-11-05 06:23:00.565 | warn | Unsupported attribute: water_box_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.s6
roborock.0 | 2024-11-05 06:22:00.511 | warn | Unsupported attribute: water_box_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.s6

### Adapter Version

v0.6.17 dev

### JS-Controller Version

 7.0.2

### Node.js Version

v20.18.0

### Operating System

Linux

**Comment by copystring** [comment]
Beim nächsten Mal bitte vorher die Suche benutzen. 
Siehe https://github.com/copystring/ioBroker.roborock/issues/697

**Comment by fL4sH3r** [comment]
Oh sorry, das habe ich wohl übersehen.
