### ISSUE TITLE
Map is cut off

### ISSUE THREAD

**Issue by mproper23** [copystring/ioBroker.roborock#70]
Version installed 0.0.7 Alpha
if i view the map the bottom is cut off.
Log File is attachted

iobroker:
![grafik](https://user-images.githubusercontent.com/25171131/217184628-abd64710-df6b-4565-9ee7-e7e666719f70.png)
App:
![grafik](https://user-images.githubusercontent.com/25171131/217184814-30ee56e7-dbe2-4b4e-90cc-c16cf1316123.png)
[export-8db08f3d2195b3f.csv](https://github.com/copystring/ioBroker.roborock/files/10673925/export-8db08f3d2195b3f.csv)

**Comment by copystring** [comment]
Ich nehme an, dass dies bei 0.6 nicht so war. Stimmt das?

**Comment by mproper23** [comment]
Richtig

**Comment by copystring** [comment]
OK. Magst du mir Mal deinen map String aus iobroker als ZIP Datei hier anhängen?
Dann gucke ich mir das genauer an.

**Comment by mproper23** [comment]
Den base64?

**Comment by copystring** [comment]
Ja genau

**Comment by mproper23** [comment]
Einfach den Wert kopieren?

**Comment by mproper23** [comment]
[base64.zip](https://github.com/copystring/ioBroker.roborock/files/10675005/base64.zip)

**Comment by copystring** [comment]
Ja aber nicht hier einfach reinschreiben sonder als ZIP Datei hier anhängen. Der String ist zu groß dafür.

**Comment by mproper23** [comment]
oben angehängt

**Comment by copystring** [comment]
Kann ich mir heute Abend angucken

**Comment by copystring** [comment]
Ich glaube ich habe einfach nur Höhe und Breite vertauscht.

**Comment by mproper23** [comment]
Kann passieren

**Comment by copystring** [comment]
https://github.com/copystring/ioBroker.roborock/tree/swap_height_width_mapCreator

**Comment by mproper23** [comment]
mit dem tree passt es wieder

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/pull/76
