### ISSUE TITLE
[BUG] falsche Umrechnung cleaned_area unter records?

### ISSUE THREAD

**Issue by fL4sH3r** [copystring/ioBroker.roborock#700]
### Bug Description

Kann es sein, dass dieser Wert falsch berechnet wurde ? Gerät ist ein Roborock S8.
![image](https://github.com/user-attachments/assets/aff4b247-ffb2-4107-bdd6-0fd4410c4ee9)

### Steps to Reproduce

Nach einer Reinigung ist der Wert Cleaned_Area unter dem Ordner Records sehr hoch. 
![image](https://github.com/user-attachments/assets/c1ba6214-e3f0-4751-b877-84d4d1847739)

### Expected Behavior

Umrechnung des Werts Cleaned_Area

### Debug Log

Log sieht normal aus

Local message with protocol 4 and id 2139 received. Result: [{"begin":1730932200,"end":1730934874,"duration":2674,"**area":39175000,**"error":0,"complete":1,"start_type":3,"clean_type":3,"finish_reason":56,"dust_collection_status":0,"avoid_count":46,"map_flag":0,"**cleaned_area":41312500**,"manual_replenish":0,"dirty_replenish":0,"clean_times":1}

### Adapter Version

0.6.17

### JS-Controller Version

7.0.2

### Node.js Version

v20.18.0

### Operating System

Linux

**Comment by copystring** [comment]
Danke für das Log. Ich kann das leider bei mir nicht testen, habe es aber in der dev angepasst.
Würdest du es für mich testen? Hier der link zur dev: https://github.com/copystring/ioBroker.roborock/tree/dev
Die bitte in ioBroker installieren. Die Berechnung sollte jetzt passen.

**Comment by fL4sH3r** [comment]
Vielen Dank für die Umsetzung, funktioniert soweit. Eventuell könnte man das ganze ja noch auf 2 Nachkommastellen ändern. Weil so der Unterschied zwischen area und cleaned_area sehr groß wirkt.
![Screenshot_20241107_230901_Samsung Internet](https://github.com/user-attachments/assets/5bcd1dbe-b170-4215-b610-c06e914ec86f)
Die 2 Nachkommastellen würde dann aber die beiden Datenpunkte "cleaned_area" und "area" betreffen.

**Comment by copystring** [comment]
Danke für den Vorschlag. Ich habe das in der dev eingebaut. Siehe https://github.com/copystring/ioBroker.roborock/commit/0bf0fccb7a9d0a4a139ee2063b707034dda50376.

**Comment by fL4sH3r** [comment]
Super, soeht gut aus. Danke für die Umsetzung. 
![Screenshot_20241109_222349_Chrome](https://github.com/user-attachments/assets/326e7d04-1104-458b-bfa4-1668c01cd962)
