### ISSUE TITLE
S6 Consumables

### ISSUE THREAD

**Issue by copystring** [copystring/ioBroker.roborock#706]
Hallo zusammen, mir werden leider auch nicht alle Datenpunkte bei meinem Roborock S6 mit Inhalt gefüllt. 
Die Prozente fehlen und der Wassertankfilter wird mir leider auch nicht angezeigt. 
Im HomeData sind die Prozentwerte auch vorhanden..
![image](https://github.com/user-attachments/assets/ec83d67f-f2de-449a-8bfa-2d1a03be3a45)

![image](https://github.com/user-attachments/assets/96219cf3-00b1-4867-9d93-45da0addd949)
![Screenshot_20241105_064506_Roborock](https://github.com/user-attachments/assets/591895da-9989-46c3-b9ac-0f05241045f2)

_Originally posted by @fL4sH3r in https://github.com/copystring/ioBroker.roborock/issues/677#issuecomment-2456287524_

**Comment by copystring** [comment]
Hi,

magst du bitte mal die dev Testen? https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by fL4sH3r** [comment]
Danke für die Umsetzung. Die fehlenden Datenpunkte sind jetzt auch beim S6 vorhanden. Leider sind ein paar Datenpunkte doppelt mit unterschiedlichen IDs.
![Screenshot_20241113_223030_Chrome](https://github.com/user-attachments/assets/524dd96e-2025-43d0-b195-40996c1b7de2)

**Comment by copystring** [comment]
Klar, der Adapter löscht die alten Datenpunkte nicht. Du müsstest du selbst löschen.

**Comment by fL4sH3r** [comment]
Hatte den Objektbaum gestern eigentlich noch gelöscht.....  naja habe den heute nochmal gelöscht und jetzt sind die oberen Datenpunkte auch nicht mehr vorhanden. Vielen Dank.

Hat das eigentlich einen Grund, dass die gleichen Datenpunkte unterschiedliche ID´s, bei unterschiedlichen Saugrobotern haben?

Roborock S6
![image](https://github.com/user-attachments/assets/aa0f5c74-a771-4a5d-9ab9-0ba423a1e7c5)

Roborock S8
![image](https://github.com/user-attachments/assets/8ec31f80-02ef-4395-9b90-7e27f1236dd6)

**Comment by Erwin40** [comment]
Dann bitte schließen 😁
