### ISSUE TITLE
Please add info that mac-os is not supported to README.md

### ISSUE THREAD

**Issue by mcm1957** [copystring/ioBroker.roborock#708]
### Bug Description

Automatic tests fail with macOs. So ist likely that the adapter does not work on macOs.

Please add an info at README.md stating that this adapter is not suppotered at macOs so that users are not surprised.

Thanks.

### Steps to Reproduce

try to active macOs GitHub tests

### Expected Behavior

README,md should list any restrictions

### Debug Log

n/a

### Adapter Version

n/a

### JS-Controller Version

n/a

### Node.js Version

n/a

### Operating System

n/a - macOs

**Comment by copystring** [comment]
Hi,

the change didn't make into the 0.6.17 release, but is upcoming in 0.6.18 once I fixed all the bugs in the dev branch.
See https://github.com/copystring/ioBroker.roborock/commit/f337f7e2044eadaf28c3e6afc853e1c1316cb249
Is this change sufficient?

**Comment by mcm1957** [comment]
thats completply OK
 THANKS

**Comment by copystring** [comment]
Fixed in upcoming release 0.6.18.
