### ISSUE TITLE
Error: Login returned empty userdata.

### ISSUE THREAD

**Issue by ArnoD15** [copystring/ioBroker.roborock#709]
### Bug Description

Hallo copystring,
bei Start vom Adapter werden mehrere Fehler im LOG ausgegeben und der Adapter wird beendet.
Ich habe bereits den Adapter deinstalliert und neu installiert, jedoch hat sich am Problem nichts geändert.

Anbei das LOG File in der Hoffnung das du mir eventuell sagen kannst, was bei mir schiefläuft.

### Steps to Reproduce

-

### Expected Behavior

-

### Debug Log

[LOG_File.txt](https://github.com/user-attachments/files/17791653/LOG_File.txt)

### Adapter Version

0.6.17

### JS-Controller Version

7.0.3

### Node.js Version

20.18.0

### Operating System

Doker / linux

**Comment by ArnoD15** [comment]
Hallo copystring,

das Problem an sich hat sich erledigt. Die Ursache war anscheinend ein Update der App, was es erforderlich machte sich einmal mit der App neu anzumelden. 
Danach funktionierte der Adapter auch wieder wie gewohnt.

Einziger Optimierung Wunsch wäre diesen Fehler abzufangen, sodass nicht gleich der iobroker komplett abschmiert. :-)
Eventuell ein Hinweis sich mit der App einmal anzumelden.

VG Arno

**Comment by copystring** [comment]
Hallo @ArnoD15,

ich hätte in dem fehlerhaften Zustand dein HomeData und UserData benötigt. Jetzt sind die AGB oder so schon bestätigt. Kannst du das irgendwie reproduzieren und mir dann HomeData und UserData zukommen lassen? Gern per E-Mail, weil in UserData Kennwörter abgelegt sind. copystring@gmail.com

**Comment by ArnoD15** [comment]
Ich kann den Fehler jetzt leider nicht mehr reproduzieren. Dachte, wenn ich die App neu installiere, würde es eventuell gehen, aber bedauerlicherweise funktioniert das nicht.

**Comment by A1uca2d** [comment]
ich hatte heute das gleiche Problem. 
Nachdem ich auf mein Handy neu gestartet hatte und dann in die Roborock App ging wurde ich aufgefordert eine aktualisierte Datenschutzerklärung zu akzeptieren. 
---> Seit dem ich diese akzeptiert habe geht es wieder in dem Adapter. Würde sagen, dass das Ausschlaggebend war.

**Comment by Erwin40** [comment]
Korrekt. Aber bei mir (Apple) hat es genügt die App neu zu starten und die Datenschutzerklärung zu bestätigen.

**Comment by copystring** [comment]
Ohne UserData und HomeData mit den Werten während der Fehler vorhanden war, lässt sich das nicht weiter prüfen.
Ich schließe das erstmal. Falls es doch nochmal auftreten sollte, brauche ich HomeData und UserData. Gerne per Mail copystring@gmail.com
