### ISSUE TITLE
[BUG] roborock.0.Devices.XXXX.commands.set_custom_mode Wert 108 Max+ fehlt in der Auswahl

### ISSUE THREAD

**Issue by KallAdam** [copystring/ioBroker.roborock#712]
### Bug Description

für den Command 
roborock.0.Devices.XXX.commands.set_custom_mode
fehlt der mögliche Einstellungswert  108 "Max+". Über Skript ist der Wert 108 möglich. Direkt unter Objekte ist Max+ aber nicht auswählbar. (siehe Bild) 
![Screenshot 2024-11-30 141943](https://github.com/user-attachments/assets/62460316-85ed-408b-987e-75b1b1a6cd28)

Gerät: S8 Pro Ultra  "roborock.vacuum.a70"

### Steps to Reproduce

Max+ in Command commands.set_custom_mode  über Objekte nicht auswählbar.

### Expected Behavior

![Screenshot 2024-11-30 141943](https://github.com/user-attachments/assets/2e73dce1-f62b-465a-8040-ce4390017f2f)
Auswählmöglichkeit Max+  Wert 108

### Debug Log

[2024-11-30 143002.855 - info host.r.txt](https://github.com/user-attachments/files/17965552/2024-11-30.143002.855.-.info.host.r.txt)

### Adapter Version

0.6.17

### JS-Controller Version

 7.0.3

### Node.js Version

v20.18.1

### Operating System

Raspberry Pi 4 Model B; linux

**Comment by copystring** [comment]
Danke. Kommt im nächsten Release. Dauert aber noch ein bisschen. Ich muss einen fiesen Bug finden und beheben.
