### ISSUE TITLE
[BUG] Datenpunkt connection wird nach beenden nicht auf false gesetzt

### ISSUE THREAD

**Issue by Erwin40** [copystring/ioBroker.roborock#718]
### Bug Description

Beim Beenden des Adapters wird roborock.0.info.connection nicht auf false gesetzt

### Steps to Reproduce

Adapter beenden

### Expected Behavior

roborock.0.info.connection = false

### Debug Log

none

### Adapter Version

0.6.17

### JS-Controller Version

7.0.3

### Node.js Version

20.18.1

### Operating System

Debian GNU/Linux (Bookworm)

**Comment by copystring** [comment]
Added via https://github.com/copystring/ioBroker.roborock/commit/90b3ce65e4f2d1617246d3176de1c5b7d3005703. Thanks. Coming in next release.
