### ISSUE TITLE
[BUG] Roborock Qrevo Slim wird nicht vollständig unterstützt

### ISSUE THREAD

**Issue by darktwo2** [copystring/ioBroker.roborock#719]
### Bug Description

Beim Start des Adapters erscheint diese Meldung: 
Failed to execute null on robot null (roborock.vacuum.a21): This robot is not fully supported just yet. Contact the dev to get this robot fully supported!

es folgen weitere Warnmeldungen, siehe Protokoll.  

### Steps to Reproduce

bei jedem Adapterstart wiederholen sich die Meldungen. 

### Expected Behavior

keine Fehlermeldungen

### Debug Log

[roborock.log](https://github.com/user-attachments/files/17981165/roborock.log)

### Adapter Version

0.6.17

### JS-Controller Version

6.0.11

### Node.js Version

20.18.1

### Operating System

docker-container

### Additional Context

Beim einem weiteren Roborock Modell (Qrevo Master) waren die Meldungen weg, nachdem ich die neue Version aus dem Issue installiert habe.
https://github.com/copystring/ioBroker.roborock/issues/695

**Comment by copystring** [comment]
Danke! Bitte installiere dir https://github.com/copystring/ioBroker.roborock/tree/dev und häng ein neues Log an, wenn es weitere Warnungen oder Fehler gibt.

**Comment by darktwo2** [comment]
Danke für die schnelle Umsetzung. Bisher habe ich keine weiteren Fehler / Warnungen bekommen.

**Comment by copystring** [comment]
👍

**Comment by darktwo2** [comment]
leider habe ich jetzt doch noch weitere Fehlermeldung bekommen: 
Die Meldungen tauchen nach einer weile auf, ca. 12 Stunden nach Adapterstart. 

Failed to execute client.on("error") on robot undefined (unknown model): MQTT connection error: Error: read ECONNRESET. rriot.r.m: ssl://mqtt-eu-3.roborock.com:8883 rriot.u: 32epqxsAIK4kmOs06xgckL, mqttUser: "entfernt" , mqttPassword: "entfernt"
Failed to execute client.on("offline") on robot undefined (unknown model): MQTT connection offline: undefined
MQTT connection close.
MQTT connection reconnect


nach der Meldung wird versucht erneut eine MQTT Verbindung aufzubauen. Das ganze geht dann alle paar Sekunden so weiter. Nach einen Adapter Neustart ist es erst wieder ok. Nach ca. 12 Stunden geht es wieder wie beschrieben los mit den Meldungen. 

[roborock.log](https://github.com/user-attachments/files/18027449/roborock.log)
