### ISSUE TITLE
[BUG] Fehlermeldung bei Adapterstart

### ISSUE THREAD

**Issue by JackDaniel007** [copystring/ioBroker.roborock#722]
### Bug Description

roborock.0 | 2024-12-07 04:18:08.736 | error | Failed to get home details: TypeError: Cannot read properties of null (reading 'rrHomeId') at Roborock.initializeHomeDetails (/opt/iobroker/node_modules/iobroker.roborock/main.js:145:40) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Roborock.onReady (/opt/iobroker/node_modules/iobroker.roborock/main.js:69:3)
roborock.0 | 2024-12-07 04:18:08.670 | error | Error retrieving or setting clientID: Login returned empty userdata.
roborock.0 | 2024-12-07 04:18:08.656 | error | Error in getUserData: Login returned empty userdata.. This is most likely due to too many reconnects.
roborock.0 | 2024-12-07 04:18:08.427 | info | Starting adapter. This might take a few minutes depending on your setup. Please wait.
roborock.0 | 2024-12-07 04:18:08.415 | info | starting. Version 0.6.17 (non-npm: copystring/ioBroker.roborock#dev) in /opt/iobroker/node_modules/iobroker.roborock, node: v20.18.1, js-controller: 7.0.4
roborock.0 | 2024-12-07 04:18:03.458 | info | terminating
roborock.0 | 2024-12-07 04:18:02.956 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
roborock.0 | 2024-12-07 04:18:02.953 | info | terminating
roborock.0 | 2024-12-07 04:18:02.947 | info | Got terminate signal TERMINATE_YOURSELF

### Adapter Version

dev

### JS-Controller Version

7.03

### Node.js Version

20

### Operating System

debian 12

**Comment by copystring** [comment]
Ich nehme an, dass es in 0.6.18 auch noch so ist? Vielleicht dann wie im Forum bereits vorgeschlagen mal den Adapter löschen und neu einrichten.

**Comment by JackDaniel007** [comment]
danke, genau das war die lösung
