### ISSUE TITLE
[BUG] Unsupported attribute: switch_status of get_status with value 0.

### ISSUE THREAD

**Issue by accessburn** [copystring/ioBroker.roborock#727]
### Bug Description

Roborock Q8max+: roborock.vacuum.a73

### Steps to Reproduce

Start Adapter
Login

### Expected Behavior

/

### Debug Log

Unsupported attribute: switch_status of get_status with value 0. Please contact the dev to add the newly found attribute of your robot. Model: roborock.vacuum.a73

### Adapter Version

0.6.17

### JS-Controller Version

7.0.3

### Node.js Version

20.18.1

### Operating System

Docker buanet

**Comment by copystring** [comment]
Thanks. Fixed via https://github.com/copystring/ioBroker.roborock/commit/cf88caf59ccd08d266b915512849395cbf521095. Coming in next release 0.6.18

**Comment by accessburn** [comment]
Wie lange dauert es denn bis ioBroker das Update bekommt? Mein log läuft langsam echt über :-D
