### ISSUE TITLE
Please add the badge for Weblate translations to your adapter repository

### ISSUE THREAD

**Issue by mcm1957** [copystring/ioBroker.roborock#73]
Please add the badge for Weblate translations to your adapter repository:
https://github.com/ioBrokerTranslator/doc#add-badge-to-readmemd

**Comment by copystring** [comment]
This? https://github.com/copystring/ioBroker.roborock/commit/1bd8f646abd20890e5610512c7eb2f6be77448f6

**Comment by mcm1957** [comment]
yes.

**Comment by copystring** [comment]
Alright. Thanks.
