### ISSUE TITLE
[BUG] Issue created by iobroker-bot not visible

### ISSUE THREAD

**Issue by mcm1957** [copystring/ioBroker.roborock#731]
For some reason I cannot see open issues created by iobroker-bot when logged in using my personal account (mcm1957).
When logged using iobroker.bot account I can see open issues created by mcm1957.

I can see closed issued independent of creator.

Did you set up some special security environment to hide some issues?

**Comment by mcm1957** [comment]
OK, this one is visible

**Comment by mcm1957** [comment]
Hmm - comments added by iobroker-bot are also not visible.

see https://github.com/copystring/ioBroker.roborock/issues/732
see https://github.com/copystring/ioBroker.roborock/issues/711

**Comment by copystring** [comment]
I noticed yesterday the issues were deleted for some reason. I thought it was you who deleted them as they were there before I merged the dev into main. I haven't touched them so I don't know what happened.

**Comment by mcm1957** [comment]
No I did not ...

Could you check if you BLOCKED the iobroker-bot?
If done to avoid some annoynce please lets find a solution for concrete problems instead of blocking in general.

**Comment by mcm1957** [comment]
If you did nothing special we could let it as it is for some days. Maybe GitHub has some troubles. But I did not notice this behavior at other repos until now,.

**Comment by copystring** [comment]
I checked if the bot got on the blocked list somehow by accident, but the blocked list is empty. I really don't know how the issues could have disappeared since I did not touch them and like you said, merging a branch should make a difference.

![Screenshot_20241212-131051.png](https://github.com/user-attachments/assets/36f6e115-722c-49e8-be8f-21e26ae2a6cd)

**Comment by mcm1957** [comment]
Thanks a lot for investigating.

That's the view from bot side:

![image](https://github.com/user-attachments/assets/e3d26f56-ee76-4510-a82b-206f350e1ca8)

Well I suggest to wait a little bit. I'll check if I can see the same problem somewhere else. Hope that's ok for you.

**Comment by copystring** [comment]
Sure. Let's wait a little. 👍

**Comment by mcm1957** [comment]
OK, problem seems to be located.
GITHUB blocked iobroker-bot for whtever reasion. I opened a ticket but it will last to get an answer :-(.
ALL Issues created b iobroker-bot are invisible at the moment ... 
Sh....

**Comment by mcm1957** [comment]
OK, github support removed the lock.
Everything should be fine again.
