### ISSUE TITLE
[BUG] State "roborock.0.HomeData" has no existing object, this might lead to an error in future versions

### ISSUE THREAD

**Issue by fuchs-1978** [copystring/ioBroker.roborock#734]
### Bug Description

Ich bekomme folgende Meldung:

<html>
<body>

State "roborock.0.HomeData" has no existing object, this might lead to an error in future versions
--

</body>
</html>

### Steps to Reproduce

Der Fehler trat mit Version 0.6.18 auf und dort regelmäßig ca. 1min

### Expected Behavior

Vermutlich fehlt das Objekt?

### Debug Log

<html>
<body>

roborock.0 | 2024-12-15 11:17:59.208 | warn | State "roborock.0.HomeData" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
roborock.0 | 2024-12-15 11:16:59.197 | warn | State "roborock.0.HomeData" has no existing object, this might lead to an error in future versions

</body>
</html>

### Adapter Version

0.6.18 

### JS-Controller Version

7.0.6

### Node.js Version

v20.18.1

### Operating System

Debian

**Comment by copystring** [comment]
Hallo,

ich brauche ein Debuglog.

**Comment by fuchs-1978** [comment]
Nachdem ich auf Debug gestellt hatte trat der Fehler nicht mehr auf. Das Objekt wurde angelegt. Daher hat sich das Problem erledigt.

**Comment by fonebone42** [comment]
das ist mir auch grad passiert, und wie oben beschrieben, ist der Fehler verschwunden, nachdem in den Adapter auf Debug gestellt hatte. Seither ist wieder Ruhe (auch mit Info Level)
Ich habe versucht das Ganze auf einem zweiten iobroker zu reproduzieren, aber ohne Erfolg.
