### ISSUE TITLE
[BUG] State "roborock.0.HomeData" has no existing object

### ISSUE THREAD

**Issue by moritz-Z** [copystring/ioBroker.roborock#739]
### Bug Description

Folgende Log-/Warn Meldungen werden minütlich generiert.

`State "roborock.0.HomeData" has no existing object, this might lead to an error in future versions`

### Steps to Reproduce

.

### Expected Behavior

No Warn

### Debug Log

<img width="1087" alt="Bildschirmfoto 2024-12-20 um 07 53 06" src="https://github.com/user-attachments/assets/1bc3ce3c-8f72-4433-a61d-ddb3d390f35b" />

### Adapter Version

0.6.18

### JS-Controller Version

 7.0.3

### Node.js Version

20.18.1

### Operating System

linux

**Comment by copystring** [comment]
Thanks. Fixed via https://github.com/copystring/ioBroker.roborock/commit/478ff52eb6e1ae2776c92f9c3ba4da3480a4996f. Coming in next release soon.
