### ISSUE TITLE
[BUG] Fehlermeldung in Log alle 3 Stunden

### ISSUE THREAD

**Issue by accessburn** [copystring/ioBroker.roborock#741]
### Bug Description

Failed to get home details: Error: Not running at healthCheck (node:dgram:922:11) at Socket.bind (node:dgram:242:3) at /opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:213:11 at new Promise (<anonymous>) at localConnector.getLocalDevices (/opt/iobroker/node_modules/iobroker.roborock/lib/localConnector.js:185:10) at Roborock.initializeHomeDetails (/opt/iobroker/node_modules/iobroker.roborock/main.js:197:56) at /opt/iobroker/node_modules/iobroker.roborock/main.js:77:4

### Adapter Version

0.6.18

### JS-Controller Version

7.0.3

### Node.js Version

20.18.1

### Operating System

Docker buanet

**Comment by copystring** [comment]
Duplicate https://github.com/copystring/ioBroker.roborock/issues/737
