### ISSUE TITLE
Feature-Request: Multible cleaning cycles

### ISSUE THREAD

**Issue by DonToben** [copystring/ioBroker.roborock#77]
Add the feature fo multible cleaning cycle.

E.g cleaning room one, two or three times in sequence

The function is included in the app

**Comment by DonToben** [comment]
Any news when it will be implemented?

**Comment by copystring** [comment]
Hm no. Not yet. I did not have a good idea how to implement this. Any suggestions?

**Comment by DonToben** [comment]
Not really. This function is already included in app. Maybe it's only a command?
Otherwise, sorry I have no idea?

**Comment by copystring** [comment]
OK. You can test this in dev branch: https://github.com/copystring/ioBroker.roborock/tree/dev
In floors there is cleanCount. Set this to whatever you like. It will be set back to 1 after start of cleaning.

**Comment by DonToben** [comment]
> OK. You can test this in dev branch: https://github.com/copystring/ioBroker.roborock/tree/dev In floors there is cleanCount. Set this to whatever you like. It will be set back to 1 after start of cleaning.

Funktioniert noch nicht. Sprich, segment_clean funktioniert mit dieser Version überhaupt nicht. Egal ob Count 1 oder 2 ist.

[Count Log.txt](https://github.com/copystring/ioBroker.roborock/files/10891475/Count.Log.txt)

**Comment by DonToben** [comment]
@copystring 
Konntest du dir das Problem schon ansehen?

**Comment by copystring** [comment]
Ja. Habe vergessen zu antworten. In der dev branch ist das gefixt.

**Comment by DonToben** [comment]
Danke, funktioniert jetzt einwandfrei.
