### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by DEV2DEV-DE** [copystring/ioBroker.roborock#78]
Version 0.0.8-alpha lässt sich nicht starten.
Auch nach kompletter Neuinstallation keine Besserung.

[roborock.log](https://github.com/copystring/ioBroker.roborock/files/10702030/roborock.log)

**Comment by copystring** [comment]
Bitte https://github.com/copystring/ioBroker.roborock/tree/testing ausprobieren. Sollte dort behoben sein.

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/pull/80
