### ISSUE TITLE
Unverhältnismäßige speichernutzung

### ISSUE THREAD

**Issue by inidona** [copystring/ioBroker.roborock#82]
Bei mir lief der Adapter jetzt  eine Woche, dabei ist mit aufgefallen das er fast 4GB RAM  benutzt hat. Auch werden die Karten nach einer Weile nicht mehr aktualisiert. Was kann ich tun um weitere Details ruazufinden ?

danke

**Comment by copystring** [comment]
Hi,
erstmal brauche ich ein log und ich muss wissen auf welchen system das ganze läuft. Auf RaspberryPi scheint es nicht richtig zu laufen.

**Comment by Lyssid** [comment]
Moin, ich konnte das Problem heute auch Beobachten.

Mein System:
Raspberry Pi 4 (4GB RAM)
Linux raspberrypi 5.15.84-v8+
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
(Raspberry Pi OS 64bit, light)

Der Adapter hat heute nach einer UpTime von ~14h (wird täglich neugestartet das gesammte System) ~1,1GB Ram belegt.

Fehlermeldungen oder ähnliches sind im Log nicht aufgelaufen. Nach einem manuellen neustart des Adapters verbraucht er grade 85mb RAM.

Ich hoffe das hilft fürs erste weiter.

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/commit/d6a7e391c51a9a7983f6131da185a2958f822501
