### ISSUE TITLE
Zonenreinigung Karte wird nicht geladen

### ISSUE THREAD

**Issue by mproper23** [copystring/ioBroker.roborock#85]
![grafik](https://user-images.githubusercontent.com/25171131/219603821-3b05396e-4cbc-4c6c-9b42-e3f0284bae1d.png)
Karte wird nicht geladen
Auf der Base 64 wird der Roboter nicht dargestellt
[Robor0.0.8.log](https://github.com/copystring/ioBroker.roborock/files/10765216/Robor0.0.8.log)

**Comment by mproper23** [comment]
Update: wenn ich das ganze direkt auf dem iobroker server mache geht es.

**Comment by copystring** [comment]
Welcher Browser? Chrome? Dort mal bitte strg+umschalttaste + j drücken. Dann geht die Konsole auf. Die Seite neu laden (F5). Dann müsste direkt als ersten in der Konsole die IP vom ioBroker host stehen.
z.B.: `Local IP address: 192.168.1.108`
Wenn das nicht passt kann keine Verbindung aufgebaut werden.

**Comment by mproper23** [comment]
`[background] BROWSER.webNavigation -| onBeforeNavigate (details): 
Object { url: "http://192.168.1.1:6824/map.html", timeStamp: 1676631163778, frameId: 0, parentFrameId: -1, tabId: 10, windowId: 53 }
[background.js:10829:33](moz-extension://5f0b4494-4288-4595-b720-dcadfc154756/scripts/background.js)
Disconnected from WebSocket server [zones.js:75:12](http://192.168.1.1:6824/zones.js)
ON BEFORE NAVIGATE 
Object { url: "http://192.168.1.1:6824/map.html", timeStamp: 1676631163778, frameId: 0, parentFrameId: -1, tabId: 10, windowId: 53 }
[background.js:10835:33](moz-extension://5f0b4494-4288-4595-b720-dcadfc154756/scripts/background.js)
WARNING Error: Could not establish connection. Receiving end does not exist.
    sendMessage moz-extension://5f0b4494-4288-4595-b720-dcadfc154756/lib.js:54
[background.js:10667:35](moz-extension://5f0b4494-4288-4595-b720-dcadfc154756/scripts/background.js)
Layout-Darstellung wurde erzwungen, bevor die Seite vollständig geladen war. Falls Stylesheet noch nicht geladen sind, kann dies zu einem kurzzeitigen Darstellung des Inhalts ohne Formatierung führen. [map.html](http://192.168.1.1:6824/map.html)
Local IP address: 192.168.44.1`

![grafik](https://user-images.githubusercontent.com/25171131/219627069-4b8e6bc2-4b7f-4e5a-a444-ea49124dfe53.png)

**Comment by copystring** [comment]
192.168.44.1 ist die richtige ip?

**Comment by mproper23** [comment]
nein

**Comment by mproper23** [comment]
server hat 192.168.1.1 und lokaler pc die 192.168.1.6

**Comment by copystring** [comment]
Hat der Server mehrere IPs? Irgendwo kommt die falsche IP her.
mal `ip addr` auf dem server eingeben. Oder bei Windows ipconfig

**Comment by mproper23** [comment]
server hat ne 2te virtuelle netzwerkkarte. die hat die 192.168.44.1
kommt von vmware

**Comment by copystring** [comment]
Ok. Naja um das zu umgehen müsste man die IP manuell einstellen. Das kann ich noch einbauen aber dauert noch ein bisschen

**Comment by mproper23** [comment]
Alles klar danke. Kann ich das in ner config datei nmanuell eintragen? Übergangsweise

**Comment by copystring** [comment]
In einer config nicht aber hier: https://github.com/copystring/ioBroker.roborock/blob/main/lib/map/zones.js#L12

**Comment by mproper23** [comment]
Danke. Hast du ne Idee warum der Roboter nicht mehr auf der Karte erscheint?

**Comment by copystring** [comment]
Ja. Das habe ich auch schon festgestellt. Da passen einige Koordinaten nicht.
Ich bin aber ohnehin dabei da noch einiges anzupassen. In meiner lokalen Version taucht er schon wieder auf.

**Comment by mproper23** [comment]
Mit Fix eingetragener IP tuts jetzt

**Comment by D-Hunt3r** [comment]
Da stimmt ein Verweis auf die mapCreator.js nicht:

![RoboRockMap_zone](https://user-images.githubusercontent.com/22468325/220544927-315b100b-f68c-498a-9f3d-e7484a8bc23b.png)

**Comment by copystring** [comment]
Oh. Ja das ist alter code. Der ist übrig geblieben und muss ich noch löschen.

**Comment by D-Hunt3r** [comment]
Passt, jetzt gibt es keine Fehler mehr

**Comment by mproper23** [comment]
Habe geupdatet auf die 0.0.10 jetzt kommt der Bug wieder obwohl ich die zones.js angepasst habe:
`06:53:29.974
GEThttp://192.168.1.1:6824/mapCreator.js
[HTTP/1.1 404 Not Found 2ms]

06:53:29.994 Laden des Moduls von "http://192.168.1.1:6824/mapCreator.js" wurde auf Grund eines nicht freigegebenen MIME-Typs ("text/html") blockiert.
[map.html](http://192.168.1.1:6824/map.html)
06:53:30.004
Uncaught (in promise) TypeError: "192.168.1.1" is not a function
    onload http://192.168.1.1:6824/zones.js:13
    onload http://192.168.1.1:6824/zones.js:380
    EventHandlerNonNull* http://192.168.1.1:6824/zones.js:11
[zones.js:13:27](http://192.168.1.1:6824/zones.js)
06:53:30.040
GEThttp://192.168.1.1:6824/favicon.ico`

**Comment by copystring** [comment]
Das Problem wurde noch nicht behoben

**Comment by mproper23** [comment]
ok. dachte nur weils davor mit der manuellen Eintragung ging

**Comment by copystring** [comment]
Das Problem sollte hier behoben sein: https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by D-Hunt3r** [comment]
Bei mir klappt die Zonenreinigung generell, aber die gezeichnete Zone weicht von der Zone ab die er dann wirklich nutzt
![zone_gezeichnet](https://user-images.githubusercontent.com/22468325/221349066-e65fe2c5-abc2-404c-a3bc-94768e8e388a.png)
![zone_umgesetzt](https://user-images.githubusercontent.com/22468325/221349067-1018dff7-88f8-49dd-9314-47d31d711b49.png)

**Comment by copystring** [comment]
Ja okay. Das ist ja ein anderes Problem. Ist das eigentliche Problem gelöst?

**Comment by copystring** [comment]
Erstellen der Zonen sollte nun hier behoben sein. Habe den Fehler gesehen und bei mir passen die Zonen nun. Bitte das hier testen. https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by D-Hunt3r** [comment]
sieht leider schlimmer aus als vorher:
![zone_gezeichnet](https://user-images.githubusercontent.com/22468325/221368212-684faced-1164-4182-92f8-8ab3716a5274.png)
![zone_umgesetzt](https://user-images.githubusercontent.com/22468325/221368219-347e1198-f456-401c-946f-89e0d0a82f1a.png)

**Comment by copystring** [comment]
OK. Dann brauche die test.rrmap aus dem Verzeichnis vom Adapter

**Comment by D-Hunt3r** [comment]
Kann ich die einfach posten? Was ist da alles drinnen?

**Comment by copystring** [comment]
Da ist die Karte drin vor dem Aufmalen als Bilddatei als nur die Karte in Rohdaten anstatt als Bild. Damit kann ich dann bei mir daraus wieder ein Bild machen und gucken warum es nicht passt.

**Comment by D-Hunt3r** [comment]
Dann hier :-)
[test.zip](https://github.com/copystring/ioBroker.roborock/files/10831771/test.zip)

**Comment by copystring** [comment]
Ist dort die Zonenreinigung aktiv?

**Comment by D-Hunt3r** [comment]
Was muss ich machen damit die Test.rrmap das enthält was du brauchst?

**Comment by copystring** [comment]
Eine Zonenreinigung über das Webinterface starten. Vorher checken ob die zu reinigende Zone auf der Karte nicht passt. Ist das der Fall dann die Datei mit der falsch positionierten Zone hier anhängen.

**Comment by D-Hunt3r** [comment]
Ich habe die Zone oben gezeichnet und unten wurde sie umgesetzt. Sollte hoffentlich so passen wir du es brauchst

[test.zip](https://github.com/copystring/ioBroker.roborock/files/10831851/test.zip)
![zone](https://user-images.githubusercontent.com/22468325/221370715-c8cd49ec-50a2-4201-af17-2071ec45d187.png)

**Comment by copystring** [comment]
Puh. Ist in der Tat falsch aber aktuell weiß ich nicht wie das sein kann. Auf meinen beiden Stockwerken kommt der Fehler nicht.
Ist das auf beiden Stockwerken so und der Adapter auf dem ganz aktuellsten Stand aus dev? https://github.com/copystring/ioBroker.roborock/tree/dev

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/commit/5d1f50fe99c198cd8ae9b78051334411c1cc5b46 in dev branch.

**Comment by copystring** [comment]
https://github.com/copystring/ioBroker.roborock/issues/87#issuecomment-1445239053
