### ISSUE TITLE
Position auf Karte stimmt nicht

### ISSUE THREAD

**Issue by D-Hunt3r** [copystring/ioBroker.roborock#87]
![RoboRockMap](https://user-images.githubusercontent.com/22468325/220539442-9107b882-fb56-40f4-b18e-306f31f4219d.png)

**Versions:**  
 - Adapter version: 0.0.10-alpha.0
 - JS-Controller version: 4.0.24
 - Node version: v16.19.0
 - Operating system: Ubuntu 22.04.1 LTS

**Comment by copystring** [comment]
Wie sieht die Karte normalerweise aus?
Sieht so aus als wäre alles nach unten verschoben.

**Comment by D-Hunt3r** [comment]
Ja es ist nur alles nach unten geschoben, sonst sieht es gut aus

**Comment by copystring** [comment]
Und mit einer älteren Version war das nicht so?

**Comment by D-Hunt3r** [comment]
In der letzten Version, als der Roboter noch zu sehen war, hat das gestimmt.

**Comment by copystring** [comment]
Ja okay. Also bei 0.0.8-alpha.0?

**Comment by D-Hunt3r** [comment]
gerade getestet, war die Version 0.0.8-alpha.0 als es ok war.

**Comment by copystring** [comment]
Magst du mal bitte https://github.com/copystring/ioBroker.roborock/tree/dev testen? Dort habe ich den Code für das Malen vom Pfad angepasst. Kommt jetzt darauf an ob der nun passt oder nicht. Abhängig davon verfahre ich dann weiter. Bitte ein neues Bild schicken.

**Comment by D-Hunt3r** [comment]
Sieht nicht so aus als hätte sich etwas verändert, außer das im roten Kreis, das ist beim losfahren erschienen.


![RoboRockMap_dev](https://user-images.githubusercontent.com/22468325/220548798-8a1ad00c-810e-4205-8496-c693fb46b294.png)

**Comment by copystring** [comment]
Ja das wird der Pfad vom Wischen sein. Ich habe zum testen nur den Wischpfad angepasst. Wäre dieser denn in der richtigen Stelle?
Dann weiß ich woran es liegt aber merkwürdig da anscheinend bei dir keinen Offset nach unten braucht bei mir aber schon. Das muss ich mir dann genauer anschauen

**Comment by D-Hunt3r** [comment]
Achso, weil gerade kein Wischer drunter ist habe ich nicht dran gedacht.
Das ist die richtige Position (aus RoboRock App)

![RoboRock_app](https://user-images.githubusercontent.com/22468325/220557365-93ade2f9-3054-4356-9237-b2899bd7ea92.jpg)

**Comment by copystring** [comment]
OK. Kannst du mir einen Gefallen tun und auf dem ioBroker host mir die Datei test.rrmap unter /opt/iobroker/node_modules/iobroker.roborock/ schicken? Dort ist deine Karte nochmal als spezieller Datei abgelegt. Diese kann ich dann bei mir einfügen und testen um zu schauen was da los ist.

**Comment by copystring** [comment]
Hast du vielleicht zwei Stockwerke? Ich konnte es bei mir auf dem oberen Stockwerk reproduzieren aber im unteren Stockwerk ist alles in Ordnung. Das verstehe ich nicht. Vielleicht sind die Stockwerke verschoben? Ist die verschobene Karte vielleicht das zweite Stockwerk?

**Comment by D-Hunt3r** [comment]
Ja ich habe mehrere Stockwerke. Ich teste mal ob andere Ebenen stimmen. Aktuell ist das Erdgeschoß verschoben.

Kann ich die rrmap hier schicken oder welche Informationen enthält diese Datei?

**Comment by Dimi1305** [comment]
Ich kann es bestätigen, auch bei mir ist das Erdgeschoss verschoben. Ich habe momentan 2 Ebenen. Auch wenn bei mir mit der Kartenerstellung der Adapter abstürtzt (Pi 4), ist das Verhalten gleich. Bis der abstürzt zeigt er mir trotzdem die Karte verschoben an.

**Comment by copystring** [comment]
> Ja ich habe mehrere Stockwerke. Ich teste mal ob andere Ebenen stimmen. Aktuell ist das Erdgeschoß verschoben.
> 
> Kann ich die rrmap hier schicken oder welche Informationen enthält diese Datei? 

Da ist deine Karte hinterlegt bevor diese als Bild "gemalt" wird. Brauche ich aber nicht mehr weil ich es ja bei mir auch reproduzieren kann.

**Comment by copystring** [comment]
Ich habe das Problem gefunden und habe angefangen das neu zu programmieren. Ich brauche daher aktuell keine logs etc nur Zeit das anzupassen.
Sobald das fertig ist poste ich ein Update.

**Comment by copystring** [comment]
Dein Problem sollte hier behoben sein: https://github.com/copystring/ioBroker.roborock/tree/dev
Bitte beide Karten (Stockwerke) für mich Testen.

**Comment by D-Hunt3r** [comment]
Sieht gut aus. Passt auf zwei verschienenen Etagen.
Allerdings zeichnet er die Linie inkl. wischmob, obwohl keiner dran ist.

Und was mit im Log aufgefallen ist:

<html><body>


error | Failed to create canvas: locating
-- | --



</body>
</html>

Location ist ja kein "error", vielleicht kann man das als info schreiben?

**Comment by copystring** [comment]
Ja das ist eine gute idee. Habe ich hier implementiert: https://github.com/copystring/ioBroker.roborock/tree/dev
Der Wischpfad sollte dort ebenfalls richtig laufen. Der Wischpfad wurde zu beginn vom Start des Roboters fälschlicherweise auf die Karte gemalt.

**Comment by D-Hunt3r** [comment]
Habe noch einmal alles gelöscht und neu installiert. 
Etage 1 sieht besser aus als Erdgeschoss:

Etage 1:
![zone_gezeichnet](https://user-images.githubusercontent.com/22468325/221372142-ca226a8c-8d1d-444a-9213-aad8a00ed2c6.png)
![zone_umgesetzt](https://user-images.githubusercontent.com/22468325/221372145-7986a94d-d25a-43d0-bf41-4d39a890495e.png)

EG:
![zone_umgesetzt_eg](https://user-images.githubusercontent.com/22468325/221372157-3cf14b77-f0d3-41c1-90cb-eb933d54ed86.png)
![zone_gezeichnet_eg](https://user-images.githubusercontent.com/22468325/221372160-13a89f84-e5a0-479b-a5ff-bcb9fd743fa7.png)

**Comment by copystring** [comment]
Welcher Browser? Ist im Browser vielleicht ein Zoom eingestellt?

**Comment by copystring** [comment]
Bitte hier fortsetzen da das eigentliche Problem gelöst ist.: https://github.com/copystring/ioBroker.roborock/issues/88
Fixed via: https://github.com/copystring/ioBroker.roborock/commit/5d1f50fe99c198cd8ae9b78051334411c1cc5b46 in dev branch
