### ISSUE TITLE
Falsche Zonenposition

### ISSUE THREAD

**Issue by copystring** [copystring/ioBroker.roborock#88]
Habe noch einmal alles gelöscht und neu installiert. 
Etage 1 sieht besser aus als Erdgeschoss:

Etage 1:
![zone_gezeichnet](https://user-images.githubusercontent.com/22468325/221372142-ca226a8c-8d1d-444a-9213-aad8a00ed2c6.png)
![zone_umgesetzt](https://user-images.githubusercontent.com/22468325/221372145-7986a94d-d25a-43d0-bf41-4d39a890495e.png)

EG:
![zone_umgesetzt_eg](https://user-images.githubusercontent.com/22468325/221372157-3cf14b77-f0d3-41c1-90cb-eb933d54ed86.png)
![zone_gezeichnet_eg](https://user-images.githubusercontent.com/22468325/221372160-13a89f84-e5a0-479b-a5ff-bcb9fd743fa7.png)

_Originally posted by @D-Hunt3r in https://github.com/copystring/ioBroker.roborock/issues/87#issuecomment-1445169376_

**Comment by D-Hunt3r** [comment]
Benutzte Firefox und es ist kein Zoom eingestellt.
Habe gerade das neue "Go To" verwendet und da fährt er aber zur richtigen Position.
Nur die Zone stimmt irgendwie nicht. Ich frage mich ob ich der einzige bin bei dem das nicht funktioniert.
![grafik](https://user-images.githubusercontent.com/22468325/221401861-ca1078b3-53c4-4db3-b9d3-c387970711a6.png)

**Comment by tschoeplis** [comment]
hast Du deine Karte um 90Grad gedreht?

**Comment by D-Hunt3r** [comment]
Ich kann leider nicht sagen ob die Karte gedreht ist oder nicht.

![grafik](https://user-images.githubusercontent.com/22468325/221402992-aab36c4d-d067-4492-8d1d-4f891c1fecbe.png)

**Comment by copystring** [comment]
OK. Es ist ein Mysterium.
Ich verstehe was passiert aber nicht warum das passiert. Bei dir wird die Square position falsch berechnet. Diese ist abhängig von der Mausposition. Tu mir mal bitte einen gefallen und klicke mit der Maus genau auf diesen Pixel der hier blau markiert ist: 
![image](https://user-images.githubusercontent.com/1298861/221404083-652a476b-2d34-4a67-a1ea-a6b76edaecbc.png)
und dann die Werte von der Konsole (gern als Screenshot genau wie gerade eben auch) hier anhängen

**Comment by D-Hunt3r** [comment]
![grafik](https://user-images.githubusercontent.com/22468325/221404320-f9a1398e-9b86-44f3-a168-ca47e427f32b.png)

**Comment by copystring** [comment]
Ok. Bitte ein vollständiges log einfügen so wie hier: 
![image](https://user-images.githubusercontent.com/1298861/221404564-a80e5b14-e042-4caa-b20d-5c97eb2b0fc5.png)

**Comment by D-Hunt3r** [comment]
![grafik](https://user-images.githubusercontent.com/22468325/221404695-711d266b-abdd-488a-9682-ace5a0ff4aa4.png)

**Comment by copystring** [comment]
OK. Dort ist kein Fehler. Dann bitte das gleiche nochmal aber vorher eine Zone einfügen und diese möglichst wenig verschieben. Am Besten nur 1 pixel nach rechts. Dann ein neues log anhängen.

**Comment by D-Hunt3r** [comment]
Ein Pixel nach Rechts
![grafik](https://user-images.githubusercontent.com/22468325/221405071-b1de3517-0aba-4e92-ab30-abdcefaf3469.png)

**Comment by copystring** [comment]
Ich habe es mal manuell mit deinen Koordinaten durchgerechnet. z.B. wird hier die X Koordinate von Pixel in das Roborock format umgerechnet: https://github.com/copystring/ioBroker.roborock/blob/dev/lib/map/zones.js#L82
Also `(left + xLoc) * 50.0` wobei left bei dir 324 ist und xLoc ist einfach nur der Pixel X oben links von der Zone. Also `(324 + 136) * 50` und das ist 23000. Warum bei dir 32600 herauskommt kann ich mir nicht erklären. Von daher weiß ich aktuell nicht was ich tun kann damit es läuft.
Zum Testen mal einen anderen Browser ausprobiert?
Wie wird das ganze aufgerufen? Einfach nur als Tab im Browser? Nichts irgendwie via iFrame eingebunden oder so?

**Comment by copystring** [comment]
Ich habe es in der dev Branch es so gemacht, dass direkt beim Erstellen einer Zone die Roborock Koordinaten ausgeben werden.
Die Zone spawnt bei dir bei x:135 y: 241. `(324 + 135) * 50 = 22950`
In der Konsole von Firefox bei der Zone muss also 22950 stehen.
https://github.com/copystring/ioBroker.roborock/tree/dev

Nichts verschieben. Einfach nur eine Zone erstellen und das log wieder anhängen. Passt das wieder nicht dann hat es nichts mit dem Verschieben der Maus zu tun.

**Comment by D-Hunt3r** [comment]
Firefox, Chrome und auf dem Handy probiert. Ist überall das gleiche verhalten.
Ich rufe das per http://192.168.178.84:6824/map.html auf

![grafik](https://user-images.githubusercontent.com/22468325/221406673-eddb591a-d11d-4aa6-adce-73d1f27d7891.png)

**Comment by copystring** [comment]
Das map bitte aufklappen so wie hier: 
![image](https://user-images.githubusercontent.com/1298861/221406838-17ac77c1-fb5d-4a9a-9565-b33884df9725.png)

**Comment by D-Hunt3r** [comment]
![grafik](https://user-images.githubusercontent.com/22468325/221406945-74e1073c-0fde-4432-84a6-fd85d32445b9.png)

**Comment by copystring** [comment]
Auch hier passt alles.
Ich habe die Berechnung ein mal angepasst.
Bitte die aktuelle dev branch testen. Am Besten direkt auf beiden Stockwerken.

**Comment by D-Hunt3r** [comment]
![grafik](https://user-images.githubusercontent.com/22468325/221417178-93ecc38e-4418-40e7-a895-33f88976373b.png)
![grafik](https://user-images.githubusercontent.com/22468325/221417195-01966afb-187f-404e-81e0-974e1e1510c7.png)

**Comment by D-Hunt3r** [comment]
andere Ebene
![grafik](https://user-images.githubusercontent.com/22468325/221417603-ced853cb-b664-447c-9bc7-e024642f4d59.png)
![grafik](https://user-images.githubusercontent.com/22468325/221417616-89146395-b023-4710-8b53-fbf6878395c9.png)

**Comment by copystring** [comment]
OK. Vielleich hat es etwas mit dem Größenverhältnis der Karte zu tun. Ich habe ein Update zum Testen in dev hochgeladen.

**Comment by D-Hunt3r** [comment]
![zone_gezeichnet_eg](https://user-images.githubusercontent.com/22468325/221570845-cd83cf0d-6db5-4ee6-b7e2-40737cc74f99.png)
![zone_umgesetzt_eg](https://user-images.githubusercontent.com/22468325/221570849-2f240b1f-646c-4ce0-85e0-a0802f783d65.png)

**Comment by D-Hunt3r** [comment]
Ergeschoss sieht gut aus. Gleich andere Ebene mal testen.
![grafik](https://user-images.githubusercontent.com/22468325/221934694-a8dee6eb-0c32-4f7f-9df2-1730ba84e664.png)

**Comment by D-Hunt3r** [comment]
Zweite Ebene sieht auch gut aus
![grafik](https://user-images.githubusercontent.com/22468325/221935645-a3cb21ad-e090-41f1-9269-5b849155ac09.png)

**Comment by D-Hunt3r** [comment]
Ich glaube ja xD

**Comment by copystring** [comment]
Okay. Habe gar nichts seit dem letzten mal geändert... Vielleicht hat der Adapter bei dir nicht neu gestartet.

**Comment by D-Hunt3r** [comment]
Also ich hatte einen Stromausfall und alles war aus. Vielleicht hat das geholfen ...

**Comment by copystring** [comment]
Gut. Dann können wir das ja schließen.

**Comment by copystring** [comment]
Fixed via https://github.com/copystring/ioBroker.roborock/pull/91/commits/53d2efc36c5c54934df828e3830c7df416f3abd9
