### ISSUE TITLE
Kartendarstellung unterschiedlich 

### ISSUE THREAD

**Issue by wuesty1977** [copystring/ioBroker.roborock#90]
Danke für den Adapter, ich habe die aktuelle dev Branche installiert, Karte und Zonen werden jetzt richtig angezeigt. Ich habe zwei Karten erstellt, in der App erscheinen beide im Hochkant Format, beim Adapter erscheint Etage 1 im Hockkant Format und Etage 2 im Querformat. Kann ich die Karten im Adapter drehen?

**Comment by copystring** [comment]
Aktuell kann man die Karte nicht drehen. Die Karten kommen so von Roborock und müssen selbst gedreht werden.
Wahrscheinlich baue ich das irgendwann in den Adapter ein aber aktuell hat das keine hohe Priorität.
